'use client';
import {confirmAction} from '../feedback/feedback';
import {useEffect,useRef,useState} from 'react';
import {targets,parseAnnouncementWrite,type Announcement,type AnnouncementWrite} from '../../announcements/model';
import {loadAnnouncements,saveAnnouncement,AnnouncementRejected} from '../../announcements/client';
const blank=():AnnouncementWrite=>({expectedVersion:0,title:'',body:'',target:'favorites',audience:'staff',enabled:false});
const value=(n:Announcement):AnnouncementWrite=>({expectedVersion:n.revision,title:n.title,body:n.body,target:n.target,audience:n.audience,enabled:n.enabled});
type Draft={id:string;write:AnnouncementWrite};
export function AnnouncementManager({initial}:{initial?:Announcement[]}){
 const [items,setItems]=useState(initial),[draft,setDraft]=useState<Draft>(),[pending,setPending]=useState<Draft>(),[backups,setBackups]=useState<Draft[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const lock=useRef(false),leaving=useRef(false);
 const saved=items?.find(x=>x.id===draft?.id),dirty=!!draft&&JSON.stringify(draft.write)!==JSON.stringify(saved?value(saved):blank());
 useEffect(()=>{if(!dirty&&!pending&&!backups.length)return;const unload=(e:BeforeUnloadEvent)=>{if(!leaving.current){e.preventDefault();e.returnValue='';}};const click=async(e:MouseEvent)=>{const a=e.target instanceof Element?e.target.closest('a[href]'):null;if(!a||e.defaultPrevented||e.ctrlKey||e.metaKey||e.shiftKey)return;e.preventDefault();e.stopPropagation();if(!lock.current&&await confirmAction('本页有未保存、待确认的公告或输入备份。确定离开吗？')){leaving.current=true;location.assign(a.getAttribute('href')!);}};addEventListener('beforeunload',unload);document.addEventListener('click',click,true);return()=>{removeEventListener('beforeunload',unload);document.removeEventListener('click',click,true);};},[dirty,pending,backups.length]);
 async function select(n?:Announcement){if(lock.current||pending||!items)return;if(dirty&&draft){if(!await confirmAction('切换前会在本页保留当前输入备份，继续吗？'))return;setBackups(xs=>[...xs,draft]);}setDraft(n?{id:n.id,write:value(n)}:{id:crypto.randomUUID(),write:blank()});setNotice('');setError('');}
 async function reload(){if(lock.current)return;if((dirty||pending)&&!await confirmAction('载入最新公告前，会保留当前输入及原请求备份。继续吗？'))return;lock.current=true;setBusy(true);setError('');try{const next=await loadAnnouncements(true);if(draft)setBackups(xs=>[...xs,pending??draft]);setItems(next);if(draft){const n=next.find(x=>x.id===draft.id);setDraft(n?{id:n.id,write:value(n)}:{id:draft.id,write:blank()});}setPending(undefined);setNotice('已载入最新公告。原输入和请求备份保留在下方，请核对后再保存。');}catch{setError('暂时无法载入公告，原输入和备份未改变。');}finally{lock.current=false;setBusy(false);}}
 async function save(retry=false){if(lock.current||!draft)return;const input=retry?pending:draft;if(!input)return;if(!retry){try{parseAnnouncementWrite(input.write);}catch{setError('标题和说明须填写单段文字，首尾不要留空格，长度分别不超过120和600字。');return;}}if(!retry&&!await confirmAction((input.write.enabled?'公告将对符合权限的员工展示。':'公告将保持暂停或停止展示。')+'每次保存生成新版本，已关闭旧版本的员工可能再次看到。确定保存吗？'))return;lock.current=true;setBusy(true);setPending(input);setError('');setNotice('');try{const n=await saveAnnouncement(input.id,input.write);setItems(xs=>[n,...(xs??[]).filter(x=>x.id!==n.id)]);setDraft({id:n.id,write:value(n)});setPending(undefined);setNotice(n.enabled?'公告已保存并启用，仅符合权限的员工可见。':'公告已保存，当前暂停展示。');}catch(e){if(e instanceof AnnouncementRejected&&!retry){setPending(undefined);setError(e.message==='ANNOUNCEMENT_CONFLICT'?'公告已变化或达到数量上限，输入已保留，请载入最新公告核对。':'当前权限或输入未通过校验，输入已保留。');}else setError('无法确认原保存结果。输入已锁定，请重试原保存，或保留备份并载入最新公告。');}finally{lock.current=false;setBusy(false);}}
 function edit(key:keyof AnnouncementWrite,v:string|boolean){if(draft)setDraft({...draft,write:{...draft.write,[key]:v}});}
 function restore(b:Draft){if(busy||pending)return;if(draft)setBackups(xs=>[...xs,draft]);const n=items?.find(x=>x.id===b.id);setDraft({id:b.id,write:{...b.write,expectedVersion:n?.revision??0}});setNotice('备份已放回编辑区，尚未保存，请核对。');}
 return <section className="announcement-manager"><header><div><p className="card-kicker">TEAM UPDATES</p><h1>新功能公告</h1><p>简单说明新功能，并带员工进入对应页面。</p></div><a className="secondary-link" href="/admin">返回管理后台</a></header><p>受众还会受目标角色权限和功能开关限制。文章 PDF、文章反馈入口先进入资料库，再选择文章使用。启用公告立即展示，修改公告不修改文章。</p><div className="announcement-actions"><button className="primary-link" disabled={busy||!!pending||!items||items.length>=50} onClick={()=>select()}>新建公告</button><button className="secondary-link" disabled={busy} onClick={()=>void reload()}>保留输入并载入最新公告</button></div>{!items?<p role="status">暂时无法读取公告，请重试。</p>:<><p>共 {items.length} 条公告（最多 50 条）</p><ul className="announcement-list">{items.map(n=><li key={n.id}><span>{n.title} · 版本 {n.revision} · {n.enabled?'启用':'暂停'}</span><button disabled={busy||!!pending} onClick={()=>select(n)}>编辑：{n.title}</button></li>)}</ul></>}
 {draft&&<form className="announcement-editor" onSubmit={e=>{e.preventDefault();void save();}}><h2>{draft.write.expectedVersion?'编辑公告 · 版本 '+draft.write.expectedVersion:'新建公告（未保存）'}</h2><label>标题<input aria-label="公告标题" required maxLength={120} disabled={busy||!!pending} value={draft.write.title} onChange={e=>edit('title',e.target.value)}/></label><label>简短说明（单段）<input aria-label="公告说明" required maxLength={600} disabled={busy||!!pending} value={draft.write.body} onChange={e=>edit('body',e.target.value)}/></label><label>功能入口<select aria-label="功能入口" disabled={busy||!!pending} value={draft.write.target} onChange={e=>edit('target',e.target.value)}>{Object.entries(targets).map(([key,t])=><option key={key} value={key}>{t.label}{t.admin?'（仅管理员）':key==='ops'?'（运营及管理员）':''}</option>)}</select></label><label>公告受众<select aria-label="公告受众" disabled={busy||!!pending} value={draft.write.audience} onChange={e=>edit('audience',e.target.value)}><option value="staff">全体员工</option><option value="ops">运营及管理员</option><option value="admin">仅管理员</option></select></label><label className="announcement-toggle"><input type="checkbox" aria-label="启用公告" disabled={busy||!!pending} checked={draft.write.enabled} onChange={e=>edit('enabled',e.target.checked)}/>启用公告</label><button className="primary-link" disabled={busy||!!pending||!dirty}>保存公告</button></form>}{pending&&<button disabled={busy} onClick={()=>void save(true)}>重试原保存</button>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{backups.map((b,i)=><details key={i} open><summary>公告输入备份 {i+1}</summary><textarea aria-label={`公告输入备份 ${i+1}`} readOnly value={JSON.stringify(b,null,2)}/><button disabled={busy||!!pending} onClick={()=>restore(b)}>恢复备份 {i+1} 到编辑区</button></details>)}</section>;
}
