'use client';
import {useRef,useState} from 'react';
import {targets,type Announcement,type ReceiptInput} from '../../announcements/model';
import {loadAnnouncements,saveAnnouncementReceipt,AnnouncementRejected} from '../../announcements/client';
export function AnnouncementFeed({initial}:{initial?:Announcement[]}){
 const [items,setItems]=useState(initial),[expanded,setExpanded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<{id:string;input:ReceiptInput;open:boolean;target:Announcement['target']}>();const lock=useRef(false);
 async function reload(){if(lock.current)return;lock.current=true;setBusy(true);try{setItems(await loadAnnouncements());setPending(undefined);setError('');}catch{setError('新功能公告暂时无法加载，资料阅读不受影响。');}finally{lock.current=false;setBusy(false);}}
 async function act(item:Announcement,action:ReceiptInput['action'],open=false,retry=false){if(lock.current)return;const request=retry?pending:{id:item.id,input:{revision:item.revision,action},open,target:item.target};if(!request)return;lock.current=true;setBusy(true);setError('');setPending(request);try{const ack=await saveAnnouncementReceipt(request.id,request.input);if(ack.target!==request.target)throw new Error('INVALID_ACK');setItems(xs=>xs?.flatMap(x=>x.id===ack.id?(ack.dismissed?[]:[{...x,seen:true}]):[x]));setPending(undefined);if(request.open&&!ack.dismissed)location.assign(targets[ack.target].href);}catch(e){if(e instanceof AnnouncementRejected&&!retry){setPending(undefined);setError('公告已变化或当前不可使用，请刷新公告后再操作。');}else setError('无法确认操作结果，公告暂时保留。请重试原操作。');}finally{lock.current=false;setBusy(false);}}
 if(items?.length===0&&!error)return null;
 return <section className="feature-announcements" aria-label="新功能公告" data-nosnippet=""><header><h2>新功能</h2><button disabled={busy} onClick={()=>void reload()}>刷新公告</button></header>{!items&&<p role="status">新功能公告暂时无法加载，资料阅读不受影响。</p>}{(expanded?items:items?.slice(0,3))?.map(n=><article key={n.id}><div><strong>{n.title}</strong><span className="announcement-seen">{n.seen?'已读':'未读'}</span><p>{n.body}</p></div><div className="announcement-actions"><button disabled={busy||!!pending} onClick={()=>void act(n,'seen',true)}>了解功能：{targets[n.target].label}</button>{!n.seen&&<button disabled={busy||!!pending} onClick={()=>void act(n,'seen')}>标为已读</button>}<button disabled={busy||!!pending} aria-label={`关闭公告：${n.title}`} onClick={()=>void act(n,'dismiss')}>关闭</button></div></article>)}{items&&items.length>3&&<button onClick={()=>setExpanded(x=>!x)}>{expanded?'收起':'查看其余 '+(items.length-3)+' 条公告'}</button>}{error&&<p role="alert">{error}</p>}{pending&&<button disabled={busy} onClick={()=>void act({} as Announcement,pending.input.action,pending.open,true)}>重试原操作</button>}</section>;
}
