'use client';
import {useReviewLeaveGuard} from './useReviewLeaveGuard';
import {requestReviewLeave} from '../../review/leave';
import {ArticleCategories} from '../categories/ArticleCategories';
import {FieldValues} from '../fields/FieldValues';
/* eslint-disable @next/next/no-img-element -- cover URLs require the current administrator session. */
import {useRef,useState} from 'react';
import type {PublicationDetail,PublicationInput} from '../../review/publication';
import {readPublication,sendPublication,publicationError,PublicationRejected} from '../../review/publication-client';
import {DocumentView} from '../gitbook/Reading/DocumentView';
import {MediaBlocks} from '../gitbook/Media/MediaBlocks';
import {parseReaderBody} from '../../reader/body';
import {kinds,statuses} from '../../workspace/model';
type Pending={input:PublicationInput;revision:number;approvedBy:string;previousPublication:number|null};
const time=(value:string,locale:'zh-CN'|'en'='zh-CN')=>new Date(value).toLocaleString(locale,{timeZone:'Asia/Kuala_Lumpur',hour12:locale==='en'});
export function PublicationPanel({initial}:{initial:PublicationDetail}){
 const [detail,setDetail]=useState(initial),[confirm,setConfirm]=useState<PublicationInput['action']|null>(null);
 const [busy,setBusy]=useState<'read'|'write'|''>(''),[uncertain,setUncertain]=useState(false),[blocked,setBlocked]=useState(false);
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[confirmedUnread,setConfirmedUnread]=useState(false),[coverFailed,setCoverFailed]=useState(false);
 const operation=useRef(false),pending=useRef<Pending|null>(null),minimumSequence=useRef(initial.article.sequence);
 const {article,approval,revision}=detail;const locked=Boolean(busy)||uncertain;
 const english=article.locale==='en';const t=(zh:string,en:string)=>english?en:zh;
 const canQueue=detail.canQueue&&article.status==='approved'&&article.lifecycle==='active'&&approval?.revision===revision;
 const canPublish=detail.canPublish&&article.status==='queued'&&article.lifecycle==='active'&&approval?.revision===revision;
 useReviewLeaveGuard({dirty:confirm!==null&&!blocked,busy:Boolean(busy),uncertain});
 async function reload(){if(operation.current||uncertain)return;if(!(await requestReviewLeave('discard'))||operation.current||uncertain)return;operation.current=true;setBusy('read');setError('');setBlocked(true);
  try{const next=await readPublication(article.documentId,minimumSequence.current);setDetail(next);minimumSequence.current=next.article.sequence;setConfirm(null);setBlocked(false);setConfirmedUnread(false);setCoverFailed(false);}catch(e){setError(publicationError(e,true,article.locale));}finally{operation.current=false;setBusy('');}
 }
 async function change(){if(operation.current||!uncertain&&(blocked||!confirm||!(confirm==='queue'?canQueue:canPublish)))return;
  const exact=pending.current??{input:{action:confirm!,expectedSequence:article.sequence},revision,approvedBy:approval!.reviewerId,previousPublication:article.publishedRevision};
  pending.current=exact;operation.current=true;setBusy('write');setError('');setNotice('');
  try{const ack=await sendPublication(article.documentId,exact.input,exact.revision,exact.approvedBy,exact.previousPublication);minimumSequence.current=ack.sequence;pending.current=null;setUncertain(false);setConfirm(null);setBlocked(true);setConfirmedUnread(true);setNotice(ack.action==='queue'?(english?`Version ${ack.revision} is scheduled. An admin must still publish it.`:`版本 ${ack.revision} 已进入等待发布，仍需管理员确认正式发布。`):(english?`Working revision ${ack.revision} is published. Employees with access can now read it.`:`工作修订 ${ack.revision} 已正式发布，具备阅读权限的员工可以查阅。`));
   setBusy('read');try{const next=await readPublication(article.documentId,ack.sequence);setDetail(next);minimumSequence.current=next.article.sequence;setBlocked(false);setConfirmedUnread(false);setCoverFailed(false);}catch(e){setError(publicationError(e,true,article.locale));}
  }catch(e){const unknown=uncertain||!(e instanceof PublicationRejected);setUncertain(unknown);if(!unknown){pending.current=null;setBlocked(true);}setError(publicationError(unknown?new Error('UNKNOWN_RESULT'):e,false,article.locale));}finally{operation.current=false;setBusy('');}
 }
 const reader=parseReaderBody(article.body);const state=english?{draft:'Draft',in_review:'In review',changes_requested:'Changes requested',approved:'Approved',queued:'Scheduled',published:'Published'}[article.status]??article.status:statuses.find(s=>s.id===article.status)?.name??article.status;
 return <section className="review-decision publication-panel" aria-label={t("文章发布管理","Manage publication")}>
  <nav className="review-decision-links" aria-label={t("发布导航","Publication navigation")}>{!locked&&<><a href={`/admin/review?article=${encodeURIComponent(article.documentId)}`}>{t("返回二审详情","Back to review")}</a><a href={`/admin/editor?article=${encodeURIComponent(article.documentId)}`}>{t("编辑文章","Edit article")}</a><a href="/admin">{t("返回内容工作台","Back to content")}</a><a href={`/admin/availability?article=${encodeURIComponent(article.documentId)}`}>{t("归档与下线","Archive or unpublish")}</a><a href={`/admin/history?article=${encodeURIComponent(article.documentId)}`}>{t("历史记录与版本","History and versions")}</a></>}<button type="button" disabled={locked} onClick={()=>void reload()}>{busy==='read'?t('正在读取…','Loading…'):t('重新读取发布状态','Reload publication status')}</button></nav>
  {notice&&<p role="status">{notice}</p>}{confirmedUnread&&<p className="review-control-warning">{t("操作已经确认。本页文章状态和记录仍是上次读取结果，请重新读取以核对最新资料。","The action was confirmed, but this page still shows the last loaded status. Reload to check the latest record.")}</p>}
  <header><p className="review-decision-eyebrow">{t("工作修订","Working revision")} {revision} · {state}</p><h2>{article.title}</h2><dl className="review-decision-metadata"><div><dt>{t("资料类型","Content type")}</dt><dd>{english?{article:"Knowledge article",ops:"OPS Internal",reference:"Reference",qa:"Q&A"}[article.kind]:kinds[article.kind]}</dd></div><div><dt>{t("发布后阅读范围","Who can read after publication")}</dt><dd>{english?{staff:'All staff',ops:'Ops and Admin',admin:'Admin only'}[article.audience]:{staff:'普通员工',ops:'Ops 与 Admin',admin:'仅 Admin'}[article.audience]}</dd></div><div><dt>{t("批准管理员","Approving reviewer")}</dt><dd>{approval?.reviewerName??t('当前版本无有效批准记录','No valid approval for this version')}</dd></div><div><dt>{t("批准时间","Approved at")}</dt><dd>{approval?<time dateTime={approval.approvedAt}>{time(approval.approvedAt,article.locale)} {t('（马来西亚时间）','(Malaysia time)')}</time>:t('尚无记录','No record')}</dd></div>{article.kind==='qa'&&<><div><dt>{t("问答分类","Q&A category")}</dt><dd>{article.qa?.category||t('未分类','Uncategorized')}</dd></div><div><dt>{t("问答排序","Q&A order")}</dt><dd>{article.qa?.position??0}</dd></div></>}</dl><p>{t('当前正式版：','Current publication: ')}{article.publishedRevision===null?t('尚未发布','Not published'):english?`Published (working revision ${article.publishedRevision})`:`已发布（工作修订 ${article.publishedRevision}）`}</p><p>{t("加入等待发布后不会自动上线。正式发布成功前，已有正式版继续可读。","Scheduling does not publish the article. The current published version remains available until the new one is published.")}</p></header>
  <section className="review-decision-controls" aria-label={t("发布操作","Publication actions")}>
   {!canQueue&&!canPublish&&<p>{article.lifecycle!=='active'?t('文章已停用，不能安排或执行发布。','This article is inactive and cannot be published.'):article.status==='published'?t('当前版本已经发布。','This version is already published.'):!approval?t('当前版本没有可用于发布的二审批准，请先完成审核。','This version has no valid review approval. Complete the review first.'):t('当前状态不能安排或执行发布，请重新核对。','This version cannot be scheduled or published in its current state. Reload and check it.')}</p>}
   {(canQueue||canPublish)&&(!confirm?<div className="review-decision-actions">{canQueue&&<button type="button" disabled={locked||blocked} onClick={()=>setConfirm('queue')}>{t("加入等待发布","Schedule publication")}</button>}{canPublish&&<button type="button" disabled={locked||blocked} onClick={()=>setConfirm('publish')}>{t("正式发布此版本","Publish this version")}</button>}</div>:<div className="review-decision-confirm"><h3>{confirm==='queue'?t('确认安排此版本','Confirm schedule'):t('确认正式发布此版本','Confirm publication')}</h3><p>{english?`This applies to approved version ${revision}, reviewed by ${approval!.reviewerName}.`:`本次操作针对已批准的版本 ${revision}，由 ${approval!.reviewerName} 完成二审。`}</p>{confirm==='queue'?<p>{t("确认后进入等待发布；员工暂时看不到这次更新。","The update will be scheduled. Employees will not see it until it is published.")}</p>:<><p>{article.publishedRevision===null?(english?`Working revision ${revision} will become the first published version.`:`发布后，工作修订 ${revision} 将成为首个正式版。`):(english?`Working revision ${revision} will replace the current published content (working revision ${article.publishedRevision}).`:`发布后，工作修订 ${revision} 将替换正式内容（工作修订 ${article.publishedRevision}）。`)}</p><p>{t("具备当前阅读权限的员工将看到本次正文、分类和附件；旧链接也按新正式版的权限检查。","Employees with access will see this content, its categories and attachments. Existing links will follow the new version’s access rules.")}</p></>}<div className="review-decision-actions"><button type="button" disabled={Boolean(busy)||blocked&&!uncertain} onClick={()=>void change()}>{busy==='write'?t('正在提交…','Submitting…'):uncertain?t('重试原操作','Retry the same action'):confirm==='queue'?t('确认加入等待发布','Confirm schedule'):t('确认正式发布','Confirm publication')}</button><button type="button" disabled={locked} onClick={()=>{setConfirm(null);setError('');}}>{t("取消操作","Cancel")}</button></div></div>)}
   {error&&<p role="alert">{error}</p>}
  </section>
  <ArticleCategories options={article.categoryOptions} ids={article.categoryIds} locale={article.locale}/><FieldValues fields={article.customFields} locale={article.locale}/><section className="publication-preview" aria-label={t("发布内容核对","Review publication content")}><h3>{t("当前保存的内容","Current saved content")}</h3><p>{t("标签：","Tags: ")}{article.tags.length?article.tags.join(english?", ":"、"):t("无标签","None")}</p>{article.cover&&<figure className="review-decision-cover">{coverFailed?<p>{t("封面暂时无法读取，请核对原文件。","Could not load the cover. Check the original file.")}</p>:<img src={`/api/admin/assets/${encodeURIComponent(article.cover.assetId)}`} alt={article.cover.alt} style={{objectPosition:`50% ${article.cover.position}%`}} onError={()=>setCoverFailed(true)}/>}<figcaption>{t('文章封面','Cover')} · {article.cover.alt||t('未填写替代文字','No alt text')}</figcaption></figure>}<article className="review-decision-body" aria-label={t("当前保存正文","Current saved body")}><DocumentView document={reader} documentId={article.documentId} locale={article.locale} admin/>{!reader.editorBlocks&&article.blocks.length>0&&<MediaBlocks blocks={article.blocks} documentId={article.documentId} locale={article.locale} admin/>}</article></section>
  <section className="review-control-history" aria-label={t("发布记录","Publication history")}><h3>{t("发布记录","Publication history")}</h3><p>{english?`${detail.history.length} schedule or publication records loaded; showing at most the latest 20.`:`已载入 ${detail.history.length} 条安排或发布记录，最多显示最近 20 条。`}{detail.historyMore?t("另有更早记录，本页未载入。"," Older records are not loaded on this page."):""}</p>{detail.history.length?<ol>{detail.history.map(h=><li key={h.sequence}><p><strong>{h.action==='queue'?t('加入等待发布','Scheduled'):t('正式发布','Published')}</strong> · {t("版本","Version")} {h.revision}</p><p>{t("操作人：","By: ")}{h.actorName}</p><time dateTime={h.at}>{time(h.at,article.locale)} {t('（马来西亚时间）','(Malaysia time)')}</time></li>)}</ol>:<p>{t("暂未记录安排或发布操作。","No scheduling or publication actions yet.")}</p>}</section>
 </section>;
}
