'use client';
import Link from 'next/link';
import {ArticleCategories} from '../categories/ArticleCategories';
import {FieldValues} from '../fields/FieldValues';
/* eslint-disable @next/next/no-img-element -- private cover images require the current admin session. */
import {useRef,useState} from 'react';
import type {ReviewDetail,DecisionInput} from '../../review/decision';
import {readDecision,sendDecision,decisionError,DecisionRejected} from '../../review/decision-client';
import {DocumentView} from '../gitbook/Reading/DocumentView';
import {MediaBlocks} from '../gitbook/Media/MediaBlocks';
import {parseReaderBody} from '../../reader/body';
import {kinds,statuses} from '../../workspace/model';
type Pending={input:DecisionInput;revision:number;reviewerId:string};
export function ReviewDecision({initial}:{initial:ReviewDetail}){
 const [detail,setDetail]=useState(initial);const [action,setAction]=useState<'approve'|'reject'|null>(null);const [reason,setReason]=useState('');
 const [busy,setBusy]=useState<'read'|'write'|''>('');const [error,setError]=useState('');const [uncertain,setUncertain]=useState(false);const [blocked,setBlocked]=useState(false);const [acknowledged,setAcknowledged]=useState(false);const [coverFailed,setCoverFailed]=useState(false);
 // Ref guards close the gap before React commits disabled controls; reads and writes never overlap.
 const operation=useRef(false);const pending=useRef<Pending|null>(null);
 const {article,review}=detail;const eligible=detail.canDecide&&article.lifecycle==='active'&&article.status==='in_review'&&review?.status==='in_review';const locked=Boolean(busy)||uncertain;
 const validReason=reason.trim().length>0&&reason.trim().length<=2000;const currentReview=article.status==='in_review'&&review?.status==='in_review';
 async function reload(){if(operation.current||uncertain)return;operation.current=true;setBusy('read');setError('');setBlocked(true);try{const next=await readDecision(article.documentId,article.sequence);setDetail(next);setAction(null);setAcknowledged(false);setCoverFailed(false);setBlocked(false);}catch(e){setError(decisionError(e,true));}finally{operation.current=false;setBusy('');}}
 async function decide(){if(operation.current||(!uncertain&&(!eligible||blocked||!action||(action==='reject'&&!validReason))))return;
  const exact=pending.current??{input:{expectedSequence:article.sequence,action:action!,...(action==='reject'?{reason:reason.trim()}:{})},revision:review!.revision,reviewerId:review!.reviewerId};
  pending.current=exact;operation.current=true;setBusy('write');setError('');try{const result=await sendDecision(article.documentId,exact.input,exact.revision,exact.reviewerId);setDetail(old=>({...old,article:{...old.article,sequence:result.sequence,status:result.status},review:old.review?{...old.review,status:result.action==='approve'?'approved':'rejected',reason:result.reason}:null,canDecide:false}));pending.current=null;setUncertain(false);setAcknowledged(true);setAction(null);setBlocked(false);}catch(e){const unknown=uncertain||!(e instanceof DecisionRejected);setUncertain(unknown);if(!unknown){pending.current=null;setBlocked(true);}setError(decisionError(unknown?new Error('UNKNOWN_RESULT'):e));}finally{operation.current=false;setBusy('');}
 }
 const reader=parseReaderBody(article.body);const status=statuses.find(s=>s.id===article.status)?.name??article.status;
 return <section className="review-decision" aria-label="二审详情"><nav className="review-decision-links" aria-label="二审导航">{!locked&&<><Link prefetch={false} href="/admin">← 返回内容工作台</Link><details className="review-more-actions"><summary>更多操作</summary><div><a href={`/admin/editor?article=${encodeURIComponent(article.documentId)}`}>编辑文章</a><a href={`/admin/review/manage?article=${encodeURIComponent(article.documentId)}`}>管理本次审核</a><a href={`/admin/review/publish?article=${encodeURIComponent(article.documentId)}`}>安排与发布</a><a href={`/admin/availability?article=${encodeURIComponent(article.documentId)}`}>归档与下线</a><a href={`/admin/history?article=${encodeURIComponent(article.documentId)}`}>历史记录与版本</a></div></details></>}<button type="button" disabled={locked} onClick={()=>void reload()}>{busy==='read'?'正在读取…':'重新读取二审状态'}</button></nav>
 <ol className="review-progress" aria-label="内容流程">{statuses.map(s=><li key={s.id} aria-current={s.id===article.status?'step':undefined}>{s.name}</li>)}</ol><div className="review-reading-panel"><header><p className="review-decision-eyebrow">{currentReview?`送审版本 ${review.revision}`:'当前保存的内容'} · {status}</p><h2>{article.title}</h2><details className="review-extra-details"><summary>资料信息</summary><dl className="review-decision-metadata"><div><dt>资料类型</dt><dd>{kinds[article.kind]}</dd></div><div><dt>阅读范围</dt><dd>{{staff:'普通员工',ops:'Ops 与 Admin',admin:'仅 Admin'}[article.audience]}</dd></div><div><dt>文章标签</dt><dd>{article.tags.length?article.tags.join('、'):'无标签'}</dd></div><div><dt>二审管理员</dt><dd>{review?.reviewerName??'尚未提交二审'}</dd></div>{article.kind==='qa'&&<><div><dt>问答分类</dt><dd>{article.qa?.category||'未分类'}</dd></div><div><dt>问答排序</dt><dd>{article.qa?.position??0}</dd></div></>}</dl></details><p>{article.publishedRevision===null?'尚未发布。':`已有正式版 ${article.publishedRevision} 继续可读。`}二审批准不会自动发布。</p></header>
 {article.cover?<figure className="review-decision-cover">{coverFailed?<p>封面暂时无法读取，请核对原文件。</p>:<img src={`/api/admin/assets/${encodeURIComponent(article.cover.assetId)}`} alt={article.cover.alt} style={{objectPosition:`50% ${article.cover.position}%`}} onError={()=>setCoverFailed(true)}/>}<figcaption>文章封面 · {article.cover.alt||'未填写替代文字'} · 垂直位置 {article.cover.position}% <a href={`/api/admin/assets/${encodeURIComponent(article.cover.assetId)}`} target="_blank" rel="noopener noreferrer">打开封面原文件</a></figcaption></figure>:null}
 {review?.reason&&<aside className="review-return-reason"><h3>版本 {review.revision} 的退回原因</h3><p>{review.reason}</p>{article.status==='draft'&&<p>以上是先前送审版本的记录；下方显示修改后保存的草稿。</p>}</aside>}
 {Boolean(article.categoryIds?.length)&&<ArticleCategories options={article.categoryOptions} ids={article.categoryIds}/>}<FieldValues fields={article.customFields}/><article className="review-decision-body" aria-label={currentReview?'本次送审正文':'当前保存正文'}><DocumentView document={reader} documentId={article.documentId} admin/>{!reader.editorBlocks&&article.blocks.length>0&&<MediaBlocks blocks={article.blocks} documentId={article.documentId} admin/>}</article>
 </div><section className="review-decision-controls" aria-label="二审操作"><h3>本次送审</h3><dl className="review-side-facts"><div><dt>指定审核人</dt><dd>{review?.reviewerName??'尚未指定'}</dd></div><div><dt>版本号</dt><dd>{review?`v${review.revision}`:'尚未送审'}</dd></div><div><dt>提交时间</dt><dd>{review?new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Kuala_Lumpur',dateStyle:'short',timeStyle:'short'}).format(new Date(review.submittedAt)):'—'}</dd></div></dl>{eligible&&<p className="review-eligible-notice">你是指定二审人，可以批准或退回本次版本。</p>}{acknowledged&&<p role="status">{article.status==='approved'?'已经批准本次版本，仍需后续发布。':'需要修改：已退回本次版本。请根据原因编辑保存，再重新选择管理员提交二审。'}</p>}
 {article.lifecycle!=='active'?<p>文章已停用，当前不能执行二审决定。</p>:!review?<p>尚无二审记录。请先在编辑页保存并提交二审。</p>:currentReview&&!detail.canDecide?<p>仅指定的二审管理员 {review.reviewerName} 可以批准或退回。本页仅供核对内容。</p>:!currentReview&&!acknowledged?<p>本次二审已结束或尚未重新提交，当前不能批准或退回。{article.status==='changes_requested'?'请先修改并保存内容，再重新提交二审。':''}</p>:null}
 {eligible&&<>{!action?<div className="review-decision-actions"><button type="button" disabled={locked||blocked} onClick={()=>setAction('approve')}>批准本次版本</button><button type="button" disabled={locked||blocked} onClick={()=>setAction('reject')}>退回修改</button></div>:<div className="review-decision-confirm"><h3>{action==='approve'?'确认批准本次版本':'填写退回原因并确认'}</h3><p>本次操作只针对送审版本 {review!.revision}。{action==='approve'?'批准后进入“已经批准”，不会自动发布。':'退回后需要先修改保存，再重新提交二审。'}</p>{action==='reject'&&<label>退回原因<textarea aria-label="退回原因" rows={5} maxLength={2000} disabled={locked} value={reason} onChange={e=>setReason(e.target.value)}/><span>必填，最多 2000 字；具体说明需要修改的地方。</span></label>}<div className="review-decision-actions"><button type="button" disabled={Boolean(busy)||(!uncertain&&(blocked||(action==='reject'&&!validReason)))} onClick={()=>void decide()}>{busy==='write'?'正在提交决定…':uncertain?'重试原决定':action==='approve'?'确认批准':'确认退回'}</button><button type="button" disabled={locked} onClick={()=>{setAction(null);setError('');}}>取消决定</button></div></div>}</>}
 {error&&<p role="alert">{error}</p>}<p className="review-side-note">批准后不会自动发布。</p><a className="review-history-link" href={`/admin/history?article=${encodeURIComponent(article.documentId)}`}>查看审核记录与版本历史</a></section></section>;
}
