'use client';
import {useReviewLeaveGuard} from './useReviewLeaveGuard';
import {requestReviewLeave} from '../../review/leave';
import Link from 'next/link';
import {ArticleCategories} from '../categories/ArticleCategories';
import {FieldValues} from '../fields/FieldValues';
/* eslint-disable @next/next/no-img-element -- private cover images require the current admin session. */
import {useRef,useState} from 'react';
import type {ReviewDetail,DecisionInput} from '../../review/decision';
import {readDecision,sendDecision,decisionError,DecisionRejected} from '../../review/decision-client';
import {DocumentView} from '../gitbook/Reading/DocumentView';
import {MediaBlocks} from '../gitbook/Media/MediaBlocks';
import {parseReaderBody} from '../../reader/body';
import {kinds,statuses} from '../../workspace/model';
type Pending={input:DecisionInput;revision:number;reviewerId:string};
export function ReviewDecision({initial}:{initial:ReviewDetail}){
 const [detail,setDetail]=useState(initial);const [action,setAction]=useState<'approve'|'reject'|null>(null);const [reason,setReason]=useState('');const [englishReviewConfirmed,setEnglishReviewConfirmed]=useState(false);
 const [busy,setBusy]=useState<'read'|'write'|''>('');const [error,setError]=useState('');const [uncertain,setUncertain]=useState(false);const [blocked,setBlocked]=useState(false);const [acknowledged,setAcknowledged]=useState(false);const [coverFailed,setCoverFailed]=useState(false);
 // Ref guards close the gap before React commits disabled controls; reads and writes never overlap.
 const operation=useRef(false);const pending=useRef<Pending|null>(null);
 const {article,review}=detail;const eligible=detail.canDecide&&article.lifecycle==='active'&&article.status==='in_review'&&review?.status==='in_review';const locked=Boolean(busy)||uncertain;
 const validReason=reason.trim().length>0&&reason.trim().length<=2000;const currentReview=article.status==='in_review'&&review?.status==='in_review';
 useReviewLeaveGuard({dirty:!acknowledged&&(reason.length>0||action!==null&&!blocked),busy:Boolean(busy),uncertain});
 async function reload(){if(operation.current||uncertain)return;if(!(await requestReviewLeave('discard'))||operation.current||uncertain)return;operation.current=true;setBusy('read');setError('');setBlocked(true);try{const next=await readDecision(article.documentId,article.sequence);setDetail(next);setAction(null);setReason('');setEnglishReviewConfirmed(false);setAcknowledged(false);setCoverFailed(false);setBlocked(false);}catch(e){setError(decisionError(e,true));}finally{operation.current=false;setBusy('');}}
 async function decide(){if(operation.current||(!uncertain&&(!eligible||blocked||!action||(action==='reject'&&!validReason)||(action==='approve'&&article.locale==='en'&&!englishReviewConfirmed))))return;
  const exact=pending.current??{input:{expectedSequence:article.sequence,action:action!,...(action==='reject'?{reason:reason.trim()}:{}),...(action==='approve'&&article.locale==='en'?{englishReviewConfirmed:true as const}:{})},revision:review!.revision,reviewerId:review!.reviewerId};
  pending.current=exact;operation.current=true;setBusy('write');setError('');try{const result=await sendDecision(article.documentId,exact.input,exact.revision,exact.reviewerId);setDetail(old=>({...old,article:{...old.article,sequence:result.sequence,status:result.status},review:old.review?{...old.review,status:result.action==='approve'?'approved':'rejected',reason:result.reason}:null,canDecide:false}));pending.current=null;setUncertain(false);setAcknowledged(true);setAction(null);setReason('');setBlocked(false);}catch(e){const unknown=uncertain||!(e instanceof DecisionRejected);setUncertain(unknown);if(!unknown){pending.current=null;setBlocked(true);}setError(decisionError(unknown?new Error('UNKNOWN_RESULT'):e));}finally{operation.current=false;setBusy('');}
 }
 const reader=parseReaderBody(article.body);const english=article.locale==='en';const t=(zh:string,en:string)=>english?en:zh;
 const status=english?{draft:'Draft',in_review:'In review',changes_requested:'Changes requested',approved:'Approved',queued:'Scheduled',published:'Published'}[article.status]??article.status:statuses.find(s=>s.id===article.status)?.name??article.status;
 return <section className="review-decision" aria-label={t("二审详情","Review details")}><nav className="review-decision-links" aria-label={t("二审导航","Review navigation")}>{!locked&&<><Link prefetch={false} href="/admin">← {t("返回内容工作台","Back to content")}</Link><details className="review-more-actions"><summary>{t("更多操作","More actions")}</summary><div><a href={`/admin/editor?article=${encodeURIComponent(article.documentId)}`}>{t("编辑文章","Edit article")}</a><a href={`/admin/review/manage?article=${encodeURIComponent(article.documentId)}`}>{t("管理本次审核","Manage review")}</a><a href={`/admin/review/publish?article=${encodeURIComponent(article.documentId)}`}>{t("安排与发布","Schedule and publish")}</a><a href={`/admin/availability?article=${encodeURIComponent(article.documentId)}`}>{t("归档与下线","Archive or unpublish")}</a><a href={`/admin/history?article=${encodeURIComponent(article.documentId)}`}>{t("历史记录与版本","History and versions")}</a></div></details></>}<button type="button" disabled={locked} onClick={()=>void reload()}>{busy==='read'?t('正在读取…','Loading…'):t('重新读取二审状态','Reload review status')}</button></nav>
 <ol className="review-progress" aria-label={t("内容流程","Content workflow")}>{statuses.map(s=><li key={s.id} aria-current={s.id===article.status?'step':undefined}>{english?{draft:"Draft",in_review:"In review",changes_requested:"Changes requested",approved:"Approved",queued:"Scheduled",published:"Published"}[s.id]??s.id:s.name}</li>)}</ol><div className="review-reading-panel"><header><p className="review-decision-eyebrow">{currentReview?(english?`Version ${review.revision} under review`:`送审版本 ${review.revision}`):t('当前保存的内容','Current saved content')} · {status}</p><h2>{article.title}</h2><details className="review-extra-details"><summary>{t("资料信息","Article details")}</summary><dl className="review-decision-metadata"><div><dt>{t("资料类型","Content type")}</dt><dd>{english?{article:"Knowledge article",ops:"OPS Internal",reference:"Reference",qa:"Q&A"}[article.kind]:kinds[article.kind]}</dd></div><div><dt>{t("阅读范围","Who can read")}</dt><dd>{english?{staff:'All staff',ops:'Ops and Admin',admin:'Admin only'}[article.audience]:{staff:'普通员工',ops:'Ops 与 Admin',admin:'仅 Admin'}[article.audience]}</dd></div><div><dt>{t("文章标签","Tags")}</dt><dd>{article.tags.length?article.tags.join(english?', ':'、'):t('无标签','None')}</dd></div><div><dt>{t("二审管理员","Reviewer")}</dt><dd>{review?.reviewerName??t('尚未提交二审','Not submitted for review')}</dd></div>{article.kind==='qa'&&<><div><dt>{t("问答分类","Q&A category")}</dt><dd>{article.qa?.category||t('未分类','Uncategorized')}</dd></div><div><dt>{t("问答排序","Q&A order")}</dt><dd>{article.qa?.position??0}</dd></div></>}</dl></details><p>{article.publishedRevision===null?t('尚未发布。','Not published yet.'):english?`The published version remains available (working revision ${article.publishedRevision}).`:`已有正式内容（工作修订 ${article.publishedRevision}） 继续可读。`}{english?' ':null}{t('二审批准不会自动发布。','Approval does not publish this draft.')}</p></header>
 {article.cover?<figure className="review-decision-cover">{coverFailed?<p>{t("封面暂时无法读取，请核对原文件。","Could not load the cover. Check the original file.")}</p>:<img src={`/api/admin/assets/${encodeURIComponent(article.cover.assetId)}`} alt={article.cover.alt} style={{objectPosition:`50% ${article.cover.position}%`}} onError={()=>setCoverFailed(true)}/>}<figcaption>{t('文章封面','Cover')} · {article.cover.alt||t('未填写替代文字','No alt text')} · {t('垂直位置','Vertical position')} {article.cover.position}% <a href={`/api/admin/assets/${encodeURIComponent(article.cover.assetId)}`} target="_blank" rel="noopener noreferrer">{t("打开封面原文件","Open original cover")}</a></figcaption></figure>:null}
 <aside className="review-return-reason"><h3>{t("本次更新说明","What changed")}</h3><p className="review-release-note">{article.releaseNote||t('未填写；发布后更新日志只显示资料标题。','No update note. The change log will show only the article title.')}</p><p>{t("这段说明会随本次正文一起二审；只有正式发布后才会显示给有阅读权限的员工。","The update note is reviewed with this draft. Readers with access see it only after publication.")}</p></aside>
 {review?.reason&&<aside className="review-return-reason"><h3>{english?`Why version ${review.revision} was returned`:`版本 ${review.revision} 的退回原因`}</h3><p>{review.reason}</p>{article.status==='draft'&&<p>{t("以上是先前送审版本的记录；下方显示修改后保存的草稿。","This note belongs to an earlier review. The revised draft appears below.")}</p>}</aside>}
 {Boolean(article.categoryIds?.length)&&<ArticleCategories options={article.categoryOptions} ids={article.categoryIds}/>}<FieldValues fields={article.customFields}/><article className="review-decision-body" aria-label={currentReview?t('本次送审正文','Body under review'):t('当前保存正文','Current saved body')}><DocumentView document={reader} documentId={article.documentId} locale={article.locale} admin/>{!reader.editorBlocks&&article.blocks.length>0&&<MediaBlocks blocks={article.blocks} documentId={article.documentId} locale={article.locale} admin/>}</article>
 </div><section className="review-decision-controls" aria-label={t("二审操作","Review actions")}><h3>{t("本次送审","Current review")}</h3><dl className="review-side-facts"><div><dt>{t("指定审核人","Assigned reviewer")}</dt><dd>{review?.reviewerName??t('尚未指定','Not assigned')}</dd></div><div><dt>{t("版本号","Version")}</dt><dd>{review?`v${review.revision}`:t('尚未送审','Not submitted')}</dd></div><div><dt>{t("提交时间","Submitted")}</dt><dd>{review?new Intl.DateTimeFormat(english?'en':'zh-CN',{timeZone:'Asia/Kuala_Lumpur',dateStyle:'short',timeStyle:'short'}).format(new Date(review.submittedAt)):'—'}</dd></div></dl>{eligible&&<p className="review-eligible-notice">{t("你是指定二审人，可以批准或退回本次版本。","You are the assigned reviewer. You can approve or return this version.")}</p>}{acknowledged&&<p role="status">{article.status==='approved'?t('已经批准本次版本，仍需后续发布。','Version approved. It still needs to be published.'):t('需要修改：已退回本次版本。请根据原因编辑保存，再重新选择管理员提交二审。','Changes requested. Edit and save the draft, then submit it for review again.')}</p>}
 {article.lifecycle!=='active'?<p>{t("文章已停用，当前不能执行二审决定。","This article is inactive. Review decisions are unavailable.")}</p>:!review?<p>{t("尚无二审记录。请先在编辑页保存并提交二审。","No review yet. Save the draft and submit it for review from the editor.")}</p>:currentReview&&!detail.canDecide?<p>{english?`Only the assigned reviewer, ${review.reviewerName}, can approve or return this version. This page is for reference only.`:`仅指定的二审管理员 ${review.reviewerName} 可以批准或退回。本页仅供核对内容。`}</p>:!currentReview&&!acknowledged?<p>{t("本次二审已结束或尚未重新提交，当前不能批准或退回。","This review has ended or has not been resubmitted. You cannot decide it now.")}{article.status==='changes_requested'?t("请先修改并保存内容，再重新提交二审。"," Make the requested changes, save, then resubmit."):""}</p>:null}
 {eligible&&<>{!action?<div className="review-decision-actions"><button type="button" disabled={locked||blocked} onClick={()=>setAction('approve')}>{t("批准本次版本","Approve version")}</button><button type="button" disabled={locked||blocked} onClick={()=>setAction('reject')}>{t("退回修改","Request changes")}</button></div>:<div className="review-decision-confirm"><h3>{action==='approve'?t('确认批准本次版本','Confirm approval'):t('填写退回原因并确认','Explain the requested changes')}</h3><p>{english?`This decision applies only to version ${review!.revision}. `:`本次操作只针对送审版本 ${review!.revision}。`}{action==='approve'?t("批准后进入“已经批准”，不会自动发布。","Approval will not publish it automatically."):t("退回后需要先修改保存，再重新提交二审。","The writer must make the changes, save, then submit it again.")}</p>{action==='approve'&&article.locale==='en'&&<label className="review-english-quality"><input type="checkbox" checked={englishReviewConfirmed} disabled={locked} onChange={event=>setEnglishReviewConfirmed(event.target.checked)}/><span>{t("我已逐项核对英文标题、步骤、按钮文案、链接说明和术语；表达自然，业务含义与已批准的中文内容一致。若我无法判断英语质量，应退回并交由熟悉业务且英语流利的审核人处理。","I have reviewed the English title, steps, button text, links and terminology. The writing reads naturally and preserves the approved business meaning. If I cannot judge its quality, I will return it for review by someone fluent in English and familiar with the process.")}</span></label>}{action==='reject'&&<label>{t("退回原因","Reason for requesting changes")}<textarea aria-label={t("退回原因","Reason for requesting changes")} rows={5} maxLength={2000} disabled={locked} value={reason} onChange={e=>setReason(e.target.value)}/><span>{t("必填，最多 2000 字；具体说明需要修改的地方。","Required, up to 2,000 characters. Explain exactly what needs to change.")}</span></label>}<div className="review-decision-actions"><button type="button" disabled={Boolean(busy)||(!uncertain&&(blocked||(action==='reject'&&!validReason)||(action==='approve'&&article.locale==='en'&&!englishReviewConfirmed)))} onClick={()=>void decide()}>{busy==='write'?t('正在提交决定…','Submitting decision…'):uncertain?t('重试原决定','Retry the same decision'):action==='approve'?t('确认批准','Confirm approval'):t('确认退回','Confirm return')}</button><button type="button" disabled={locked} onClick={async()=>{if(reason.length&&!(await requestReviewLeave('discard')))return;setAction(null);setReason('');setEnglishReviewConfirmed(false);setError('');}}>{t("取消决定","Cancel decision")}</button></div></div>}</>}
 {error&&<p role="alert">{error}</p>}<p className="review-side-note">{t("批准后不会自动发布。","Approval does not publish the article.")}</p><a className="review-history-link" href={`/admin/history?article=${encodeURIComponent(article.documentId)}`}>{t("查看审核记录与版本历史","View review and version history")}</a></section></section>;
}
