'use client';
import {useEffect,useRef,useState} from 'react';
import {readReviewers,submitReview,reviewError,ReviewRejected,type ReviewerPage,type ReviewSubmission,type SubmissionAck} from '../../review/client';
export function SubmitReview({id,sequence,disabled,onLock,onSubmitted,compact=false,locale='zh-CN'}:{id:string;sequence:number|null;disabled:boolean;onLock:(locked:boolean)=>void;onSubmitted:(result:SubmissionAck)=>void;compact?:boolean;locale?:'zh-CN'|'en'}){
 const t=(zh:string,en:string)=>locale==='en'?en:zh;
 const [open,setOpen]=useState(false);const [page,setPage]=useState<ReviewerPage|null>(null);const [selected,setSelected]=useState('');const [busy,setBusy]=useState<'read'|'submit'|''>('');const [error,setError]=useState('');const [pending,setPending]=useState<{input:ReviewSubmission;revision:number}|null>(null);const [uncertain,setUncertain]=useState(false);const [rejected,setRejected]=useState(false);const [done,setDone]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const el=dialog.current;if(!compact||!el)return;if(open&&!done&&!el.open)el.showModal();else if((!open||done)&&el.open)el.close();},[compact,open,done]);
 const close=()=>{if(busy||uncertain)return;setOpen(false);setPage(null);setSelected('');setError('');};
 const stale=page!==null&&page.sequence!==sequence;
 async function read(after=''){if(busy||uncertain||sequence===null)return;setOpen(true);setBusy('read');setError('');try{const next=await readReviewers(id,sequence,after);setPage(previous=>after&&previous?.sequence===next.sequence?{...next,reviewers:[...previous.reviewers,...next.reviewers.filter(a=>!previous.reviewers.some(b=>b.id===a.id))]}:next);if(!after)setSelected('');setRejected(false);}catch(e){setError(reviewError(e,true));if(!after)setPage(null);}finally{setBusy('');}}
 async function submit(){if(busy||(!uncertain&&(disabled||stale||rejected||!page||!selected||sequence===null)))return;const exact=pending??{input:{expectedSequence:sequence!,reviewerId:selected},revision:page!.revision};setPending(exact);setBusy('submit');setError('');onLock(true);try{const result=await submitReview(id,exact.input,exact.revision);setDone(true);setPending(null);setUncertain(false);onSubmitted(result);onLock(false);}catch(e){const unknown=uncertain||!(e instanceof ReviewRejected);setUncertain(unknown);if(!unknown){setPending(null);setRejected(true);onLock(false);}setError(unknown?reviewError(new Error('UNKNOWN_RESULT')):reviewError(e));}finally{setBusy('');}}
 const panel=<div className="review-submission-panel"><h3 id="editor-review-title">{t('选择二审管理员','Choose a reviewer')}</h3><p>{t('提交后暂停编辑本次版本；已有正式版本保持可读。','This draft is locked after submission. The published version stays available.')}</p>{busy==='read'&&<p>{t('正在读取可用管理员…','Loading available reviewers…')}</p>}{page&&<><label>{t('二审管理员','Reviewer')}<select aria-label={t('二审管理员','Reviewer')} value={selected} disabled={Boolean(busy)||uncertain||disabled||stale} onChange={e=>setSelected(e.target.value)}><option value="">{t('请选择另一位管理员','Choose another admin')}</option>{page.reviewers.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{page.reviewers.length===0&&!page.nextCursor&&!busy&&!error&&<div role="status"><p>{t('这篇内容目前没有可用的二审管理员。','No reviewer is available for this draft.')}</p><p>{t('二审人员不能是本次提交人、作者或编辑人，且账号必须处于可用状态。请在成员与权限中核对管理员配置，再重新读取名单。','The reviewer must be an active admin who did not write or submit this draft. Check member access, then refresh the list.')}</p></div>}{page.nextCursor&&<button type="button" disabled={Boolean(busy)||uncertain||stale} onClick={()=>void read(page.nextCursor!)}>{t('载入更多管理员','Load more reviewers')}</button>}</>}{stale&&<p>{t('草稿已更新，请重新读取管理员，确认本次版本后再提交。','This draft changed. Refresh the reviewer list before submitting it.')}</p>}{error&&<p role="alert">{error}</p>}<div className="review-submission-actions"><button type="button" disabled={Boolean(busy)||(!uncertain&&(disabled||!page||!selected||stale||rejected))} onClick={()=>void submit()}>{busy==='submit'?t('正在提交…','Submitting…'):uncertain?t('重试原提交','Retry the same submission'):t('确认提交二审','Submit for review')}</button><button type="button" disabled={Boolean(busy)||uncertain||disabled} onClick={()=>void read()}>{t('重新读取管理员','Refresh reviewers')}</button><button type="button" disabled={Boolean(busy)||uncertain} onClick={()=>{setOpen(false);setPage(null);setSelected('');setError('');}}>{t('取消二审提交','Cancel submission')}</button></div></div>;
 return <section className={compact?"review-submission is-compact":"review-submission"} aria-label={t('提交二审','Submit for review')}>{done?<p role="status">{compact?t('已提交二审','Sent for review'):t('已提交给所选管理员二审，当前版本已锁定。已有正式版本继续可读。','Sent to the selected reviewer. This draft is locked; the published version stays available.')}</p>:<><button type="button" disabled={disabled||sequence===null||Boolean(busy)||uncertain} onClick={()=>void read()}>{t('提交二审','Submit for review')}</button>{!compact&&<p>{t('先保存文章，再选择另一位管理员二审。二审批准后，内容才会进入“已经批准”。','Save the draft first, then choose another admin to review it. Approval does not publish it.')}</p>}{compact?<dialog ref={dialog} className="editor-review-dialog" aria-labelledby="editor-review-title" onCancel={event=>{event.preventDefault();close();}}>{panel}</dialog>:open&&panel}</>}</section>;
}
