'use client';
import {useEffect,useRef,useState} from 'react';
import {readReviewers,submitReview,reviewError,ReviewRejected,type ReviewerPage,type ReviewSubmission,type SubmissionAck} from '../../review/client';
export function SubmitReview({id,sequence,disabled,onLock,onSubmitted,compact=false}:{id:string;sequence:number|null;disabled:boolean;onLock:(locked:boolean)=>void;onSubmitted:(result:SubmissionAck)=>void;compact?:boolean}){
 const [open,setOpen]=useState(false);const [page,setPage]=useState<ReviewerPage|null>(null);const [selected,setSelected]=useState('');const [busy,setBusy]=useState<'read'|'submit'|''>('');const [error,setError]=useState('');const [pending,setPending]=useState<{input:ReviewSubmission;revision:number}|null>(null);const [uncertain,setUncertain]=useState(false);const [rejected,setRejected]=useState(false);const [done,setDone]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const el=dialog.current;if(!compact||!el)return;if(open&&!done&&!el.open)el.showModal();else if((!open||done)&&el.open)el.close();},[compact,open,done]);
 const close=()=>{if(busy||uncertain)return;setOpen(false);setPage(null);setSelected('');setError('');};
 const stale=page!==null&&page.sequence!==sequence;
 async function read(after=''){if(busy||uncertain||sequence===null)return;setOpen(true);setBusy('read');setError('');try{const next=await readReviewers(id,sequence,after);setPage(previous=>after&&previous?.sequence===next.sequence?{...next,reviewers:[...previous.reviewers,...next.reviewers.filter(a=>!previous.reviewers.some(b=>b.id===a.id))]}:next);if(!after)setSelected('');setRejected(false);}catch(e){setError(reviewError(e,true));if(!after)setPage(null);}finally{setBusy('');}}
 async function submit(){if(busy||(!uncertain&&(disabled||stale||rejected||!page||!selected||sequence===null)))return;const exact=pending??{input:{expectedSequence:sequence!,reviewerId:selected},revision:page!.revision};setPending(exact);setBusy('submit');setError('');onLock(true);try{const result=await submitReview(id,exact.input,exact.revision);setDone(true);setPending(null);setUncertain(false);onSubmitted(result);onLock(false);}catch(e){const unknown=uncertain||!(e instanceof ReviewRejected);setUncertain(unknown);if(!unknown){setPending(null);setRejected(true);onLock(false);}setError(unknown?reviewError(new Error('UNKNOWN_RESULT')):reviewError(e));}finally{setBusy('');}}
 const panel=<div className="review-submission-panel"><h3 id="editor-review-title">选择二审管理员</h3><p>提交后暂停编辑本次版本；已有正式版本保持可读。</p>{busy==='read'&&<p>正在读取可用管理员…</p>}{page&&<><label>二审管理员<select aria-label="二审管理员" value={selected} disabled={Boolean(busy)||uncertain||disabled||stale} onChange={e=>setSelected(e.target.value)}><option value="">请选择另一位管理员</option>{page.reviewers.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{page.reviewers.length===0&&<p>没有其他可用的二审管理员。请先完成管理员配置；不能自行审核自己的内容。</p>}{page.nextCursor&&<button type="button" disabled={Boolean(busy)||uncertain||stale} onClick={()=>void read(page.nextCursor!)}>载入更多管理员</button>}</>}{stale&&<p>草稿已更新，请重新读取管理员，确认本次版本后再提交。</p>}{error&&<p role="alert">{error}</p>}<div className="review-submission-actions"><button type="button" disabled={Boolean(busy)||(!uncertain&&(disabled||!page||!selected||stale||rejected))} onClick={()=>void submit()}>{busy==='submit'?'正在提交…':uncertain?'重试原提交':'确认提交二审'}</button><button type="button" disabled={Boolean(busy)||uncertain||disabled} onClick={()=>void read()}>重新读取管理员</button><button type="button" disabled={Boolean(busy)||uncertain} onClick={()=>{setOpen(false);setPage(null);setSelected('');setError('');}}>取消二审提交</button></div></div>;
 return <section className={compact?"review-submission is-compact":"review-submission"} aria-label="提交二审">{done?<p role="status">{compact?"已提交二审":"已提交给所选管理员二审，当前版本已锁定。已有正式版本继续可读。"}</p>:<><button type="button" disabled={disabled||sequence===null||Boolean(busy)||uncertain} onClick={()=>void read()}>提交二审</button>{!compact&&<p>先保存文章，再选择另一位管理员二审。二审批准后，内容才会进入“已经批准”。</p>}{compact?<dialog ref={dialog} className="editor-review-dialog" aria-labelledby="editor-review-title" onCancel={event=>{event.preventDefault();close();}}>{panel}</dialog>:open&&panel}</>}</section>;
}
