'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {confirmAction} from '../feedback/feedback';
import {pruneDeviceRecovery,clearDeviceRecovery,enableRecovery,readLocalCopy,recoveryEnabled,removeLocalCopy,writeLocalCopy,type LocalCopy} from '../../editor/local-recovery';
export function LocalRecovery({owner,id,sequence,text,dirty,blocked,onRestore,locale='zh-CN'}:{owner:string;id:string;sequence:number|null;text:string;dirty:boolean;blocked:boolean;locale?:'zh-CN'|'en';onRestore:(text:string)=>void}){
 const t=useCallback((zh:string,en:string)=>locale==='en'?en:zh,[locale]);
 const [enabled,setEnabled]=useState(false),[candidate,setCandidate]=useState<LocalCopy|null>(null),[message,setMessage]=useState(''),[checking,setChecking]=useState(false);
 const [ready,setReady]=useState(false);const lastWritten=useRef<string|null>(null);
 useEffect(()=>{let cancelled=false;queueMicrotask(()=>{if(cancelled)return;try{pruneDeviceRecovery(localStorage);setEnabled(recoveryEnabled(localStorage,owner));setCandidate(readLocalCopy(localStorage,owner,id));}catch{setMessage(t('浏览器无法使用本机恢复，请保留页面并复制输入。','Local recovery is unavailable in this browser. Keep this page open and copy your input.'));}setReady(true);});return()=>{cancelled=true;};},[owner,id,t]);
 useEffect(()=>{const reset=()=>{setEnabled(false);setCandidate(null);};const storage=(e:StorageEvent)=>{if(e.key===null||e.key?.startsWith('juyu:editor-recovery:')){try{if(!recoveryEnabled(localStorage,owner))reset();}catch{reset();}}};addEventListener('storage',storage);addEventListener('juyu-clear-recovery',reset);return()=>{removeEventListener('storage',storage);removeEventListener('juyu-clear-recovery',reset);};},[owner]);
 useEffect(()=>{if(!ready||!enabled||candidate||!owner)return;let cancelled=false;queueMicrotask(()=>{if(cancelled)return;try{if(!recoveryEnabled(localStorage,owner))return;if(dirty){const other=readLocalCopy(localStorage,owner,id);if(other&&other.text!==lastWritten.current&&other.text!==text){setCandidate(other);setMessage(t('另一页面有本机副本，已停止覆盖。请先核对两份输入。','Another tab has a local copy. We stopped overwriting it. Compare both copies first.'));return;}writeLocalCopy(localStorage,{owner,id,sequence,text,at:Date.now()});lastWritten.current=text;setMessage(t('未保存输入已备份到本机。','Unsaved input backed up on this device.'));}else if(!blocked){removeLocalCopy(localStorage,owner,id);setMessage(t('服务器已保存，无需本机副本。','Saved on the server. No local copy is needed.'));}}catch{setMessage(t('本机备份失败，可能因为存储空间不足。请保留页面并复制输入。','Local backup failed, possibly because storage is full. Keep this page open and copy your input.'));}});return()=>{cancelled=true;};},[ready,enabled,candidate,owner,id,sequence,text,dirty,blocked,t]);
 if(!owner)return null;
 return <details className="editor-input-backup" open={candidate?true:undefined}><summary>{t("本机草稿恢复","Local draft recovery")}{enabled?t(" · 已开启"," · On"):""}</summary><p>{t("仅在自己的设备开启。副本未加密，24 小时内可恢复，过期后再次打开编辑器时清理；退出时清除。恢复不会直接发布。","Turn this on only on your own device. Local copies are not encrypted. You can recover them for 24 hours; they are cleared after expiry when you reopen the editor, or when you sign out. Recovery never publishes an article.")}</p>
 {!enabled?<button type="button" onClick={()=>{try{enableRecovery(localStorage,owner);setEnabled(true);}catch{setMessage(t('无法开启本机恢复，请复制输入保管。','Could not turn on local recovery. Copy your input to keep it safe.'));}}}>{t("在此设备开启恢复","Turn on recovery on this device")}</button>:<button type="button" onClick={async()=>{if(!await confirmAction(t('关闭并删除此浏览器的本机恢复副本？服务器草稿不受影响。','Turn off local recovery and delete copies on this browser? Your server draft will not change.')))return;try{clearDeviceRecovery(localStorage);dispatchEvent(new Event('juyu-clear-recovery'));setMessage(t('本机副本已清除。','Local copies deleted.'));}catch{setMessage(t('本机副本未能清除，请在浏览器设置清除网站数据。','Could not delete the local copies. Clear this site’s data in your browser settings.'));}}}>{t("关闭并清除本机副本","Turn off and delete local copies")}</button>}
 {candidate&&<section aria-label={t("可恢复输入","Recoverable input")}><p>{t("发现未保存输入：","Unsaved input found: ")}{new Date(candidate.at).toLocaleString(locale)}{t("。恢复前会核对服务器版本。",". We will check the server version before restoring it.")}</p><details><summary>{t("查看副本以便手动复制","View copy for manual copying")}</summary><textarea aria-label={t("本机恢复副本","Local recovery copy")} readOnly value={candidate.text} rows={6}/></details><button type="button" disabled={blocked||checking} onClick={async()=>{if(!await confirmAction(t('用本机副本替换当前编辑区输入？恢复后仍需检查并保存。','Replace the current editor input with this local copy? Check and save it afterward.'),t('恢复草稿？','Restore draft?')))return;setChecking(true);try{
 const response=await fetch(`/api/admin/editor/${encodeURIComponent(id)}`,{cache:'no-store'});
 if(sequence===null){if(response.status!==404)throw Error('SERVER_CHANGED');}
 else{if(!response.ok)throw Error('SERVER_CHANGED');const latest=await response.json();if(latest.documentId!==id||latest.sequence!==sequence||candidate.sequence!==sequence||latest.lifecycle!=='active'||latest.status==='in_review')throw Error('SERVER_CHANGED');}
 onRestore(candidate.text);lastWritten.current=candidate.text;setCandidate(null);setMessage(t('已恢复到编辑区，请核对内容。','Restored to the editor. Please check the content.'));
 }catch{setMessage(t('无法安全恢复：服务器版本或权限可能已变化。副本仍保留，请复制后与最新文章对照。','Cannot safely restore: the server version or your access may have changed. Your local copy is still here. Copy it and compare it with the latest article.'));}finally{setChecking(false);}}}>{t("恢复到编辑区","Restore to editor")}</button><button type="button" disabled={checking} onClick={async()=>{if(await confirmAction(t('删除这份本机副本？此操作不会删除服务器文章。','Delete this local copy? The server article will not be deleted.'))){try{removeLocalCopy(localStorage,owner,id);setCandidate(null);}catch{setMessage(t('副本未能删除。','Could not delete the copy.'));}}}}>{t("放弃此副本","Discard this copy")}</button></section>}
 {message&&<p role="status">{message}</p>}</details>;
}
