'use client';
import type {MediaBlock,ManagedAsset} from '../../media/model';
import {RichBlockFields} from '../rich-block-fields';
import {ScienceFields} from '../science-fields';
import {TableConfigFields} from './TableConfigFields';
import {ArticleReferenceFields} from './ArticleReferenceFields';
import {ExternalEmbed} from '../gitbook/Media/ExternalEmbed';
import {externalLinkSource} from '../../media/external-embed';
export function MediaFields({block,assets,documentId,frozen=false,locale='zh-CN',onChange}:{block:MediaBlock;assets:ManagedAsset[];documentId?:string;frozen?:boolean;locale?:'zh-CN'|'en';onChange:(b:MediaBlock)=>void}){
 const t=(zh:string,en:string)=>locale==='en'?en:zh;
 if(block.type==='hint'||block.type==='code'||block.type==='tabs'||block.type==='steps'||block.type==='columns')return <RichBlockFields block={block} assets={assets} documentId={documentId} frozen={frozen} locale={locale} onChange={onChange}/>;
 if(block.type==='math'||block.type==='diagram')return <ScienceFields block={block} locale={locale} onChange={onChange}/>;
 if(block.type==='articleReference')return <ArticleReferenceFields block={block} locale={locale} onChange={onChange}/>;
 if(block.type==='externalEmbed')return <><label>{t('外部内容网址','External URL')}<input aria-label={t('外部内容网址','External URL')} type="url" maxLength={2048} value={block.url} onChange={event=>onChange({...block,url:event.target.value})} placeholder="https://www.youtube.com/watch?v=…"/></label><label>{t('内容说明','Description')}<input aria-label={t('外部内容说明','External content description')} maxLength={300} value={block.caption} onChange={event=>onChange({...block,caption:event.target.value})}/></label><p>{t('YouTube、Vimeo、Loom、Figma 和 Google Drive 可在员工点击后站内预览；其他 HTTPS 网址会显示为外部链接卡片。PDF 保留链接。','Readers can open YouTube, Vimeo, Loom, Figma and Google Drive previews after clicking. Other HTTPS URLs appear as link cards. PDFs keep a clickable link.')}</p>{externalLinkSource(block.url)?<div aria-label={t('外部内容效果预览','External content preview')}><ExternalEmbed key={block.url} block={block}/></div>:block.url?<p role="alert">{t('请填写不含账号密码的 HTTPS 网址；不能使用本机或内网地址。','Use an HTTPS URL without credentials. Local and internal network addresses are not allowed.')}</p>:null}</>;
 if(block.type==='button')return <><label>{t('按钮文字','Button label')}<input aria-label={t('按钮文字','Button label')} maxLength={80} value={block.label} onChange={event=>onChange({...block,label:event.target.value})}/></label><label>{t('跳转地址','Link URL')}<input aria-label={t('按钮跳转地址','Button link URL')} maxLength={2048} placeholder={t('https://… 或 /help-centre?article=…','https://… or /help-centre?article=…')} value={block.href} onChange={event=>onChange({...block,href:event.target.value})}/></label><label>{t('按钮样式','Button style')}<select aria-label={t('按钮样式','Button style')} value={block.variant} onChange={event=>onChange({...block,variant:event.target.value as typeof block.variant})}><option value="primary">{t('主要操作','Primary')}</option><option value="secondary">{t('次要操作','Secondary')}</option></select></label><p>{t('填写后才能保存；外部网址在新标签打开，资料库内部链接留在当前页面。','Add a label and URL before saving. External links open in a new tab; Help Centre links stay on this page.')}</p></>;
 if(block.type==='table')return <><TableConfigFields block={block} locale={locale} onChange={onChange}/><div className="reader-scroll-region"><table><thead><tr>{block.headers.map((v,c)=><th key={c}><input aria-label={t(`表头 ${c+1}`,`Column heading ${c+1}`)} value={v} maxLength={200} onChange={e=>onChange({...block,headers:block.headers.map((old,j)=>j===c?e.target.value:old)})}/><button type="button" disabled={block.headers.length===1} onClick={()=>onChange({...block,headers:block.headers.filter((_,j)=>j!==c),rows:block.rows.map(r=>r.filter((_,j)=>j!==c))})}>{t(`删除列 ${c+1}`,`Delete column ${c+1}`)}</button></th>)}</tr></thead><tbody>{block.rows.map((row,r)=><tr key={r}>{row.map((v,c)=><td key={c}><textarea aria-label={t(`第 ${r+1} 行第 ${c+1} 列`,`Row ${r+1}, column ${c+1}`)} value={v} rows={2} maxLength={2000} onChange={e=>onChange({...block,rows:block.rows.map((old,i)=>i===r?old.map((t,j)=>j===c?e.target.value:t):old)})}/></td>)}<td><button type="button" onClick={()=>onChange({...block,rows:block.rows.filter((_,i)=>i!==r)})}>{t(`删除行 ${r+1}`,`Delete row ${r+1}`)}</button></td></tr>)}</tbody></table></div><div className="media-toolbar"><button type="button" disabled={block.rows.length>=200} onClick={()=>onChange({...block,rows:[...block.rows,block.headers.map(()=>'')]})}>{t('增加行','Add row')}</button><button type="button" disabled={block.headers.length>=8} onClick={()=>onChange({...block,headers:[...block.headers,t('新列','New column')],rows:block.rows.map(r=>[...r,''])})}>{t('增加列','Add column')}</button></div></>;
 return <><p>{assets.find(a=>a.id===block.assetId)?.filename??t('本篇附件','Article attachment')}</p>{block.type==='image'&&<label>{t('深色主题图片（可选）','Dark theme image (optional)')}<select value={block.darkAssetId??''} onChange={e=>onChange({...block,darkAssetId:e.target.value||null})}><option value="">{t('沿用浅色图片','Use the light theme image')}</option>{assets.filter(a=>a.status==='ready'&&a.mime.startsWith('image/')&&a.id!==block.assetId).map(a=><option key={a.id} value={a.id}>{a.filename}</option>)}</select></label>}<label>{t('说明','Caption')}<input value={block.caption} maxLength={500} onChange={e=>onChange({...block,caption:e.target.value})}/></label><label>{t('替代文字','Alt text')}<textarea value={block.alt} maxLength={500} onChange={e=>onChange({...block,alt:e.target.value})}/></label></>;
}
