'use client';
import type {MediaBlock,ManagedAsset} from '../../media/model';
import {RichBlockFields} from '../rich-block-fields';
import {ScienceFields} from '../science-fields';
import {TableConfigFields} from './TableConfigFields';
import {ArticleReferenceFields} from './ArticleReferenceFields';
import {ExternalEmbed} from '../gitbook/Media/ExternalEmbed';
import {externalLinkSource} from '../../media/external-embed';
export function MediaFields({block,assets,documentId,frozen=false,locale='zh-CN',onChange}:{block:MediaBlock;assets:ManagedAsset[];documentId?:string;frozen?:boolean;locale?:'zh-CN'|'en';onChange:(b:MediaBlock)=>void}){
 if(block.type==='hint'||block.type==='code'||block.type==='tabs'||block.type==='steps'||block.type==='columns')return <RichBlockFields block={block} assets={assets} documentId={documentId} frozen={frozen} locale={locale} onChange={onChange}/>;
 if(block.type==='math'||block.type==='diagram')return <ScienceFields block={block} onChange={onChange}/>;
 if(block.type==='articleReference')return <ArticleReferenceFields block={block} onChange={onChange}/>;
 if(block.type==='externalEmbed')return <><label>外部内容网址<input aria-label="外部内容网址" type="url" maxLength={2048} value={block.url} onChange={event=>onChange({...block,url:event.target.value})} placeholder="https://www.youtube.com/watch?v=…"/></label><label>内容说明<input aria-label="外部内容说明" maxLength={300} value={block.caption} onChange={event=>onChange({...block,caption:event.target.value})}/></label><p>YouTube、Vimeo、Loom、Figma 和 Google Drive 可在员工点击后站内预览；其他 HTTPS 网址会显示为外部链接卡片。PDF 保留链接。</p>{externalLinkSource(block.url)?<div aria-label="外部内容效果预览"><ExternalEmbed key={block.url} block={block}/></div>:block.url?<p role="alert">请填写不含账号密码的 HTTPS 网址；不能使用本机或内网地址。</p>:null}</>;
 if(block.type==='button')return <><label>按钮文字<input aria-label="按钮文字" maxLength={80} value={block.label} onChange={event=>onChange({...block,label:event.target.value})}/></label><label>跳转地址<input aria-label="按钮跳转地址" maxLength={2048} placeholder="https://… 或 /help-centre?article=…" value={block.href} onChange={event=>onChange({...block,href:event.target.value})}/></label><label>按钮样式<select aria-label="按钮样式" value={block.variant} onChange={event=>onChange({...block,variant:event.target.value as typeof block.variant})}><option value="primary">主要操作</option><option value="secondary">次要操作</option></select></label><p>填写后才能保存；外部网址在新标签打开，资料库内部链接留在当前页面。</p></>;
 if(block.type==='table')return <><TableConfigFields block={block} onChange={onChange}/><div className="reader-scroll-region"><table><thead><tr>{block.headers.map((v,c)=><th key={c}><input aria-label={`表头 ${c+1}`} value={v} maxLength={200} onChange={e=>onChange({...block,headers:block.headers.map((old,j)=>j===c?e.target.value:old)})}/><button type="button" disabled={block.headers.length===1} onClick={()=>onChange({...block,headers:block.headers.filter((_,j)=>j!==c),rows:block.rows.map(r=>r.filter((_,j)=>j!==c))})}>删除列 {c+1}</button></th>)}</tr></thead><tbody>{block.rows.map((row,r)=><tr key={r}>{row.map((v,c)=><td key={c}><textarea aria-label={`第 ${r+1} 行第 ${c+1} 列`} value={v} rows={2} maxLength={2000} onChange={e=>onChange({...block,rows:block.rows.map((old,i)=>i===r?old.map((t,j)=>j===c?e.target.value:t):old)})}/></td>)}<td><button type="button" onClick={()=>onChange({...block,rows:block.rows.filter((_,i)=>i!==r)})}>删除行 {r+1}</button></td></tr>)}</tbody></table></div><div className="media-toolbar"><button type="button" disabled={block.rows.length>=200} onClick={()=>onChange({...block,rows:[...block.rows,block.headers.map(()=>'')]})}>增加行</button><button type="button" disabled={block.headers.length>=8} onClick={()=>onChange({...block,headers:[...block.headers,'新列'],rows:block.rows.map(r=>[...r,''])})}>增加列</button></div></>;
 return <><p>{assets.find(a=>a.id===block.assetId)?.filename??'本篇附件'}</p>{block.type==='image'&&<label>深色主题图片（可选）<select value={block.darkAssetId??''} onChange={e=>onChange({...block,darkAssetId:e.target.value||null})}><option value="">沿用浅色图片</option>{assets.filter(a=>a.status==='ready'&&a.mime.startsWith('image/')&&a.id!==block.assetId).map(a=><option key={a.id} value={a.id}>{a.filename}</option>)}</select></label>}<label>说明<input value={block.caption} maxLength={500} onChange={e=>onChange({...block,caption:e.target.value})}/></label><label>替代文字<textarea value={block.alt} maxLength={500} onChange={e=>onChange({...block,alt:e.target.value})}/></label></>;
}
