import {test,expect,type Page} from '@playwright/test';import {analyticsBrowserBundle} from '../helpers/analytics-browser';
let bundle:Awaited<ReturnType<typeof analyticsBrowserBundle>>;test.beforeAll(async()=>{bundle=await analyticsBrowserBundle();});
async function mount(page:Page,props:unknown={documentId:'analytics-local',revision:1},mode='view',hidden=false){
 await page.route('**/__analytics_fixture',r=>r.fulfill({contentType:'text/html',body:`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${bundle.css}</style></head><body><header>使用采集 · 本地测试样例（非真实员工数据）</header><div id="analytics"></div><p id="reading">阅读不等待统计保存</p><script>window.fixtureVisible=${!hidden};Object.defineProperty(document,'visibilityState',{configurable:true,get:()=>window.fixtureVisible?'visible':'hidden'});window.changeVisibility=(v)=>{window.fixtureVisible=v;document.dispatchEvent(new Event('visibilitychange'));};</script><script id="data" type="application/json">${JSON.stringify({mode,props}).replace(/</g,'\\u003c')}</script><script>${bundle.script.replace(/<\/script/gi,'<\\/script')}</script></body></html>`}));await page.goto('/__analytics_fixture');
}
const search={status:'ready',query:'转出',page:2,pages:2,total:21,results:[{id:'analytics-local',revision:1,title:'转出 · 正文不进统计',href:'/__analytics_destination?article=analytics-local',breadcrumbs:['说明'],snippet:'摘要不进统计',kind:'article'}]};
test('view collection waits for visibility deduplicates StrictMode and uses a new id for a new visible visit',async({page})=>{
 const events:Record<string,unknown>[]=[];await page.route('**/api/analytics',r=>{const input=r.request().postDataJSON();events.push(input);return r.fulfill({json:{kind:input.kind,eventId:input.eventId}});});await mount(page,undefined,'view',true);await page.evaluate(()=>new Promise(requestAnimationFrame));expect(events).toEqual([]);await page.evaluate(()=>(window as unknown as {changeVisibility:(v:boolean)=>void}).changeVisibility(true));await expect.poll(()=>events.length).toBe(1);await page.evaluate(()=>{window.dispatchEvent(new Event('focus'));document.dispatchEvent(new Event('visibilitychange'));});await page.evaluate(()=>new Promise(requestAnimationFrame));expect(events.length).toBe(1);await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));await expect.poll(()=>events.length).toBe(2);expect(events[0].eventId).not.toBe(events[1].eventId);expect(Object.keys(events[0]).sort()).toEqual(['documentId','eventId','kind','revision']);
});
test('transient view failure retries the same event once without adding a blocking UI',async({page})=>{
 const events:unknown[]=[];await page.route('**/api/analytics',r=>{events.push(r.request().postDataJSON());return r.fulfill({status:503,json:{error:'ANALYTICS_UNAVAILABLE'}});});await mount(page);await expect(page.locator('#reading')).toBeVisible();await expect.poll(()=>events.length).toBe(2);expect(events[0]).toEqual(events[1]);await expect(page.getByRole('alert')).toHaveCount(0);await expect(page.getByRole('button')).toHaveCount(0);
});
test('leaving an article cancels its scheduled retry and records the next article with a new event id',async({page})=>{
 const events:Record<string,unknown>[]=[];await page.route('**/api/analytics',r=>{const input=r.request().postDataJSON();events.push(input);return input.documentId==='analytics-local'?r.fulfill({status:503,json:{error:'ANALYTICS_UNAVAILABLE'}}):r.fulfill({json:{kind:input.kind,eventId:input.eventId}});});await mount(page);await expect.poll(()=>events.length).toBe(1);await page.evaluate(()=>(window as unknown as {switchAnalytics:(id:string)=>void}).switchAnalytics('next'));await expect.poll(()=>events.length).toBe(2);await page.waitForTimeout(1100);expect(events.length).toBe(2);expect(events.map(x=>x.documentId)).toEqual(['analytics-local','next']);expect(events[0].eventId).not.toBe(events[1].eventId);
});
test('search impression and immediate keyboard click share the snapshot without delaying navigation',async({page})=>{
 const events:Record<string,unknown>[]=[];let release!:()=>void;const held=new Promise<void>(r=>release=r);await page.route('**/api/analytics',async r=>{const input=r.request().postDataJSON();events.push(input);await held;await r.fulfill({json:{kind:input.kind,eventId:input.eventId}}).catch(()=>{});});await page.route('**/__analytics_destination*',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><meta charset="utf-8"><h1>正式文章已打开 · 本地样例</h1>'}));await mount(page,{search},'search');await expect.poll(()=>events.filter(x=>x.kind==='search').length).toBe(1);const link=page.getByRole('link',{name:'阅读：'+search.results[0].title});await link.focus();await page.keyboard.press('Enter');await expect(page.getByRole('heading',{name:'正式文章已打开 · 本地样例'})).toBeVisible();await expect.poll(()=>events.filter(x=>x.kind==='search_click').length).toBe(1);const impression=events.find(x=>x.kind==='search')!,click=events.find(x=>x.kind==='search_click')!;expect(click.position).toBe(21);expect(click.search).toEqual({eventId:impression.eventId,query:'转出',page:2,total:21,results:[{documentId:'analytics-local',revision:1}]});expect(JSON.stringify(events)).not.toMatch(/正文不进|摘要不进|breadcrumbs|href/);release();
});
test('search zero results are captured but empty invalid and denied states are not',async({page})=>{
 const events:Record<string,unknown>[]=[];await page.route('**/api/analytics',r=>{const input=r.request().postDataJSON();events.push(input);return r.fulfill({json:{kind:input.kind,eventId:input.eventId}});});await mount(page,{search:{...search,results:[],total:0,page:1,pages:0}},'search');await expect.poll(()=>events.length).toBe(1);expect(events[0].total).toBe(0);
 for(const props of [{search:{...search,status:'empty',query:''}},{search:{...search,status:'invalid'}},{search,enabled:false}]){await page.unroute('**/__analytics_fixture');await mount(page,props,'search');await page.evaluate(()=>new Promise(requestAnimationFrame));expect(events.length).toBe(1);}
});
test('search navigation and non-result links do not count as search result clicks',async({page},info)=>{
 const events:Record<string,unknown>[]=[];await page.route('**/api/analytics',r=>{const input=r.request().postDataJSON();events.push(input);return r.fulfill({json:{kind:input.kind,eventId:input.eventId}});});await mount(page,{search},'search');await expect.poll(()=>events.length).toBe(1);await page.getByRole('link',{name:'返回资料目录'}).evaluate(el=>el.addEventListener('click',e=>e.preventDefault()));await page.getByRole('link',{name:'返回资料目录'}).click();expect(events.length).toBe(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`output/verification/analytics-search-${info.project.name}.png`,fullPage:true,animations:'disabled'});
});
test('middle-click is correlated while a rejected acknowledgement cannot block the result link',async({page})=>{
 const events:Record<string,unknown>[]=[];await page.route('**/api/analytics',r=>{events.push(r.request().postDataJSON());return r.fulfill({status:403,json:{error:'FORBIDDEN'}});});await mount(page,{search},'search');await expect.poll(()=>events.length).toBe(1);await page.getByRole('link',{name:'阅读：'+search.results[0].title}).evaluate(el=>el.dispatchEvent(new MouseEvent('auxclick',{button:1,bubbles:true})));await expect.poll(()=>events.length).toBe(2);expect(events[1].kind).toBe('search_click');await expect(page.getByRole('link',{name:'阅读：'+search.results[0].title})).toBeVisible();
});
test('real analytics endpoint refuses forged identities and has no public read API',async({request})=>{
 const r=await request.post('/api/analytics',{headers:{'x-role':'admin','x-user-id':'other'},data:{kind:'view',eventId:'00000000-0000-4000-8000-000000000001',documentId:'x',revision:1}});expect(r.status()).toBe(503);expect(r.headers()['cache-control']).toBe('private, no-store');expect(await r.json()).toEqual({error:'ANALYTICS_UNAVAILABLE'});expect((await request.get('/api/analytics')).status()).toBe(405);
});
