import {test,expect} from '@playwright/test';import {navigationBrowserBundle} from '../helpers/navigation-browser';
let bundle:Awaited<ReturnType<typeof navigationBrowserBundle>>;test.beforeAll(async()=>{bundle=await navigationBrowserBundle();});
test('only authorized formal reading emits a view and unavailable collection never blocks the article',async({page})=>{
 let failed=false;const events:unknown[]=[];const data=()=>({analytics:true,failed,pages:[{type:'document',id:'read-local',title:'阅读采集 · 本地样例',href:'/help-centre?article=read-local'}],requested:'read-local',article:{id:'read-local',title:'阅读采集 · 本地样例',revision:1,body:'# 正式说明\n\n统计失败仍能阅读。'}});await page.route('**/__analytics_reader',r=>r.fulfill({contentType:'text/html',body:`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${bundle.css}</style></head><body><div id="presentation"></div><script id="data" type="application/json">${JSON.stringify(data()).replace(/</g,'\\u003c')}</script><script>${bundle.script.replace(/<\/script/gi,'<\\/script')}</script></body></html>`}));await page.route('**/api/analytics',r=>{events.push(r.request().postDataJSON());return r.fulfill({status:403,json:{error:'FORBIDDEN'}});});await page.goto('/__analytics_reader');await expect.poll(()=>events.length).toBe(1);await expect(page.locator('.gitbook-document')).toContainText('统计失败仍能阅读');await expect(page.locator('#presentation')).not.toHaveAttribute('data-hydration-error');failed=true;await page.reload();await expect(page.locator('.gitbook-document')).toHaveCount(0);expect(events.length).toBe(1);
});
test('search analytics preserves the full GitBook sidebar and results layout in both themes',async({page},info)=>{
 const events:Record<string,unknown>[]=[];const data={analytics:true,pages:[{type:'document',id:'read-local',title:'转出说明',href:'/help-centre?article=read-local'}],retryHref:'/help-centre?q=转出',search:{status:'ready',query:'转出',page:1,pages:1,total:1,results:[{id:'read-local',title:'转出说明',href:'/help-centre?article=read-local',breadcrumbs:['本地样例'],kind:'article',revision:1,tags:['转出'],snippet:'这是已授权的正式搜索结果。'}]}};
 await page.route('**/__analytics_search_reader',r=>r.fulfill({contentType:'text/html',body:`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${bundle.css}</style></head><body><header>完整搜索采集 · 本地测试样例</header><div id="presentation"></div><script id="data" type="application/json">${JSON.stringify(data)}</script><script>${bundle.script.replace(/<\/script/gi,'<\\/script')}</script></body></html>`}));await page.route('**/api/analytics',r=>{const input=r.request().postDataJSON();events.push(input);return r.fulfill({json:{eventId:input.eventId,kind:input.kind}});});await page.goto('/__analytics_search_reader');await expect.poll(()=>events.length).toBe(1);if(info.project.name==='mobile'){await page.getByRole('button',{name:'打开文章目录'}).click();await expect(page.getByRole('dialog',{name:'文章目录菜单'}).getByRole('navigation',{name:'文章目录'})).toBeVisible();await page.keyboard.press('Escape');}else await expect(page.getByRole('navigation',{name:'文章目录'})).toBeVisible();await expect(page.locator('.search-analytics main')).toHaveCount(1);await expect(page.getByRole('link',{name:'阅读：转出说明'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('#presentation')).not.toHaveAttribute('data-hydration-error');await page.screenshot({path:`output/verification/analytics-layout-${info.project.name}.png`,fullPage:true,animations:'disabled'});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await expect.poll(()=>page.locator('html').evaluate(el=>getComputedStyle(el).backgroundColor)).toBe('rgb(25, 25, 31)');await page.screenshot({path:`output/verification/analytics-layout-dark-${info.project.name}.png`,fullPage:true,animations:'disabled'});
});
