import {test,expect,type Page} from '@playwright/test';
import {availabilityBrowserBundle,availabilityFixture as fixture} from '../helpers/availability-browser';
import type {AvailabilityDetail} from '../../src/availability/model';
let bundle:Awaited<ReturnType<typeof availabilityBrowserBundle>>;test.beforeAll(async()=>{bundle=await availabilityBrowserBundle();});
async function mount(page:Page,initial:unknown=fixture,list=false){await page.route('**/__availability_fixture',r=>r.fulfill({contentType:'text/html',body:`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${bundle.css}</style></head><body data-list="${list?'1':'0'}"><header><a href="/" class="brand" aria-label="JUYU Help Centre 首页"><span>JUYU Help Centre</span></a></header><main class="editor-main"><h1>资料可用状态 · 本地样例</h1><script type="application/json" id="data">${JSON.stringify(initial).replace(/</g,'\\u003c')}</script><div id="root"></div></main><script>${bundle.script.replace(/<\/script/gi,'<\\/script')}</script></body></html>`}));await page.goto('/__availability_fixture');await expect(page.getByRole('region',{name:list?'归档资料列表':'归档与下线管理'})).toBeVisible();}
const ack=(action:'archive'|'unpublish'|'unarchive',sequence=6)=>({documentId:fixture.documentId,sequence,revision:2,action,lifecycle:action==='archive'?'archived':'active',status:'draft',publishedRevision:null});
function changed(action:'archive'|'unpublish'|'unarchive',sequence=6):AvailabilityDetail{return {...fixture,sequence,lifecycle:action==='archive'?'archived':'active',status:'draft',publishedRevision:null,canArchive:action!=='archive',canUnpublish:false,canUnarchive:action==='archive',history:[{sequence,revision:2,action,actorId:'a',actorName:'Alex',previousPublishedRevision:action==='unarchive'?null:1,at:'2026-09-09T03:00:00Z'}]};}
test('archive requires confirmation then recovery stays unpublished and preserves real history',async({page},info)=>{const writes:unknown[]=[];let action:'archive'|'unarchive'='archive';await page.route('**/api/admin/availability/*',r=>{if(r.request().method()==='GET')return r.fulfill({json:changed(action,action==='archive'?6:7)});const x=r.request().postDataJSON();writes.push(x);action=x.action;return r.fulfill({json:ack(action,action==='archive'?6:7)});});await mount(page);await page.getByRole('button',{name:'归档文章',exact:true}).click();await expect(page.getByText('当前审核会结束，批准记录不能用于再次发布。',{exact:true})).toBeVisible();await page.getByRole('button',{name:'取消操作'}).click();expect(writes).toHaveLength(0);await page.getByRole('button',{name:'归档文章',exact:true}).click();await page.screenshot({path:`output/verification/availability-confirm-${info.project.name}.png`,fullPage:true});await page.getByRole('button',{name:'确认归档',exact:true}).click();await expect(page.getByRole('status')).toContainText('已归档');await expect(page.getByRole('region',{name:'可用状态记录'})).toContainText('原正式版 1');await page.getByRole('button',{name:'恢复为未发布草稿',exact:true}).click();await page.getByRole('button',{name:'确认恢复为草稿',exact:true}).click();await expect(page.getByRole('status')).toContainText('仍未发布');await expect(page.getByRole('button',{name:'下线正式版',exact:true})).toHaveCount(0);expect(writes).toEqual([{expectedSequence:5,action:'archive'},{expectedSequence:6,action:'unarchive'}]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`output/verification/availability-restored-${info.project.name}.png`,fullPage:true});});
test('unpublish removes formal access but keeps the article editable in the workspace',async({page})=>{await page.route('**/api/admin/availability/*',r=>r.fulfill({json:r.request().method()==='GET'?changed('unpublish'):ack('unpublish')}));await mount(page);await page.getByRole('button',{name:'下线正式版',exact:true}).click();await page.getByRole('button',{name:'确认下线',exact:true}).click();await expect(page.getByRole('status')).toContainText('正式版已下线');await expect(page.getByText('当前正式版：无',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'编辑文章'})).toBeVisible();await expect(page.getByRole('button',{name:'归档文章',exact:true})).toBeEnabled();});
test('invalid ack locks other actions and replays exactly the same archive request',async({page})=>{const writes:unknown[]=[];await page.route('**/api/admin/availability/*',r=>{if(r.request().method()==='GET')return r.fulfill({json:changed('archive')});writes.push(r.request().postDataJSON());return r.fulfill({json:writes.length===1?{...ack('archive'),publishedRevision:1}:ack('archive')});});await mount(page);await page.getByRole('button',{name:'归档文章',exact:true}).click();await page.getByRole('button',{name:'确认归档',exact:true}).click();await expect(page.getByRole('alert')).toContainText('尚未确认');await expect(page.getByRole('button',{name:'重新读取资料状态'})).toBeDisabled();await expect(page.getByRole('button',{name:'取消操作'})).toBeDisabled();await expect(page.getByRole('link',{name:'编辑文章'})).toHaveCount(0);await page.getByRole('button',{name:'重试原操作'}).click();await expect(page.getByRole('status')).toContainText('已归档');expect(writes).toEqual([{expectedSequence:5,action:'archive'},{expectedSequence:5,action:'archive'}]);});
test('confirmed archive followed by read failure preserves confirmation and blocks stale controls',async({page})=>{await page.route('**/api/admin/availability/*',r=>r.request().method()==='POST'?r.fulfill({json:ack('archive')}):r.fulfill({status:503,json:{error:'FAILED'}}));await mount(page);await page.getByRole('button',{name:'归档文章',exact:true}).click();await page.getByRole('button',{name:'确认归档',exact:true}).click();await expect(page.getByRole('status')).toContainText('已归档');await expect(page.getByRole('alert')).toContainText('未能读取');await expect(page.getByRole('button',{name:'归档文章',exact:true})).toBeDisabled();await expect(page.getByRole('region',{name:'可用状态记录'})).not.toContainText('Alex');});
test('conflict and pending uploads require a fresh snapshot and cannot reuse stale data',async({page})=>{for(const error of ['CONFLICT','UPLOAD_IN_PROGRESS']){await page.route('**/api/admin/availability/*',r=>r.request().method()==='POST'?r.fulfill({status:409,json:{error}}):r.fulfill({json:{...fixture,sequence:4}}));await mount(page);await page.getByRole('button',{name:'下线正式版',exact:true}).click();await page.getByRole('button',{name:'确认下线',exact:true}).click();await expect(page.getByRole('button',{name:'确认下线',exact:true})).toBeDisabled();await page.getByRole('button',{name:'重新读取资料状态'}).click();await expect(page.getByRole('alert')).toContainText('未能读取');await page.unroute('**/api/admin/availability/*');}});
test('requests prevent concurrent navigation and transport uncertainty survives rejected retries',async({page})=>{let release!:()=>void;const pending=new Promise<void>(r=>{release=r;});let count=0;await page.route('**/api/admin/availability/*',async r=>{await pending;return ++count===1?r.abort('failed'):r.fulfill({status:409,json:{error:'CONFLICT'}});});await mount(page);await page.getByRole('button',{name:'归档文章',exact:true}).click();await page.getByRole('button',{name:'确认归档',exact:true}).click();await expect(page.getByRole('button',{name:'重新读取资料状态'})).toBeDisabled();await expect(page.getByRole('link',{name:'归档资料列表'})).toHaveCount(0);release();await page.getByRole('button',{name:'重试原操作'}).click();await expect(page.getByRole('alert')).toContainText('尚未确认');await expect(page.getByRole('button',{name:'取消操作'})).toBeDisabled();});
test('unavailable or wrong state exposes no unauthorized action and history scope remains honest',async({page})=>{await mount(page,{...fixture,lifecycle:'trashed',canArchive:false,canUnpublish:false});await expect(page.getByRole('button',{name:'归档文章',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'下线正式版',exact:true})).toHaveCount(0);await mount(page,{...fixture,historyMore:true});await expect(page.getByRole('region',{name:'可用状态记录'})).toContainText('更早记录');});
test('archives list uses actual count pagination and safe titles with recovery links',async({page},info)=>{await mount(page,{items:[{documentId:'archived-id',title:'旧流程 <script> 不执行',sequence:8,revision:3}],total:31,page:1,pages:2},true);await expect(page.getByRole('link',{name:'旧流程 <script> 不执行',exact:true})).toHaveAttribute('href','/admin/availability?article=archived-id');await expect(page.getByRole('region',{name:'归档资料列表'})).toContainText('共 31 篇');await expect(page.getByRole('link',{name:'下一页'})).toHaveAttribute('href','/admin/availability?page=2');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`output/verification/archives-${info.project.name}.png`,fullPage:true});});
test('empty archives differ from failed reads without fabricated counts',async({page})=>{await mount(page,{items:[],total:0,page:1,pages:1},true);await expect(page.getByText('没有归档资料。',{exact:true})).toBeVisible();await mount(page,null,true);await expect(page.getByRole('alert')).toContainText('暂时无法读取');await expect(page.getByText('没有归档资料。',{exact:true})).toHaveCount(0);await expect(page.getByRole('link',{name:'重新读取归档列表'})).toBeVisible();});
test('actual availability and archive endpoints reject forged identities while unconfigured',async({page,request})=>{for(const method of ['get','post'] as const){const r=await request[method]('/api/admin/availability/00000000-0000-4000-8000-000000000038',{headers:{'x-role':'admin','x-user-id':'a'},...(method==='post'?{data:{action:'archive',expectedSequence:5}}:{})});expect(r.status()).toBe(503);expect(r.headers()['cache-control']).toBe('private, no-store');}const r=await request.get('/api/admin/archives');expect(r.status()).toBe(503);await page.goto('/admin/availability?article=00000000-0000-4000-8000-000000000038');await expect(page.getByRole('region',{name:'归档与下线管理'})).toHaveCount(0);});
test('outside-panel home link and unload stay guarded through transport uncertainty until exact success',async({page})=>{
 const writes:unknown[]=[];let release!:()=>void;const held=new Promise<void>(r=>{release=r;});
 await page.route('**/api/admin/availability/*',async r=>{if(r.request().method()==='GET')return r.fulfill({json:changed('archive')});writes.push(r.request().postDataJSON());if(writes.length===1){await held;return r.abort('failed');}return r.fulfill({json:ack('archive')});});
 await mount(page);await page.getByRole('button',{name:'归档文章',exact:true}).click();await page.getByRole('button',{name:'确认归档',exact:true}).click();
 const home=page.getByRole('link',{name:'JUYU Help Centre 首页',exact:true});await expect(page.getByRole('region',{name:'归档与下线管理'}).getByRole('link',{name:'JUYU Help Centre 首页'})).toHaveCount(0);
 try{await home.locator('span').click();await expect(page).toHaveURL(/\/__availability_fixture$/);expect(await page.evaluate(()=>{const event=new Event('beforeunload',{cancelable:true});window.dispatchEvent(event);return event.defaultPrevented;})).toBe(true);}finally{release();}
 await expect(page.getByRole('button',{name:'重试原操作'})).toBeEnabled();await home.click();await expect(page).toHaveURL(/\/__availability_fixture$/);
 // A dismissed beforeunload cancels navigation, so there must be no wait for a new load.
 const dialogPromise=page.waitForEvent('dialog');await page.evaluate(()=>{setTimeout(()=>window.location.reload(),0);});const dialog=await dialogPromise;expect(dialog.type()).toBe('beforeunload');await dialog.dismiss();await expect(page).toHaveURL(/\/__availability_fixture$/);await expect(page.getByRole('button',{name:'重试原操作'})).toBeEnabled();
 await page.getByRole('button',{name:'重试原操作'}).click();await expect(page.getByRole('status')).toContainText('已归档');await expect(page.getByRole('button',{name:'重新读取资料状态'})).toBeEnabled();expect(await page.evaluate(()=>{const event=new Event('beforeunload',{cancelable:true});window.dispatchEvent(event);return event.defaultPrevented;})).toBe(false);expect(writes).toEqual([{expectedSequence:5,action:'archive'},{expectedSequence:5,action:'archive'}]);
 await home.click();await expect(page).toHaveURL(/\/sign-in$/);
});
test('known member busy rejection permits a fresh read and new confirmation while transport uncertainty stays locked',async({page})=>{
 const writes:unknown[]=[];let reads=0;await page.route('**/api/admin/availability/*',r=>{if(r.request().method()==='GET'){reads++;return r.fulfill({json:{...fixture,sequence:6}});}writes.push(r.request().postDataJSON());return writes.length===1?r.fulfill({status:409,json:{error:'MEMBER_BUSY'}}):r.abort('failed');});
 await mount(page);await page.getByRole('button',{name:'归档文章',exact:true}).click();await page.getByRole('button',{name:'确认归档',exact:true}).click();await expect(page.getByRole('alert')).toContainText('成员状态正在更新');await expect(page.getByRole('alert')).toContainText('操作未执行');await expect(page.getByRole('button',{name:'重新读取资料状态'})).toBeEnabled();await expect(page.getByRole('button',{name:'取消操作'})).toBeEnabled();expect(await page.evaluate(()=>{const event=new Event('beforeunload',{cancelable:true});window.dispatchEvent(event);return event.defaultPrevented;})).toBe(false);
 await page.getByRole('button',{name:'重新读取资料状态'}).click();await expect(page.getByRole('button',{name:'归档文章',exact:true})).toBeEnabled();expect(reads).toBe(1);await page.getByRole('button',{name:'归档文章',exact:true}).click();await page.getByRole('button',{name:'确认归档',exact:true}).click();await expect(page.getByRole('alert')).toContainText('尚未确认');await expect(page.getByRole('button',{name:'重新读取资料状态'})).toBeDisabled();await expect(page.getByRole('button',{name:'取消操作'})).toBeDisabled();expect(writes).toEqual([{expectedSequence:5,action:'archive'},{expectedSequence:6,action:'archive'}]);
});
