import {fixtureAssets} from '../helpers/fixture-assets';
import {test,expect,type Page} from '@playwright/test';
import {decisionBrowserBundle,decisionFixture} from '../helpers/decision-browser';
import type {ReviewDetail} from '../../src/review/decision';
let bundle:Awaited<ReturnType<typeof decisionBrowserBundle>>;
test.beforeEach(async({page})=>{await fixtureAssets(page,'decision');});
test.beforeAll(async()=>{bundle=await decisionBrowserBundle();});
async function mount(page:Page,initial:ReviewDetail=decisionFixture){
 await page.route('**/__decision_fixture',r=>r.fulfill({contentType:'text/html',body:`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${bundle.css}</style></head><body><main class="editor-main"><h1>内容二审 · 本地样例</h1><script type="application/json" id="data">${JSON.stringify(initial).replace(/</g,'\\u003c')}</script><div id="review"></div></main><script>${bundle.script.replace(/<\/script/gi,'<\\/script')}</script></body></html>`}));
 await page.goto('/__decision_fixture');await expect(page.getByRole('region',{name:'二审详情'})).toBeVisible();
}
const ack=(action:'approve'|'reject'='approve',reason:string|null=null)=>({documentId:'decision-local',sequence:5,revision:2,reviewerId:'admin-b',status:action==='approve'?'approved':'changes_requested',action,reason});
test('approval requires explicit confirmation and keeps the previous formal version',async({page},info)=>{
 const writes:unknown[]=[];await page.route('**/api/admin/review/*/decision',r=>{writes.push(r.request().postDataJSON());return r.fulfill({json:ack()});});await mount(page);await expect(page.getByRole('heading',{name:'需要二审的文章'})).toBeVisible();await expect(page.locator('.gitbook-document')).toContainText('完整正文 <script>alert(1)</script>');await expect(page.locator('[contenteditable=true]')).toHaveCount(0);await expect(page.locator('.gitbook-document script')).toHaveCount(0);await page.getByRole('button',{name:'批准本次版本',exact:true}).click();expect(writes).toHaveLength(0);await page.getByRole('button',{name:'取消决定',exact:true}).click();expect(writes).toHaveLength(0);await page.getByRole('button',{name:'批准本次版本',exact:true}).click();await page.getByRole('button',{name:'确认批准',exact:true}).click();await expect(page.getByRole('status')).toContainText('已经批准');await expect(page.getByRole('region',{name:'二审详情'})).toContainText('不会自动发布');await expect(page.getByRole('region',{name:'二审详情'})).toContainText('正式版 1');expect(writes).toEqual([{expectedSequence:4,action:'approve'}]);await expect(page.getByRole('button',{name:'批准本次版本',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`output/verification/decision-approved-${info.project.name}.png`,fullPage:true});
});
test('rejection requires a reason and preserves the original text until exact acknowledgement',async({page},info)=>{
 const writes:unknown[]=[];await page.route('**/api/admin/review/*/decision',r=>{writes.push(r.request().postDataJSON());return r.fulfill({json:ack('reject','请补充来源 <b>核对</b>')});});await mount(page);await page.getByRole('button',{name:'退回修改',exact:true}).click();await expect(page.getByRole('button',{name:'确认退回',exact:true})).toBeDisabled();await page.getByLabel('退回原因',{exact:true}).fill('   ');await expect(page.getByRole('button',{name:'确认退回',exact:true})).toBeDisabled();await page.getByLabel('退回原因',{exact:true}).fill('  请补充来源 <b>核对</b>  ');await page.screenshot({path:`output/verification/decision-reason-${info.project.name}.png`,fullPage:true});await page.getByRole('button',{name:'确认退回',exact:true}).click();await expect(page.getByRole('status')).toContainText('需要修改');await expect(page.getByRole('region',{name:'二审详情'})).toContainText('请补充来源 <b>核对</b>');await expect(page.locator('.review-return-reason b')).toHaveCount(0);expect(writes).toEqual([{expectedSequence:4,action:'reject',reason:'请补充来源 <b>核对</b>'}]);await page.getByText('更多操作',{exact:true}).click();await expect(page.getByRole('link',{name:'编辑文章'})).toHaveAttribute('href','/admin/editor?article=decision-local');
});
test('other administrators can read but cannot decide and inactive records remain closed',async({page})=>{
 await mount(page,{...decisionFixture,canDecide:false});await expect(page.getByRole('region',{name:'二审详情'})).toContainText('仅指定的二审管理员');await expect(page.getByRole('button',{name:'批准本次版本',exact:true})).toHaveCount(0);await mount(page,{...decisionFixture,article:{...decisionFixture.article,lifecycle:'trashed'},canDecide:true});await expect(page.getByRole('button',{name:'退回修改',exact:true})).toHaveCount(0);await expect(page.getByRole('region',{name:'二审详情'})).toContainText('已停用');
});
test('unknown and wrong acknowledgements lock the action and retry the identical decision',async({page})=>{
 const writes:unknown[]=[];await page.route('**/api/admin/review/*/decision',r=>{writes.push(r.request().postDataJSON());return r.fulfill({json:writes.length===1?{...ack('reject','原退回原因'),action:'approve'}:ack('reject','原退回原因')});});await mount(page);await page.getByRole('button',{name:'退回修改',exact:true}).click();await page.getByLabel('退回原因',{exact:true}).fill('原退回原因');await page.getByRole('button',{name:'确认退回',exact:true}).click();await expect(page.getByRole('alert')).toContainText('尚未确认');await expect(page.getByLabel('退回原因',{exact:true})).toHaveValue('原退回原因');await expect(page.getByLabel('退回原因',{exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'取消决定'})).toBeDisabled();await expect(page.getByRole('button',{name:'重新读取二审状态'})).toBeDisabled();await expect(page.getByRole('link',{name:'编辑文章'})).toHaveCount(0);await page.getByRole('button',{name:'重试原决定'}).click();await expect(page.getByRole('status')).toContainText('需要修改');expect(writes).toEqual([{expectedSequence:4,action:'reject',reason:'原退回原因'},{expectedSequence:4,action:'reject',reason:'原退回原因'}]);
});
test('CAS rejection preserves input and explicit refresh keeps returned revision reason after edits',async({page})=>{
 await page.route('**/api/admin/review/*/decision',r=>r.request().method()==='POST'?r.fulfill({status:409,json:{error:'CONFLICT'}}):r.fulfill({json:{...decisionFixture,article:{...decisionFixture.article,sequence:6,status:'draft',title:'退回后已修改的内容'},review:{...decisionFixture.review!,status:'rejected',reason:'已记录的退回原因',decidedAt:'2026-09-09T02:00:00Z'},canDecide:false}}));await mount(page);await page.getByRole('button',{name:'退回修改',exact:true}).click();await page.getByLabel('退回原因',{exact:true}).fill('未提交的说明');await page.getByRole('button',{name:'确认退回',exact:true}).click();await expect(page.getByRole('alert')).toContainText('版本已改变');await expect(page.getByLabel('退回原因',{exact:true})).toHaveValue('未提交的说明');await expect(page.getByRole('button',{name:'确认退回',exact:true})).toBeDisabled();await page.getByRole('button',{name:'重新读取二审状态'}).click();await page.getByRole('button',{name:'确认继续',exact:true}).click();await expect(page.getByRole('heading',{name:'退回后已修改的内容'})).toBeVisible();await expect(page.getByRole('region',{name:'二审详情'})).toContainText('版本 2 的退回原因');await expect(page.getByRole('region',{name:'二审详情'})).toContainText('已记录的退回原因');await expect(page.getByRole('button',{name:'批准本次版本',exact:true})).toHaveCount(0);
});
test('refresh blocks decisions while reading and refuses an older snapshot',async({page})=>{
 let release!:()=>void;const held=new Promise<void>(resolve=>{release=resolve;});await page.route('**/api/admin/review/*/decision',async r=>{await held;await r.fulfill({json:{...decisionFixture,article:{...decisionFixture.article,sequence:3}}});});await mount(page);await page.getByRole('button',{name:'重新读取二审状态'}).click();await expect(page.getByRole('button',{name:'批准本次版本',exact:true})).toBeDisabled();release();await expect(page.getByRole('alert')).toContainText('读取');await expect(page.getByRole('button',{name:'批准本次版本',exact:true})).toBeDisabled();
});
test('real unconfigured decision endpoints and page fail closed for forged roles',async({page,request})=>{
 for(const method of ['get','post'] as const){const r=await request[method]('/api/admin/review/00000000-0000-4000-8000-000000000035/decision',{headers:{'x-role':'admin','x-user-id':'admin-b'},...(method==='post'?{data:{expectedSequence:4,action:'approve'}}:{})});expect(r.status()).toBe(503);expect(r.headers()['cache-control']).toBe('private, no-store');}await page.goto('/admin/review?article=00000000-0000-4000-8000-000000000035');await expect(page.getByRole('button',{name:'确认批准'})).toHaveCount(0);await expect(page.getByRole('button',{name:'确认退回'})).toHaveCount(0);
});

test('review includes audience tags private cover and legacy rich blocks',async({page},info)=>{
 const assetId='00000000-0000-4000-8000-000000000035';await page.route(`**/api/admin/assets/${assetId}`,r=>r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="200" height="100"><rect width="200" height="100" fill="#26775a"/></svg>'}));await mount(page,{...decisionFixture,article:{...decisionFixture.article,audience:'admin',tags:['内部流程','来源核对'],cover:{assetId,alt:'本次送审封面',position:70},blocks:[{id:'00000000-0000-4000-8000-000000000036',type:'table',headers:['旧格式项目','核对要求'],rows:[['交易信息','补齐出处']]}]}});await page.getByText('资料信息',{exact:true}).click();await expect(page.getByRole('definition').filter({hasText:'仅 Admin'})).toBeVisible();await expect(page.getByRole('definition').filter({hasText:'内部流程、来源核对'})).toBeVisible();await expect(page.getByRole('img',{name:'本次送审封面'})).toHaveAttribute('src',`/api/admin/assets/${assetId}`);await expect(page.getByRole('table')).toContainText('补齐出处');await expect(page.getByRole('link',{name:'打开封面原文件'})).toHaveAttribute('href',`/api/admin/assets/${assetId}`);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`output/verification/decision-complete-${info.project.name}.png`,fullPage:true});
});

test('an in-flight decision disables refresh and editing until exact acknowledgement',async({page})=>{
 let release!:()=>void;const held=new Promise<void>(resolve=>{release=resolve;});let reads=0;await page.route('**/api/admin/review/*/decision',async r=>{if(r.request().method()==='GET'){reads++;return r.fulfill({json:decisionFixture});}await held;return r.fulfill({json:ack()});});await mount(page);await page.getByRole('button',{name:'批准本次版本',exact:true}).click();await page.getByRole('button',{name:'确认批准',exact:true}).click();await expect(page.getByRole('button',{name:'重新读取二审状态'})).toBeDisabled();await expect(page.getByRole('link',{name:'编辑文章'})).toHaveCount(0);await expect(page.getByRole('button',{name:'取消决定'})).toBeDisabled();expect(reads).toBe(0);release();await expect(page.getByRole('status')).toContainText('已经批准');
});

test('uncertain transport result remains locked even when its retry is rejected',async({page})=>{
 let count=0;await page.route('**/api/admin/review/*/decision',r=>++count===1?r.abort('failed'):r.fulfill({status:409,json:{error:'CONFLICT'}}));await mount(page);await page.getByRole('button',{name:'退回修改',exact:true}).click();await page.getByLabel('退回原因',{exact:true}).fill('需要继续核对');await page.getByRole('button',{name:'确认退回',exact:true}).click();await expect(page.getByRole('alert')).toContainText('尚未确认');await page.getByRole('button',{name:'重试原决定'}).click();await expect(page.getByRole('alert')).toContainText('尚未确认');await expect(page.getByRole('button',{name:'重新读取二审状态'})).toBeDisabled();await expect(page.getByRole('button',{name:'取消决定'})).toBeDisabled();await expect(page.getByLabel('退回原因',{exact:true})).toHaveValue('需要继续核对');
});

test('Q&A category and ordering are visible when reviewing the saved version',async({page})=>{await mount(page,{...decisionFixture,article:{...decisionFixture.article,kind:'qa',qa:{category:'待核对分类',position:17}}});await page.getByText('资料信息',{exact:true}).click();await expect(page.getByText('待核对分类',{exact:true})).toBeVisible();await expect(page.getByText('17',{exact:true})).toBeVisible();});

test('R18 unfinished rejection is protected from global sidebar and refresh',async({page})=>{
 await page.route('**/__leave_target',r=>r.fulfill({contentType:'text/html',body:'离开目标 · 本地样例'}));
 await mount(page);
 await page.evaluate(()=>{const link=document.createElement('a');link.href='/__leave_target';link.textContent='全局侧栏测试';document.body.prepend(link);});
 await page.getByRole('button',{name:'退回修改',exact:true}).click();await page.getByRole('textbox',{name:'退回原因'}).fill('请补齐核对步骤');
 await page.getByRole('link',{name:'全局侧栏测试'}).click();
 await expect(page.getByRole('dialog')).toBeVisible({timeout:2000});
 await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();
 await expect(page.getByRole('textbox',{name:'退回原因'})).toHaveValue('请补齐核对步骤');
 await page.getByRole('button',{name:'重新读取二审状态'}).click();
 await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();
 await expect(page.getByRole('textbox',{name:'退回原因'})).toHaveValue('请补齐核对步骤');
 await page.getByRole('link',{name:'全局侧栏测试'}).click();await page.getByRole('dialog').getByRole('button',{name:'确认继续'}).click();await expect(page).toHaveURL(/__leave_target$/);
});

test('R18 browser back and native unload protect a typed reason while hash links remain usable',async({page},info)=>{
 await mount(page);await page.evaluate(()=>history.pushState({},'',location.href));
 await page.getByRole('button',{name:'退回修改',exact:true}).click();await page.getByLabel('退回原因',{exact:true}).fill('保留这段审核意见');
 await page.evaluate(()=>history.back());await expect(page.getByRole('dialog')).toBeVisible();
 await page.screenshot({path:`output/verification/R18-leave-${info.project.name}.png`,fullPage:true});
 await page.getByRole('button',{name:'取消',exact:true}).click();await expect(page.getByLabel('退回原因',{exact:true})).toHaveValue('保留这段审核意见');
 expect(await page.evaluate(()=>{const event=new Event('beforeunload',{cancelable:true});dispatchEvent(event);return event.defaultPrevented;})).toBe(true);
 await page.evaluate(()=>{const a=document.createElement('a');a.href='#review-notes';a.textContent='页内位置';document.body.prepend(a);});
 await page.getByRole('link',{name:'页内位置'}).click();await expect(page).toHaveURL(/#review-notes$/);await expect(page.getByRole('dialog')).toHaveCount(0);
});

test('history fallback without Navigation API restores the page before asking and permits confirmed back',async({page})=>{await page.addInitScript(()=>Object.defineProperty(window,'navigation',{value:undefined,configurable:true}));await mount(page);await page.evaluate(()=>history.pushState({},'',location.pathname+'?editing=1'));await page.getByRole('button',{name:'退回修改',exact:true}).click();await page.getByLabel('退回原因',{exact:true}).fill('后退必须保留');await page.evaluate(()=>history.back());await expect(page.getByRole('dialog')).toBeVisible();await expect(page).toHaveURL(/editing=1/);await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();await expect(page.getByLabel('退回原因',{exact:true})).toHaveValue('后退必须保留');await page.evaluate(()=>history.back());await page.getByRole('dialog').getByRole('button',{name:'确认继续'}).click();await expect(page).toHaveURL(/__decision_fixture$/);});

test('history fallback preserves forward navigation after cancelling back',async({page})=>{await page.addInitScript(()=>Object.defineProperty(window,'navigation',{value:undefined,configurable:true}));await mount(page);await page.evaluate(()=>{history.pushState({},'',location.pathname+'?step=1');history.pushState({},'',location.pathname+'?step=2');history.back();});await expect(page).toHaveURL(/step=1/);await page.getByRole('button',{name:'退回修改',exact:true}).click();await page.getByLabel('退回原因',{exact:true}).fill('前进也要保留');await page.evaluate(()=>history.forward());await expect(page.getByRole('dialog')).toBeVisible();await expect(page).toHaveURL(/step=1/);await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();await expect(page.getByLabel('退回原因',{exact:true})).toHaveValue('前进也要保留');await page.evaluate(()=>history.forward());await page.getByRole('dialog').getByRole('button',{name:'确认继续'}).click();await expect(page).toHaveURL(/step=2/);});

test('history fallback does not block a same-page heading link',async({page})=>{await page.addInitScript(()=>Object.defineProperty(window,'navigation',{value:undefined,configurable:true}));await mount(page);await page.getByRole('button',{name:'退回修改',exact:true}).click();await page.getByLabel('退回原因',{exact:true}).fill('跳转段落不丢失');await page.evaluate(()=>{location.hash='notes';});await expect(page).toHaveURL(/#notes$/);await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByLabel('退回原因',{exact:true})).toHaveValue('跳转段落不丢失');});
