import {test,expect,type Page} from '@playwright/test';
import {navigationBrowserBundle} from '../helpers/navigation-browser';
import {decisionBrowserBundle,decisionFixture} from '../helpers/decision-browser';
import {publicationBrowserBundle,publicationFixture} from '../helpers/publication-browser';
import {historyBrowserBundle,historyVersionFixture} from '../helpers/history-browser';
import type {FieldSnapshot} from '../../src/fields/model';
const fields:FieldSnapshot[]=[{id:'00000000-0000-4000-8000-000000000048',version:1,name:'原正式字段',type:'text',required:true,enabled:true,options:[],value:'原版本说明 <script>不执行</script>'}];
let reader:Awaited<ReturnType<typeof navigationBrowserBundle>>,review:Awaited<ReturnType<typeof decisionBrowserBundle>>,publication:Awaited<ReturnType<typeof publicationBrowserBundle>>,history:Awaited<ReturnType<typeof historyBrowserBundle>>;
test.beforeAll(async()=>{reader=await navigationBrowserBundle();review=await decisionBrowserBundle();publication=await publicationBrowserBundle();history=await historyBrowserBundle();});
async function mount(page:Page,bundle:{css:string;script:string},data:unknown,id:string){await page.route('**/__fields_reading',r=>r.fulfill({contentType:'text/html',body:`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${bundle.css}</style></head><body><header>版本字段 · 本地测试样例</header><div id="${id}"></div><script id="data" type="application/json">${JSON.stringify(data).replace(/</g,'\\u003c')}</script><script>${bundle.script.replace(/<\/script/gi,'<\\/script')}</script></body></html>`}));await page.goto('/__fields_reading');}
test('reader and PDF view use supplied formal field snapshot with safe text and responsive layout',async({page},info)=>{const article={id:'field-reader',title:'正式字段样例',revision:2,body:'# 正式资料\n\n已经发布的正文。',customFields:fields};await mount(page,reader,{pages:[{type:'document',id:article.id,title:article.title,href:'/help-centre?article='+article.id}],requested:article.id,article},'presentation');await expect(page.getByRole('region',{name:'自定义资料',exact:true})).toContainText(fields[0].value as string);await expect(page.locator('.field-values script')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`output/verification/fields-reader-${info.project.name}.png`,fullPage:true,animations:'disabled'});await page.unrouteAll();await mount(page,reader,{pdfSnapshot:{article,files:[]}},'reader');await expect(page.locator('.pdf-paper')).toContainText('原正式字段');await expect(page.locator('.pdf-paper')).toContainText(fields[0].value as string);await expect(page.locator('.pdf-paper script')).toHaveCount(0);});
test('review publication and history display version-specific field labels and values',async({page})=>{for(const item of [{bundle:review,data:{...decisionFixture,article:{...decisionFixture.article,customFields:fields}},id:'review'},{bundle:publication,data:{...publicationFixture,article:{...publicationFixture.article,customFields:fields}},id:'review'},{bundle:history,data:{...historyVersionFixture,assets:[],version:{...historyVersionFixture.version,cover:null,blocks:[],customFields:fields}},id:'root'}]){await mount(page,item.bundle,item.data,item.id);await expect(page.getByRole('region',{name:'自定义资料',exact:true})).toContainText('原正式字段');await expect(page.getByRole('region',{name:'自定义资料',exact:true})).toContainText(fields[0].value as string);await page.unrouteAll();}});
