import {test,expect,type Page} from '@playwright/test';
import {editorBrowserBundle,editorFixture} from '../helpers/editor-browser';
import {prepareFieldSnapshots,type FieldDefinition} from '../../src/fields/model';
import type {EditorData} from '../../src/editor/contract';
let bundle:Awaited<ReturnType<typeof editorBrowserBundle>>;test.beforeAll(async()=>{bundle=await editorBrowserBundle();});
const def=(n:number,type:FieldDefinition['type'],name:string,required=false):FieldDefinition=>({id:`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,version:1,enabled:true,name,type,required,options:type==='select'?['普通','紧急']:[]});
const definitions=[def(1,'text','处理说明',true),def(2,'number','处理金额',true),def(3,'date','生效日期'),def(4,'select','处理优先级'),def(5,'boolean','需要升级',true)];
async function mount(page:Page,initial:()=>EditorData|null,defs=definitions){await page.route(url=>['/__field_editor','/admin/editor'].includes(url.pathname),r=>r.fulfill({contentType:'text/html',body:`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${bundle.css}</style></head><body><main class="editor-main"><h1>字段编辑 · 本地样例</h1><script type="application/json" id="data">${JSON.stringify(initial()).replace(/</g,'\\u003c')}</script><script type="application/json" id="definitions">${JSON.stringify(defs)}</script><div id="editor"></div></main><script>${bundle.script.replace(/<\/script/gi,'<\\/script')}</script></body></html>`}));await page.goto('/__field_editor');await expect(page.locator('.bn-editor')).toBeVisible();}
test('new editor validates required fields and saves zero and false with exact metadata',async({page},info)=>{let saved:EditorData|null=null;const writes:Record<string,unknown>[]=[];await page.route('**/api/admin/editor/*',r=>{const x=r.request().postDataJSON();writes.push(x);saved={...editorFixture,...x,documentId:new URL(r.request().url()).pathname.split('/').pop(),sequence:x.expectedSequence===null?0:x.expectedSequence+1,fieldDefinitions:definitions};return r.fulfill({json:saved});});await mount(page,()=>saved);await page.getByLabel('文章标题',{exact:true}).fill('字段测试');await expect(page.getByRole('alert')).toContainText('格式或长度');expect(writes).toHaveLength(0);await page.getByLabel('处理说明 *',{exact:true}).fill('升级核对 <script>');await page.getByLabel('处理金额 *',{exact:true}).fill('-');await page.getByLabel('需要升级 *',{exact:true}).selectOption('false');await expect(page.getByRole('button',{name:'立即保存',exact:true})).toBeDisabled();await page.getByLabel('处理金额 *',{exact:true}).fill('0');await page.getByLabel('生效日期',{exact:true}).fill('2026-09-09');await page.getByLabel('处理优先级',{exact:true}).selectOption('紧急');await expect(page.getByRole('status')).toContainText('所有修改已保存',{timeout:8000});expect(saved!.customFields!.map(f=>f.value)).toEqual(['升级核对 <script>',0,'2026-09-09','紧急',false]);await page.reload();await expect(page.getByLabel('处理金额 *',{exact:true})).toHaveValue('0');await expect(page.getByLabel('需要升级 *',{exact:true})).toHaveValue('false');await page.getByRole('button',{name:'预览草稿',exact:true}).click();await expect(page.locator('.editor-preview')).toContainText('否');await expect(page.locator('.editor-preview script')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`output/verification/fields-editor-${info.project.name}.png`,fullPage:true,animations:'disabled'});});
test('disabled fields stay read only and survive editing without requiring old missing values',async({page})=>{const old={...def(8,'text','旧字段',true),value:null};const defs=[{...old,version:2,enabled:false}].map(({value,...d})=>{void value;return d;});let saved:EditorData={...editorFixture,customFields:[old],fieldDefinitions:defs};await page.route('**/api/admin/editor/*',r=>{const x=r.request().postDataJSON();saved={...saved,...x,sequence:saved.sequence+1};return r.fulfill({json:saved});});await mount(page,()=>saved,defs);await expect(page.getByText('以下字段已停用，保留原有资料，不能在此修改。')).toBeVisible();await expect(page.getByLabel('旧字段 *')).toHaveCount(0);await page.getByLabel('文章标题',{exact:true}).fill('停用字段继续保留');await expect(page.getByRole('status')).toContainText('所有修改已保存',{timeout:8000});expect(saved.customFields).toEqual([old]);});
test('stale settings reject saving without losing field input and recovery loads new definitions',async({page})=>{const defs=[def(1,'text','备注')];let saved:EditorData={...editorFixture,fieldDefinitions:defs,customFields:prepareFieldSnapshots(defs)};await page.route('**/api/admin/editor/*',r=>r.request().method()==='PUT'?r.fulfill({status:409,json:{error:'FIELD_CONFLICT'}}):r.fulfill({json:{...saved,fieldDefinitions:[{...defs[0],version:2,name:'新备注'}]}}));await mount(page,()=>saved,defs);await page.getByLabel('备注',{exact:true}).fill('保留这份输入');await expect(page.getByRole('status')).toContainText('字段设置已更新',{timeout:8000});await expect(page.getByLabel('备注',{exact:true})).toHaveValue('保留这份输入');await page.getByRole('button',{name:'读取服务器最新版本'}).click();page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'保留备份并载入此版本'}).click();await expect(page.getByLabel('新备注',{exact:true})).toBeVisible();await expect(page.getByLabel('载入前的输入备份 1')).toHaveValue(/保留这份输入/);saved={...saved};});
test('submitting the newly saved draft keeps its new field value visible while frozen',async({page})=>{const defs=[def(1,'text','备注')];let saved:EditorData={...editorFixture,fieldDefinitions:defs,customFields:[{...defs[0],value:'旧值'}]};await page.route('**/api/admin/editor/*',r=>{saved={...saved,...r.request().postDataJSON(),sequence:saved.sequence+1};return r.fulfill({json:saved});});await page.route('**/api/admin/review/*',r=>r.request().method()==='GET'?r.fulfill({json:{documentId:'editor-local',sequence:saved.sequence,revision:2,status:'draft',lifecycle:'active',reviewers:[{id:'admin-b',name:'Ivy'}],nextCursor:null}}):r.fulfill({json:{documentId:'editor-local',sequence:saved.sequence+1,revision:2,reviewerId:'admin-b',status:'in_review'}}));await mount(page,()=>saved,defs);await page.getByLabel('备注',{exact:true}).fill('新送审值');await expect(page.getByRole('status')).toContainText('所有修改已保存',{timeout:8000});await page.getByRole('button',{name:'提交二审',exact:true}).click();await page.getByLabel('二审管理员',{exact:true}).selectOption('admin-b');await page.getByRole('button',{name:'确认提交二审',exact:true}).click();await expect(page.getByRole('region',{name:'提交二审'})).toContainText('已提交');await expect(page.getByRole('region',{name:'自定义资料',exact:true})).toContainText('新送审值');await expect(page.getByRole('region',{name:'自定义资料',exact:true})).not.toContainText('旧值');});

test('frozen draft preview preserves saved labels even when current settings changed',async({page})=>{const old={...def(1,'select','原审核字段'),options:['旧选项'],value:'旧选项'};const defs=[{...def(1,'select','已改名字段',true),version:2,options:['新选项']}];const saved:EditorData={...editorFixture,status:'in_review',fieldDefinitions:defs,customFields:[old]};await mount(page,()=>saved,defs);await page.getByRole('button',{name:'预览草稿',exact:true}).click();await expect(page.locator('.editor-preview')).toContainText('原审核字段');await expect(page.locator('.editor-preview')).toContainText('旧选项');await expect(page.locator('.editor-preview')).not.toContainText('已改名字段');});
