import {test,expect,type Page} from '@playwright/test';
import {fieldsBrowserBundle} from '../helpers/fields-browser';
import type {FieldDefinition} from '../../src/fields/model';
let bundle:Awaited<ReturnType<typeof fieldsBrowserBundle>>;test.beforeAll(async()=>{bundle=await fieldsBrowserBundle();});
const field:FieldDefinition={id:'00000000-0000-4000-8000-000000000048',version:1,name:'所属团队',type:'select',required:true,enabled:true,options:['客服','运营']};
async function mount(page:Page,props:unknown={initial:[field]}){await page.route('**/__fields_fixture',r=>r.fulfill({contentType:'text/html',body:`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${bundle.css}</style></head><body><header>字段设置 · 本地测试样例（非真实公司设置）</header><main><div id="fields"></div></main><script id="data" type="application/json">${JSON.stringify(props).replace(/</g,'\\u003c')}</script><script>${bundle.script.replace(/<\/script/gi,'<\\/script')}</script></body></html>`}));await page.goto('/__fields_fixture');}
test('admin creates typed field and disables existing definition without deleting history',async({page},info)=>{const writes:Record<string,unknown>[]=[];await page.route('**/api/admin/fields/*',r=>{const x=r.request().postDataJSON();writes.push(x);return r.fulfill({json:{...x,id:new URL(r.request().url()).pathname.split('/').pop(),version:(x.expectedVersion??0)+1,expectedVersion:undefined}});});await mount(page);await page.getByRole('button',{name:/所属团队/}).click();await expect(page.getByLabel('字段类型')).toBeDisabled();await page.getByLabel('启用字段').uncheck();await page.getByRole('button',{name:'保存字段',exact:true}).click();await expect(page.getByRole('status')).toContainText('字段已停用');expect(writes[0]).toMatchObject({expectedVersion:1,enabled:false});
 await page.getByRole('button',{name:'新建字段',exact:true}).click();await page.getByLabel('字段名称').fill('是否需要升级 <script>');await page.getByLabel('字段类型').selectOption('boolean');await page.getByLabel('设为必填').check();await page.getByRole('button',{name:'保存字段',exact:true}).click();await expect(page.getByRole('status')).toContainText('已保存');expect(writes[1]).toMatchObject({expectedVersion:null,type:'boolean',required:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator('main script')).toHaveCount(0);await page.screenshot({path:`output/verification/fields-${info.project.name}.png`,fullPage:true,animations:'disabled'});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await expect.poll(()=>page.locator('html').evaluate(el=>getComputedStyle(el).backgroundColor)).toBe('rgb(25, 25, 31)');await page.screenshot({path:`output/verification/fields-dark-${info.project.name}.png`,fullPage:true,animations:'disabled'});
});
test('uncertain save locks exact original submission and refuses stale acknowledgement',async({page})=>{let count=0;const writes:unknown[]=[];await page.route('**/api/admin/fields/*',r=>{count++;const x=r.request().postDataJSON();writes.push(x);return r.fulfill({json:{...field,...x,expectedVersion:undefined,version:count===1?99:2}});});await mount(page);await page.getByRole('button',{name:/所属团队/}).click();await page.getByLabel('字段名称').fill('新的团队');await page.getByRole('button',{name:'保存字段',exact:true}).click();await expect(page.getByRole('alert')).toContainText('无法确认');await expect(page.getByLabel('字段名称')).toBeDisabled();await expect(page.getByRole('button',{name:'新建字段',exact:true})).toBeDisabled();await expect(page.getByRole('link',{name:'设置变更记录'})).toHaveAttribute('aria-disabled','true');await expect(page.getByRole('link',{name:'设置变更记录'})).not.toHaveAttribute('href');await page.getByRole('button',{name:'重试原提交'}).click();await expect(page.getByRole('status')).toContainText('已保存');expect(writes).toHaveLength(2);expect(writes[0]).toEqual(writes[1]);});
test('conflict retains form then explicitly loads current settings and empty differs from unavailable',async({page})=>{await page.route('**/api/admin/fields/*',r=>r.fulfill({status:409,json:{error:'FIELD_CONFLICT'}}));await page.route('**/api/admin/fields',r=>r.fulfill({json:[{...field,name:'服务器团队',version:3}]}));await mount(page);await page.getByRole('button',{name:/所属团队/}).click();await page.getByLabel('字段名称').fill('本地输入');await page.getByRole('button',{name:'保存字段',exact:true}).click();await expect(page.getByLabel('字段名称')).toHaveValue('本地输入');await expect(page.getByRole('button',{name:'保存字段',exact:true})).toBeDisabled();await page.getByRole('button',{name:'重新载入最新设置（放弃当前输入）'}).click();await expect(page.getByLabel('字段名称')).toHaveValue('服务器团队');await page.unrouteAll();await mount(page,{initial:[],state:'ready'});await expect(page.getByText('还没有自定义字段。点击“新建字段”添加第一项。')).toBeVisible();await page.unrouteAll();await mount(page,{initial:[field],state:'unavailable'});await expect(page.getByText('字段设置暂时不可用')).toBeVisible();await expect(page.getByRole('button',{name:/所属团队/})).toHaveCount(0);});
test('invalid options keep input without writes and real routes require configured administrator',async({page,request})=>{let writes=0;await page.route('**/api/admin/fields/*',r=>{writes++;return r.fulfill({status:500});});await mount(page);await page.getByRole('button',{name:'新建字段',exact:true}).click();await page.getByLabel('字段名称').fill('业务');await page.getByLabel('字段类型').selectOption('select');await page.getByLabel('单选选项').fill('重复\n重复');await page.getByRole('button',{name:'保存字段',exact:true}).click();await expect(page.getByRole('alert')).toContainText('不重复');expect(writes).toBe(0);await expect(page.getByLabel('单选选项')).toHaveValue('重复\n重复');const r=await request.get('/api/admin/fields',{headers:{'x-role':'admin'}});expect(r.status()).toBe(503);expect(await r.json()).toEqual({error:'FIELDS_UNAVAILABLE'});expect(r.headers()['cache-control']).toBe('private, no-store');const put=await request.put('/api/admin/fields/'+field.id,{data:{name:'forged'},headers:{'x-role':'admin'}});expect(put.status()).toBe(503);page.on('dialog',d=>d.accept());await page.goto('/admin/settings/fields');await expect(page).toHaveURL(/\/admin\/sign-in$/);});
