import {test,expect,type Page} from '@playwright/test';
import {formsBrowserBundle} from '../helpers/forms-browser';
import type {FormDefinition,FormRecord} from '../../src/forms/model';
let bundle:Awaited<ReturnType<typeof formsBrowserBundle>>;test.beforeAll(async()=>{bundle=await formsBrowserBundle();});
const id=(n:number)=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const fields=[['text','事项说明'],['number','处理金额'],['date','生效日期'],['select','优先级'],['boolean','需要升级']].map(([type,name],n)=>({field:{id:id(n+1),version:1,name,type:type as 'text'|'number'|'date'|'select'|'boolean',options:type==='select'?['普通','紧急']:[],required:false,enabled:true},required:n!==2,width:(n===0?'full':'half') as 'full'|'half'}));
const form:FormDefinition={id:id(10),version:1,title:'异常处理申请',description:'请填写需要协助的事项。',enabled:true,audience:'staff',fields};
const values=[{fieldId:id(1),value:'原始填写 <script>'},{fieldId:id(2),value:0},{fieldId:id(3),value:null},{fieldId:id(4),value:'普通'},{fieldId:id(5),value:false}];
const record:FormRecord={id:id(20),formId:form.id,formVersion:1,title:form.title,submittedBy:{id:'support',name:'客服甲'},submittedAt:'2026-09-09T01:00:00.000Z',status:'new',sequence:0,note:'',processedBy:null,processedAt:null,fields,values};
async function mount(page:Page,view:string,data:unknown){await page.route('**/__forms_fixture',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+bundle.css+'</style></head><body><main class="forms-main"><p>本地表单测试样例 · 非真实公司数据</p><div id="forms"></div></main><script type="application/json" id="data">'+JSON.stringify({view,data}).replaceAll('<','\\u003c')+'</script><script>'+bundle.script.replaceAll('</script','<\\/script')+'</script></body></html>'}));await page.goto('/__forms_fixture');}
async function fill(page:Page){await page.getByLabel('事项说明 *',{exact:true}).fill('原始填写 <script>');await page.getByLabel('处理金额 *',{exact:true}).fill('0');await page.getByLabel('优先级 *',{exact:true}).selectOption('普通');await page.getByLabel('需要升级 *',{exact:true}).selectOption('false');}
test('employee validates and submits typed content once in both layouts and themes',async({page},info)=>{const writes:unknown[]=[];await page.route('**/api/forms/*/submissions',r=>{const x=r.request().postDataJSON();writes.push(x);return r.fulfill({json:{id:x.id,formId:form.id,formVersion:x.formVersion,submittedAt:record.submittedAt}});});await mount(page,'fill',form);await page.getByRole('button',{name:'提交表单',exact:true}).click();await expect(page.getByRole('alert')).toContainText('必填项');expect(writes).toHaveLength(0);await fill(page);await page.getByRole('button',{name:'提交表单',exact:true}).click();await expect(page.getByRole('status')).toContainText('提交成功');expect((writes[0] as {values:unknown}).values).toEqual(values);await expect(page.getByLabel('事项说明 *',{exact:true})).toBeDisabled();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'output/verification/forms-fill-'+info.project.name+'.png',fullPage:true});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await expect.poll(()=>page.locator('html').evaluate(e=>getComputedStyle(e).backgroundColor)).toBe('rgb(25, 25, 31)');await page.screenshot({path:'output/verification/forms-fill-dark-'+info.project.name+'.png',fullPage:true});});
test('unknown submit preserves exact UUID and values across rejected retry until matching receipt',async({page})=>{const writes:Record<string,unknown>[]=[];await page.route('**/api/forms/*/submissions',r=>{const x=r.request().postDataJSON();writes.push(x);return writes.length===1?r.fulfill({status:503}):writes.length===2?r.fulfill({status:409,json:{error:'SUBMISSION_CONFLICT'}}):r.fulfill({json:{id:x.id,formId:form.id,formVersion:1,submittedAt:record.submittedAt}});});await mount(page,'fill',form);await fill(page);await page.getByRole('button',{name:'提交表单',exact:true}).click();await expect(page.getByRole('alert')).toContainText('无法确认');await page.getByRole('button',{name:'重试原提交'}).click();await expect(page.getByRole('alert')).toContainText('无法确认');await expect(page.getByLabel('事项说明 *',{exact:true})).toBeDisabled();await page.getByRole('button',{name:'重试原提交'}).click();await expect(page.getByRole('status')).toContainText('提交成功');expect(writes[1]).toEqual(writes[0]);expect(writes[2]).toEqual(writes[0]);});
test('stale form reload preserves multiple input backups and warns when leaving',async({page})=>{await page.route('**/api/forms/*/submissions',r=>r.fulfill({status:409,json:{error:'FORM_CONFLICT'}}));await page.route('**/api/forms/'+form.id,r=>r.fulfill({json:{...form,version:2,fields:[{...fields[0],field:{...fields[0].field,name:'新版事项'}}]}}));await mount(page,'fill',form);await fill(page);await page.getByRole('button',{name:'提交表单',exact:true}).click();await expect(page.getByRole('alert')).toContainText('表单已经更新');await expect(page.getByLabel('事项说明 *',{exact:true})).toHaveValue('原始填写 <script>');await page.getByRole('button',{name:'保留输入并载入最新版'}).click();await page.getByRole('dialog').getByRole('button',{name:'确认继续'}).click();await expect(page.getByLabel('新版事项 *',{exact:true})).toBeVisible();await expect(page.getByLabel('载入前的表单输入备份 1',{exact:true})).toHaveValue(/原始填写/);await page.getByRole('button',{name:'保留输入并载入最新版'}).click();await expect(page.getByLabel('载入前的表单输入备份 2',{exact:true})).toBeVisible();await expect(page.getByLabel('载入前的表单输入备份 1',{exact:true})).toHaveValue(/原始填写/);await page.getByRole('link',{name:'返回表单列表'}).click();await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();expect(page.url()).toContain('__forms_fixture');});
test('admin processes immutable submitted fields and retries exact unknown operation',async({page},info)=>{const writes:Record<string,unknown>[]=[];await page.route('**/api/admin/form-records/*',r=>{const x=r.request().postDataJSON();writes.push(x);return r.fulfill({json:{id:record.id,sequence:writes.length===1?99:1,status:x.status,note:x.note,processedBy:{id:'admin',name:'管理员乙'},processedAt:'2026-09-09T03:00:00.000Z'}});});await mount(page,'record',record);await expect(page.locator('.forms-answers')).toContainText('原始填写 <script>');await expect(page.locator('.forms-answers')).toContainText('否');await page.getByLabel('处理状态',{exact:true}).selectOption('resolved');await page.getByLabel('处理备注',{exact:true}).fill('已核对并完成');await page.getByRole('button',{name:'保存处理结果'}).click();await expect(page.getByRole('alert')).toContainText('无法确认');await expect(page.getByLabel('处理备注',{exact:true})).toBeDisabled();await page.getByRole('button',{name:'重试原操作'}).click();await expect(page.getByRole('status')).toContainText('处理结果已保存');expect(writes[1]).toEqual(writes[0]);await expect(page.getByText('最近处理：管理员乙',{exact:false})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'output/verification/forms-record-'+info.project.name+'.png',fullPage:true});});
test('processing conflict retains notes across failed and repeated reload with exit warning',async({page})=>{let reads=0;await page.route('**/api/admin/form-records/*',r=>r.request().method()==='PUT'?r.fulfill({status:409,json:{error:'CONFLICT'}}):++reads===1?r.fulfill({status:503}):r.fulfill({json:{...record,status:'processing',sequence:1,note:'已接手',processedBy:{id:'b',name:'管理员乙'},processedAt:'2026-09-09T02:00:00.000Z'}}));await mount(page,'record',record);await page.getByLabel('处理备注',{exact:true}).fill('我的备注');await page.getByRole('button',{name:'保存处理结果'}).click();await expect(page.getByRole('alert')).toContainText('另一位管理员');await page.getByRole('button',{name:'保留输入并载入最新记录'}).click();await page.getByRole('dialog').getByRole('button',{name:'确认继续'}).click();await expect(page.getByLabel('处理备注',{exact:true})).toHaveValue('我的备注');await page.getByRole('button',{name:'保留输入并载入最新记录'}).click();await page.getByRole('dialog').getByRole('button',{name:'确认继续'}).click();await expect(page.getByLabel('处理备注',{exact:true})).toHaveValue('已接手');await page.getByRole('button',{name:'保留输入并载入最新记录'}).click();await expect(page.getByLabel('处理输入备份 1',{exact:true})).toHaveValue(/我的备注/);await expect(page.getByLabel('处理输入备份 2',{exact:true})).toBeVisible();await page.getByRole('link',{name:'返回提交记录'}).click();await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();expect(page.url()).toContain('__forms_fixture');});
test('lists distinguish unavailable empty and records while actual APIs reject forged identity',async({page,request})=>{await mount(page,'collection',undefined);await expect(page.getByRole('status')).toContainText('暂时无法读取');await mount(page,'collection',[]);await expect(page.getByText('目前没有可填写的表单。')).toBeVisible();await mount(page,'records',{items:[record],total:1,page:1,pages:1});await expect(page.getByRole('link',{name:/异常处理申请/})).toHaveAttribute('href','/admin/forms/'+record.id);for(const path of ['/api/forms','/api/admin/forms','/api/admin/form-records']){const response=await request.get(path,{headers:{'x-role':'admin'}});expect([403,503]).toContain(response.status());expect(response.headers()['cache-control']).toBe('private, no-store');}});

test('custom reload confirmation cancels without changing employee input',async({page})=>{await mount(page,'fill',form);await fill(page);page.on('dialog',d=>d.dismiss());await page.getByRole('button',{name:'保留输入并载入最新版'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();await expect(page.getByLabel('事项说明 *',{exact:true})).toHaveValue('原始填写 <script>');});
