import {fixtureAssets} from '../helpers/fixture-assets';
import {test,expect,type Page} from '@playwright/test';
import {historyBrowserBundle,historyVersionFixture as fixture,historyPageFixture,historyAssetId} from '../helpers/history-browser';
import type {HistoryPage,HistoryVersion,DeletedHistoryPage} from '../../src/history/model';
let bundle:Awaited<ReturnType<typeof historyBrowserBundle>>;
test.beforeEach(async({page})=>{await fixtureAssets(page,'history');});
test.beforeAll(async()=>{bundle=await historyBrowserBundle();});
const endpoint='**/api/admin/history/history-local/versions/1';
const ack={documentId:'history-local',sequence:10,revision:4,sourceRevision:1,status:'draft',publishedRevision:2};
const refreshed={...fixture,sequence:10,currentRevision:4};
async function mount(page:Page,data:HistoryVersion|HistoryPage|DeletedHistoryPage=fixture,timeline:boolean|'deleted'=false){
 await page.route('**/__history_fixture',r=>r.fulfill({contentType:'text/html',body:`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${bundle.css}</style></head><body data-timeline="${timeline==='deleted'?'2':timeline?'1':'0'}"><header><a href="/sign-in" aria-label="JUYU Help Centre 首页"><span>JUYU Help Centre</span></a><p>历史管理 · 本地测试样例（非真实资料）</p></header><main style="max-width:960px;margin:auto;padding:20px"><script id="data" type="application/json">${JSON.stringify(data).replace(/</g,'\\u003c')}</script><div id="root"></div></main><script>${bundle.script.replace(/<\/script/gi,'<\\/script')}</script></body></html>`}));
 await page.route(`**/api/admin/history/history-local/versions/1/assets/${historyAssetId}`,r=>r.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/lV0AAAAASUVORK5CYII=','base64')}));
 await page.goto('/__history_fixture');await expect(page.getByRole('region',{name:timeline==='deleted'?'永久删除记录':timeline?'文章历史记录':'历史版本详情',exact:true})).toBeVisible();
}
async function confirm(page:Page){await page.getByRole('button',{name:'恢复此版本为新草稿',exact:true}).click();await page.getByRole('button',{name:'确认恢复为新草稿',exact:true}).click();}
test('full selected source retains metadata body categories cover and selected-version-only file routes',async({page},info)=>{
 await mount(page);const panel=page.getByRole('region',{name:'历史版本详情',exact:true});
 for(const label of ['完整历史正文','保留这段旧版说明 <script>不执行</script>','旧版标签','客服流程（旧版）','原作者 Ivy','当时编辑 Alex','运营与管理员'])await expect(panel.getByText(label,{exact:true})).toBeVisible();
 const hint=panel.getByRole('note',{name:'注意',exact:true});await expect(hint).toContainText('旧版提醒');await expect(hint).toContainText('请保留来源说明');
 await expect(page.getByRole('img',{name:'旧版封面'})).toHaveAttribute('src',`/api/admin/history/history-local/versions/1/assets/${historyAssetId}`);
 await expect(page.getByRole('link',{name:'打开 source-only.png',exact:true})).toHaveAttribute('href',`/api/admin/history/history-local/versions/1/assets/${historyAssetId}`);
 await expect(panel.locator('a[href^="/api/admin/assets/"]')).toHaveCount(0);await expect(panel.locator('[contenteditable="true"],textarea,input')).toHaveCount(0);await expect(page.getByRole('table')).toContainText('核对资料');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`output/verification/history-preview-${info.project.name}.png`,fullPage:true});
});
test('timeline exposes truthful separate totals pagination evidence and immutable version links',async({page},info)=>{
 await mount(page,historyPageFixture,true);const history=page.getByRole('region',{name:'操作时间线',exact:true});await expect(history).toContainText('共 32 条');await expect(history).toContainText('本页 2 条');await expect(history).toContainText('来源版本 1');await expect(history).toContainText('原正式版 2');await expect(history).toContainText('旧审核人');await expect(history).toContainText('新审核人');await expect(history).toContainText('交接给其他审核人');
 await expect(page.getByRole('link',{name:'下一页操作记录'})).toHaveAttribute('href','/admin/history?article=history-local&eventPage=2&versionPage=1');await expect(page.getByRole('link',{name:'下一页版本'})).toHaveAttribute('href','/admin/history?article=history-local&eventPage=1&versionPage=2');await expect(page.getByRole('link',{name:'查看版本 1'})).toHaveAttribute('href','/admin/history?article=history-local&revision=1');await expect(page.getByRole('region',{name:'版本列表'})).toContainText('共 31 个版本');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`output/verification/history-timeline-${info.project.name}.png`,fullPage:true});
});
test('purged receipts display metadata and audit only with no preview or recovery',async({page})=>{
 await mount(page,{...historyPageFixture,lifecycle:'purged',revision:null,status:null,publishedRevision:null,versions:[],versionTotal:0,versionPages:1,events:[{...historyPageFixture.events[0],action:'purge',sourceRevision:null,revision:null}],eventTotal:1,eventPages:1},true);await expect(page.getByText('永久删除记录',{exact:true})).toBeVisible();await expect(page.getByText('正文已永久删除；版本文件不再提供预览或恢复。附件清理进度请查看回收站。',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:/查看版本/})).toHaveCount(0);await expect(page.getByRole('button',{name:/恢复/})).toHaveCount(0);await expect(page.getByRole('region',{name:'操作时间线'})).toContainText('永久删除');await expect(page.getByRole('link',{name:'查看附件清理进度'})).toHaveAttribute('href','/admin/trash');
});
test('restore confirmation creates a new draft and preserves the existing formal publication',async({page},info)=>{
 const writes:unknown[]=[];await page.route(endpoint,r=>{if(r.request().method()==='GET')return r.fulfill({json:refreshed});writes.push(r.request().postDataJSON());return r.fulfill({json:ack});});await mount(page);await page.getByRole('button',{name:'恢复此版本为新草稿',exact:true}).click();await expect(page.getByText('当前正式内容（工作修订 2） 保持不变。',{exact:true})).toBeVisible();await expect(page.getByText('新草稿必须重新提交独立二审，再由管理员发布。',{exact:true})).toBeVisible();await page.getByRole('button',{name:'取消恢复'}).click();expect(writes).toHaveLength(0);await confirm(page);await expect(page.getByRole('status')).toContainText('新草稿版本 4');await expect(page.getByRole('status')).toContainText('正式内容（工作修订 2） 保持不变');await expect(page.getByText('当前工作版本：4',{exact:true})).toBeVisible();expect(writes).toEqual([{expectedSequence:9,sourceRevision:1}]);await page.screenshot({path:`output/verification/history-restored-${info.project.name}.png`,fullPage:true});
});
test('in-review current source and archived or trashed documents cannot restore',async({page})=>{
 for(const data of [{...fixture,status:'in_review' as const,canRestore:false},{...fixture,currentRevision:1,publishedRevision:null,canRestore:false},{...fixture,lifecycle:'archived' as const,canRestore:false},{...fixture,lifecycle:'trashed' as const,canRestore:false}]){await mount(page,data);await expect(page.getByRole('button',{name:'恢复此版本为新草稿',exact:true})).toHaveCount(0);await expect(page.getByRole('region',{name:'历史版本详情'})).toContainText(data.status==='in_review'?'请先结束当前审核':data.lifecycle==='archived'?'请先从归档恢复资料':data.lifecycle==='trashed'?'请先从回收站恢复资料':'当前工作版本不能作为历史恢复来源');}
});
test('malformed ack retains an exact retry and freezes cancellation refresh and all outside navigation',async({page})=>{
 const writes:unknown[]=[];await page.route(endpoint,r=>{if(r.request().method()==='GET')return r.fulfill({json:refreshed});writes.push(r.request().postDataJSON());return r.fulfill({json:writes.length===1?{...ack,publishedRevision:null}:ack});});await mount(page);await confirm(page);await expect(page.getByRole('alert')).toContainText('尚未确认');await expect(page.getByRole('button',{name:'取消恢复'})).toBeDisabled();await expect(page.getByRole('button',{name:'重新读取版本状态'})).toBeDisabled();await page.getByRole('link',{name:'JUYU Help Centre 首页'}).locator('span').click();await expect(page).toHaveURL(/\/__history_fixture$/);expect(await page.evaluate(()=>{const e=new Event('beforeunload',{cancelable:true});window.dispatchEvent(e);return e.defaultPrevented;})).toBe(true);await page.getByRole('button',{name:'重试原操作'}).click();await expect(page.getByRole('status')).toContainText('新草稿版本 4');expect(writes).toEqual([{expectedSequence:9,sourceRevision:1},{expectedSequence:9,sourceRevision:1}]);expect(await page.evaluate(()=>{const e=new Event('beforeunload',{cancelable:true});window.dispatchEvent(e);return e.defaultPrevented;})).toBe(false);
});
test('transport uncertainty survives a rejected retry and protects pending request navigation immediately',async({page})=>{
 let release!:()=>void;const held=new Promise<void>(r=>{release=r;});let count=0;await page.route(endpoint,async r=>{if(++count===1){await held;return r.abort('failed');}return r.fulfill({status:409,json:{error:'CONFLICT'}});});await mount(page);await confirm(page);try{await page.getByRole('link',{name:'JUYU Help Centre 首页'}).click();await expect(page).toHaveURL(/\/__history_fixture$/);await expect(page.getByRole('button',{name:'重新读取版本状态'})).toBeDisabled();}finally{release();}await page.getByRole('button',{name:'重试原操作'}).click();await expect(page.getByRole('alert')).toContainText('尚未确认');await expect(page.getByRole('button',{name:'取消恢复'})).toBeDisabled();await expect(page.getByRole('button',{name:'重新读取版本状态'})).toBeDisabled();
});
test('known rejection permits refresh and a new confirmation with the newly read sequence',async({page})=>{
 const writes:unknown[]=[];await page.route(endpoint,r=>{if(r.request().method()==='GET')return r.fulfill({json:{...fixture,sequence:10}});writes.push(r.request().postDataJSON());return writes.length===1?r.fulfill({status:409,json:{error:'MEMBER_BUSY'}}):r.abort('failed');});await mount(page);await confirm(page);await expect(page.getByRole('alert')).toContainText('恢复未执行');await expect(page.getByRole('button',{name:'重新读取版本状态'})).toBeEnabled();await expect(page.getByRole('button',{name:'确认恢复为新草稿'})).toBeDisabled();await page.getByRole('button',{name:'重新读取版本状态'}).click();await confirm(page);expect(writes).toEqual([{expectedSequence:9,sourceRevision:1},{expectedSequence:10,sourceRevision:1}]);await expect(page.getByRole('alert')).toContainText('尚未确认');
});
test('confirmed restore survives failed or stale reads and only a fresh snapshot unlocks controls',async({page})=>{
 let reads=0;await page.route(endpoint,r=>r.request().method()==='POST'?r.fulfill({json:ack}):++reads===1?r.fulfill({status:503,json:{error:'FAILED'}}):r.fulfill({json:reads===2?fixture:refreshed}));await mount(page);await confirm(page);await expect(page.getByRole('status')).toContainText('新草稿版本 4');await expect(page.getByRole('alert')).toContainText('未能读取');await expect(page.getByRole('button',{name:'恢复此版本为新草稿',exact:true})).toBeDisabled();await page.getByRole('button',{name:'重新读取版本状态'}).click();await expect(page.getByRole('alert')).toContainText('未能读取');await expect(page.getByRole('status')).toContainText('新草稿版本 4');await page.getByRole('button',{name:'重新读取版本状态'}).click();await expect(page.getByRole('button',{name:'恢复此版本为新草稿',exact:true})).toBeEnabled();await expect(page.getByText('当前工作版本：4',{exact:true})).toBeVisible();
});
test('fresh reads surface role denial and pending uploads without stale restore controls',async({page})=>{
 await page.route(endpoint,r=>r.request().method()==='POST'?r.fulfill({status:409,json:{error:'UPLOAD_IN_PROGRESS'}}):r.fulfill({status:403,json:{error:'FORBIDDEN'}}));await mount(page);await confirm(page);await expect(page.getByRole('alert')).toContainText('未完成的上传');await page.getByRole('button',{name:'重新读取版本状态'}).click();await expect(page.getByRole('alert')).toContainText('没有历史记录管理权限');await expect(page.getByRole('button',{name:'确认恢复为新草稿'})).toBeDisabled();
});
test('actual history routes reject forged identities while services remain unconfigured',async({request,page})=>{
 const base='/api/admin/history/00000000-0000-4000-8000-000000000039';for(const url of [base,`${base}/versions/1`,`${base}/versions/1/assets/${historyAssetId}`]){const r=await request.get(url,{headers:{'x-role':'admin','x-user-id':'a'}});expect(r.status()).toBe(503);expect(r.headers()['cache-control']).toBe('private, no-store');}const r=await request.post(`${base}/versions/1`,{headers:{'x-role':'admin'},data:{expectedSequence:9,sourceRevision:1}});expect(r.status()).toBe(503);await page.goto('/admin/history?article=00000000-0000-4000-8000-000000000039');await expect(page.getByRole('region',{name:'文章历史记录'})).toHaveCount(0);
});
test('deleted records remain discoverable with real count pagination and a distinct empty state',async({page},info)=>{
 await mount(page,{items:[{documentId:'purged-old',title:'已删除 <script> 历史资料',sequence:12,actorId:'operator',actorName:'Tony',deletedAt:'2026-09-09T01:00:00Z'}],total:31,page:1,pages:2},'deleted');await expect(page.getByRole('region',{name:'永久删除记录',exact:true})).toContainText('共 31 篇');await expect(page.getByRole('link',{name:'已删除 <script> 历史资料',exact:true})).toHaveAttribute('href','/admin/history?article=purged-old');await expect(page.getByRole('link',{name:'下一页删除记录'})).toHaveAttribute('href','/admin/history?page=2');await expect(page.getByRole('button',{name:/恢复/})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`output/verification/history-deleted-${info.project.name}.png`,fullPage:true});
 await mount(page,{items:[],total:0,page:1,pages:1},'deleted');await expect(page.getByText('没有永久删除记录。',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'下一页删除记录'})).toHaveCount(0);
});
test('structured source media and generated diagrams use the selected history revision',async({page})=>{
 const image={id:'source-image',type:'image' as const,assetId:historyAssetId,caption:'正文历史图片',alt:'正文原图'};const diagram={id:'source-diagram',type:'diagram' as const,source:'flowchart TD\n A --> B',caption:'历史流程图'};
 const body='JUYU_BLOCKNOTE_V1\n'+JSON.stringify([image,diagram].map(block=>({id:block.id,type:'juyu',props:{payload:JSON.stringify(block)},children:[]})));
 let diagrams=0;await page.route('**/api/admin/history/history-local/versions/1/diagram',r=>{expect(r.request().postDataJSON()).toEqual({source:diagram.source});diagrams++;return r.fulfill({json:{image:'data:image/svg+xml;base64,'+Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="40"><text y="20">History</text></svg>').toString('base64')}});});await mount(page,{...fixture,version:{...fixture.version,body,blocks:[image,diagram]}});await expect(page.getByRole('img',{name:'正文原图'})).toHaveCount(1);await expect(page.getByRole('button',{name:'检查并预览流程图'})).toHaveCount(1);await expect(page.getByRole('region',{name:'历史版本正文'}).locator('figure').first()).toContainText('正文历史图片');await expect(page.getByRole('img',{name:'正文原图'})).toHaveAttribute('src',`/api/admin/history/history-local/versions/1/assets/${historyAssetId}`);await page.getByRole('button',{name:'检查并预览流程图'}).click();await expect(page.getByRole('img',{name:'历史流程图'})).toBeVisible();expect(diagrams).toBe(1);
});
test('source files that are unavailable preserve the old body and explain disabled restoration',async({page})=>{
 await mount(page,{...fixture,canRestore:false,assets:[{...fixture.assets[0],status:'quarantined'}]});await expect(page.getByText('完整历史正文',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'恢复此版本为新草稿',exact:true})).toHaveCount(0);await expect(page.getByRole('region',{name:'恢复历史版本'})).toContainText('来源文件不允许恢复');await expect(page.getByRole('region',{name:'来源版本全部附件'})).toContainText('此来源文件当前无法读取');
});

test('Q&A source classification and ordering remain visible in historical preview',async({page})=>{await mount(page,{...fixture,version:{...fixture.version,qa:{category:'来源问答分类样例',position:23}}});await expect(page.getByText('来源问答分类样例',{exact:true})).toBeVisible();await expect(page.getByText('23',{exact:true})).toBeVisible();});
