import {test,expect,type Page} from '@playwright/test';import {lifecycleBrowserBundle,trashFixture} from '../helpers/lifecycle-browser';
let bundle:Awaited<ReturnType<typeof lifecycleBrowserBundle>>;test.beforeAll(async()=>{bundle=await lifecycleBrowserBundle();});
async function mount(page:Page){await page.route('**/__trash_fixture',r=>r.fulfill({contentType:'text/html',body:`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${bundle.css}</style></head><body><header>JUYU · 本地样例</header><script id="data" type="application/json">${JSON.stringify(trashFixture).replace(/</g,'\\u003c')}</script><div id="root"></div><script>${bundle.script.replace(/<\/script/gi,'<\\/script')}</script></body></html>`}));await page.goto('/__trash_fixture');await expect(page.getByRole('heading',{name:'回收站',exact:true})).toBeVisible();}
test('trash restore requires acknowledged success and stays unpublished',async({page})=>{
 let writes=0;await page.route('**/api/admin/lifecycle/*',r=>{const v=r.request().postDataJSON();expect(v).toEqual({action:'restore',expectedSequence:6});writes++;return r.fulfill({json:{documentId:'trash-1',action:'restore',sequence:7,cleanupPending:0}});});await page.route('**/api/admin/trash?*',r=>r.fulfill({json:{...trashFixture,items:[],total:0}}));await mount(page);await page.getByRole('button',{name:'恢复为未发布草稿'}).click();await expect(page.getByRole('status')).toContainText('已恢复为未发布草稿');await expect(page.getByText('回收站没有文章。')).toBeVisible();expect(writes).toBe(1);
});
test('purge has independent exact-title confirmation and exposes unfinished attachment cleanup',async({page},info)=>{
 let purges=0,pending=2;await page.route('**/api/admin/lifecycle/trash-1',r=>{expect(r.request().postDataJSON()).toEqual({action:'purge',expectedSequence:6,confirmation:trashFixture.items[0].title});purges++;return r.fulfill({json:{documentId:'trash-1',action:'purge',sequence:7,cleanupPending:2}});});await page.route('**/api/admin/trash?*',r=>r.fulfill({json:{...trashFixture,items:[],total:0,cleanup:pending?[{documentId:'trash-1',title:trashFixture.items[0].title,pending}]:[],cleanupTotal:pending?1:0}}));await page.route('**/api/admin/lifecycle/trash-1/cleanup',r=>{pending=0;return r.fulfill({json:{documentId:'trash-1',cleanupPending:0}});});
 await mount(page);await page.getByRole('button',{name:'永久删除',exact:true}).click();await expect(page.getByRole('button',{name:'永久删除这篇文章'})).toBeDisabled();await page.getByLabel('输入文章标题确认永久删除').fill('不匹配');await expect(page.getByRole('button',{name:'永久删除这篇文章'})).toBeDisabled();await page.getByLabel('输入文章标题确认永久删除').fill(trashFixture.items[0].title);expect(purges).toBe(0);await page.screenshot({path:`output/verification/trash-${info.project.name}.png`,fullPage:true});await page.getByRole('button',{name:'永久删除这篇文章'}).click();await expect(page.getByRole('status')).toContainText('2 个附件待清理');await expect(page.getByRole('button',{name:'重试清理附件'})).toBeVisible();await page.getByRole('button',{name:'重试清理附件'}).click();await expect(page.getByRole('status')).toContainText('附件清理完成');expect(purges).toBe(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('conflicts and unconfirmed results keep confirmation input and never claim deletion',async({page})=>{
 await page.route('**/api/admin/lifecycle/*',r=>r.fulfill({status:409,json:{error:'CONFLICT'}}));await mount(page);await page.getByRole('button',{name:'永久删除',exact:true}).click();await page.getByLabel('输入文章标题确认永久删除').fill(trashFixture.items[0].title);await page.getByRole('button',{name:'永久删除这篇文章'}).click();await expect(page.getByRole('alert')).toContainText('已被更新');await expect(page.getByLabel('输入文章标题确认永久删除')).toHaveValue(trashFixture.items[0].title);await expect(page.getByRole('status')).toHaveCount(0);await page.getByRole('button',{name:'取消永久删除'}).click();await expect(page.getByRole('region',{name:'永久删除确认'})).toHaveCount(0);
});
test('actual trash and lifecycle endpoints reject forged identity before mutations',async({request,page})=>{
 for(const path of ['/api/admin/trash','/api/admin/lifecycle/fixture','/api/admin/lifecycle/fixture/cleanup']){const r=path.endsWith('/trash')?await request.get(path):await request.post(path,{headers:{'x-role':'admin'},data:{action:'purge',expectedSequence:0,confirmation:'forged'}});expect(r.status()).toBe(503);expect(r.headers()['cache-control']).toBe('private, no-store');}await page.goto('/admin/trash');await expect(page.getByRole('button',{name:'永久删除',exact:true})).toHaveCount(0);
});
