import {test,expect,type Page} from '@playwright/test';
import {navigationBrowserBundle} from '../helpers/navigation-browser';import {editorBrowserBundle,editorFixture} from '../helpers/editor-browser';import {referenceBrowserBundle} from '../helpers/reference-browser';
import {largeBody,longTable} from '../performance/fixtures';import {summary,writeReport} from '../performance/report';import {decodeEditorBody} from '../../src/editor/document';
const bundles=new Map<string,Promise<{script:string;css:string}>>();
async function bundleFor(kind:string){if(!bundles.has(kind))bundles.set(kind,kind==='reader'?navigationBrowserBundle():kind==='editor'?editorBrowserBundle():referenceBrowserBundle());return bundles.get(kind)!;}
async function mount(page:Page,kind:string,data:()=>unknown){const bundle=await bundleFor(kind);const root=kind==='reader'?'presentation':kind;await page.route('**/api/**',r=>r.fulfill({status:503,json:{error:'LOCAL_FIXTURE_ONLY'}}));await page.route(url=>url.pathname==='/__scale'||(kind==='editor'&&url.pathname==='/admin/editor'),r=>r.fulfill({contentType:'text/html; charset=utf-8',body:`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${bundle.css}</style></head><body><div ${kind==='reader'?'':`class="${kind==='editor'?'editor-main':'editor-main search-main'}"`}><h1>规模验收 · 本地合成资料</h1><div id="${root}"></div></div><script id="data" type="application/json">${JSON.stringify(data()).replaceAll('<','\\u003c')}</script><script>${bundle.script.replaceAll('</script','<\\/script')}</script></body></html>`}));}
async function noOverflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
const body=largeBody();
test('T058 1000-entry directory and 300-block reading stay usable',async({page},info)=>{
 test.setTimeout(120000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const pages=Array.from({length:20},(_,g)=>({id:`group-${g}`,type:'group',title:`资料组 ${g+1}`,descendants:Array.from({length:50},(_,i)=>({id:`doc-${g*50+i}`,type:'document',title:`本地资料 ${g*50+i+1}`,href:`/help-centre?article=doc-${g*50+i}`}))}));
 await mount(page,'reader',()=>({pages,requested:'doc-999',article:{id:'doc-999',title:'大文章本地验收',revision:1,body,blocks:[],tags:[]}}));
 const loads:number[]=[],menus:number[]=[];
 for(let i=0;i<5;i++){const start=performance.now();await page.goto('/__scale');await expect(page.locator('#main-content')).toContainText('结束标记300');loads.push(performance.now()-start);await noOverflow(page);
  const begin=performance.now();if(info.project.name==='mobile'){await page.getByRole('button',{name:'打开文章目录'}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('dialog').locator('[aria-current="page"]')).toHaveText('本地资料 1000');menus.push(performance.now()-begin);await page.keyboard.press('Escape');}else{const group=page.locator('.desktop-navigation').getByRole('button',{name:'资料组 20',exact:true});await group.click();await expect(group).toHaveAttribute('aria-expanded','false');await group.click();await expect(group).toHaveAttribute('aria-expanded','true');menus.push(performance.now()-begin);}
 }
 await page.screenshot({path:`output/verification/T058/reader-${info.project.name}.png`});await writeReport(`browser-reader-${info.project.name}`,{scope:'Existing development component fixture with built CSS; no auth or network backend; bundle compilation excluded.',entries:1000,groups:20,blocks:300,bodyChars:body.length,load:summary(loads),menu:summary(menus),domNodes:await page.locator('*').count()});expect(errors).toEqual([]);expect(Math.max(...loads)).toBeLessThan(3000);expect(Math.max(...menus)).toBeLessThan(1000);
});
test('T058 300-block BlockNote edit autosave and reload preserve every block',async({page},info)=>{
 test.setTimeout(120000);let saved={...editorFixture,body};await mount(page,'editor',()=>saved);let writes=0;
 await page.route('**/api/admin/editor/*',r=>{const value=r.request().postDataJSON();expect(value.expectedSequence).toBe(saved.sequence);saved={...saved,...value,sequence:saved.sequence+1};writes++;return r.fulfill({json:saved});});
 const loads:number[]=[],saves:number[]=[];
 for(let i=0;i<5;i++){const start=performance.now();await page.goto('/__scale');const area=page.locator('.bn-editor[contenteditable="true"]');await expect(area).toBeVisible();await expect(area).toContainText('结束标记300');loads.push(performance.now()-start);
  const begin=performance.now();await area.focus();await area.press('ControlOrMeta+End');await page.keyboard.insertText(` 保存核对${i}`);await expect.poll(()=>writes,{timeout:10000}).toBe(i+1);await expect(page.locator('.editor-save-bar')).toContainText('所有修改已保存');saves.push(performance.now()-begin);expect(decodeEditorBody(saved.body)).toHaveLength(300);expect(saved.body).toContain(`保存核对${i}`);await noOverflow(page);
 }
 await page.reload();await expect(page.locator('.bn-editor')).toContainText('保存核对4');await page.locator('.editor-save-bar').scrollIntoViewIfNeeded();await page.screenshot({path:`output/verification/T058/editor-${info.project.name}.png`});await writeReport(`browser-editor-${info.project.name}`,{scope:'Actual BlockNote component, simulated save transport; not durable database timing.',blocks:300,bodyChars:body.length,load:summary(loads),saveConfirmation:summary(saves),writes});expect(Math.max(...loads)).toBeLessThan(5000);expect(Math.max(...saves)).toBeLessThan(5000);
});
test('T058 200-row eight-column Reference filters last row without overflow',async({page},info)=>{
 test.setTimeout(90000);const detail={id:'scale-reference',title:'规模速查表',revision:1,tags:[],tables:[longTable]};await mount(page,'reference',()=>({state:'ready',detailState:'ready',data:{items:[detail],total:1,page:1,pages:1,canEdit:false},detail}));const filters:number[]=[];
 await page.goto('/__scale');const table=page.getByRole('region',{name:'速查表 1',exact:true});await expect(table.getByRole('status')).toContainText('共 200 行');
 for(let i=0;i<5;i++){const start=performance.now();await table.getByRole('textbox',{name:'筛选表格'}).fill('最后行针尖');await expect(table.getByRole('status')).toContainText('符合 1 行');await expect(table.getByRole('rowheader')).toHaveText('200');filters.push(performance.now()-start);await table.getByRole('button',{name:'清除筛选'}).click();}
 await table.getByRole('button',{name:'下一页',exact:true}).click();await expect(table.getByRole('rowheader').first()).toHaveText('21');await noOverflow(page);await table.scrollIntoViewIfNeeded();await page.screenshot({path:`output/verification/T058/reference-${info.project.name}.png`});await writeReport(`browser-table-${info.project.name}`,{rows:200,columns:8,visibleRows:20,filter:summary(filters)});expect(Math.max(...filters)).toBeLessThan(1000);
});
