import {fixtureAssets} from '../helpers/fixture-assets';
import {test,expect,type Page} from '@playwright/test';
import {publicationBrowserBundle,publicationFixture as fixture} from '../helpers/publication-browser';
import type {PublicationDetail} from '../../src/review/publication';
let bundle:Awaited<ReturnType<typeof publicationBrowserBundle>>;
test.beforeEach(async({page})=>{await fixtureAssets(page,'publication');});
test.beforeAll(async()=>{bundle=await publicationBrowserBundle();});
async function mount(page:Page,initial=fixture){await page.route('**/__publication_fixture',r=>r.fulfill({contentType:'text/html',body:`<!doctype html><html lang="${initial.article.locale==='en'?'en':'zh-CN'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${bundle.css}</style></head><body><main class="editor-main"><h1>文章发布 · 本地样例</h1><script type="application/json" id="data">${JSON.stringify(initial).replace(/</g,'\\u003c')}</script><div id="review"></div></main><script>${bundle.script.replace(/<\/script/gi,'<\\/script')}</script></body></html>`}));await page.goto('/__publication_fixture');await expect(page.getByRole('region',{name:initial.article.locale==='en'?'Manage publication':'文章发布管理'})).toBeVisible();}
const ack=(action:'queue'|'publish'|'direct_publish')=>({documentId:fixture.article.documentId,sequence:action==='publish'?7:6,revision:2,action,status:action==='queue'?'queued':'published',publishedRevision:action==='queue'?1:2,approvedBy:action==='direct_publish'?'super-a':'admin-b'});
test('Super Admin can cancel or confirm direct publication without a reason field',async({page})=>{const writes:unknown[]=[];const direct={...fixture,article:{...fixture.article,status:'draft' as const,sequence:5},approval:null,canQueue:false,canPublish:false,canDirectPublish:true};await page.route('**/api/admin/review/*/publication',r=>{if(r.request().method()==='GET')return r.fulfill({json:{...direct,article:{...direct.article,status:'published',sequence:6,publishedRevision:2},canDirectPublish:false}});writes.push(r.request().postDataJSON());return r.fulfill({json:ack('direct_publish')});});await mount(page,direct);await page.getByRole('button',{name:'批准并发布',exact:true}).click();const dialog=page.getByRole('dialog',{name:'批准并发布'});await expect(dialog).toContainText('这份当前保存的内容将由你的 Super Admin 账号直接批准并发布。');await expect(dialog.locator('textarea,input[type="text"]')).toHaveCount(0);await dialog.getByRole('button',{name:'取消',exact:true}).click();expect(writes).toHaveLength(0);await page.getByRole('button',{name:'批准并发布',exact:true}).click();await page.getByRole('dialog',{name:'批准并发布'}).getByRole('button',{name:'确认发布',exact:true}).click();expect(writes).toEqual([{expectedSequence:5,action:'direct_publish'}]);await expect(page.getByRole('status')).toContainText('已由你的 Super Admin 账号批准并发布');});
test('English direct publication requires a natural-English confirmation',async({page})=>{const writes:unknown[]=[];const direct={...fixture,article:{...fixture.article,locale:'en' as const,status:'changes_requested' as const,sequence:5},approval:null,canQueue:false,canPublish:false,canDirectPublish:true};await page.route('**/api/admin/review/*/publication',r=>{if(r.request().method()==='GET')return r.fulfill({json:{...direct,article:{...direct.article,status:'published',sequence:6,publishedRevision:2},canDirectPublish:false}});writes.push(r.request().postDataJSON());return r.fulfill({json:ack('direct_publish')});});await mount(page,direct);await page.getByRole('button',{name:'Approve and publish',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Approve and publish'});const confirm=dialog.getByRole('button',{name:'Confirm publication',exact:true});await expect(confirm).toBeDisabled();await dialog.getByRole('checkbox').check();await expect(confirm).toBeEnabled();await confirm.click();expect(writes).toEqual([{expectedSequence:5,action:'direct_publish',englishQualityConfirmed:true}]);});
test('English publication shows clear native-language actions and still requires confirmation',async({page})=>{const writes:unknown[]=[];await page.route('**/api/admin/review/*/publication',r=>{if(r.request().method()==='GET')return r.fulfill({json:{...fixture,article:{...fixture.article,locale:'en',status:'queued',sequence:6},canQueue:false,canPublish:true}});writes.push(r.request().postDataJSON());return r.fulfill({json:ack('queue')});});await mount(page,{...fixture,article:{...fixture.article,locale:'en',title:'How to update your account email',body:'# Before you start\n\nCheck that you can access your current email.'}});await expect(page.getByText('Current publication: Published (working revision 1)')).toBeVisible();await page.getByRole('button',{name:'Schedule publication',exact:true}).click();await expect(page.getByText('Employees will not see it until it is published.',{exact:false})).toBeVisible();expect(writes).toHaveLength(0);await page.getByRole('button',{name:'Confirm schedule',exact:true}).click();await expect(page.getByRole('status')).toContainText('Version 2 is scheduled');expect(writes).toEqual([{expectedSequence:5,action:'queue'}]);});
test('English publication uses approved category names and English custom-field labels',async({page})=>{const id='00000000-0000-4000-8000-000000000126';await mount(page,{...fixture,article:{...fixture.article,locale:'en',categoryIds:[id],categoryOptions:[{id,version:1,name:'账户安全',englishName:'Account security',parentId:null,position:0,audience:'staff',enabled:true}],customFields:[{id:'00000000-0000-4000-8000-000000000127',version:1,enabled:true,name:'Requires approval',type:'boolean',required:false,options:[],value:true}]}});await expect(page.getByRole('region',{name:'Article categories'})).toContainText('Account security · All staff');await expect(page.getByRole('region',{name:'Custom fields'})).toContainText('Requires approval');await expect(page.getByRole('region',{name:'Custom fields'})).toContainText('Yes');});
function changed(action:'queue'|'publish'):PublicationDetail{return {...fixture,article:{...fixture.article,sequence:action==='queue'?6:7,status:action==='queue'?'queued':'published',publishedRevision:action==='queue'?1:2},canQueue:false,canPublish:action==='queue',history:[{sequence:action==='queue'?6:7,revision:2,action,actorId:'admin-a',actorName:'Alex',at:'2026-09-09T02:00:00Z'}]};}
test('queue confirmation never publishes and explicit second confirmation replaces the formal version',async({page},info)=>{let action:'queue'|'publish'='queue';const writes:unknown[]=[];await page.route('**/api/admin/review/*/publication',r=>{if(r.request().method()==='GET')return r.fulfill({json:changed(action)});const input=r.request().postDataJSON();writes.push(input);action=input.action;return r.fulfill({json:ack(action)});});await mount(page);await expect(page.getByRole('button',{name:'正式发布此版本',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'加入等待发布',exact:true}).click();await page.getByRole('button',{name:'取消操作'}).click();expect(writes).toHaveLength(0);await page.getByRole('button',{name:'加入等待发布',exact:true}).click();await page.getByRole('button',{name:'确认加入等待发布',exact:true}).click();await expect(page.getByRole('status')).toContainText('等待发布');await expect(page.getByText('当前正式版：已发布（工作修订 1）',{exact:true})).toBeVisible();await page.getByRole('button',{name:'正式发布此版本',exact:true}).click();await expect(page.getByText('发布后，工作修订 2 将替换正式内容（工作修订 1）。',{exact:true})).toBeVisible();await page.screenshot({path:`output/verification/publication-confirm-${info.project.name}.png`,fullPage:true});await page.getByRole('button',{name:'确认正式发布',exact:true}).click();await expect(page.getByRole('status')).toContainText('工作修订 2 已正式发布');await expect(page.getByText('当前正式版：已发布（工作修订 2）',{exact:true})).toBeVisible();expect(writes).toEqual([{expectedSequence:5,action:'queue'},{expectedSequence:6,action:'publish'}]);await expect(page.getByRole('region',{name:'发布记录'})).toContainText('Alex');await expect(page.getByRole('button',{name:'正式发布此版本',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`output/verification/publication-done-${info.project.name}.png`,fullPage:true});});
test('initial publication states show actual audience approval and complete saved body',async({page})=>{await mount(page,{...fixture,article:{...fixture.article,publishedRevision:null,audience:'ops',kind:'ops'}});await expect(page.getByText('Ops 与 Admin',{exact:true})).toBeVisible();await expect(page.getByText('当前正式版：尚未发布',{exact:true})).toBeVisible();await expect(page.getByRole('region',{name:'文章发布管理'})).toContainText('Ivy');await expect(page.getByRole('article',{name:'当前保存正文'})).toContainText('已批准的完整正文');});
test('draft review rejected inactive or unapproved snapshots expose no publication actions',async({page})=>{for(const state of ['draft','in_review','changes_requested','published'] as const){await mount(page,{...fixture,article:{...fixture.article,status:state},canQueue:false,canPublish:false,approval:null});await expect(page.getByRole('button',{name:'加入等待发布',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'正式发布此版本',exact:true})).toHaveCount(0);}await mount(page,{...fixture,article:{...fixture.article,lifecycle:'trashed'}});await expect(page.getByRole('button',{name:'加入等待发布',exact:true})).toHaveCount(0);});
test('invalid publication acknowledgement locks version and navigation until exact retry succeeds',async({page})=>{const writes:unknown[]=[];await page.route('**/api/admin/review/*/publication',r=>{if(r.request().method()==='GET')return r.fulfill({json:changed('publish')});writes.push(r.request().postDataJSON());return r.fulfill({json:writes.length===1?{...ack('publish'),publishedRevision:1}:ack('publish')});});await mount(page,changed('queue'));await page.getByRole('button',{name:'正式发布此版本',exact:true}).click();await page.getByRole('button',{name:'确认正式发布',exact:true}).click();await expect(page.getByRole('alert')).toContainText('尚未确认');await expect(page.getByRole('button',{name:'重新读取发布状态'})).toBeDisabled();await expect(page.getByRole('button',{name:'取消操作'})).toBeDisabled();await expect(page.getByRole('link',{name:'返回二审详情'})).toHaveCount(0);await page.getByRole('button',{name:'重试原操作'}).click();await expect(page.getByRole('status')).toContainText('已正式发布');expect(writes).toEqual([{expectedSequence:6,action:'publish'},{expectedSequence:6,action:'publish'}]);});
test('confirmed publish survives failed refresh without invented records or actions on old data',async({page})=>{let reads=0;await page.route('**/api/admin/review/*/publication',r=>r.request().method()==='POST'?r.fulfill({json:ack('publish')}):++reads===1?r.fulfill({status:503,json:{error:'FAILED'}}):r.fulfill({json:changed('publish')}));await mount(page,changed('queue'));await page.getByRole('button',{name:'正式发布此版本',exact:true}).click();await page.getByRole('button',{name:'确认正式发布',exact:true}).click();await expect(page.getByRole('status')).toContainText('已正式发布');await expect(page.getByRole('alert')).toContainText('未能读取');await expect(page.getByRole('region',{name:'发布记录'})).not.toContainText('正式发布');await expect(page.getByRole('button',{name:'正式发布此版本',exact:true})).toBeDisabled();await page.getByRole('button',{name:'重新读取发布状态'}).click();await expect(page.getByText('当前正式版：已发布（工作修订 2）',{exact:true})).toBeVisible();});
test('definite rejection blocks old confirmation and refuses a stale refresh',async({page})=>{await page.route('**/api/admin/review/*/publication',r=>r.request().method()==='POST'?r.fulfill({status:409,json:{error:'INVALID_APPROVAL'}}):r.fulfill({json:{...fixture,article:{...fixture.article,sequence:4}}}));await mount(page);await page.getByRole('button',{name:'加入等待发布',exact:true}).click();await page.getByRole('button',{name:'确认加入等待发布',exact:true}).click();await expect(page.getByRole('alert')).toContainText('缺少有效');await expect(page.getByRole('button',{name:'确认加入等待发布',exact:true})).toBeDisabled();await page.getByRole('button',{name:'重新读取发布状态'}).click();await expect(page.getByRole('alert')).toContainText('未能读取');});
test('write and refresh exclude each other while a request is pending',async({page})=>{let release!:()=>void;const held=new Promise<void>(resolve=>{release=resolve;});await page.route('**/api/admin/review/*/publication',async r=>{await held;return r.fulfill({json:fixture});});await mount(page);await page.getByRole('button',{name:'重新读取发布状态'}).click();await expect(page.getByRole('button',{name:'加入等待发布',exact:true})).toBeDisabled();await expect(page.getByRole('link',{name:'返回二审详情'})).toHaveCount(0);release();await expect(page.getByRole('button',{name:'加入等待发布',exact:true})).toBeEnabled();});
test('transport uncertainty cannot turn a later conflict into a false failed publication',async({page})=>{let calls=0;await page.route('**/api/admin/review/*/publication',r=>++calls===1?r.abort('failed'):r.fulfill({status:409,json:{error:'CONFLICT'}}));await mount(page,changed('queue'));await page.getByRole('button',{name:'正式发布此版本',exact:true}).click();await page.getByRole('button',{name:'确认正式发布',exact:true}).click();await page.getByRole('button',{name:'重试原操作'}).click();await expect(page.getByRole('alert')).toContainText('尚未确认');await expect(page.getByRole('button',{name:'重新读取发布状态'})).toBeDisabled();});
test('history explains its bounded scope and missing files produce a recoverable rejection',async({page})=>{await page.route('**/api/admin/review/*/publication',r=>r.fulfill({status:409,json:{error:'INVALID_MEDIA'}}));await mount(page,{...fixture,historyMore:true});await expect(page.getByRole('region',{name:'发布记录'})).toContainText('更早记录');await page.getByRole('button',{name:'加入等待发布',exact:true}).click();await page.getByRole('button',{name:'确认加入等待发布',exact:true}).click();await expect(page.getByRole('alert')).toContainText('附件');await expect(page.getByRole('button',{name:'重新读取发布状态'})).toBeEnabled();});
test('real unconfigured publication endpoints cannot be opened using forged administrator headers',async({page,request})=>{for(const method of ['get','post'] as const){const r=await request[method]('/api/admin/review/00000000-0000-4000-8000-000000000037/publication',{headers:{'x-role':'admin','x-user-id':'admin-a'},...(method==='post'?{data:{action:'publish',expectedSequence:6}}:{})});expect(r.status()).toBe(503);expect(r.headers()['cache-control']).toBe('private, no-store');}await page.goto('/admin/review/publish?article=00000000-0000-4000-8000-000000000037');await expect(page.getByRole('region',{name:'文章发布管理'})).toHaveCount(0);});

test('Q&A category and ordering are visible when reviewing the saved version',async({page})=>{await mount(page,{...fixture,article:{...fixture.article,kind:'qa',qa:{category:'待核对分类',position:17}}});await expect(page.getByText('待核对分类',{exact:true})).toBeVisible();await expect(page.getByText('17',{exact:true})).toBeVisible();});

test('R18 global navigation stays blocked through uncertain publication and clears after acknowledgement',async({page})=>{
 let calls=0;await page.route('**/api/admin/review/*/publication',r=>r.fulfill({json:r.request().method()==='GET'?changed('publish'):++calls===1?{...ack('publish'),publishedRevision:1}:ack('publish')}));
 await page.route('**/__leave_target',r=>r.fulfill({body:'left safely'}));await mount(page,changed('queue'));
 await page.evaluate(()=>{const a=document.createElement('a');a.href='/__leave_target';a.textContent='全局侧栏测试';document.body.prepend(a);});
 await page.getByRole('button',{name:'正式发布此版本',exact:true}).click();await page.getByRole('button',{name:'确认正式发布',exact:true}).click();
 await page.getByRole('link',{name:'全局侧栏测试'}).click();await expect(page).toHaveURL(/__publication_fixture/);await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('button',{name:'重试原操作'}).click();await expect(page.getByRole('status')).toContainText('已正式发布');
 await page.getByRole('link',{name:'全局侧栏测试'}).click();await expect(page).toHaveURL(/__leave_target/);expect(calls).toBe(2);
});
