import {test,expect,type Page} from '@playwright/test';import {qaBrowserBundle} from '../helpers/qa-browser';
let bundle:Awaited<ReturnType<typeof qaBrowserBundle>>;test.beforeAll(async()=>{bundle=await qaBrowserBundle();});
async function mount(page:Page,options:{admin?:boolean;state?:'ready'|'denied'|'unavailable';empty?:boolean;category?:string}={}){
 const data={state:options.state??'ready',data:{items:options.empty?[]:[{id:'qa-local',title:'如何核对 <script>账户</script>？',revision:2,tags:['本地样例'],category:'账户 / 问题',position:2},{id:'qa-empty',title:'如何联系负责人？',revision:1,tags:[],category:'',position:4}],total:options.empty?0:22,page:1,pages:options.empty?1:2,canEdit:options.admin??false,...(options.category!==undefined?{category:options.category}:{})}};
 await page.route('**/__qa_fixture',r=>r.fulfill({contentType:'text/html',body:`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${bundle.css}</style></head><body><header>Q&A · 本地测试样例（非真实业务资料）</header><main class="editor-main search-main"><div id="qa"></div></main><script id="data" type="application/json">${JSON.stringify(data).replace(/</g,'\\u003c')}</script><script>${bundle.script.replace(/<\/script/gi,'<\\/script')}</script></body></html>`}));await page.goto('/__qa_fixture');await expect(page.getByRole('heading',{name:'常见问答',exact:true})).toBeVisible();
}
test('Q&A list preserves formal question links literal text category navigation and page filters',async({page},info)=>{
 await mount(page,{category:'账户 / 问题'});await expect(page.getByRole('status')).toContainText('共 22 条正式问答');await expect(page.getByRole('link',{name:'阅读答案：如何核对 <script>账户</script>？'})).toHaveAttribute('href','/help-centre?article=qa-local');await expect(page.locator('.qa-view script')).toHaveCount(0);
 const next=new URL(await page.getByRole('link',{name:'下一页',exact:true}).getAttribute('href')??'', 'http://local');expect(next.searchParams.get('category')).toBe('账户 / 问题');expect(next.searchParams.get('page')).toBe('2');await expect(page.getByRole('link',{name:'查看分类：未分类',exact:true})).toHaveAttribute('href','/help-centre/qa?page=1&category=');await expect(page.getByRole('link',{name:'新建问答'})).toHaveCount(0);await expect(page.getByRole('link',{name:/^编辑问答：/})).toHaveCount(0);
 await expect(page.getByRole('search',{name:'按问答分类查找'})).toHaveAttribute('method','get');await expect(page.getByRole('textbox',{name:'问答分类'})).toHaveValue('账户 / 问题');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`output/verification/qa-${info.project.name}.png`,fullPage:true});await page.evaluate(()=>document.documentElement.dataset.theme='dark');
 const contrast=()=>page.getByRole('button',{name:'查看此分类',exact:true}).evaluate(el=>{const s=getComputedStyle(el),canvas=document.createElement('canvas'),c=canvas.getContext('2d')!;const luminance=(color:string)=>{c.fillStyle=color;c.fillRect(0,0,1,1);const rgb=[...c.getImageData(0,0,1,1).data].slice(0,3).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;});return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];};const a=luminance(s.color),b=luminance(s.backgroundColor);return {ratio:(Math.max(a,b)+.05)/(Math.min(a,b)+.05),fg:s.color,bg:s.backgroundColor,panel:s.getPropertyValue('--panel'),rootPanel:getComputedStyle(document.documentElement).getPropertyValue('--panel')};});await expect.poll(async()=>(await contrast()).ratio).toBeGreaterThanOrEqual(4.5);
 await page.screenshot({path:`output/verification/qa-dark-${info.project.name}.png`,fullPage:true,animations:'disabled'});
});
test('Q&A admin entry uses the shared reviewed editor while denied states suppress supplied private data',async({page})=>{
 await mount(page,{admin:true});await expect(page.getByRole('link',{name:'新建问答'})).toHaveAttribute('href','/admin/editor?kind=qa');await expect(page.getByRole('link',{name:'编辑问答：如何核对 <script>账户</script>？'})).toHaveAttribute('href','/admin/editor?article=qa-local');
 for(const state of ['denied','unavailable'] as const){await page.unrouteAll();await mount(page,{admin:true,state});await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByRole('list',{name:'正式问题'})).toHaveCount(0);await expect(page.getByRole('link',{name:'新建问答'})).toHaveCount(0);await expect(page.getByRole('status')).toHaveCount(0);}
});
test('Q&A empty collection and empty exact classification explain the actual scope',async({page})=>{
 await mount(page,{empty:true});await expect(page.getByText('暂时没有已发布的问答',{exact:true})).toBeVisible();await page.unrouteAll();await mount(page,{empty:true,category:''});await expect(page.getByText('此分类下没有可阅读的正式问答',{exact:true})).toBeVisible();await expect(page.getByRole('status')).toContainText('分类：未分类');
});
test('actual Q&A routes reject unconfigured forged identities before any private content',async({page,request})=>{
 const r=await request.get('/api/qa',{headers:{'x-role':'admin','x-user-id':'a'}});expect(r.status()).toBe(503);expect(r.headers()['cache-control']).toBe('private, no-store');expect(await r.json()).toEqual({error:'QA_UNAVAILABLE'});await page.goto('/help-centre/qa');await expect(page).toHaveURL(/\/sign-in$/);await page.goto('/admin/editor?kind=qa');await expect(page.locator('.bn-editor')).toHaveCount(0);
});
