import {test,expect,type Page} from '@playwright/test';import {recentBrowserBundle} from '../helpers/recent-browser';
let bundle:Awaited<ReturnType<typeof recentBrowserBundle>>;test.beforeAll(async()=>{bundle=await recentBrowserBundle();});
async function mount(page:Page,props:unknown={documentId:'recent-local',revision:1},mode='recorder',hidden=false){
 await page.route('**/__recent_fixture*',r=>r.fulfill({contentType:'text/html',body:`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${bundle.css}</style></head><body><header>最近浏览 · 本地测试样例（非真实员工资料）</header><main class="editor-main search-main"><div id="recent"></div></main><script>window.fixtureVisible=${!hidden};Object.defineProperty(document,'visibilityState',{configurable:true,get:()=>window.fixtureVisible?'visible':'hidden'});window.changeVisibility=(v)=>{window.fixtureVisible=v;document.dispatchEvent(new Event('visibilitychange'));};</script><script id="data" type="application/json">${JSON.stringify({mode,props}).replace(/</g,'\\u003c')}</script><script>${bundle.script.replace(/<\/script/gi,'<\\/script')}</script></body></html>`}));await page.goto('/__recent_fixture');
}
const receipt=(id='recent-local',revision=1)=>({documentId:id,revision,viewedAt:'2026-09-09T01:00:00.000Z'});
const item={id:'recent-local',title:'重新打开 <script>仅文字</script>',kind:'qa',revision:2,viewedRevision:1,tags:['本地样例'],viewedAt:'2026-09-09T01:00:00.000Z'};
test('recent recorder waits for visible committed reading and records once under StrictMode',async({page})=>{
 const writes:unknown[]=[];await page.route('**/api/recent/*',r=>{writes.push(r.request().postDataJSON());return r.fulfill({json:receipt()});});await mount(page,undefined,'recorder',true);
 await page.evaluate(()=>new Promise(requestAnimationFrame));expect(writes).toEqual([]);await page.evaluate(()=>(window as unknown as {changeVisibility:(v:boolean)=>void}).changeVisibility(true));await expect.poll(()=>writes.length).toBe(1);expect(writes).toEqual([{revision:1}]);
 await page.evaluate(()=>{document.dispatchEvent(new Event('visibilitychange'));window.dispatchEvent(new Event('focus'));});await page.evaluate(()=>new Promise(requestAnimationFrame));expect(writes.length).toBe(1);await expect(page.getByRole('status')).toHaveCount(0);
 await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));await expect.poll(()=>writes.length).toBe(2);await page.reload();await page.evaluate(()=>new Promise(requestAnimationFrame));expect(writes.length).toBe(2);await page.evaluate(()=>(window as unknown as {changeVisibility:(v:boolean)=>void}).changeVisibility(true));await expect.poll(()=>writes.length).toBe(3);
});
test('unconfirmed recent write leaves reading available and can retry without concurrent duplicates',async({page})=>{
 let count=0,release!:()=>void;const held=new Promise<void>(r=>release=r);await page.route('**/api/recent/*',async r=>{count++;if(count===1)return r.fulfill({json:receipt('wrong')});await held;return r.fulfill({json:receipt()});});await mount(page);await expect(page.getByRole('status')).toContainText('尚未确认');await page.getByRole('button',{name:'重试记录浏览'}).evaluate(el=>{(el as HTMLButtonElement).click();(el as HTMLButtonElement).click();});await expect(page.getByRole('button',{name:'正在记录…'})).toBeDisabled();await expect.poll(()=>count).toBe(2);release();await expect(page.getByRole('status')).toHaveCount(0);
});
test('rejected recent write prompts a refresh without claiming it was saved',async({page})=>{
 await page.route('**/api/recent/*',r=>r.fulfill({status:409,json:{error:'VERSION_CHANGED'}}));await mount(page);await expect(page.getByRole('status')).toContainText('本次浏览未记录');await expect(page.getByRole('link',{name:'刷新文章'})).toHaveAttribute('href','/help-centre?article=recent-local');
});
test('late recording acknowledgements are isolated across article and revision changes',async({page})=>{
 let release!:()=>void;const held=new Promise<void>(r=>release=r),writes:string[]=[];await page.route('**/api/recent/*',async r=>{const id=new URL(r.request().url()).pathname.split('/').pop()!,rev=r.request().postDataJSON().revision;writes.push(`${id}:${rev}`);if(id==='recent-local'&&rev===1){await held;await r.fulfill({status:503,json:{error:'RECENT_UNAVAILABLE'}}).catch(()=>{});return;}return r.fulfill({json:receipt(id,rev)});});await mount(page);await expect.poll(()=>writes.length).toBe(1);await page.evaluate(()=>(window as unknown as {switchRecent:(id:string,revision:number)=>void}).switchRecent('recent-local',2));await expect.poll(()=>writes.length).toBe(2);release();await expect(page.getByRole('status')).toHaveCount(0);await page.evaluate(()=>(window as unknown as {switchRecent:(id:string)=>void}).switchRecent('next'));await expect.poll(()=>writes.length).toBe(3);expect(writes).toEqual(['recent-local:1','recent-local:2','next:1']);
});
test('recent list uses current formal metadata and server time with responsive pagination',async({page},info)=>{
 let writes=0;await page.route('**/api/recent/*',r=>{writes++;return r.fulfill({json:receipt()});});await mount(page,{state:'ready',data:{items:[item],total:21,page:1,pages:2}},'list');await expect(page.getByRole('link',{name:'再次阅读：'+item.title})).toHaveAttribute('href','/help-centre?article=recent-local');await expect(page.getByText(/上次阅读后有更新/)).toBeVisible();await expect(page.locator('time')).toHaveAttribute('datetime',item.viewedAt);await expect(page.locator('time')).toContainText('09:00');await expect(page.getByRole('status')).toContainText('21 篇可阅读');await expect(page.getByRole('link',{name:'下一页',exact:true})).toHaveAttribute('href','/help-centre/recent?page=2');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(writes).toBe(0);await expect(page.locator('.recent-view script')).toHaveCount(0);
 await page.screenshot({path:`output/verification/recent-${info.project.name}.png`,fullPage:true,animations:'disabled'});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await expect.poll(()=>page.locator('html').evaluate(el=>getComputedStyle(el).backgroundColor)).toBe('rgb(25, 25, 31)');await page.screenshot({path:`output/verification/recent-dark-${info.project.name}.png`,fullPage:true,animations:'disabled'});
});
test('recent empty and failure states stay distinct and real unconfigured endpoints reject forged identities',async({page,request})=>{
 await mount(page,{state:'ready',data:{items:[],total:0,page:1,pages:1}},'list');await expect(page.getByText('暂无可阅读的浏览记录',{exact:true})).toBeVisible();await page.unrouteAll();
 for(const state of ['denied','unavailable']){await mount(page,{state,data:{items:[item],total:1,page:1,pages:1}},'list');await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByRole('link',{name:'再次阅读：'+item.title})).toHaveCount(0);await expect(page.getByRole('status')).toHaveCount(0);await page.unrouteAll();}
 const list=await request.get('/api/recent',{headers:{'x-role':'admin','x-user-id':'other'}});expect(list.status()).toBe(503);expect(list.headers()['cache-control']).toBe('private, no-store');expect(await list.json()).toEqual({error:'RECENT_UNAVAILABLE'});const write=await request.post('/api/recent/any',{headers:{'x-role':'admin'},data:{revision:1}});expect(write.status()).toBe(503);expect(write.headers()['cache-control']).toBe('private, no-store');expect((await request.get('/api/recent/any')).status()).toBe(405);await page.goto('/help-centre/recent');await expect(page).toHaveURL(/\/sign-in$/);
});
