import {test,expect,type Page} from '@playwright/test';
import {navigationBrowserBundle} from '../helpers/navigation-browser';
import type {MediaEditorData} from '../../src/media/editor';
import type {MediaBlock} from '../../src/media/model';
let bundle:Awaited<ReturnType<typeof navigationBrowserBundle>>;
const code='<script>window.richInjected=true</script>\n  const 中文 = "保留缩进";\n\t下一行\n';
const blocks:MediaBlock[]=[{id:'hint',type:'hint',style:'warning',title:'执行前核对',body:'先确认身份\n再检查费用。'},{id:'code',type:'code',language:'html',code},{id:'tabs',type:'tabs',tabs:[{id:'one',title:'注册',body:'注册操作内容'},{id:'two',title:'转入',body:'转入操作内容'},{id:'three',title:'异常',body:'异常升级内容'}]}];
const initial:MediaEditorData={documentId:'rich-test',title:'内容块 · 本地示例',body:'基础正文',sequence:0,status:'draft',lifecycle:'active',blocks:[],cover:null,tags:[],assets:[]};
test.beforeAll(async()=>{bundle=await navigationBrowserBundle();});
function html(data:unknown){return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${bundle.css}</style></head><body><div id="presentation"></div><script id="data" type="application/json">${JSON.stringify(data).replace(/</g,'\\u003c')}</script><script>${bundle.script}</script></body></html>`;}
async function editor(page:Page){let state=structuredClone(initial);const bodies:Record<string,unknown>[]=[];
 await page.route(url=>url.pathname==='/admin/media',route=>route.fulfill({contentType:'text/html',body:html({mediaEditor:state})}));
 await page.route('**/api/admin/media/rich-test',route=>{const body=route.request().postDataJSON();bodies.push(body);state={...state,blocks:body.blocks,cover:body.cover,sequence:state.sequence+1};return route.fulfill({json:state});});await page.goto('/admin/media?article=rich-test');return bodies;
}
async function reader(page:Page,content=blocks){await page.route(url=>url.pathname==='/help-centre',route=>route.fulfill({contentType:'text/html',body:html({pages:[{type:'document',id:'rich-test',title:'提示、代码和标签 · 本地示例',href:'/help-centre?article=rich-test'}],requested:'rich-test',article:{id:'rich-test',title:'提示、代码和标签 · 本地示例',revision:1,body:'员工正式阅读示例',blocks:content}})}));await page.route('**/api/articles/rich-test/feedback?**',route=>route.fulfill({json:{feedback:null}}));await page.goto('/help-centre');}
test('hint code and tabs survive save reload ordering and tab removal',async({page},info)=>{
 const bodies=await editor(page);await page.getByRole('button',{name:'新增提示框',exact:true}).click();await page.getByLabel('提示类型',{exact:true}).selectOption('warning');await page.getByLabel('提示标题',{exact:true}).fill('执行前核对');await page.getByRole('textbox',{name:'提示内容',exact:true}).fill('第一行\n第二行');
 await page.getByRole('button',{name:'新增代码框',exact:true}).click();await page.getByLabel('代码语言',{exact:true}).fill('html');await page.getByRole('textbox',{name:'代码内容',exact:true}).fill(code);
 await page.getByRole('button',{name:'新增分页标签',exact:true}).click();await page.getByLabel('标签 1 标题',{exact:true}).fill('注册');await page.getByLabel('标签 1 内容',{exact:true}).fill('注册步骤');await page.getByLabel('标签 2 标题',{exact:true}).fill('转入');await page.getByLabel('标签 2 内容',{exact:true}).fill('转入步骤');
 await page.getByRole('region',{name:'编辑标签 2',exact:true}).getByRole('button',{name:'标签上移',exact:true}).click();await page.getByRole('button',{name:'保存草稿',exact:true}).click();await expect(page.getByRole('status')).toContainText('草稿已保存');await page.reload();await expect(page.getByRole('textbox',{name:'代码内容',exact:true})).toHaveValue(code);await expect(page.getByRole('textbox',{name:'提示内容',exact:true})).toHaveValue('第一行\n第二行');await expect(page.getByLabel('标签 1 标题',{exact:true})).toHaveValue('转入');expect(bodies[0].expectedSequence).toBe(0);
 await page.getByRole('button',{name:'删除标签 2',exact:true}).click();await expect(page.getByRole('button',{name:'删除标签 1',exact:true})).toBeDisabled();await page.getByRole('button',{name:'保存草稿',exact:true}).click();await expect(page.getByRole('status')).toContainText('草稿已保存');await page.screenshot({path:`output/verification/rich-editor-${info.project.name}.png`,fullPage:true});
});
test('tabs support arrows home end click and independent sets with no overflow',async({page})=>{
 await reader(page,[blocks[0],{...(blocks[1] as Extract<MediaBlock,{type:'code'}>),code:code+'a'.repeat(1000)},blocks[2],{...(blocks[2] as Extract<MediaBlock,{type:'tabs'}>),id:'second-tabs'}]);const groups=page.getByRole('tablist',{name:'内容标签'});const first=groups.nth(0);await first.getByRole('tab',{name:'注册',exact:true}).focus();await page.keyboard.press('ArrowLeft');await expect(first.getByRole('tab',{name:'异常',exact:true})).toBeFocused();await expect(first.getByRole('tab',{name:'异常',exact:true})).toHaveAttribute('aria-selected','true');await page.keyboard.press('Home');await page.keyboard.press('ArrowRight');await expect(first.getByRole('tab',{name:'转入',exact:true})).toBeFocused();await page.keyboard.press('End');await expect(first.getByRole('tab',{name:'异常',exact:true})).toBeFocused();await expect(groups.nth(1).getByRole('tab',{name:'注册',exact:true})).toHaveAttribute('aria-selected','true');
 await first.getByRole('tab',{name:'转入',exact:true}).click();await expect(page.getByRole('tabpanel',{name:'转入',exact:true})).toBeVisible();await page.keyboard.press('Tab');await expect(page.getByRole('tabpanel',{name:'转入',exact:true})).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);expect(await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(x=>x.id);return ids.length===new Set(ids).size;})).toBe(true);
 await page.emulateMedia({media:'print'});await expect(page.getByText('异常升级内容',{exact:true})).toHaveCount(2);await expect(page.getByText('异常升级内容',{exact:true}).first()).toBeVisible();
});
test('copy preserves actual clipboard bytes and literal code never runs in either theme',async({page,context},info)=>{
 await context.grantPermissions(['clipboard-read','clipboard-write']);await reader(page);await page.getByRole('button',{name:'复制代码',exact:true}).click();await expect(page.getByText('已复制',{exact:true})).toBeVisible();expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe(code);expect(await page.evaluate(()=>Object.hasOwn(window,'richInjected'))).toBe(false);
 for(const theme of ['浅色','深色']){await page.getByRole('radio',{name:theme,exact:true}).check();await expect(page.locator('html')).toHaveAttribute('data-theme',theme==='浅色'?'light':'dark');await expect(page.locator('.reader-pdf-link')).toHaveCSS('background-color',theme==='浅色'?'rgb(255, 255, 255)':'rgb(34, 34, 41)');await page.screenshot({path:`output/verification/rich-reader-${info.project.name}-${theme==='浅色'?'light':'dark'}.png`,fullPage:true});}
});
test('clipboard rejection never reports success and retry succeeds',async({page})=>{
 await page.addInitScript(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('DENIED');}}});});await reader(page);await page.getByRole('button',{name:'复制代码',exact:true}).click();await expect(page.getByText('复制失败，请选中代码后手动复制。',{exact:true})).toBeVisible();await expect(page.getByText('已复制',{exact:true})).toHaveCount(0);await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{}}});});await page.getByRole('button',{name:'复制代码',exact:true}).click();await expect(page.getByText('已复制',{exact:true})).toBeVisible();
});
test('invalid language retains draft text and copy waits for confirmation',async({page})=>{
 const bodies=await editor(page);await page.getByRole('button',{name:'新增代码框',exact:true}).click();await page.getByRole('textbox',{name:'代码内容',exact:true}).fill('保留这段');await page.getByLabel('代码语言',{exact:true}).fill('<script>');await expect(page.getByRole('alert')).toContainText('输入已保留');await expect(page.getByRole('button',{name:'保存草稿',exact:true})).toBeDisabled();expect(bodies).toHaveLength(0);await page.getByLabel('代码语言',{exact:true}).fill('text');await page.getByRole('button',{name:'保存草稿',exact:true}).click();await expect(page.getByRole('status')).toContainText('草稿已保存');
 await reader(page);await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>new Promise<void>(resolve=>{(window as unknown as {finishCopy:()=>void}).finishCopy=resolve;})}});});await page.getByRole('button',{name:'复制代码',exact:true}).click();await expect(page.getByRole('button',{name:'正在复制…',exact:true})).toBeDisabled();await expect(page.getByText('已复制',{exact:true})).toHaveCount(0);await page.evaluate(()=>(window as unknown as {finishCopy:()=>void}).finishCopy());await expect(page.getByText('已复制',{exact:true})).toBeVisible();
});
