import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {navigationBrowserBundle} from '../helpers/navigation-browser';
import type {MediaEditorData} from '../../src/media/editor';
import {diagramSVG,svgImage} from '../../src/server/science/render';
let bundle:Awaited<ReturnType<typeof navigationBrowserBundle>>;
const initial:MediaEditorData={documentId:'science',title:'科学内容 · 本地示例',body:'基础正文',sequence:0,status:'draft',lifecycle:'active',blocks:[],cover:null,tags:[],assets:[]};
test.beforeAll(async()=>{bundle=await navigationBrowserBundle();});
function html(data:unknown){return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${bundle.css}</style></head><body><div id="presentation"></div><script id="data" type="application/json">${JSON.stringify(data).replace(/</g,'\\u003c')}</script><script>${bundle.script}</script></body></html>`;}
async function editor(page:Page){let state=structuredClone(initial);await page.route(url=>url.pathname==='/admin/media',route=>route.fulfill({contentType:'text/html',body:html({mediaEditor:state})}));await page.route('**/api/admin/media/science',route=>{const body=route.request().postDataJSON();state={...state,blocks:body.blocks,cover:body.cover,sequence:state.sequence+1};return route.fulfill({json:state});});await page.route('**/api/admin/media/science/diagram',async route=>{try{return route.fulfill({json:{image:svgImage(await diagramSVG(route.request().postDataJSON().source))}});}catch(e){return route.fulfill({status:400,json:{error:String(e)}});}});await page.goto('/admin/media?article=science');}
test('formula and diagram save reload and preview actual rendered SVG',async({page},info)=>{
 await editor(page);await page.getByRole('button',{name:'新增数学公式',exact:true}).click();await page.getByRole('textbox',{name:'公式原文',exact:true}).fill('\\frac{a+b}{2}');await page.getByRole('button',{name:'新增流程图',exact:true}).click();await page.getByRole('button',{name:'保存草稿',exact:true}).click();await expect(page.getByRole('status')).toContainText('草稿已保存');await page.reload();await expect(page.getByRole('textbox',{name:'公式原文',exact:true})).toHaveValue('\\frac{a+b}{2}');await page.getByText('预览内容块（未发布）',{exact:true}).click();await expect(page.locator('math')).toBeVisible();await page.getByRole('button',{name:'检查并预览流程图',exact:true}).click();await expect(page.getByAltText('文章流程图')).toBeVisible();await expect.poll(()=>page.getByAltText('文章流程图').evaluate((x)=>(x as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);await page.screenshot({path:`output/verification/science-editor-${info.project.name}.png`,fullPage:true});
});
test('invalid formula and diagram retain editable input and diagram retry recovers',async({page})=>{
 await editor(page);await page.getByRole('button',{name:'新增数学公式',exact:true}).click();await page.getByRole('textbox',{name:'公式原文',exact:true}).fill('\\frac{');await expect(page.getByRole('alert')).toContainText('KaTeX');await page.getByRole('button',{name:'新增流程图',exact:true}).click();await page.getByRole('textbox',{name:'流程图原文',exact:true}).fill('flowchart TD\nA[missing');await page.getByText('预览内容块（未发布）',{exact:true}).click();await page.getByRole('button',{name:'检查并预览流程图',exact:true}).click();await expect(page.getByText(/Parse error/)).toBeVisible();await page.getByRole('textbox',{name:'公式原文',exact:true}).fill('x^2');await page.getByRole('textbox',{name:'流程图原文',exact:true}).fill('flowchart LR\nA[开始] --> B[结束]');await page.getByRole('button',{name:'检查并预览流程图',exact:true}).click();await expect(page.getByAltText('文章流程图')).toBeVisible();
});
test('published reader displays Chinese emphasis formula and diagram without page overflow',async({page},info)=>{
 const blocks=[{id:'m',type:'math',source:'\\sum_{i=1}^{n} i=\\frac{n(n+1)}{2}',caption:'求和公式'},{id:'d',type:'diagram',source:'flowchart TD\nA-->B',caption:'内容审核流程'}];await page.route(url=>url.pathname==='/help-centre',route=>route.fulfill({contentType:'text/html',body:html({pages:[{type:'document',id:'science',title:'公式与流程图 · 本地示例',href:'/help-centre?article=science'}],requested:'science',article:{id:'science',title:'公式与流程图 · 本地示例',revision:1,body:'# **操作说明**\n中文**重点**，*注意*。\n\n  - 核对身份\n  - 提交审核',blocks}})}));await page.route('**/api/articles/science/diagram?**',async route=>route.fulfill({contentType:'image/svg+xml',body:await readFile('output/verification/science-diagram.svg')}));await page.route('**/api/articles/science/feedback?**',route=>route.fulfill({json:{feedback:null}}));await page.goto('/help-centre');await expect(page.locator('.paragraph strong')).toHaveText('重点');await expect(page.locator('.paragraph em')).toHaveText('注意');await expect(page.getByRole('listitem').filter({hasText:'核对身份'})).toBeVisible();await expect(page.locator('math')).toBeVisible();await expect.poll(()=>page.getByAltText('内容审核流程').evaluate(x=>(x as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:`output/verification/science-reader-${info.project.name}.png`,fullPage:true});
});
test('diagram endpoints refuse unconfigured and forged identities',async({request})=>{
 const ordinary=await request.get('/api/articles/science/diagram?revision=1&block=d',{headers:{'x-role':'admin'}});expect(ordinary.status()).toBeGreaterThanOrEqual(400);expect(ordinary.headers()['cache-control']).toContain('no-store');const preview=await request.post('/api/admin/media/science/diagram',{headers:{'x-role':'admin'},data:{source:'flowchart TD\nA-->B'}});expect(preview.status()).toBeGreaterThanOrEqual(400);expect(await preview.text()).not.toContain('data:image');
});
test('PDF web page preserves list markers and two diagram images',async({page})=>{
 const snapshot={article:{id:'science',title:'PDF科学内容 · 本地示例',revision:1,body:'- 圆点项目\n\n1. 序号项目',blocks:[{id:'d1',type:'diagram',source:'flowchart TD\nA-->B',caption:'第一张图'},{id:'d2',type:'diagram',source:'flowchart TD\nC-->D',caption:'第二张图'}]},files:[]};await page.route('**/help-centre/pdf?**',route=>route.fulfill({contentType:'text/html',body:html({pdfSnapshot:snapshot})}));await page.route('**/api/articles/science/diagram?**',async route=>{const block=snapshot.article.blocks.find(b=>new URL(route.request().url()).searchParams.get('block')===b.id)!;return route.fulfill({contentType:'image/svg+xml',body:await diagramSVG(block.source)});});await page.goto('/help-centre/pdf?article=science&revision=1');await expect(page.locator('.pdf-paper ul')).toHaveCSS('list-style-type','disc');await expect(page.locator('.pdf-paper ol')).toHaveCSS('list-style-type','decimal');for(const alt of ['第一张图','第二张图'])await expect.poll(()=>page.getByAltText(alt).evaluate(x=>(x as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
});
