import {queueConfirmation,settleConfirmation} from '../helpers/site-confirmation';
import {test,expect,type Page} from '@playwright/test';
import {settingHistoryBrowserBundle} from '../helpers/setting-history-browser';
import {defaultFeatureFlags} from '../../src/features/model';
const id='00000000-0000-4000-8000-000000000001';
const entry={kind:'features',id,version:1,label:'功能开关',actor:{id:'admin-a',name:'管理员 A'},changedAt:'2026-09-10T00:00:00.000Z',restoredFrom:null};
const initial={items:[entry],total:1,page:1,pages:1};
const detail={entry,before:{flags:defaultFeatureFlags},after:{flags:{...defaultFeatureFlags,search:false}},current:{version:2,config:{flags:defaultFeatureFlags}}};
let bundle:Awaited<ReturnType<typeof settingHistoryBrowserBundle>>;test.beforeAll(async()=>{bundle=await settingHistoryBrowserBundle();});
async function mount(page:Page,value:unknown=initial){await page.route('**/__setting_history_fixture',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html lang="zh-CN" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+bundle.css+'</style></head><body><p>设置历史 · 本地测试样例，非真实公司数据</p><main id="history"></main><script type="application/json" id="data">'+JSON.stringify({initial:value}).replaceAll('<','\\u003c')+'</script><script>'+bundle.script.replaceAll('</script','<\\/script')+'</script></body></html>'}));await page.goto('/__setting_history_fixture');}
async function inspect(page:Page){await page.route('**/api/admin/settings/history/detail?*',r=>r.fulfill({json:{result:detail}}));await page.getByRole('button',{name:'查看 功能开关 版本 1',exact:true}).click();await settleConfirmation(page);await expect(page.getByRole('region',{name:'版本详情'})).toBeVisible();}
test('history shows before after and current values in both themes and restores only after confirmation',async({page},info)=>{
 const writes:Record<string,unknown>[]=[];await page.route('**/api/admin/settings/history/restore',r=>{const x=r.request().postDataJSON();writes.push(x);return r.fulfill({json:{result:{...x,newVersion:x.expectedVersion+1}}});});await mount(page);await inspect(page);await expect(page.getByRole('heading',{name:'修改前',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'修改后（恢复目标）',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'当前设置 · 版本 2'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'output/verification/setting-history-'+info.project.name+'.png',fullPage:true});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await expect.poll(()=>page.locator('.setting-snapshot').first().evaluate(e=>getComputedStyle(e).backgroundColor)).toBe('rgb(34, 34, 41)');await expect.poll(()=>page.getByRole('link',{name:'返回管理后台'}).evaluate(e=>getComputedStyle(e).backgroundColor)).toBe('rgb(34, 34, 41)');await page.screenshot({path:'output/verification/setting-history-dark-'+info.project.name+'.png',fullPage:true});
 queueConfirmation(page,d=>d.dismiss());await page.getByRole('button',{name:'恢复此版本为新设置'}).click();await settleConfirmation(page);expect(writes.length).toBe(0);queueConfirmation(page,d=>d.accept());await page.getByRole('button',{name:'恢复此版本为新设置'}).click();await settleConfirmation(page);await expect(page.getByRole('status')).toContainText('生成版本 3');expect(writes).toHaveLength(1);expect(writes[0]).toMatchObject({kind:'features',id,version:1,expectedVersion:2});expect(Object.keys(writes[0])).toHaveLength(5);await expect(page.getByRole('button',{name:'恢复此版本为新设置'})).toHaveCount(0);
});
test('unknown restore outcomes preserve exact request through later conflict and protect leaving',async({page})=>{
 const writes:Record<string,unknown>[]=[];await page.route('**/api/admin/settings/history/restore',r=>{const x=r.request().postDataJSON();writes.push(x);return writes.length===1?r.fulfill({status:503}):writes.length===2?r.fulfill({status:409,json:{error:'HISTORY_CONFLICT'}}):r.fulfill({json:{result:{...x,newVersion:3}}});});await mount(page);await inspect(page);queueConfirmation(page,d=>d.accept());await page.getByRole('button',{name:'恢复此版本为新设置'}).click();await settleConfirmation(page);await expect(page.getByRole('alert')).toContainText('无法确认');await expect(page.getByRole('combobox')).toBeDisabled();await expect(page.getByLabel('恢复请求记录')).toHaveValue(/"expectedVersion": 2/);queueConfirmation(page,d=>d.dismiss());await page.getByRole('link',{name:'返回管理后台'}).click();await settleConfirmation(page);expect(page.url()).toContain('__setting_history_fixture');await page.getByRole('button',{name:'重试原恢复请求'}).click();await settleConfirmation(page);await expect(page.getByRole('alert')).toContainText('无法确认');await page.getByRole('button',{name:'重试原恢复请求'}).click();await settleConfirmation(page);await expect(page.getByRole('status')).toContainText('恢复操作已确认');expect(writes[1]).toEqual(writes[0]);expect(writes[2]).toEqual(writes[0]);
});
test('conflict requires fresh detail and failed reads never leave an actionable stale target',async({page})=>{
 let reads=0;await page.route('**/api/admin/settings/history/restore',r=>r.fulfill({status:409,json:{error:'HISTORY_CONFLICT'}}));await mount(page);await page.route('**/api/admin/settings/history/detail?*',r=>++reads===2?r.fulfill({status:503}):r.fulfill({json:{result:{...detail,current:{...detail.current,version:reads>2?3:2}}}}));await page.getByRole('button',{name:'查看 功能开关 版本 1'}).click();await settleConfirmation(page);queueConfirmation(page,d=>d.accept());await page.getByRole('button',{name:'恢复此版本为新设置'}).click();await settleConfirmation(page);await expect(page.getByRole('alert')).toContainText('设置已变化');await expect(page.getByRole('button',{name:'恢复此版本为新设置'})).toBeDisabled();await page.getByRole('button',{name:'重新载入详情'}).click();await settleConfirmation(page);await expect(page.getByRole('alert')).toContainText('暂时无法读取');await expect(page.getByRole('button',{name:'恢复此版本为新设置'})).toHaveCount(0);await page.getByRole('button',{name:'重新载入详情'}).click();await settleConfirmation(page);await expect(page.getByRole('heading',{name:'当前设置 · 版本 3'})).toBeVisible();await expect(page.getByRole('button',{name:'恢复此版本为新设置'})).toBeEnabled();
});
test('filter and pagination retain committed state when requests fail and show empty only after a valid response',async({page})=>{
 const rows=Array.from({length:20},(_,i)=>({...entry,version:22-i}));await mount(page,{items:rows,total:21,page:1,pages:2});let calls=0;await page.route('**/api/admin/settings/history?*',r=>{const u=new URL(r.request().url());if(++calls===1)return r.fulfill({status:503});return r.fulfill({json:{result:u.searchParams.get('page')==='2'?{items:[entry],total:21,page:2,pages:2}:{items:[],total:0,page:1,pages:1}}});});await page.getByRole('button',{name:'下一页',exact:true}).click();await settleConfirmation(page);await expect(page.getByText('共 21 条记录 · 第 1 / 2 页')).toBeVisible();await expect(page.getByRole('alert')).toContainText('已有记录未改变');await page.getByRole('button',{name:'下一页',exact:true}).click();await settleConfirmation(page);await expect(page.getByText('共 21 条记录 · 第 2 / 2 页')).toBeVisible();await page.getByRole('combobox').selectOption('field');await expect(page.getByText('尚无已保存的设置变更记录。')).toBeVisible();
});
test('unavailable history and real endpoints never impersonate an administrator',async({page,request})=>{
 await mount(page,null);await expect(page.getByRole('status')).toContainText('暂时无法读取');await expect(page.getByText('尚无已保存的设置变更记录。')).toHaveCount(0);
 for(const path of ['/api/admin/settings/history','/api/admin/settings/history/detail?kind=features&id='+id+'&version=1']){const r=await request.get(path,{headers:{'x-role':'admin'}});expect(r.status()).toBe(503);expect(r.headers()['cache-control']).toBe('private, no-store');}const r=await request.post('/api/admin/settings/history/restore',{headers:{origin:'http://127.0.0.1:3210','x-role':'admin'},data:{kind:'features',id,version:1,expectedVersion:2,requestId:id}});expect(r.status()).toBe(503);await page.goto('/admin/settings/history');await expect(page).toHaveURL(/\/admin\/sign-in/);
});
