import {test,expect,type Page} from '@playwright/test';
import {editorBrowserBundle,editorFixture} from '../helpers/editor-browser';
import type {EditorData} from '../../src/editor/contract';
let bundle:Awaited<ReturnType<typeof editorBrowserBundle>>;
test.beforeAll(async()=>{bundle=await editorBrowserBundle();});
async function mount(page:Page,initial:EditorData|null=editorFixture){
 await page.route('**/__submission_fixture',r=>r.fulfill({contentType:'text/html',body:`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${bundle.css}</style></head><body><main class="editor-main"><h1>文章提交二审 · 本地样例</h1><script type="application/json" id="data">${JSON.stringify(initial).replace(/</g,'\\u003c')}</script><div id="editor"></div></main><script>${bundle.script.replace(/<\/script/gi,'<\\/script')}</script></body></html>`}));
 await page.goto('/__submission_fixture');await expect(page.locator('.bn-editor')).toBeVisible();
}
const options=(sequence=3)=>({documentId:'editor-local',sequence,revision:2,status:'draft',lifecycle:'active',reviewers:[{id:'admin-b',name:'Ivy'}],nextCursor:null});
const ack=(sequence=4)=>({documentId:'editor-local',sequence,revision:2,reviewerId:'admin-b',status:'in_review'});
test('saved draft explicitly selects second reviewer then freezes with correct next sequence',async({page},info)=>{
 let saved={...editorFixture,publishedRevision:1};let reads=0;const submissions:unknown[]=[];
 await page.route('**/api/admin/editor/*',r=>{saved={...saved,...r.request().postDataJSON(),sequence:saved.sequence+1};return r.fulfill({json:saved});});
 await page.route('**/api/admin/review/*',r=>{if(r.request().method()==='GET'){reads++;return r.fulfill({json:options(saved.sequence)});}submissions.push(r.request().postDataJSON());return r.fulfill({json:ack(5)});});
 await page.route('**/api/admin/lifecycle/*',r=>{expect(r.request().postDataJSON().expectedSequence).toBe(5);return r.fulfill({json:{documentId:'editor-local',sequence:6,action:'trash',cleanupPending:0}});});
 await mount(page,saved);expect(reads).toBe(0);await page.getByLabel('文章标题',{exact:true}).fill('需要二审的正式资料');await expect(page.getByRole('button',{name:'提交二审',exact:true})).toBeDisabled();await expect.poll(()=>saved.sequence,{timeout:8000}).toBe(4);
 await page.getByRole('button',{name:'提交二审',exact:true}).click();await expect(page.getByRole('button',{name:'确认提交二审',exact:true})).toBeDisabled();await page.getByLabel('二审管理员',{exact:true}).selectOption('admin-b');await page.getByRole('region',{name:'提交二审'}).scrollIntoViewIfNeeded();await page.screenshot({path:`output/verification/submission-choice-${info.project.name}.png`,fullPage:false});await page.getByRole('button',{name:'确认提交二审',exact:true}).click();
 await expect(page.getByRole('region',{name:'提交二审'})).toContainText('已提交');expect(submissions).toEqual([{expectedSequence:4,reviewerId:'admin-b'}]);await expect(page.getByLabel('文章标题',{exact:true})).toBeDisabled();await expect(page.locator('.bn-editor')).toHaveAttribute('contenteditable','false');await expect(page.locator('.editor-published-note')).toContainText('旧正式版 1 仍可阅读');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`output/verification/submission-${info.project.name}.png`,fullPage:true});
 await page.getByRole('button',{name:'文章设置',exact:true}).click();await page.getByRole('button',{name:/^保存与管理/}).click();await page.getByRole('button',{name:'删除文章',exact:true}).click();const trash=page.getByRole('dialog',{name:'将文章移入回收站？'});await trash.getByRole('textbox').fill(saved.title);await trash.getByRole('button',{name:'移入回收站',exact:true}).click();await expect(page.getByRole('region',{name:'文章删除'})).toContainText('已移入回收站');
});
test('empty reviewers differs from failed list and list can be retried',async({page})=>{
 let mode='failure';await page.route('**/api/admin/review/*',r=>mode==='failure'?r.fulfill({status:503,json:{error:'REVIEW_UNAVAILABLE'}}):r.fulfill({json:mode==='empty'?{...options(),reviewers:[]}:options()}));await mount(page);await page.getByRole('button',{name:'提交二审',exact:true}).click();await expect(page.getByRole('region',{name:'提交二审'})).toContainText('未能读取');await expect(page.getByLabel('二审管理员',{exact:true})).toHaveCount(0);mode='empty';await page.getByRole('button',{name:'重新读取管理员',exact:true}).click();await expect(page.getByRole('region',{name:'提交二审'})).toContainText('这篇内容目前没有可用的二审管理员');await expect(page.getByRole('button',{name:'确认提交二审',exact:true})).toBeDisabled();await expect(page.getByLabel('文章标题',{exact:true})).toBeEnabled();mode='available';await page.getByRole('button',{name:'重新读取管理员',exact:true}).click();await expect(page.getByText('这篇内容目前没有可用的二审管理员。')).toHaveCount(0);await expect(page.getByRole('option',{name:'Ivy'})).toBeAttached();
});
test('stale reviewer snapshot blocks confirmation without losing article input',async({page})=>{
 await page.route('**/api/admin/review/*',r=>r.fulfill({json:options(4)}));await mount(page);await page.getByRole('button',{name:'提交二审',exact:true}).click();await expect(page.getByRole('region',{name:'提交二审'})).toContainText('版本已改变');await expect(page.getByRole('button',{name:'确认提交二审',exact:true})).toBeDisabled();await expect(page.getByLabel('文章标题',{exact:true})).toHaveValue(editorFixture.title);
});
test('unknown submit result freezes editing and retries exact payload before reporting success',async({page})=>{
 const writes:unknown[]=[];await page.route('**/api/admin/review/*',r=>{if(r.request().method()==='GET')return r.fulfill({json:options()});writes.push(r.request().postDataJSON());return r.fulfill({json:writes.length===1?{...ack(),reviewerId:'wrong'}:ack()});});
 await mount(page);await page.getByRole('button',{name:'提交二审',exact:true}).click();await page.getByLabel('二审管理员',{exact:true}).selectOption('admin-b');await page.getByRole('button',{name:'确认提交二审',exact:true}).click();await expect(page.getByRole('region',{name:'提交二审'})).toContainText('尚未确认');await expect(page.getByLabel('文章标题',{exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'取消二审提交'})).toBeDisabled();await expect(page.getByLabel('二审管理员',{exact:true})).toHaveValue('admin-b');await expect(page.getByRole('button',{name:'取消二审提交'})).toBeDisabled();await page.getByRole('button',{name:'重试原提交',exact:true}).click();await expect(page.getByRole('region',{name:'提交二审'})).toContainText('已提交');expect(writes).toEqual([{expectedSequence:3,reviewerId:'admin-b'},{expectedSequence:3,reviewerId:'admin-b'}]);
});
test('reviewer rejection retains chosen reviewer and unlocks editor without success',async({page})=>{
 await page.route('**/api/admin/review/*',r=>r.request().method()==='GET'?r.fulfill({json:options()}):r.fulfill({status:409,json:{error:'INVALID_REVIEWER'}}));await mount(page);await page.getByRole('button',{name:'提交二审',exact:true}).click();await page.getByLabel('二审管理员',{exact:true}).selectOption('admin-b');await page.getByRole('button',{name:'确认提交二审',exact:true}).click();await expect(page.getByRole('region',{name:'提交二审'})).toContainText('管理员已不可用');await expect(page.getByLabel('文章标题',{exact:true})).toBeEnabled();await expect(page.getByLabel('二审管理员',{exact:true})).toHaveValue('admin-b');await expect(page.getByRole('region',{name:'提交二审'}).getByRole('status')).toHaveCount(0);
});
test('reviewer pagination offers later administrators and blocks submission on changed draft',async({page})=>{
 let saved=structuredClone(editorFixture);await page.route('**/api/admin/editor/*',r=>{saved={...saved,...r.request().postDataJSON(),sequence:saved.sequence+1};return r.fulfill({json:saved});});await page.route('**/api/admin/review/*',r=>r.fulfill({json:new URL(r.request().url()).searchParams.has('after')?{...options(),reviewers:[{id:'admin-z',name:'Later Admin'}]}:{...options(),nextCursor:'admin-b'}}));await mount(page);await page.getByRole('button',{name:'提交二审',exact:true}).click();await page.getByRole('button',{name:'载入更多管理员'}).click();await page.getByLabel('二审管理员',{exact:true}).selectOption('admin-z');await page.getByRole('button',{name:'取消二审提交'}).click();await page.getByLabel('文章标题',{exact:true}).fill('保留后续修改');await expect(page.getByRole('button',{name:'提交二审',exact:true})).toBeDisabled();await expect.poll(()=>saved.sequence,{timeout:8000}).toBe(4);await page.getByRole('button',{name:'提交二审',exact:true}).click();await expect(page.getByRole('button',{name:'确认提交二审',exact:true})).toBeDisabled();await expect(page.getByRole('region',{name:'提交二审'})).toContainText('版本已改变');
});
test('new unsaved document cannot submit and real review routes reject forged identity',async({page,request})=>{
 await mount(page,null);await expect(page.getByRole('button',{name:'提交二审',exact:true})).toBeDisabled();for(const method of ['get','post'] as const){const r=await request[method]('/api/admin/review/00000000-0000-4000-8000-000000000034',{headers:{'x-role':'admin','x-user-id':'admin'},...(method==='post'?{data:{expectedSequence:3,reviewerId:'admin-b'}}:{})});expect(r.status()).toBe(503);expect(r.headers()['cache-control']).toBe('private, no-store');}
});

test('already published content must be saved as a new draft before another review',async({page})=>{
 let saved={...editorFixture,status:'published',publishedRevision:1};await page.route('**/api/admin/editor/*',r=>{saved={...saved,...r.request().postDataJSON(),sequence:saved.sequence+1,status:'draft'};return r.fulfill({json:saved});});await mount(page,saved);await expect(page.getByRole('button',{name:'提交二审',exact:true})).toBeDisabled();await page.getByLabel('文章标题',{exact:true}).fill('正式文章的新修改');await expect.poll(()=>saved.sequence,{timeout:8000}).toBe(4);await expect(page.getByRole('button',{name:'提交二审',exact:true})).toBeEnabled();
});

test('preloaded recovery cannot replace the editor while submission outcome is unknown',async({page})=>{
 let attempts=0;await page.route('**/api/admin/editor/*',r=>r.request().method()==='GET'?r.fulfill({json:{...editorFixture,sequence:4,title:'较新草稿'}}):r.fulfill({status:409,json:{error:'CONFLICT'}}));await page.route('**/api/admin/review/*',r=>r.request().method()==='GET'?r.fulfill({json:options()}):r.fulfill({json:++attempts===1?{...ack(),documentId:'wrong'}:ack()}));await mount(page);await page.getByLabel('文章标题',{exact:true}).fill('触发冲突');await expect(page.getByRole('region',{name:'保存恢复'})).toBeVisible();await page.getByRole('button',{name:'读取服务器最新版本',exact:true}).click();await expect(page.getByRole('button',{name:'保留备份并载入此版本'})).toBeEnabled();await page.getByLabel('文章标题',{exact:true}).fill(editorFixture.title);await page.getByRole('button',{name:'提交二审',exact:true}).click();await page.getByLabel('二审管理员',{exact:true}).selectOption('admin-b');await page.getByRole('button',{name:'确认提交二审',exact:true}).click();await expect(page.getByRole('region',{name:'提交二审'})).toContainText('尚未确认');await expect(page.getByRole('button',{name:'保留备份并载入此版本'})).toBeDisabled();await expect(page.getByLabel('文章标题',{exact:true})).toBeDisabled();await page.getByRole('button',{name:'重试原提交',exact:true}).click();await expect(page.getByRole('region',{name:'提交二审'})).toContainText('已提交');await expect(page.getByRole('button',{name:'保留备份并载入此版本'})).toBeDisabled();
});

test('returned revision cannot be submitted again until a changed draft is saved',async({page})=>{
 let saved={...editorFixture,status:'changes_requested'};await page.route('**/api/admin/editor/*',r=>{saved={...saved,...r.request().postDataJSON(),sequence:saved.sequence+1,status:'draft'};return r.fulfill({json:saved});});await mount(page,saved);await expect(page.getByRole('button',{name:'提交二审',exact:true})).toBeDisabled();await page.getByLabel('文章标题',{exact:true}).fill('按退回原因修改后的标题');await expect.poll(()=>saved.sequence,{timeout:8000}).toBe(4);await expect(page.getByRole('button',{name:'提交二审',exact:true})).toBeEnabled();
});
