import assert from 'node:assert/strict';import {test} from 'node:test';
import {parseAnnouncementWrite,parseReceipt,normalizeAnnouncements,normalizeReceipt,targets} from '../src/announcements/model.ts';
const id='00000000-0000-4000-8000-000000000001';const config={title:'新功能',body:'简单说明',target:'favorites',audience:'staff',enabled:true};
test('announcement configuration accepts fixed existing targets and bounded plain text only',()=>{assert.equal(parseAnnouncementWrite({expectedVersion:0,...config}).target,'favorites');for(const x of [{...config,target:'https://evil.test'},{...config,script:'x'},{...config,title:'x'.repeat(121)},{...config,body:''},{...config,audience:'owner'}])assert.throws(()=>parseAnnouncementWrite({expectedVersion:0,...x}));assert.equal(targets.editor.href,'/admin/editor');});
test('versioned receipt and publication envelopes reject forged links and mismatched types',()=>{assert.deepEqual(parseReceipt({revision:1,action:'dismiss'}),{revision:1,action:'dismiss'});assert.throws(()=>parseReceipt({revision:0,action:'seen'}));assert.throws(()=>parseReceipt({revision:1,action:'seen',memberId:'other'}));const entry={id,revision:1,...config,seen:false};assert.equal(normalizeAnnouncements([entry]).length,1);assert.throws(()=>normalizeAnnouncements([{...entry,href:'https://evil.test'}]));assert.throws(()=>normalizeReceipt({id,revision:1,seen:false,dismissed:true,target:'favorites'}));assert.equal(normalizeReceipt({id,revision:1,seen:true,dismissed:false,target:'favorites'}).target,'favorites');});

import {saveAnnouncement,saveAnnouncementReceipt,loadAnnouncements,AnnouncementRejected} from '../src/announcements/client.ts';
import {announcementResponse,announcementBody} from '../src/server/announcements/http.ts';
test('client acknowledgements bind the exact announcement and revision without accepting forged content',async()=>{const original=globalThis.fetch;try{const input={expectedVersion:0,...config,target:'favorites' as const,audience:'staff' as const};globalThis.fetch=async()=>Response.json({result:{id,revision:1,...config,title:'Wrong',seen:false}});await assert.rejects(saveAnnouncement(id,input),/INVALID_ACK/);globalThis.fetch=async()=>Response.json({result:{id,revision:2,seen:true,dismissed:true,target:'favorites'}});await assert.rejects(saveAnnouncementReceipt(id,{revision:1,action:'dismiss'}),/INVALID_ACK/);globalThis.fetch=async()=>new Response('',{status:409});await assert.rejects(saveAnnouncement(id,input),AnnouncementRejected);globalThis.fetch=async()=>new Response('',{status:503});await assert.rejects(saveAnnouncement(id,input),/UNKNOWN_RESULT/);globalThis.fetch=async()=>Response.json({result:[{id,revision:1,...config,seen:false,enabled:false}]});await assert.rejects(loadAnnouncements(),/INVALID_ACK/);}finally{globalThis.fetch=original;}});
test('announcement HTTP refuses unsafe bodies and exposes no private service error details',async()=>{for(const [code,status] of [['FORBIDDEN',403],['NOT_FOUND',404],['INVALID_INPUT',400],['ANNOUNCEMENT_CONFLICT',409],['database password detail',503]] as const){const r=await announcementResponse(async()=>{throw new Error(code);});assert.equal(r.status,status);assert.equal(r.headers.get('cache-control'),'private, no-store');if(status===503)assert.deepEqual(await r.json(),{error:'ANNOUNCEMENT_UNAVAILABLE'});}await assert.rejects(announcementBody(new Request('http://localhost/api',{method:'PUT',headers:{origin:'https://bad.test','content-type':'application/json'},body:'{}'})));await assert.rejects(announcementBody(new Request('http://localhost/api',{method:'PUT',headers:{origin:'http://localhost','content-type':'application/json'},body:' '.repeat(9000)})));});
