import {saveFeatures,FeatureRejected} from '../src/features/client.ts';
import {featureResponse} from '../src/server/features/http.ts';
import test from 'node:test';import assert from 'node:assert/strict';
import {featureKeys,defaultFeatureFlags,normalizeFeatureConfig,parseFeatureWrite} from '../src/features/model.ts';
test('fixed feature contract keeps all seven boolean flags and zero default version',()=>{assert.equal(featureKeys.length,7);assert.ok(Object.values(defaultFeatureFlags).every(x=>x));assert.deepEqual(normalizeFeatureConfig({version:0,flags:defaultFeatureFlags}),{version:0,flags:defaultFeatureFlags});assert.equal(parseFeatureWrite({expectedVersion:0,flags:{...defaultFeatureFlags,search:false}}).flags.search,false);});
test('missing unknown nonboolean and forged config metadata fail closed',()=>{for(const flags of [{},{...defaultFeatureFlags,search:'false'},{...defaultFeatureFlags,script:true},null])assert.throws(()=>parseFeatureWrite({expectedVersion:0,flags}),/INVALID_INPUT/);for(const n of [-1,0.5,2147483647])assert.throws(()=>parseFeatureWrite({expectedVersion:n,flags:defaultFeatureFlags}),/INVALID_INPUT/);assert.throws(()=>normalizeFeatureConfig({version:0,flags:defaultFeatureFlags,actor:'fake'}),/INVALID_INPUT/);});

test('feature write acknowledgements require exact next version and every saved flag',async()=>{const original=globalThis.fetch,input={expectedVersion:0,flags:defaultFeatureFlags};try{globalThis.fetch=async()=>Response.json({config:{version:2,flags:defaultFeatureFlags}});await assert.rejects(saveFeatures(input),/INVALID_ACK/);globalThis.fetch=async()=>Response.json({config:{version:1,flags:{...defaultFeatureFlags,search:false}}});await assert.rejects(saveFeatures(input),/INVALID_ACK/);globalThis.fetch=async()=>Response.json({error:'FEATURE_CONFLICT'},{status:409});await assert.rejects(saveFeatures(input),FeatureRejected);globalThis.fetch=async()=>new Response('',{status:503});await assert.rejects(saveFeatures(input),/UNKNOWN_RESULT/);}finally{globalThis.fetch=original;}});
test('feature responses classify disabled conflict and unavailable errors without reflecting internals',async()=>{for(const [message,status,error] of [['FEATURE_DISABLED',403,'FEATURE_DISABLED'],['FEATURE_CONFLICT',409,'FEATURE_CONFLICT'],['database password',503,'FEATURE_UNAVAILABLE']] as const){const response=await featureResponse(async()=>{throw new Error(message);});assert.equal(response.status,status);assert.equal(response.headers.get('cache-control'),'private, no-store');assert.equal((await response.json()).error,error);}});
