import {test} from 'node:test';
import assert from 'node:assert/strict';
import {pruneDeviceRecovery,readLocalCopy,writeLocalCopy,clearDeviceRecovery,enableRecovery,recoveryEnabled,newRecoveryId,RECOVERY_TTL} from '../src/editor/local-recovery.ts';
function storage(){const m=new Map<string,string>();return {get length(){return m.size;},getItem:(k:string)=>m.get(k)??null,setItem:(k:string,v:string)=>{m.set(k,v);},removeItem:(k:string)=>{m.delete(k);},key:(i:number)=>[...m.keys()][i]??null,clear:()=>m.clear()} as Storage;}
test('device recovery isolates accounts/articles and expires after 24 hours',()=>{const s=storage();const c={owner:'a',id:'doc',at:100,sequence:2,text:'{}'};writeLocalCopy(s,c);assert.deepEqual(readLocalCopy(s,'a','doc',100),c);assert.equal(readLocalCopy(s,'b','doc',100),null);assert.equal(readLocalCopy(s,'a','other',100),null);assert.equal(readLocalCopy(s,'a','doc',101+RECOVERY_TTL),null);assert.equal(s.length,0);});
test('opt-in new article keeps identity across reopening, logout clears only recovery data',()=>{const s=storage();assert.equal(recoveryEnabled(s,'a'),false);enableRecovery(s,'a');const id=newRecoveryId(s,'a','article');writeLocalCopy(s,{owner:'a',id,at:Date.now(),sequence:null,text:'{"kind":"article"}'});assert.equal(newRecoveryId(s,'a','article'),id);s.setItem('unrelated','keep');clearDeviceRecovery(s);assert.equal(recoveryEnabled(s,'a'),false);assert.equal(readLocalCopy(s,'a',id),null);assert.equal(s.getItem('unrelated'),'keep');});
test('English draft copy cannot replace the Chinese new-article recovery pointer',()=>{const s=storage();enableRecovery(s,'a');const chinese=newRecoveryId(s,'a','article');writeLocalCopy(s,{owner:'a',id:chinese,at:Date.now(),sequence:null,text:'{"kind":"article","locale":"zh-CN"}'});writeLocalCopy(s,{owner:'a',id:'english',at:Date.now(),sequence:null,text:'{"kind":"article","locale":"en","translationOf":"source"}'});assert.equal(newRecoveryId(s,'a','article'),chinese);assert.ok(readLocalCopy(s,'a','english'));});
test('oversize and full storage fail explicitly',()=>{const s=storage();assert.throws(()=>writeLocalCopy(s,{owner:'a',id:'x',at:1,sequence:1,text:'x'.repeat(2000001)}));s.setItem=()=>{throw Error('QuotaExceeded');};assert.throws(()=>writeLocalCopy(s,{owner:'a',id:'x',at:1,sequence:1,text:'{}'}));});

test('expired copies are pruned when returning while preferences remain',()=>{const s=storage();enableRecovery(s,'a');writeLocalCopy(s,{owner:'a',id:'old',at:1,sequence:1,text:'{}'});pruneDeviceRecovery(s,RECOVERY_TTL+2);assert.equal(readLocalCopy(s,'a','old'),null);assert.equal(recoveryEnabled(s,'a'),true);});
