import {test} from 'node:test';import assert from 'node:assert/strict';import {randomBytes} from 'node:crypto';
import {temporaryDatabase} from '../database/fixture.ts';import {migrate} from '../../src/server/database/migrate.ts';import {ScopedDatabase} from '../../src/server/database/scoped.ts';import {AuthorizationService} from '../../src/server/authorization/service.ts';
import {largeBody} from './fixtures.ts';import {summary,writeReport} from './report.ts';import type {Viewer} from '../../src/domain/model.ts';
test('T058 indexed Chinese search, authorized directory and concurrent durable draft saves',{timeout:180000},async()=>{
 const fixture=await temporaryDatabase();let runtime:ReturnType<typeof fixture.connectAs>|undefined,issuer:typeof runtime;const report:Record<string,unknown>={scope:'Temporary PostgreSQL, real scoped runtime roles/transactions. Bulk synthetic seed with integrity triggers retained. Not Clerk/Supabase network latency.'};
 try{
  await migrate(fixture.pool);await fixture.pool.query("INSERT INTO juyu.members(clerk_user_id,display_name,observed_role,verified_email,observed_at) VALUES('a','管理员A','admin','a@example.test',now()),('b','管理员B','admin','b@example.test',now()),('s','客服','support','s@example.test',now()),('o','运营','ops','o@example.test',now())");
  const rp=randomBytes(24).toString('hex'),ip=randomBytes(24).toString('hex');await fixture.pool.query(`CREATE ROLE scale_runtime LOGIN PASSWORD '${rp}' IN ROLE juyu_runtime; CREATE ROLE scale_issuer LOGIN PASSWORD '${ip}' IN ROLE juyu_context_issuer`);runtime=fixture.connectAs('scale_runtime',rp);issuer=fixture.connectAs('scale_issuer',ip);const db=new ScopedDatabase(runtime,issuer);const service=(id:string,role:Viewer['role'])=>new AuthorizationService(db,async()=>({id,role,companyVerified:true}));
  const seed=performance.now();const c=await fixture.pool.connect();try{await c.query('BEGIN');
   await c.query("INSERT INTO juyu.documents(id,kind,sequence,workflow_revision_id,workflow_state,published_revision_id,submitted_by,reviewer_id,approved_by) SELECT 'scale-'||i,CASE WHEN i BETWEEN 1001 AND 1200 THEN 'ops' ELSE 'article' END,CASE WHEN i<=1300 THEN 4 ELSE 0 END,1,CASE WHEN i<=1300 THEN 'published' ELSE 'draft' END,CASE WHEN i<=1300 THEN 1 ELSE null END,CASE WHEN i<=1300 THEN 'a' END,CASE WHEN i<=1300 THEN 'b' END,CASE WHEN i<=1300 THEN 'b' END FROM generate_series(1,1400) i");
   await c.query("INSERT INTO juyu.revisions(document_id,revision_id,title,body,audience,author_id,editor_id,created_at) SELECT 'scale-'||i,1,'本地资料 '||lpad(i::text,4,'0'),'共同续费规则 '||repeat('核对注册商费用和账户资料。',80)||CASE WHEN i=999 THEN ' 稀有针尖' ELSE '' END,CASE WHEN i BETWEEN 1001 AND 1200 THEN 'ops' WHEN i BETWEEN 1201 AND 1300 THEN 'admin' ELSE 'staff' END,'a','a',now() FROM generate_series(1,1400) i");
   await c.query("INSERT INTO juyu.reviews(document_id,submitted_sequence,revision_id,submitted_by,reviewer_id,status,decided_by,submitted_at,decided_at) SELECT 'scale-'||i,1,1,'a','b','approved','b',now(),now() FROM generate_series(1,1300) i");
   await c.query("INSERT INTO juyu.audit_log(document_id,sequence,action,actor_id,revision_id,at) SELECT 'scale-'||i,n,CASE n WHEN 0 THEN 'create' WHEN 1 THEN 'submit' WHEN 2 THEN 'approve' WHEN 3 THEN 'queue' ELSE 'publish' END,CASE n WHEN 2 THEN 'b' ELSE 'a' END,1,now() FROM generate_series(1,1400) i CROSS JOIN generate_series(0,4) n WHERE i<=1300 OR n=0");await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}
  await fixture.pool.query('ANALYZE juyu.revision_search; ANALYZE juyu.revisions; ANALYZE juyu.documents');report.seed={documents:1400,published:1300,staff:1000,ops:200,admin:100,draft:100,elapsedMs:performance.now()-seed};
  const metrics:Record<string,unknown>={};report.metrics=metrics;
  for(const [id,role,total] of [['s','support',1000],['o','ops',1200],['a','admin',1300]] as const){
   for(const [query,expected] of [['续费',total],['稀有针尖',1],['没有的词',0],['费',total]] as const){const samples:number[]=[];for(let n=0;n<5;n++){const start=performance.now();const found=(await service(id,role).search(query)).search;samples.push(performance.now()-start);assert.equal(found.total,expected);assert.ok(found.results.length<=20);assert.ok(found.results.every(x=>Number(x.id.split('-')[1])<=total));}metrics[`${role}:search:${query}`]=summary(samples);assert.ok(Math.max(...samples)<1000,`${role} ${query} exceeded 1s`);}
   const samples:number[]=[];for(let n=0;n<5;n++){const start=performance.now();const nav=await service(id,role).navigationTree();samples.push(performance.now()-start);assert.equal(nav.length,total);}metrics[`${role}:navigation`]=summary(samples);assert.ok(Math.max(...samples)<3000,`${role} navigation exceeded 3s`);
  }
  const body=largeBody();const input={expectedSequence:null,title:'大文章并发本地验收',body,kind:'article',audience:'staff',tags:[],cover:null};let saved=await service('a','admin').saveDraft('00000000-0000-4000-8000-000000000058',input);const concurrent:number[]=[];
  for(let n=0;n<5;n++){const start=performance.now();const attempts=await Promise.allSettled(['a','b'].map(id=>service(id,'admin').saveDraft('00000000-0000-4000-8000-000000000058',{...input,expectedSequence:saved.sequence,title:`${id} 第${n+1}轮`})));concurrent.push(performance.now()-start);const wins=attempts.filter(x=>x.status==='fulfilled');const losses=attempts.filter(x=>x.status==='rejected');assert.equal(wins.length,1);assert.equal(losses.length,1);assert.match(String((losses[0] as PromiseRejectedResult).reason),/CONFLICT/);saved=(wins[0] as PromiseFulfilledResult<typeof saved>).value;assert.equal(saved.body,body);}
  assert.equal(saved.sequence,5);assert.equal((await fixture.pool.query("SELECT count(*)::int n FROM juyu.audit_log WHERE document_id='00000000-0000-4000-8000-000000000058'")).rows[0].n,6);report.concurrentSaves={bodyChars:body.length,bodyBytes:Buffer.byteLength(body),blocks:300,...summary(concurrent),winners:5,conflicts:5,auditEntries:6};assert.ok(Math.max(...concurrent)<5000,'concurrent save exceeded 5s');
 }finally{await writeReport('database',report);await runtime?.end();await issuer?.end();await fixture.close();}
});
