// Run in a fresh process: node --experimental-strip-types tests/performance/upload-memory.ts 1|2
import {mkdtemp,rm,stat} from 'node:fs/promises';import {createReadStream,createWriteStream} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {Readable} from 'node:stream';import {pipeline} from 'node:stream/promises';import assert from 'node:assert/strict';
import {uploadFile} from '../../src/server/media/upload.ts';import {writeReport} from './report.ts';
const count=Number(process.argv[2]);assert.ok(count===1||count===2);const size=50*1024*1024;const dir=await mkdtemp(join(tmpdir(),'juyu-upload-scale-'));const initial=process.memoryUsage();const start=performance.now();let rss=initial.rss;
const timer=setInterval(()=>{rss=Math.max(rss,process.memoryUsage().rss);},2);
try{
 const jobs=Array.from({length:count},async()=>{let sent=0;const input=new ReadableStream<Uint8Array>({pull(c){if(sent===size){c.close();return;}const chunk=Buffer.alloc(Math.min(65536,size-sent),65);if(sent===0)chunk.write('ftyp',4);sent+=chunk.length;c.enqueue(chunk);}});
 const request=new Request('http://local/upload',{method:'POST',headers:{'content-type':'application/octet-stream','x-file-name':'synthetic.mp4'},body:input,duplex:'half'} as RequestInit);
 return uploadFile(request,'local',{authorize:async()=>{},reserve:async()=>{},finish:async(_id,ready)=>assert.equal(ready,true),storage:()=>({put:async(key,stream)=>{await pipeline(Readable.fromWeb(stream as Parameters<typeof Readable.fromWeb>[0]),createWriteStream(join(dir,key)));},read:async key=>{const file=join(dir,key),s=await stat(file);return new Response(Readable.toWeb(createReadStream(file)) as ReadableStream<Uint8Array>,{headers:{'content-length':String(s.size)}});}})});});
 const result=await Promise.all(jobs);assert.ok(result.every(x=>x.status==='ready'));rss=Math.max(rss,process.memoryUsage().rss);await writeReport(`upload-memory-${count}`,{scope:'Fresh process, generated streaming requests, temporary disk storage; includes harness and filesystem stream overhead, no real cloud. Signature-only synthetic video.',concurrent:count,fileBytes:size,elapsedMs:performance.now()-start,initialRssBytes:initial.rss,sampledPeakRssBytes:rss,maxProcessRssKiB:process.resourceUsage().maxRSS,final:process.memoryUsage()});assert.ok(process.resourceUsage().maxRSS<512*1024,'Fresh-process upload peak exceeds the local 512 MiB diagnostic budget (excluding Next.js).');
}finally{clearInterval(timer);await rm(dir,{recursive:true,force:true});}
