import {readFile,readdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {before,after,beforeEach,test} from 'node:test';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import type {Pool} from 'pg';
import {temporaryDatabase} from './fixture.ts';
import {migrate} from '../../src/server/database/migrate.ts';
import {ScopedDatabase} from '../../src/server/database/scoped.ts';
import {DocumentRepository} from '../../src/server/database/repository.ts';
import {AuthorizationService} from '../../src/server/authorization/service.ts';
import type {Viewer,Document} from '../../src/domain/model.ts';
import type {MediaBlock} from '../../src/media/model.ts';
let fixture:Awaited<ReturnType<typeof temporaryDatabase>>,runtime:Pool,issuer:Pool,db:ScopedDatabase,repo:DocumentRepository;
const admin:Viewer={id:'a',role:'admin',companyVerified:true},reviewer:Viewer={...admin,id:'b'},ops:Viewer={id:'o',role:'ops',companyVerified:true},support:Viewer={id:'s',role:'support',companyVerified:true};
const service=(v:Viewer|null=support)=>new AuthorizationService(db,async()=>v);
async function draft(title='Reference formal',kind:Document['kind']='reference',audience:'ops'|'admin'|'staff'='staff',body='Formal body',blocks:MediaBlock[]=[]){return repo.create({id:randomUUID(),kind,title,audience,body,blocks,tags:['Formal tag']},admin);}
async function publish(d:Document){await service(admin).submitReview(d.id,{expectedSequence:d.sequence,reviewerId:'b'});await service(reviewer).decideReview(d.id,{expectedSequence:d.sequence+1,action:'approve'});await service(admin).changePublication(d.id,{expectedSequence:d.sequence+2,action:'queue'});await service(admin).changePublication(d.id,{expectedSequence:d.sequence+3,action:'publish'});return (await repo.getForManagement(d.id,admin))!;}
before(async()=>{fixture=await temporaryDatabase();await migrate(fixture.pool);await fixture.pool.query("INSERT INTO juyu.members(clerk_user_id,display_name,observed_role,verified_email,observed_at) VALUES('a','Admin','admin','a@example.test',now()),('b','Reviewer','admin','b@example.test',now()),('o','Ops','ops','o@example.test',now()),('s','Support','support','s@example.test',now())");const rp=randomBytes(24).toString('hex'),ip=randomBytes(24).toString('hex');await fixture.pool.query(`CREATE ROLE analytics_runtime LOGIN PASSWORD '${rp}' IN ROLE juyu_runtime; CREATE ROLE analytics_issuer LOGIN PASSWORD '${ip}' IN ROLE juyu_context_issuer`);runtime=fixture.connectAs('analytics_runtime',rp);issuer=fixture.connectAs('analytics_issuer',ip);db=new ScopedDatabase(runtime,issuer);repo=new DocumentRepository(db);});
after(async()=>{await runtime?.end();await issuer?.end();await fixture?.close();});
beforeEach(async()=>{await fixture.pool.query('TRUNCATE juyu.documents,juyu.search_queries CASCADE');});



const capture=(input:unknown,v:Viewer|null=support)=>db.run(v,async c=>(await import('../../src/server/analytics/repository.ts')).captureAnalytics(c,input));
const view=(documentId:string,eventId=randomUUID(),revision=1)=>({kind:'view' as const,eventId,documentId,revision});
const snapshot=(documentId?:string,eventId=randomUUID(),query='Formal')=>({eventId,query,page:1,total:documentId?1:0,results:documentId?[{documentId,revision:1}]:[]});
const events=async()=> (await fixture.pool.query('SELECT * FROM juyu.analytics_events ORDER BY occurred_at')).rows;

test('view records server identity and time, acknowledges only metadata, and exactly deduplicates across retries',async()=>{
 const d=await publish(await draft()),input=view(d.id),before=Date.now();assert.deepEqual(await capture(input),{eventId:input.eventId,kind:'view'});const stored=(await events())[0];assert.equal(stored.member_id,'s');assert.ok(stored.occurred_at.getTime()>=before&&stored.occurred_at.getTime()<=Date.now());await capture(input);assert.deepEqual(await events(),[stored]);
 await assert.rejects(capture(input,ops),/CONFLICT/);await assert.rejects(capture({...input,revision:2}),/CONFLICT|VERSION_CHANGED/);const other=await publish(await draft('Another'));await assert.rejects(capture({...input,documentId:other.id}),/CONFLICT/);
});
test('views recheck current formal publication and identity for both first capture and retries',async()=>{
 const d=await publish(await draft()),input=view(d.id);await capture(input);await assert.rejects(capture(view(d.id,randomUUID(),2)),/VERSION_CHANGED/);
 const hidden=await publish(await draft('Private','ops','ops'));await assert.rejects(capture(view(hidden.id)),/NOT_FOUND/);await capture(view(hidden.id),ops);
 const parent=randomUUID(),child=randomUUID();await fixture.pool.query("INSERT INTO juyu.categories(id,name,audience) VALUES($1,'Parent','admin')",[parent]);await fixture.pool.query("INSERT INTO juyu.categories(id,name,parent_id) VALUES($1,'Child',$2)",[child,parent]);await fixture.pool.query('INSERT INTO juyu.revision_categories VALUES($1,1,$2)',[d.id,child]);await assert.rejects(capture(input),/NOT_FOUND/);await fixture.pool.query('DELETE FROM juyu.revision_categories WHERE document_id=$1',[d.id]);
 for(const state of ["disabled_at=now()","observed_role='ops'","verified_email=null","verified_email='   '","observed_at=null"]){await fixture.pool.query(`UPDATE juyu.members SET ${state} WHERE clerk_user_id='s'`);try{await assert.rejects(capture(input),/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.members SET disabled_at=null,observed_role='support',verified_email='s@example.test',observed_at=now() WHERE clerk_user_id='s'");}}
 await assert.rejects(capture(input,null),/FORBIDDEN/);await service(admin).changeAvailability(d.id,{expectedSequence:d.sequence,action:'archive'});await assert.rejects(capture(input),/NOT_FOUND/);assert.equal((await events()).length,2);
});
test('search count and ordered results are verified, raw query is never persisted and retry payload is exact',async()=>{
 const d=await publish(await draft()),s=snapshot(d.id),input={kind:'search',...s};assert.deepEqual(await capture(input),{eventId:s.eventId,kind:'search'});const row=(await fixture.pool.query('SELECT * FROM juyu.search_queries')).rows[0];assert.equal(row.member_id,'s');assert.equal(row.query,'sha256:'+createHash('sha256').update('Formal').digest('hex'));assert.equal(row.search_page,1);assert.equal(row.result_count,1);assert.equal(JSON.stringify(row).includes('Formal'),false);
 await capture({...input,query:'  Formal  '});assert.equal((await fixture.pool.query('SELECT count(*)::int n FROM juyu.search_queries')).rows[0].n,1);
 await assert.rejects(capture({...input,query:'formal'}),/CONFLICT/);await assert.rejects(capture(input,ops),/CONFLICT/);await assert.rejects(capture({...input,total:0,results:[]}),/CONFLICT/);
 for(const bad of [{...input,eventId:randomUUID(),total:99},{...input,eventId:randomUUID(),results:[]},{...input,eventId:randomUUID(),results:[{documentId:d.id,revision:2}]}])await assert.rejects(capture(bad),/SNAPSHOT_CHANGED/);
 await capture({kind:'search',...snapshot(undefined,randomUUID(),'NoSuchTerm')});const rows=(await fixture.pool.query('SELECT * FROM juyu.search_queries ORDER BY occurred_at')).rows;assert.equal(rows.length,2);assert.equal(rows[1].result_count,0);
 const changed=snapshot(d.id);await publish(await draft('Another Formal'));await assert.rejects(capture({kind:'search',...changed}),/SNAPSHOT_CHANGED/);
});
test('pagination stores global positions and rejects swapped results and fabricated page totals',async()=>{
 const ids:string[]=[];for(let i=0;i<22;i++)ids.push((await publish(await draft('Formal '+String(i).padStart(2,'0')))).id);
 const s={eventId:randomUUID(),query:'Formal',page:2,total:22,results:ids.slice(20).map(documentId=>({documentId,revision:1}))};await capture({kind:'search',...s});assert.deepEqual((await fixture.pool.query('SELECT position,document_id FROM juyu.search_results WHERE search_id=$1 ORDER BY position',[s.eventId])).rows,[{position:21,document_id:ids[20]},{position:22,document_id:ids[21]}]);
 await assert.rejects(capture({kind:'search',...s,eventId:randomUUID(),results:[...s.results].reverse()}),/SNAPSHOT_CHANGED/);await assert.rejects(capture({kind:'search',...s,eventId:randomUUID(),page:1}),/SNAPSHOT_CHANGED/);
 await capture({kind:'search',...s,eventId:randomUUID(),page:3,results:[]});
});
test('click-before-search captures the exact search atomically and enforces result identity actor position and retries',async()=>{
 const d=await publish(await draft()),s=snapshot(d.id),click={kind:'search_click',eventId:randomUUID(),documentId:d.id,revision:1,position:1,search:s};assert.deepEqual(await capture(click),{eventId:click.eventId,kind:'search_click'});await capture({kind:'search',...s});await capture(click);assert.equal((await events()).length,1);assert.equal((await fixture.pool.query('SELECT count(*)::int n FROM juyu.search_queries')).rows[0].n,1);
 await assert.rejects(capture({...click,eventId:randomUUID(),position:2}),/NOT_FOUND|INVALID_INPUT/);await assert.rejects(capture({...click,eventId:randomUUID()},ops),/CONFLICT/);const other=await publish(await draft('Other'));await assert.rejects(capture({...click,eventId:randomUUID(),documentId:other.id}),/NOT_FOUND/);
 await assert.rejects(capture({...click,search:{...s,query:'Other'}}),/CONFLICT/);await assert.rejects(capture(view(d.id,s.eventId)),/CONFLICT/);await assert.rejects(capture({kind:'search',...s,eventId:click.eventId}),/CONFLICT/);
 await service(admin).changeAvailability(d.id,{expectedSequence:d.sequence,action:'unpublish'});await assert.rejects(capture(click),/NOT_FOUND|SNAPSHOT_CHANGED/);
});
test('feedback captures metadata once per saved version, excludes comments, and isolates analytics failure',async()=>{
 const d=await publish(await draft());const save=(helpful:boolean,comment:string,expectedVersion:number)=>service().saveFeedback(d.id,{revision:1,helpful,comment,expectedVersion});
 await save(true,'private feedback comment',0);await save(true,'private feedback comment',0);let rows=await events();assert.equal(rows.length,1);assert.equal(rows[0].kind,'feedback');assert.equal(rows[0].feedback_helpful,true);assert.equal(rows[0].feedback_version,1);assert.equal(JSON.stringify(rows).includes('private feedback'),false);
 await save(false,'updated private comment',1);rows=await events();assert.equal(rows.length,2);assert.equal(rows[1].feedback_helpful,false);assert.equal(rows[1].feedback_version,2);
 await fixture.pool.query("CREATE FUNCTION juyu.test_analytics_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'forced analytics failure'; END $$; CREATE TRIGGER test_analytics_failure BEFORE INSERT ON juyu.analytics_events FOR EACH ROW EXECUTE FUNCTION juyu.test_analytics_failure()");try{const saved=await save(true,'still saved',2);assert.equal(saved.version,3);assert.equal((await events()).length,2);assert.equal((await fixture.pool.query('SELECT comment,version FROM juyu.feedback WHERE document_id=$1',[d.id])).rows[0].comment,'still saved');}finally{await fixture.pool.query('DROP TRIGGER test_analytics_failure ON juyu.analytics_events; DROP FUNCTION juyu.test_analytics_failure()');}
});
test('runtime has no raw analytics writes and direct SQL rejects actor timestamp and private content fields',async()=>{
 const d=await publish(await draft()),input=view(d.id);await assert.rejects(runtime.query('SELECT juyu.capture_analytics($1::jsonb)',[JSON.stringify(input)]),/FORBIDDEN/);
 for(const table of ['analytics_events','search_queries','search_results'])for(const operation of ['INSERT','UPDATE','DELETE'])assert.equal((await fixture.pool.query('SELECT has_table_privilege($1,$2,$3) allowed',['analytics_runtime','juyu.'+table,operation])).rows[0].allowed,false);
 for(const bad of [{...input,actorId:'a'},{...input,occurredAt:'2030'},{...input,title:'private'},{...input,kind:'feedback'}, {kind:'search',...snapshot(d.id),results:[{documentId:d.id,revision:1,title:'secret'}]}, {kind:'search',...snapshot(d.id),query:''}])await assert.rejects(db.run(support,c=>c.query('SELECT juyu.capture_analytics($1::jsonb)',[JSON.stringify(bad)])),/INVALID_INPUT/);
 for(const fn of ['juyu.capture_analytics(jsonb)','juyu.capture_analytics_search(jsonb)']){const p=(await fixture.pool.query("SELECT prosecdef,proconfig,EXISTS(SELECT 1 FROM aclexplode(proacl) a WHERE a.grantee=0 AND a.privilege_type='EXECUTE') public_execute FROM pg_proc WHERE oid=$1::regprocedure",[fn])).rows[0];assert.equal(p.prosecdef,true);assert.deepEqual(p.proconfig,['search_path=pg_catalog, juyu']);assert.equal(p.public_execute,false);}
});
async function waitForLock(pid:number){for(let i=0;i<100;i++){if((await fixture.pool.query('SELECT wait_event_type FROM pg_stat_activity WHERE pid=$1',[pid])).rows[0]?.wait_event_type==='Lock')return;await new Promise(resolve=>setTimeout(resolve,10));}assert.fail('database operation must wait on a real transaction lock');}
test('concurrent retries capture one event and concurrent member/document changes are rechecked',async()=>{
 const d=await publish(await draft()),input=view(d.id);const {captureAnalytics}=await import('../../src/server/analytics/repository.ts');let release!:()=>void,ready!:()=>void,start!:(pid:number)=>void;const gate=new Promise<void>(r=>{release=r;}),written=new Promise<void>(r=>{ready=r;}),started=new Promise<number>(r=>{start=r;});const first=db.run(support,async c=>{await captureAnalytics(c,input);ready();await gate;});await written;const second=db.run(support,async c=>{start((await c.query('SELECT pg_backend_pid() pid')).rows[0].pid);return captureAnalytics(c,input);});try{await waitForLock(await started);}finally{release();}await first;await second;assert.equal((await events()).length,1);
 for(const change of ['document','member']){const owner=await fixture.pool.connect();let startWait!:(pid:number)=>void;const begun=new Promise<number>(r=>{startWait=r;});try{await owner.query('BEGIN');if(change==='document')await owner.query("UPDATE juyu.documents SET lifecycle='archived' WHERE id=$1",[d.id]);else await owner.query("UPDATE juyu.members SET disabled_at=now() WHERE clerk_user_id='s'");const result=db.run(support,async c=>{startWait((await c.query('SELECT pg_backend_pid() pid')).rows[0].pid);return captureAnalytics(c,view(d.id));}).then(value=>({value}),error=>({error}));await waitForLock(await begun);await owner.query('COMMIT');assert.match(String((await result as {error:Error}).error),change==='document'?/NOT_FOUND/:/FORBIDDEN/);}finally{await owner.query('ROLLBACK');owner.release();if(change==='document')await fixture.pool.query("UPDATE juyu.documents SET lifecycle='active' WHERE id=$1",[d.id]);else await fixture.pool.query("UPDATE juyu.members SET disabled_at=null WHERE clerk_user_id='s'");}}
 const lock=await fixture.pool.connect();try{await lock.query('BEGIN');await lock.query('SELECT pg_advisory_xact_lock(84620915)');await assert.rejects(capture(view(d.id)),/MEMBER_BUSY/);}finally{await lock.query('ROLLBACK');lock.release();}
});
test('purge removes dependent analytics while preserving no raw query',async()=>{
 const d=await publish(await draft()),s=snapshot(d.id);await capture(view(d.id));await capture({kind:'search_click',eventId:randomUUID(),documentId:d.id,revision:1,position:1,search:s});await service().saveFeedback(d.id,{revision:1,helpful:true,comment:'private',expectedVersion:0});await service(admin).lifecycle(d.id,{expectedSequence:d.sequence,action:'trash'});await service(admin).lifecycle(d.id,{expectedSequence:d.sequence+1,action:'purge',confirmation:'Reference formal'});assert.equal((await events()).length,0);assert.equal((await fixture.pool.query('SELECT count(*)::int n FROM juyu.search_results')).rows[0].n,0);await assert.rejects(capture({kind:'search',...s}),/CONFLICT|SNAPSHOT_CHANGED/);
});
test('SQL validates nested result keys instead of silently replacing caller-supplied kind or event identity',async()=>{
 const d=await publish(await draft());for(const extra of [{kind:'view'},{eventId:randomUUID()}])await assert.rejects(db.run(support,c=>c.query('SELECT juyu.capture_analytics($1::jsonb)',[JSON.stringify({kind:'search',...snapshot(d.id),results:[{documentId:d.id,revision:1,...extra}]})])),/INVALID_INPUT/);
});
test('search and click arriving concurrently share one search snapshot, and conflicting callers cannot claim its id',async()=>{
 const d=await publish(await draft()),s=snapshot(d.id),click={kind:'search_click',eventId:randomUUID(),documentId:d.id,revision:1,position:1,search:s};await Promise.all([capture({kind:'search',...s}),capture(click),capture(click)]);assert.equal((await events()).length,1);assert.equal((await fixture.pool.query('SELECT count(*)::int n FROM juyu.search_queries')).rows[0].n,1);
 const id=randomUUID(),a={kind:'search',...snapshot(d.id,id)},b={kind:'search',...snapshot(undefined,id,'NoSuchTerm')};const outcomes=await Promise.allSettled([capture(a),capture(b)]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);const failed=outcomes.find(x=>x.status==='rejected') as PromiseRejectedResult;assert.match(String(failed.reason),/CONFLICT/);
});
test('search retries and feedback analytics respect pending identity changes and search retries deny revoked results',async()=>{
 const d=await publish(await draft()),s=snapshot(d.id);await capture({kind:'search',...s});await fixture.pool.query("INSERT INTO juyu.member_operations(actor_id,target_id,kind,before_role,requested_role) VALUES('a','s','role','support','ops')");try{await assert.rejects(capture({kind:'search',...s}),/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.member_operations SET status='conflict',finished_at=now() WHERE target_id='s' AND status='pending'");}
 await service(admin).changeAvailability(d.id,{expectedSequence:d.sequence,action:'archive'});await assert.rejects(capture({kind:'search',...s}),/NOT_FOUND/);
});
test('migration protects populated legacy query text and preserves event relations and unrelated data',async()=>{
 const old=await temporaryDatabase();try{await old.pool.query('CREATE SCHEMA juyu; CREATE TABLE juyu.schema_migrations(version text PRIMARY KEY,checksum text NOT NULL,applied_at timestamptz NOT NULL DEFAULT now())');const directory=new URL('../../src/server/database/migrations/',import.meta.url);for(const file of (await readdir(directory)).filter(file=>file.endsWith('.sql')&&file<'0019').sort()){const sql=await readFile(new URL(file,directory),'utf8');await old.pool.query(sql);await old.pool.query('INSERT INTO juyu.schema_migrations(version,checksum) VALUES($1,$2)',[file.slice(0,-4),createHash('sha256').update(sql).digest('hex')]);}
 await old.pool.query("BEGIN; INSERT INTO juyu.members(clerk_user_id,display_name) VALUES('a','Admin'),('s','Support'); INSERT INTO juyu.documents(id,kind,sequence,workflow_revision_id,workflow_state) VALUES('old','article',0,1,'draft'); INSERT INTO juyu.revisions(document_id,revision_id,title,body,audience,author_id,editor_id,created_at) VALUES('old',1,'Old title','Old body','staff','a','a',now()); INSERT INTO juyu.audit_log(document_id,sequence,action,actor_id,revision_id,at) VALUES('old',0,'create','a',1,now()); INSERT INTO juyu.search_queries(id,member_id,query,result_count) VALUES('11111111-1111-4111-8111-111111111111','s','private legacy query',1); INSERT INTO juyu.search_results VALUES('11111111-1111-4111-8111-111111111111',1,'old',1); INSERT INTO juyu.analytics_events(id,member_id,kind,document_id,revision_id,search_id,result_position) VALUES('22222222-2222-4222-8222-222222222222','s','search_click','old',1,'11111111-1111-4111-8111-111111111111',1); INSERT INTO juyu.analytics_events(id,member_id,kind,document_id,revision_id) VALUES('33333333-3333-4333-8333-333333333333','s','feedback','old',1); INSERT INTO juyu.feedback(member_id,document_id,revision_id,helpful,comment) VALUES('s','old',1,true,'Private comment'); INSERT INTO juyu.favorites VALUES('s','old',now()); COMMIT;");
 const feedback=(await old.pool.query('SELECT * FROM juyu.feedback')).rows,favorites=(await old.pool.query('SELECT * FROM juyu.favorites')).rows,results=(await old.pool.query('SELECT * FROM juyu.search_results')).rows;assert.deepEqual(await migrate(old.pool),['0019_analytics', '0020_custom_fields', '0021_categories', '0022_forms', '0023_navigation_settings', '0024_feature_flags', '0025_setting_history', '0026_announcements', '0027_native_editor', '0028_qa_search', '0029_shared_revision_config_locks', '0030_publication_number', '0031_scoped_search', '0032_category_icons', '0033_publication_icons', '0034_article_description', '0035_publication_timestamp', '0036_reader_changelog', '0037_reusable_fragments', '0038_reusable_fragment_versions', '0039_release_notes', '0040_document_locales', '0041_english_review_confirmation', '0042_draft_actions', '0043_super_admin_role', '0044_super_admin_direct_publish', '0045_search_relevance']);assert.deepEqual(await migrate(old.pool),[]);assert.deepEqual((await old.pool.query('SELECT * FROM juyu.feedback')).rows,feedback);assert.deepEqual((await old.pool.query('SELECT * FROM juyu.favorites')).rows,favorites);assert.deepEqual((await old.pool.query('SELECT * FROM juyu.search_results')).rows,results);const query=(await old.pool.query('SELECT * FROM juyu.search_queries')).rows[0];assert.equal(query.query,'sha256:'+createHash('sha256').update('private legacy query').digest('hex'));assert.equal(query.search_page,1);assert.equal((await old.pool.query('SELECT count(*)::int n FROM juyu.analytics_events')).rows[0].n,2);
 }finally{await old.close();}
});
test('analytics query cancellation is isolated from a valid feedback save',async()=>{
 const d=await publish(await draft());await fixture.pool.query("CREATE FUNCTION juyu.test_analytics_timeout() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION USING ERRCODE='57014',MESSAGE='forced analytics cancellation'; END $$; CREATE TRIGGER test_analytics_timeout BEFORE INSERT ON juyu.analytics_events FOR EACH ROW EXECUTE FUNCTION juyu.test_analytics_timeout()");try{const saved=await service().saveFeedback(d.id,{revision:1,helpful:true,comment:'Saved despite analytics timeout',expectedVersion:0});assert.equal(saved.version,1);assert.equal((await fixture.pool.query('SELECT comment FROM juyu.feedback WHERE document_id=$1',[d.id])).rows[0].comment,'Saved despite analytics timeout');assert.equal((await events()).length,0);}finally{await fixture.pool.query('DROP TRIGGER test_analytics_timeout ON juyu.analytics_events; DROP FUNCTION juyu.test_analytics_timeout()');}
});
