import assert from 'node:assert/strict';
import {before,after,test} from 'node:test';
import {randomBytes,randomUUID} from 'node:crypto';
import type {Pool} from 'pg';
import {temporaryDatabase} from './fixture.ts';
import {migrate} from '../../src/server/database/migrate.ts';
import {ScopedDatabase} from '../../src/server/database/scoped.ts';
import {DocumentRepository} from '../../src/server/database/repository.ts';
import {AuthorizationService} from '../../src/server/authorization/service.ts';
import type {Viewer} from '../../src/domain/model.ts';
let fixture:Awaited<ReturnType<typeof temporaryDatabase>>,runtime:Pool,issuer:Pool,db:ScopedDatabase,repo:DocumentRepository;
const a:Viewer={id:'a',role:'admin',companyVerified:true},b:Viewer={...a,id:'b'},c:Viewer={...a,id:'c'},manager:Viewer={...a,id:'manager'},staff:Viewer={id:'staff',role:'support',companyVerified:true};
const service=(v:Viewer|null=manager)=>new AuthorizationService(db,async()=>v);
async function draft(){return repo.create({id:randomUUID(),kind:'article',title:'审核管理',body:'正式内容',audience:'staff'},a);}
async function pending(){const d=await draft();await service(a).submitReview(d.id,{expectedSequence:0,reviewerId:'b'});return d;}
async function restoreMember(id:string){await fixture.pool.query("UPDATE juyu.members SET disabled_at=null,observed_role='admin',verified_email=$2,observed_at=now() WHERE clerk_user_id=$1",[id,`${id}@example.test`]);}
before(async()=>{fixture=await temporaryDatabase();await migrate(fixture.pool);await fixture.pool.query("INSERT INTO juyu.members(clerk_user_id,display_name,observed_role,verified_email,observed_at) VALUES('a','A','admin','a@example.test',now()),('b','B','admin','b@example.test',now()),('c','C','admin','c@example.test',now()),('manager','Manager','admin','manager@example.test',now()),('staff','Support','support','staff@example.test',now())");const rp=randomBytes(24).toString('hex'),ip=randomBytes(24).toString('hex');await fixture.pool.query(`CREATE ROLE availability_runtime LOGIN PASSWORD '${rp}' IN ROLE juyu_runtime; CREATE ROLE availability_issuer LOGIN PASSWORD '${ip}' IN ROLE juyu_context_issuer`);runtime=fixture.connectAs('availability_runtime',rp);issuer=fixture.connectAs('availability_issuer',ip);db=new ScopedDatabase(runtime,issuer);repo=new DocumentRepository(db);});
after(async()=>{if(runtime)await runtime.end();if(issuer)await issuer.end();if(fixture)await fixture.close();});
async function approved(){const d=await pending();await service(b).decideReview(d.id,{expectedSequence:1,action:'approve'});return (await repo.getForManagement(d.id,a))!;}
async function publish(id:string,sequence:number){await service().changePublication(id,{expectedSequence:sequence,action:'queue'});return service().changePublication(id,{expectedSequence:sequence+1,action:'publish'});}
async function asset(id:string,mime='image/png',status='ready'){const aid=randomUUID();await fixture.pool.query("INSERT INTO juyu.assets(id,document_id,uploaded_by,filename,mime_type,byte_size,object_key,status) VALUES($1::uuid,$2,'a','file',$3,4,$1::text,$4)",[aid,id,mime,status]);return aid;}
async function waitForLock(query:string,count=1){const deadline=Date.now()+3000;let n=0;while(Date.now()<deadline){n=(await fixture.pool.query("SELECT count(*)::int AS n FROM pg_stat_activity WHERE wait_event_type='Lock' AND query LIKE $1",[query])).rows[0].n;if(n>=count)break;await new Promise(r=>setTimeout(r,5));}assert.equal(n,count,'independent real DB connections must overlap');}
test('availability boundary exposes secured actions and archived listing',()=>{
 assert.equal(typeof service().availabilityDetail,'function');assert.equal(typeof service().changeAvailability,'function');assert.equal(typeof service().archives,'function');
});
test('current eligible admin required for detail listing and writes',async()=>{
 const d=await draft();for(const v of [null,staff,{...manager,companyVerified:false}]){await assert.rejects(service(v).availabilityDetail(d.id),/FORBIDDEN/);await assert.rejects(service(v).archives(),/FORBIDDEN/);await assert.rejects(service(v).changeAvailability(d.id,{expectedSequence:0,action:'archive'}),/FORBIDDEN/);}
 for(const update of ["disabled_at=now()","observed_role='support'","verified_email=null","observed_at=null"]){await fixture.pool.query(`UPDATE juyu.members SET ${update} WHERE clerk_user_id='manager'`);try{await assert.rejects(service().availabilityDetail(d.id),/FORBIDDEN/);await assert.rejects(service().archives(),/FORBIDDEN/);await assert.rejects(service().changeAvailability(d.id,{expectedSequence:0,action:'archive'}),/FORBIDDEN/);}finally{await restoreMember('manager');}}
 const op=(await fixture.pool.query("INSERT INTO juyu.member_operations(actor_id,target_id,kind,requested_role) VALUES('a','manager','role','support') RETURNING id")).rows[0].id;try{await assert.rejects(service().availabilityDetail(d.id),/FORBIDDEN/);await assert.rejects(service().archives(),/FORBIDDEN/);await assert.rejects(service().changeAvailability(d.id,{expectedSequence:0,action:'archive'}),/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.member_operations SET status='conflict',finished_at=now() WHERE id=$1",[op]);}
 await fixture.pool.query("INSERT INTO juyu.role_enrollments(member_id,requested_role,purpose) VALUES('manager','support','default')");try{await assert.rejects(service().availabilityDetail(d.id),/FORBIDDEN/);await assert.rejects(service().archives(),/FORBIDDEN/);await assert.rejects(service().changeAvailability(d.id,{expectedSequence:0,action:'archive'}),/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.role_enrollments SET state='complete',confirmed_at=now() WHERE member_id='manager'");}
});
test('strict action and sequence input rejects coercion unknown fields invalid bounds',async()=>{
 const d=await draft();for(const input of [null,[],{}, {expectedSequence:0,action:'publish'},{expectedSequence:'0',action:'archive'},{expectedSequence:-1,action:'archive'},{expectedSequence:1.5,action:'archive'},{expectedSequence:2147483647,action:'archive'},{expectedSequence:NaN,action:'archive'},{expectedSequence:0,action:'archive',actorId:'a'}])await assert.rejects(service().changeAvailability(d.id,input),/INVALID_INPUT/);
 for(const id of ['', 'x'.repeat(201)]){await assert.rejects(service().availabilityDetail(id),/INVALID_INPUT/);await assert.rejects(service().changeAvailability(id,{expectedSequence:0,action:'archive'}),/INVALID_INPUT/);}await assert.rejects(service().availabilityDetail('missing'),/NOT_FOUND/);await assert.rejects(service().changeAvailability('missing',{expectedSequence:0,action:'archive'}),/NOT_FOUND/);
 for(const page of [0,-1,1.5,NaN,'1'])await assert.rejects(service().archives(page as number),/INVALID_INPUT/);
});
test('availability detail reports active archived trashed states and only legal actions',async()=>{
 const d=await draft();assert.deepEqual(await service().availabilityDetail(d.id),{documentId:d.id,title:'审核管理',sequence:0,revision:1,lifecycle:'active',status:'draft',publishedRevision:null,canArchive:true,canUnpublish:false,canUnarchive:false,history:[],historyMore:false});await assert.rejects(service().changeAvailability(d.id,{expectedSequence:0,action:'unpublish'}),/INVALID_STATE/);await assert.rejects(service().changeAvailability(d.id,{expectedSequence:0,action:'unarchive'}),/INVALID_STATE/);
 await service().changeAvailability(d.id,{expectedSequence:0,action:'archive'});const archived=await service().availabilityDetail(d.id);assert.equal(archived.canUnarchive,true);assert.equal(archived.canArchive,false);assert.equal(archived.canUnpublish,false);await assert.rejects(service().changeAvailability(d.id,{expectedSequence:1,action:'archive'}),/INVALID_STATE/);await service(a).lifecycle(d.id,{expectedSequence:1,action:'trash'});const trashed=await service().availabilityDetail(d.id);assert.equal(trashed.lifecycle,'trashed');assert.equal(trashed.canArchive||trashed.canUnpublish||trashed.canUnarchive,false);for(const action of ['archive','unpublish','unarchive'])await assert.rejects(service().changeAvailability(d.id,{expectedSequence:2,action}),/INVALID_STATE/);
});
test('archive and unpublish reset every current review state while preserving bodies files and completed history',async()=>{
 for(const action of ['archive','unpublish'] as const)for(const stage of ['published','draft','in_review','approved','queued'] as const){let d=await approved();await publish(d.id,2);let sequence=4;if(stage!=='published'){d=await repo.execute(d.id,{type:'edit',title:'修订内容',body:'新正文',audience:'staff'},a,{expectedSequence:4});sequence=5;if(stage!=='draft'){await service(a).submitReview(d.id,{expectedSequence:5,reviewerId:'b'});sequence=6;}if(['approved','queued'].includes(stage)){await service(b).decideReview(d.id,{expectedSequence:6,action:'approve'});sequence=7;}if(stage==='queued'){await service().changePublication(d.id,{expectedSequence:7,action:'queue'});sequence=8;}}
 const file=await asset(d.id,'application/pdf');await fixture.pool.query("INSERT INTO juyu.revision_assets(document_id,revision_id,asset_id,usage) VALUES($1,1,$2,'attachment')",[d.id,file]);const before=(await repo.getForManagement(d.id,a))!;const reviews=(await fixture.pool.query("SELECT * FROM juyu.reviews WHERE document_id=$1 AND status<>'in_review' ORDER BY submitted_sequence",[d.id])).rows;
 const result=await service().changeAvailability(d.id,{expectedSequence:sequence,action});assert.deepEqual(result,{documentId:d.id,sequence:sequence+1,revision:before.workflow.revisionId,action,lifecycle:action==='archive'?'archived':'active',status:'draft',publishedRevision:null});const after=(await repo.getForManagement(d.id,a))!;assert.deepEqual(after.revisions,before.revisions);assert.deepEqual(after.audit.slice(0,-1),before.audit);assert.deepEqual(after.workflow,{revisionId:before.workflow.revisionId,status:'draft',approvalMode:'standard',submittedBy:null,reviewerId:null,approvedBy:null});assert.deepEqual((await fixture.pool.query("SELECT * FROM juyu.reviews WHERE document_id=$1 AND submitted_sequence=1",[d.id])).rows,reviews.filter(r=>r.submitted_sequence===1));assert.equal((await fixture.pool.query('SELECT count(*)::int n FROM juyu.assets WHERE id=$1',[file])).rows[0].n,1);assert.equal((await fixture.pool.query('SELECT count(*)::int n FROM juyu.revision_assets WHERE asset_id=$1',[file])).rows[0].n,1);
 if(stage==='in_review'){const receipt=(await fixture.pool.query('SELECT * FROM juyu.reviews WHERE document_id=$1 ORDER BY submitted_sequence DESC LIMIT 1',[d.id])).rows[0];assert.equal(receipt.status,'withdrawn');assert.equal(receipt.decided_by,'manager');assert.ok(receipt.decided_at);assert.equal(receipt.reason,null);}
 const event=(await service().availabilityDetail(d.id)).history[0];assert.equal(event.previousPublishedRevision,1);assert.equal(event.actorId,'manager');assert.equal(event.actorName,'Manager');assert.equal(event.action,action);assert.equal(event.sequence,sequence+1);assert.ok(event.at);assert.equal(await service(staff).article(d.id),null);await assert.rejects(service(staff).pdf(d.id,1),/NOT_FOUND/);assert.equal(await service(staff).asset(file),null);
 }
});
test('draft pending and approved unpublished documents can archive and pending review is withdrawn',async()=>{
 for(const stage of ['draft','in_review','approved'] as const){const d=stage==='draft'?await draft():stage==='in_review'?await pending():await approved(),sequence=stage==='draft'?0:stage==='in_review'?1:2;await service().changeAvailability(d.id,{expectedSequence:sequence,action:'archive'});assert.equal((await service().availabilityDetail(d.id)).history[0].previousPublishedRevision,null);assert.equal((await fixture.pool.query("SELECT count(*)::int n FROM juyu.reviews WHERE document_id=$1 AND status='in_review'",[d.id])).rows[0].n,0);}
});
test('unarchive restores an unpublished draft requiring a fresh independent review before republish',async()=>{
 for(const action of ['archive','unpublish'] as const){const d=await approved();await publish(d.id,2);await service().changeAvailability(d.id,{expectedSequence:4,action});let sequence=5;if(action==='archive'){await service().changeAvailability(d.id,{expectedSequence:5,action:'unarchive'});sequence=6;assert.equal((await service().availabilityDetail(d.id)).history[0].previousPublishedRevision,null);}const detail=await service().publicationDetail(d.id);assert.equal(detail.approval,null);assert.equal(detail.article.status,'draft');assert.equal(detail.canPublish||detail.canQueue,false);assert.equal(await service(staff).article(d.id),null);await assert.rejects(service().changePublication(d.id,{expectedSequence:sequence,action:'queue'}),/INVALID_STATE/);await assert.rejects(service().changePublication(d.id,{expectedSequence:3,action:'publish'}),/CONFLICT/);await service(a).submitReview(d.id,{expectedSequence:sequence,reviewerId:'b'});await service(b).decideReview(d.id,{expectedSequence:sequence+1,action:'approve'});await publish(d.id,sequence+2);assert.equal((await service(staff).article(d.id))?.body,'正式内容');}
});
test('pending uploads block archive and unpublish but quarantine never blocks unarchive recovery',async()=>{
 for(const action of ['archive','unpublish'] as const){const d=await approved();await publish(d.id,2);const aid=await asset(d.id,'image/png','pending'),before=await repo.getForManagement(d.id,a);await assert.rejects(service().changeAvailability(d.id,{expectedSequence:4,action}),/UPLOAD_IN_PROGRESS/);assert.deepEqual(await repo.getForManagement(d.id,a),before);await fixture.pool.query("UPDATE juyu.assets SET status='quarantined' WHERE id=$1",[aid]);await service().changeAvailability(d.id,{expectedSequence:4,action});if(action==='archive')await service().changeAvailability(d.id,{expectedSequence:5,action:'unarchive'});}
});
test('same actor exact concurrent retries acknowledge one immutable action and later changes conflict',async()=>{
 const d=await approved();await publish(d.id,2);let sequence=4;for(const action of ['unpublish','archive','unarchive'] as const){const input={expectedSequence:sequence,action},results=await Promise.all([service().changeAvailability(d.id,input),service().changeAvailability(d.id,input)]);assert.deepEqual(results[0],results[1]);const before=await repo.getForManagement(d.id,a);assert.deepEqual(await service().changeAvailability(d.id,input),results[0]);assert.deepEqual(await repo.getForManagement(d.id,a),before);await assert.rejects(service(c).changeAvailability(d.id,input),/CONFLICT/);sequence++;}assert.equal((await service().availabilityDetail(d.id)).history.length,3);await assert.rejects(service().changeAvailability(d.id,{expectedSequence:4,action:'unpublish'}),/CONFLICT/);await repo.execute(d.id,{type:'edit',title:'又一次编辑',body:'正文',audience:'staff'},a,{expectedSequence:sequence});await assert.rejects(service().changeAvailability(d.id,{expectedSequence:sequence-1,action:'unarchive'}),/CONFLICT/);
});
test('dedicated SQL command is closed to anonymous callers and lifecycle capabilities cannot be forged',async()=>{
 const d=await draft();assert.equal((await fixture.pool.query("SELECT EXISTS(SELECT 1 FROM pg_proc p CROSS JOIN LATERAL aclexplode(p.proacl) a WHERE p.oid='juyu.change_document_availability(text,text,integer)'::regprocedure AND a.grantee=0 AND a.privilege_type='EXECUTE') ok")).rows[0].ok,false);await assert.rejects(runtime.query('SELECT * FROM juyu.change_document_availability($1,$2,$3)',[d.id,'archive',0]),/FORBIDDEN/);await assert.rejects(db.run(staff,c=>c.query('SELECT * FROM juyu.change_document_availability($1,$2,$3)',[d.id,'archive',0])),/FORBIDDEN/);await assert.rejects(db.run(manager,c=>c.query("UPDATE juyu.documents SET lifecycle='archived' WHERE id=$1",[d.id])),/LIFECYCLE_COMMAND_REQUIRED/);await assert.rejects(db.run(manager,c=>c.query("INSERT INTO juyu.documents(id,kind,sequence,lifecycle,workflow_revision_id,workflow_state) VALUES($1,'article',0,'archived',1,'draft')",[randomUUID()])),/LIFECYCLE_COMMAND_REQUIRED/);await assert.rejects(db.run(manager,c=>c.query("INSERT INTO juyu.lifecycle_contexts VALUES(pg_backend_pid(),txid_current(),$1,'archive')",[d.id])),/permission denied/);await service().changeAvailability(d.id,{expectedSequence:0,action:'archive'});await assert.rejects(db.run(manager,c=>c.query("UPDATE juyu.documents SET lifecycle='active' WHERE id=$1",[d.id])),/LIFECYCLE_COMMAND_REQUIRED/);await assert.rejects(db.run(manager,c=>c.query("UPDATE juyu.audit_log SET previous_published_revision_id=1 WHERE document_id=$1",[d.id])),/permission denied|IMMUTABLE/);
});
test('audit failure rolls back lifecycle pointer pending review and workflow atomically',async()=>{
 for(const action of ['archive','unpublish','unarchive'] as const){const d=await approved();await publish(d.id,2);await repo.execute(d.id,{type:'edit',title:'当前草稿',body:'新正文',audience:'staff'},a,{expectedSequence:4});await service(a).submitReview(d.id,{expectedSequence:5,reviewerId:'b'});let sequence=6;if(action==='unarchive'){await service().changeAvailability(d.id,{expectedSequence:6,action:'archive'});sequence=7;}const before=await repo.getForManagement(d.id,a),reviews=(await fixture.pool.query('SELECT * FROM juyu.reviews WHERE document_id=$1 ORDER BY submitted_sequence',[d.id])).rows;await fixture.pool.query("CREATE FUNCTION juyu.fail_availability_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected availability failure'; END $$; CREATE TRIGGER fail_availability BEFORE INSERT ON juyu.audit_log FOR EACH ROW EXECUTE FUNCTION juyu.fail_availability_audit()");try{await assert.rejects(service().changeAvailability(d.id,{expectedSequence:sequence,action}),/injected availability failure/);assert.deepEqual(await repo.getForManagement(d.id,a),before);assert.deepEqual((await fixture.pool.query('SELECT * FROM juyu.reviews WHERE document_id=$1 ORDER BY submitted_sequence',[d.id])).rows,reviews);}finally{await fixture.pool.query('DROP TRIGGER fail_availability ON juyu.audit_log; DROP FUNCTION juyu.fail_availability_audit()');}}
});
test('availability read visibility changes only at commit across reader navigation search files PDF favorites and recent',async()=>{
 for(const action of ['archive','unpublish'] as const){const d=await approved();await publish(d.id,2);const aid=await asset(d.id,'application/pdf');await fixture.pool.query("INSERT INTO juyu.revision_assets(document_id,revision_id,asset_id,usage) VALUES($1,1,$2,'attachment')",[d.id,aid]);await fixture.pool.query("INSERT INTO juyu.favorites(member_id,document_id) VALUES('staff',$1);",[d.id]);await fixture.pool.query("INSERT INTO juyu.recent_views(member_id,document_id,revision_id) VALUES('staff',$1,1)",[d.id]);let ready!:()=>void,release!:()=>void;const reached=new Promise<void>(r=>ready=r),go=new Promise<void>(r=>release=r);const work=db.run(manager,async c=>{await c.query('SELECT * FROM juyu.change_document_availability($1,$2,$3)',[d.id,action,4]);ready();await go;});await reached;try{assert.ok(await service(staff).article(d.id));assert.ok(await service(staff).asset(aid));assert.ok(await service(staff).pdf(d.id,1));assert.equal((await service(staff).navigation()).some(x=>x.id===d.id),true);assert.equal((await db.run(staff,c=>c.query('SELECT 1 FROM juyu.favorites WHERE document_id=$1',[d.id]),true)).rowCount,1);}finally{release();}await work;assert.equal(await service(staff).article(d.id),null);assert.equal(await service(staff).asset(aid),null);await assert.rejects(service(staff).pdf(d.id,1),/NOT_FOUND/);assert.equal((await service(staff).navigation()).some(x=>x.id===d.id),false);assert.equal((await service(staff).search('审核管理')).pages.some(x=>x.id===d.id),false);for(const table of ['favorites','recent_views']){assert.equal((await db.run(staff,c=>c.query(`SELECT 1 FROM juyu.${table} WHERE document_id=$1`,[d.id]),true)).rowCount,0);assert.equal((await fixture.pool.query(`SELECT 1 FROM juyu.${table} WHERE document_id=$1`,[d.id])).rowCount,1);}}
});
test('availability serializes actual competing edit publication trash and other availability actions',async()=>{
 for(const rival of ['edit','publish','trash','availability'] as const){const d=await approved();await publish(d.id,2);await repo.execute(d.id,{type:'edit',title:'草稿',body:'新正文',audience:'staff'},a,{expectedSequence:4});await service(a).submitReview(d.id,{expectedSequence:5,reviewerId:'b'});await service(b).decideReview(d.id,{expectedSequence:6,action:'approve'});await service().changePublication(d.id,{expectedSequence:7,action:'queue'});const blocker=await fixture.pool.connect();await blocker.query('BEGIN');await blocker.query('SELECT id FROM juyu.documents WHERE id=$1 FOR UPDATE',[d.id]);const first=service().changeAvailability(d.id,{expectedSequence:8,action:'unpublish'});await waitForLock('SELECT%FROM juyu.change_document_availability%');const second=rival==='edit'?service(a).saveDraft(d.id,{expectedSequence:8,title:'竞争编辑',body:'JUYU_BLOCKNOTE_V1\n[]',kind:'article',audience:'staff',tags:[],cover:null}):rival==='publish'?service(c).changePublication(d.id,{expectedSequence:8,action:'publish'}):rival==='trash'?service(a).lifecycle(d.id,{expectedSequence:8,action:'trash'}):service(c).changeAvailability(d.id,{expectedSequence:8,action:'archive'});const work=Promise.allSettled([first,second]);try{await waitForLock(rival==='trash'?'SELECT * FROM juyu.change_document_lifecycle%':rival==='availability'?'SELECT%FROM juyu.change_document_availability%':'SELECT pg_advisory_xact_lock(hashtextextended%',rival==='availability'?2:1);}finally{await blocker.query('ROLLBACK');blocker.release();}const result=await work;assert.equal(result.filter(x=>x.status==='fulfilled').length,1);assert.match(String((result.find(x=>x.status==='rejected') as PromiseRejectedResult).reason),/CONFLICT|INACTIVE_DOCUMENT/);assert.equal((await service().availabilityDetail(d.id)).sequence,9);assert.equal((await service().availabilityDetail(d.id)).publishedRevision,null);}
});
test('actor role updates waiting during command are checked again and member operations exclude commands',async()=>{
 const d=await draft(),blocker=await fixture.pool.connect();await blocker.query('BEGIN');await blocker.query("UPDATE juyu.members SET observed_role='support' WHERE clerk_user_id='manager'");const work=service().changeAvailability(d.id,{expectedSequence:0,action:'archive'}).then(value=>({value,error:null}),error=>({value:null,error}));try{await waitForLock('SELECT%FROM juyu.change_document_availability%');}finally{await blocker.query('COMMIT');blocker.release();}try{assert.match((await work).error?.message??'unexpected success',/FORBIDDEN/);assert.equal((await service(a).availabilityDetail(d.id)).sequence,0);}finally{await restoreMember('manager');}const lock=await issuer.connect();await lock.query('SELECT pg_advisory_lock(84620915)');try{await assert.rejects(service().changeAvailability(d.id,{expectedSequence:0,action:'archive'}),/MEMBER_BUSY/);}finally{await lock.query('SELECT pg_advisory_unlock(84620915)');lock.release();}
});
test('history is last twenty events and archived pagination is stable clamped and only archived',async()=>{
 const d=await draft();for(let sequence=0;sequence<22;sequence++)await service().changeAvailability(d.id,{expectedSequence:sequence,action:sequence%2?'unarchive':'archive'});const detail=await service().availabilityDetail(d.id);assert.equal(detail.history.length,20);assert.equal(detail.historyMore,true);assert.equal(detail.history[0].sequence,22);assert.equal(detail.history.at(-1)?.sequence,3);for(let i=0;i<33;i++){const item=await draft();await service().changeAvailability(item.id,{expectedSequence:0,action:'archive'});}const first=await service().archives(),last=await service().archives(999);assert.equal(first.items.length,30);assert.equal(last.page,last.pages);assert.equal(last.total,first.total);assert.deepEqual((await service().archives()).items,first.items);assert.equal(new Set([...first.items,...last.items].map(x=>x.documentId)).size,first.items.length+last.items.length);for(const item of [...first.items,...last.items]){assert.deepEqual(Object.keys(item).sort(),['documentId','revision','sequence','title']);assert.equal((await service().availabilityDetail(item.documentId)).lifecycle,'archived');}
});
test('published editor saves a new draft while old reader stays available through review and queue until manual publication',async()=>{
 const d=await approved();await publish(d.id,2);const saved=await service(a).saveDraft(d.id,{expectedSequence:4,title:'下一正式标题',body:'JUYU_BLOCKNOTE_V1\n[]',kind:'article',audience:'staff',tags:[],cover:null});assert.equal(saved.sequence,5);assert.equal(saved.status,'draft');assert.equal(saved.publishedRevision,1);assert.equal((await service(staff).article(d.id))?.title,'审核管理');assert.equal((await service(staff).article(d.id))?.revision_id,1);await service(a).submitReview(d.id,{expectedSequence:5,reviewerId:'b'});assert.equal((await service(staff).article(d.id))?.title,'审核管理');await service(b).decideReview(d.id,{expectedSequence:6,action:'approve'});assert.equal((await service(staff).article(d.id))?.title,'审核管理');await service().changePublication(d.id,{expectedSequence:7,action:'queue'});assert.equal((await service(staff).article(d.id))?.title,'审核管理');await service().changePublication(d.id,{expectedSequence:8,action:'publish'});assert.equal((await service(staff).article(d.id))?.title,'下一正式标题');assert.equal((await service(staff).article(d.id))?.revision_id,2);
});
test('retry rejects an unexpected later audit even when current workflow fields still match',async()=>{
 const d=await draft(),input={expectedSequence:0,action:'archive'};await service().changeAvailability(d.id,input);
 // Simulate extra evidence independent of the document pointer: a retry must use
 // the actual latest event instead of acknowledging an older matching event.
 await fixture.pool.query("INSERT INTO juyu.audit_log(document_id,sequence,action,actor_id,revision_id,at) VALUES($1,2,'edit','a',1,clock_timestamp())",[d.id]);
 await assert.rejects(service().changeAvailability(d.id,input),/CONFLICT/);
});
