import assert from 'node:assert/strict';
import {before,after,test} from 'node:test';
import {randomBytes,randomUUID} from 'node:crypto';
import type {Pool} from 'pg';
import {temporaryDatabase} from './fixture.ts';
import {migrate} from '../../src/server/database/migrate.ts';
import {ScopedDatabase} from '../../src/server/database/scoped.ts';
import {DocumentRepository} from '../../src/server/database/repository.ts';
import {AuthorizationService} from '../../src/server/authorization/service.ts';
import type {Viewer} from '../../src/domain/model.ts';
let fixture:Awaited<ReturnType<typeof temporaryDatabase>>,runtime:Pool,issuer:Pool,db:ScopedDatabase,repo:DocumentRepository;
const a:Viewer={id:'a',role:'admin',companyVerified:true},b:Viewer={...a,id:'b'},c:Viewer={...a,id:'c'},manager:Viewer={...a,id:'manager'},staff:Viewer={id:'staff',role:'support',companyVerified:true};
const service=(v:Viewer|null=manager)=>new AuthorizationService(db,async()=>v);
async function draft(){return repo.create({id:randomUUID(),kind:'article',title:'审核管理',body:'正式内容',audience:'staff'},a);}
async function pending(){const d=await draft();await service(a).submitReview(d.id,{expectedSequence:0,reviewerId:'b'});return d;}
async function receipt(id:string){return (await fixture.pool.query('SELECT * FROM juyu.reviews WHERE document_id=$1 ORDER BY submitted_sequence DESC LIMIT 1',[id])).rows[0];}
async function restoreMember(id:string){await fixture.pool.query("UPDATE juyu.members SET disabled_at=null,observed_role='admin',verified_email=$2,observed_at=now() WHERE clerk_user_id=$1",[id,`${id}@example.test`]);}
before(async()=>{fixture=await temporaryDatabase();await migrate(fixture.pool);await fixture.pool.query("INSERT INTO juyu.members(clerk_user_id,display_name,observed_role,verified_email,observed_at) VALUES('a','A','admin','a@example.test',now()),('b','B','admin','b@example.test',now()),('c','C','admin','c@example.test',now()),('manager','Manager','admin','manager@example.test',now()),('staff','Support','support','staff@example.test',now())");const rp=randomBytes(24).toString('hex'),ip=randomBytes(24).toString('hex');await fixture.pool.query(`CREATE ROLE control_runtime LOGIN PASSWORD '${rp}' IN ROLE juyu_runtime; CREATE ROLE control_issuer LOGIN PASSWORD '${ip}' IN ROLE juyu_context_issuer`);runtime=fixture.connectAs('control_runtime',rp);issuer=fixture.connectAs('control_issuer',ip);db=new ScopedDatabase(runtime,issuer);repo=new DocumentRepository(db);});
after(async()=>{if(runtime)await runtime.end();if(issuer)await issuer.end();if(fixture)await fixture.close();});
test('any eligible Admin can reassign while preserving revision, original submitter and immutable audit',async()=>{
 const d=await pending();assert.equal(typeof service().controlReviewDetail,'function');const before=await receipt(d.id),detail=await service().controlReviewDetail(d.id);
 assert.equal(detail.canManageReview,true);assert.equal(detail.reviewerAvailable,true);assert.equal(detail.reviewerName,'B');assert.deepEqual(detail.reviewers,[{id:'c',name:'C'}]);assert.deepEqual(detail.history,[]);
 const ack=await service().changeReviewControl(d.id,{expectedSequence:1,action:'reassign',reviewerId:'c'});assert.deepEqual(ack,{documentId:d.id,sequence:2,revision:1,action:'reassign',status:'in_review',previousReviewerId:'b',reviewerId:'c'});
 const saved=await service().controlReviewDetail(d.id),r=await receipt(d.id);assert.equal(saved.submittedBy,'a');assert.equal(saved.revision,1);assert.equal(saved.history.length,1);assert.deepEqual({...saved.history[0],at:'time'},{sequence:2,revision:1,action:'reassign',actorId:'manager',actorName:'Manager',previousReviewerId:'b',previousReviewerName:'B',reviewerId:'c',reviewerName:'C',at:'time'});assert.equal(r.submitted_by,'a');assert.equal(r.submitted_sequence,before.submitted_sequence);assert.deepEqual(r.submitted_at,before.submitted_at);
 assert.equal((await service(b).reviewDetail(d.id)).canDecide,false);assert.equal((await service(c).reviewDetail(d.id)).canDecide,true);await assert.rejects(service(b).decideReview(d.id,{expectedSequence:1,action:'approve'}),/CONFLICT/);await assert.rejects(service(b).decideReview(d.id,{expectedSequence:2,action:'approve'}),/NOT_REVIEWER/);
});
test('withdraw returns the same revision to editable draft and later resubmission has a new receipt',async()=>{
 const d=await pending();const ack=await service().changeReviewControl(d.id,{expectedSequence:1,action:'withdraw'});assert.deepEqual(ack,{documentId:d.id,sequence:2,revision:1,action:'withdraw',status:'draft',previousReviewerId:'b',reviewerId:null});const detail=await service().controlReviewDetail(d.id);assert.equal(detail.submittedBy,null);assert.equal(detail.reviewerId,null);assert.equal(detail.reviewerName,null);assert.equal(detail.reviewerAvailable,false);assert.equal(detail.canManageReview,false);assert.equal((await receipt(d.id)).status,'withdrawn');
 await repo.execute(d.id,{type:'edit',title:'补充',body:'新正文',audience:'staff'},a,{expectedSequence:2});await service(a).submitReview(d.id,{expectedSequence:3,reviewerId:'c'});assert.equal((await service(c).reviewDetail(d.id)).canDecide,true);assert.equal((await receipt(d.id)).revision_id,2);assert.equal((await service().controlReviewDetail(d.id)).history[0].revision,1);
});
test('disabled, demoted and pending old reviewers can be replaced or withdrawn by another Admin',async()=>{
 for(const update of ["disabled_at=now()","observed_role='support'","verified_email=null","observed_at=null"]){const d=await pending();await fixture.pool.query(`UPDATE juyu.members SET ${update} WHERE clerk_user_id='b'`);try{const detail=await service().controlReviewDetail(d.id);assert.equal(detail.reviewerAvailable,false);assert.equal(detail.canManageReview,true);await service().changeReviewControl(d.id,{expectedSequence:1,action:'reassign',reviewerId:'c'});assert.equal((await service(c).reviewDetail(d.id)).canDecide,true);}finally{await restoreMember('b');}}
 for(const action of ['withdraw','reassign']){const d=await pending();const op=(await fixture.pool.query("INSERT INTO juyu.member_operations(actor_id,target_id,kind,requested_role) VALUES('a','b','role','support') RETURNING id")).rows[0].id;try{assert.equal((await service().controlReviewDetail(d.id)).reviewerAvailable,false);await service().changeReviewControl(d.id,{expectedSequence:1,action,...(action==='reassign'?{reviewerId:'c'}:{})});}finally{await fixture.pool.query("UPDATE juyu.member_operations SET status='conflict',finished_at=now() WHERE id=$1",[op]);}}
});
test('control rejects unauthorized or stale Admin identity on both reads and writes',async()=>{
 const d=await pending();for(const actor of [null,staff,{...manager,companyVerified:false}]){await assert.rejects(service(actor).controlReviewDetail(d.id),/FORBIDDEN/);await assert.rejects(service(actor).changeReviewControl(d.id,{expectedSequence:1,action:'withdraw'}),/FORBIDDEN/);}
 for(const update of ["disabled_at=now()","observed_role='support'","verified_email=null","observed_at=null"]){await fixture.pool.query(`UPDATE juyu.members SET ${update} WHERE clerk_user_id='manager'`);try{await assert.rejects(service().controlReviewDetail(d.id),/FORBIDDEN/);await assert.rejects(service().changeReviewControl(d.id,{expectedSequence:1,action:'withdraw'}),/FORBIDDEN/);}finally{await restoreMember('manager');}}
 await fixture.pool.query("INSERT INTO juyu.role_enrollments(member_id,requested_role,purpose) VALUES('manager','support','default')");try{await assert.rejects(service().controlReviewDetail(d.id),/FORBIDDEN/);await assert.rejects(service().changeReviewControl(d.id,{expectedSequence:1,action:'withdraw'}),/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.role_enrollments SET state='complete',confirmed_at=now() WHERE member_id='manager'");}
});
test('target must be eligible and independent of actor, original submitter, author, editor and current reviewer',async()=>{
 const d=await draft();await repo.execute(d.id,{type:'edit',title:'编辑版',body:'内容',audience:'staff'},c,{expectedSequence:0});await service(a).submitReview(d.id,{expectedSequence:1,reviewerId:'b'});
 for(const id of ['a','b','c','manager','staff','missing'])await assert.rejects(service().changeReviewControl(d.id,{expectedSequence:2,action:'reassign',reviewerId:id}),/INVALID_REVIEWER/);
 const target='candidate';await fixture.pool.query("INSERT INTO juyu.members(clerk_user_id,display_name,observed_role,verified_email,observed_at) VALUES($1,'Candidate','admin','candidate@example.test',now())",[target]);
 for(const update of ["disabled_at=now()","observed_role='support'","verified_email=null","observed_at=null"]){await fixture.pool.query(`UPDATE juyu.members SET ${update} WHERE clerk_user_id='candidate'`);try{assert.ok(!(await service().controlReviewDetail(d.id)).reviewers.some(x=>x.id===target));await assert.rejects(service().changeReviewControl(d.id,{expectedSequence:2,action:'reassign',reviewerId:target}),/INVALID_REVIEWER/);}finally{await restoreMember(target);}}
 const op=(await fixture.pool.query("INSERT INTO juyu.member_operations(actor_id,target_id,kind,requested_role) VALUES('a','candidate','role','support') RETURNING id")).rows[0].id;try{await assert.rejects(service().changeReviewControl(d.id,{expectedSequence:2,action:'reassign',reviewerId:target}),/INVALID_REVIEWER/);}finally{await fixture.pool.query("UPDATE juyu.member_operations SET status='conflict',finished_at=now() WHERE id=$1",[op]);}
 await fixture.pool.query("INSERT INTO juyu.role_enrollments(member_id,requested_role,purpose) VALUES('candidate','support','default')");try{await assert.rejects(service().changeReviewControl(d.id,{expectedSequence:2,action:'reassign',reviewerId:target}),/INVALID_REVIEWER/);}finally{await fixture.pool.query("UPDATE juyu.role_enrollments SET state='complete',confirmed_at=now() WHERE member_id='candidate'");}
 assert.equal((await service().editor(d.id)).sequence,2);
});
test('malformed inputs, stale sequence, inactive documents and unsubmitted workflows fail without mutation',async()=>{
 const d=await pending();for(const input of [null,[],{}, {expectedSequence:1,action:'approve'},{expectedSequence:'1',action:'withdraw'},{expectedSequence:-1,action:'withdraw'},{expectedSequence:2147483647,action:'withdraw'},{expectedSequence:1,action:'withdraw',reviewerId:'c'},{expectedSequence:1,action:'reassign'},{expectedSequence:1,action:'reassign',reviewerId:null},{expectedSequence:1,action:'reassign',reviewerId:' c'},{expectedSequence:1,action:'withdraw',reason:'x'}])await assert.rejects(service().changeReviewControl(d.id,input),/INVALID_INPUT/);
 await assert.rejects(service().changeReviewControl(d.id,{expectedSequence:0,action:'withdraw'}),/CONFLICT/);await assert.rejects(service().controlReviewDetail(randomUUID()),/NOT_FOUND/);await assert.rejects(service().changeReviewControl(randomUUID(),{expectedSequence:1,action:'withdraw'}),/NOT_FOUND/);await assert.rejects(service().controlReviewDetail(d.id,' bad'),/INVALID_INPUT/);
 const fresh=await draft();assert.equal((await service().controlReviewDetail(fresh.id)).canManageReview,false);await assert.rejects(service().changeReviewControl(fresh.id,{expectedSequence:0,action:'withdraw'}),/INVALID_STATE/);await service(a).lifecycle(d.id,{expectedSequence:1,action:'trash'});assert.equal((await service().controlReviewDetail(d.id)).canManageReview,false);await assert.rejects(service().changeReviewControl(d.id,{expectedSequence:2,action:'withdraw'}),/INACTIVE_DOCUMENT/);
});
test('exact concurrent retries return one acknowledgement and changed actor, target or later state cannot replay',async()=>{
 for(const action of ['withdraw','reassign']){const d=await pending(),input={expectedSequence:1,action,...(action==='reassign'?{reviewerId:'c'}:{})};const results=await Promise.all([service().changeReviewControl(d.id,input),service().changeReviewControl(d.id,input)]);assert.deepEqual(results[0],results[1]);assert.equal((await service().controlReviewDetail(d.id)).history.length,1);
 await assert.rejects(service(a).changeReviewControl(d.id,input),/CONFLICT/);await assert.rejects(service().changeReviewControl(d.id,{expectedSequence:1,action:'reassign',reviewerId:'candidate'}),/CONFLICT/);
 if(action==='reassign'){await fixture.pool.query("UPDATE juyu.members SET disabled_at=now() WHERE clerk_user_id='c'");try{assert.deepEqual(await service().changeReviewControl(d.id,input),results[0]);}finally{await restoreMember('c');}await service(c).decideReview(d.id,{expectedSequence:2,action:'approve'});}else await repo.execute(d.id,{type:'edit',title:'新',body:'新',audience:'staff'},a,{expectedSequence:2});
 await assert.rejects(service().changeReviewControl(d.id,input),/CONFLICT/);}
});
test('both control actions preserve the existing employee publication and published revision',async()=>{
 for(const action of ['withdraw','reassign']){let d=await draft();for(const type of ['submit','approve','queue','publish'] as const)d=await repo.execute(d.id,{type},type==='approve'?b:a,{expectedSequence:d.sequence,reviewer:b});d=await repo.execute(d.id,{type:'edit',title:'新草稿',body:'不能发布',audience:'staff'},a,{expectedSequence:d.sequence});await service(a).submitReview(d.id,{expectedSequence:d.sequence,reviewerId:'b'});await service().changeReviewControl(d.id,{expectedSequence:d.sequence+1,action,...(action==='reassign'?{reviewerId:'c'}:{})});assert.equal((await service(staff).article(d.id))?.body,'正式内容');assert.equal((await service().controlReviewDetail(d.id)).publishedRevision,1);}
});
test('audit failure rolls back workflow and review receipt together',async()=>{
 const d=await pending(),before=await repo.getForManagement(d.id,a),r=await receipt(d.id);await fixture.pool.query("CREATE FUNCTION juyu.fail_control_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected control failure'; END $$; CREATE TRIGGER fail_control BEFORE INSERT ON juyu.audit_log FOR EACH ROW EXECUTE FUNCTION juyu.fail_control_audit()");try{for(const action of ['withdraw','reassign']){await assert.rejects(service().changeReviewControl(d.id,{expectedSequence:1,action,...(action==='reassign'?{reviewerId:'c'}:{})}),/injected control failure/);assert.deepEqual(await repo.getForManagement(d.id,a),before);assert.deepEqual(await receipt(d.id),r);}}finally{await fixture.pool.query('DROP TRIGGER fail_control ON juyu.audit_log; DROP FUNCTION juyu.fail_control_audit()');}
});
async function waitForLock(query:string,count=1){const deadline=Date.now()+3000;let n=0;while(Date.now()<deadline){n=(await fixture.pool.query("SELECT count(*)::int AS n FROM pg_stat_activity WHERE wait_event_type='Lock' AND query LIKE $1",[query])).rows[0].n;if(n>=count)break;await new Promise(r=>setTimeout(r,5));}assert.equal(n,count,'independent real DB connections must overlap');}
test('control competes atomically with approve, reject and another control on real DB locks',async()=>{
 for(const rival of ['approve','reject','withdraw','reassign'] as const){const d=await pending(),blocker=await fixture.pool.connect();await blocker.query('BEGIN');await blocker.query('SELECT id FROM juyu.documents WHERE id=$1 FOR UPDATE',[d.id]);const second=rival==='approve'||rival==='reject'?service(b).decideReview(d.id,{expectedSequence:1,action:rival,...(rival==='reject'?{reason:'补证据'}:{})}):service(a).changeReviewControl(d.id,{expectedSequence:1,action:rival,...(rival==='reassign'?{reviewerId:'c'}:{})});const work=Promise.allSettled([service().changeReviewControl(d.id,{expectedSequence:1,action:'withdraw'}),second]);try{await waitForLock('SELECT id FROM juyu.documents%');await waitForLock('SELECT pg_advisory_xact_lock(hashtextextended%');}finally{await blocker.query('ROLLBACK');blocker.release();}const results=await work;assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.match(String((results.find(x=>x.status==='rejected') as PromiseRejectedResult).reason),/CONFLICT/);assert.equal((await service().editor(d.id)).sequence,2);}
});
test('actor and candidate demotions committed while control waits are rechecked after row locking',async()=>{
 for(const target of ['manager','c']){const d=await pending(),blocker=await fixture.pool.connect();await blocker.query('BEGIN');await blocker.query("UPDATE juyu.members SET observed_role='support' WHERE clerk_user_id=$1",[target]);const work=service().changeReviewControl(d.id,{expectedSequence:1,action:'reassign',reviewerId:'c'}).then(value=>({value,error:null}),error=>({value:null,error}));try{await waitForLock('SELECT clerk_user_id FROM juyu.members%');}finally{await blocker.query('COMMIT');blocker.release();}try{assert.match((await work).error?.message??'unexpected success',target==='manager'?/FORBIDDEN/:/INVALID_REVIEWER/);assert.equal((await service(a).editor(d.id)).sequence,1);}finally{await restoreMember(target);}}
});
test('exclusive member-management operations cause explicit retryable busy control response',async()=>{
 const d=await pending(),lock=await issuer.connect();await lock.query('SELECT pg_advisory_lock(84620915)');try{await assert.rejects(service().changeReviewControl(d.id,{expectedSequence:1,action:'withdraw'}),/MEMBER_BUSY/);}finally{await lock.query('SELECT pg_advisory_unlock(84620915)');lock.release();}
});
test('candidate pages have no omissions and only the most recent 20 immutable control events are returned',async()=>{
 const d=await pending();await fixture.pool.query("INSERT INTO juyu.members(clerk_user_id,display_name,observed_role,verified_email,observed_at) SELECT 'page_'||lpad(i::text,2,'0'),'Page '||i,'admin','page'||i||'@example.test',now() FROM generate_series(1,65) i");let after='';const ids:string[]=[];do{const detail=await service().controlReviewDetail(d.id,after);assert.ok(detail.reviewers.length<=30);ids.push(...detail.reviewers.map(x=>x.id));after=detail.nextCursor??'';}while(after);assert.equal(ids.length,67);assert.equal(new Set(ids).size,67);assert.ok(!ids.some(id=>['a','b','manager','staff'].includes(id)));
 for(let index=0;index<22;index++)await service().changeReviewControl(d.id,{expectedSequence:index+1,action:'reassign',reviewerId:index%2===0?'c':'b'});const detail=await service().controlReviewDetail(d.id);assert.equal(detail.history.length,20);assert.equal(detail.historyMore,true);assert.equal(detail.history[0].sequence,23);assert.equal(detail.history.at(-1)?.sequence,4);assert.equal((await fixture.pool.query("SELECT count(*)::int AS n FROM juyu.audit_log WHERE document_id=$1 AND action='reassign'",[d.id])).rows[0].n,22);
 await assert.rejects(db.run(manager,c=>c.query("UPDATE juyu.audit_log SET reviewer_id='manager' WHERE document_id=$1",[d.id])),/permission denied/);
});
