import assert from 'node:assert/strict';
import {before,after,test} from 'node:test';
import {randomBytes,randomUUID} from 'node:crypto';
import type {Pool} from 'pg';
import {temporaryDatabase} from './fixture.ts';
import {migrate} from '../../src/server/database/migrate.ts';
import {ScopedDatabase} from '../../src/server/database/scoped.ts';
import {DocumentRepository} from '../../src/server/database/repository.ts';
import {AuthorizationService} from '../../src/server/authorization/service.ts';
import type {Viewer} from '../../src/domain/model.ts';
let fixture:Awaited<ReturnType<typeof temporaryDatabase>>,runtime:Pool,issuer:Pool,db:ScopedDatabase,repo:DocumentRepository;
const a:Viewer={id:'a',role:'admin',companyVerified:true},b:Viewer={...a,id:'b'},c:Viewer={...a,id:'c'},staff:Viewer={id:'staff',role:'support',companyVerified:true};
const service=(v:Viewer|null=b)=>new AuthorizationService(db,async()=>v);
async function draft(){return repo.create({id:randomUUID(),kind:'article',title:'二审资料',body:'正式内容',audience:'staff'},a);}
async function pending(){const d=await draft();await service(a).submitReview(d.id,{expectedSequence:0,reviewerId:'b'});return d;}
async function counts(id:string){return (await fixture.pool.query("SELECT (SELECT count(*)::int FROM juyu.reviews WHERE document_id=$1) AS reviews,(SELECT count(*)::int FROM juyu.audit_log WHERE document_id=$1 AND action IN ('approve','reject')) AS decisions",[id])).rows[0];}
before(async()=>{fixture=await temporaryDatabase();await migrate(fixture.pool);await fixture.pool.query("INSERT INTO juyu.members(clerk_user_id,display_name,observed_role,verified_email,observed_at) VALUES('a','A','admin','a@example.test',now()),('b','B','admin','b@example.test',now()),('c','C','admin','c@example.test',now()),('staff','Support','support','staff@example.test',now())");const rp=randomBytes(24).toString('hex'),ip=randomBytes(24).toString('hex');await fixture.pool.query(`CREATE ROLE decision_runtime LOGIN PASSWORD '${rp}' IN ROLE juyu_runtime; CREATE ROLE decision_issuer LOGIN PASSWORD '${ip}' IN ROLE juyu_context_issuer`);runtime=fixture.connectAs('decision_runtime',rp);issuer=fixture.connectAs('decision_issuer',ip);db=new ScopedDatabase(runtime,issuer);repo=new DocumentRepository(db);});
after(async()=>{if(runtime)await runtime.end();if(issuer)await issuer.end();if(fixture)await fixture.close();});
test('review detail exposes saved current content and only the assigned independent Admin can approve',async()=>{
 const d=await pending();assert.equal(typeof service().reviewDetail,'function');
 const detail=await service().reviewDetail(d.id);assert.equal(detail.article.body,'正式内容');assert.equal(detail.article.sequence,1);assert.equal(detail.canDecide,true);assert.equal(detail.review?.revision,1);assert.equal(detail.review?.reviewerName,'B');assert.equal(detail.review?.status,'in_review');assert.equal(detail.review?.decidedAt,null);assert.equal((await service(c).reviewDetail(d.id)).canDecide,false);
 for(const actor of [a,c])await assert.rejects(service(actor).decideReview(d.id,{expectedSequence:1,action:'approve'}),/NOT_REVIEWER/);
 const ack=await service().decideReview(d.id,{expectedSequence:1,action:'approve'});assert.deepEqual(ack,{documentId:d.id,sequence:2,revision:1,status:'approved',action:'approve',reason:null,reviewerId:'b'});
 const saved=await service().reviewDetail(d.id);assert.equal(saved.canDecide,false);assert.equal(saved.article.status,'approved');assert.equal(saved.review?.status,'approved');assert.ok(saved.review?.decidedAt);assert.equal(saved.article.publishedRevision,null);assert.deepEqual(await counts(d.id),{reviews:1,decisions:1});
});
test('rejection requires a bounded reason and exposes the normalized result without approving',async()=>{
 const d=await pending();for(const reason of [undefined,'','   '])await assert.rejects(service().decideReview(d.id,{expectedSequence:1,action:'reject',...(reason===undefined?{}:{reason})}),/REASON_REQUIRED/);
 for(const input of [null,[],{}, {expectedSequence:1,action:'publish'},{expectedSequence:'1',action:'approve'},{expectedSequence:-1,action:'approve'},{expectedSequence:2147483647,action:'approve'},{expectedSequence:1,action:'approve',reviewerId:'b'},{expectedSequence:1,action:'reject',reason:5},{expectedSequence:1,action:'reject',reason:'x'.repeat(2001)},{expectedSequence:1,action:'approve',reason:'hidden'}])await assert.rejects(service().decideReview(d.id,input),/INVALID_INPUT/);
 const ack=await service().decideReview(d.id,{expectedSequence:1,action:'reject',reason:'  补充来源  '});assert.equal(ack.reason,'补充来源');assert.equal(ack.status,'changes_requested');const detail=await service(a).reviewDetail(d.id);assert.equal(detail.review?.reason,'补充来源');assert.equal(detail.review?.status,'rejected');assert.equal(detail.article.status,'changes_requested');assert.equal(detail.canDecide,false);assert.deepEqual(await counts(d.id),{reviews:1,decisions:1});
});
test('detail and decision reject absent, support, unverified, disabled, stale and pending current actors',async()=>{
 const d=await pending();for(const actor of [null,staff,{...b,companyVerified:false}]){await assert.rejects(service(actor).reviewDetail(d.id),/FORBIDDEN/);await assert.rejects(service(actor).decideReview(d.id,{expectedSequence:1,action:'approve'}),/FORBIDDEN/);}
 for(const update of ["disabled_at=now()","observed_role='support'","verified_email=null","observed_at=null"]){await fixture.pool.query(`UPDATE juyu.members SET ${update} WHERE clerk_user_id='b'`);try{await assert.rejects(service().reviewDetail(d.id),/FORBIDDEN/);await assert.rejects(service().decideReview(d.id,{expectedSequence:1,action:'approve'}),/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.members SET disabled_at=null,observed_role='admin',verified_email='b@example.test',observed_at=now() WHERE clerk_user_id='b'");}}
 const op=(await fixture.pool.query("INSERT INTO juyu.member_operations(actor_id,target_id,kind,requested_role) VALUES('a','b','role','support') RETURNING id")).rows[0].id;try{await assert.rejects(service().reviewDetail(d.id),/FORBIDDEN/);await assert.rejects(service().decideReview(d.id,{expectedSequence:1,action:'approve'}),/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.member_operations SET status='conflict',finished_at=now() WHERE id=$1",[op]);}assert.equal((await service(a).editor(d.id)).sequence,1);
});
test('exact decision retries acknowledge once while changed action, reason, sequence or actor cannot replay',async()=>{
 const d=await pending(),input={expectedSequence:1,action:'reject',reason:'补来源'};const results=await Promise.all([service().decideReview(d.id,input),service().decideReview(d.id,{...input,reason:' 补来源 '})]);assert.deepEqual(results[0],results[1]);
 for(const changed of [{...input,reason:'另一原因'},{expectedSequence:1,action:'approve'},{...input,expectedSequence:0},{...input,expectedSequence:2}])await assert.rejects(service().decideReview(d.id,changed),/CONFLICT|INVALID_STATE/);
 await assert.rejects(service(c).decideReview(d.id,input),/CONFLICT|NOT_REVIEWER/);assert.deepEqual(await counts(d.id),{reviews:1,decisions:1});
 await repo.execute(d.id,{type:'edit',title:'改后',body:'改后正文',audience:'staff'},a,{expectedSequence:2});await assert.rejects(service().decideReview(d.id,input),/CONFLICT/);
});
test('rejection must be edited before resubmission and old reasons remain labeled with their revision',async()=>{
 const d=await pending();await service().decideReview(d.id,{expectedSequence:1,action:'reject',reason:'补来源'});await assert.rejects(service(a).submitReview(d.id,{expectedSequence:2,reviewerId:'c'}),/EDIT_REQUIRED/);
 await repo.execute(d.id,{type:'edit',title:'改后',body:'带来源',audience:'staff'},a,{expectedSequence:2});const edited=await service(a).reviewDetail(d.id);assert.equal(edited.article.body,'带来源');assert.equal(edited.article.status,'draft');assert.equal(edited.review?.revision,1);assert.equal(edited.review?.reason,'补来源');assert.equal(edited.canDecide,false);
 const submit=await service(a).submitReview(d.id,{expectedSequence:3,reviewerId:'c'});assert.equal(submit.revision,2);assert.equal((await service(c).reviewDetail(d.id)).canDecide,true);assert.equal((await service(c).reviewDetail(d.id)).review?.reason,null);await service(c).decideReview(d.id,{expectedSequence:4,action:'approve'});assert.deepEqual(await counts(d.id),{reviews:2,decisions:2});
});
test('approval and rejection both leave the existing employee publication untouched',async()=>{
 for(const action of ['approve','reject'] as const){let d=await draft();for(const type of ['submit','approve','queue','publish'] as const)d=await repo.execute(d.id,{type},type==='approve'?b:a,{expectedSequence:d.sequence,reviewer:b});d=await repo.execute(d.id,{type:'edit',title:'未发布',body:'新的正文',audience:'staff'},a,{expectedSequence:d.sequence});await service(a).submitReview(d.id,{expectedSequence:d.sequence,reviewerId:'b'});await service().decideReview(d.id,{expectedSequence:d.sequence+1,action,...(action==='reject'?{reason:'补内容'}:{})});assert.equal((await service(staff).article(d.id))?.body,'正式内容');assert.equal((await service().reviewDetail(d.id)).article.publishedRevision,1);}
});
test('stale, missing and inactive documents cannot decide and unsubmitted detail is safe',async()=>{
 const d=await draft();const detail=await service().reviewDetail(d.id);assert.equal(detail.review,null);assert.equal(detail.canDecide,false);await assert.rejects(service().decideReview(d.id,{expectedSequence:0,action:'approve'}),/INVALID_STATE/);await assert.rejects(service().reviewDetail(randomUUID()),/NOT_FOUND/);await assert.rejects(service().decideReview(randomUUID(),{expectedSequence:0,action:'approve'}),/NOT_FOUND/);
 await service(a).submitReview(d.id,{expectedSequence:0,reviewerId:'b'});await assert.rejects(service().decideReview(d.id,{expectedSequence:0,action:'approve'}),/CONFLICT/);await service(a).lifecycle(d.id,{action:'trash',expectedSequence:1});assert.equal((await service().reviewDetail(d.id)).canDecide,false);await assert.rejects(service().decideReview(d.id,{expectedSequence:2,action:'approve'}),/INACTIVE_DOCUMENT/);
});
test('an audit failure rolls back the decision, review receipt and workflow atomically',async()=>{
 const d=await pending(),before=await repo.getForManagement(d.id,a);await fixture.pool.query("CREATE FUNCTION juyu.fail_decision_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected decision failure'; END $$; CREATE TRIGGER fail_decision BEFORE INSERT ON juyu.audit_log FOR EACH ROW EXECUTE FUNCTION juyu.fail_decision_audit()");try{await assert.rejects(service().decideReview(d.id,{expectedSequence:1,action:'approve'}),/injected decision failure/);assert.deepEqual(await repo.getForManagement(d.id,a),before);assert.equal((await service().reviewDetail(d.id)).review?.status,'in_review');assert.deepEqual(await counts(d.id),{reviews:1,decisions:0});}finally{await fixture.pool.query('DROP TRIGGER fail_decision ON juyu.audit_log; DROP FUNCTION juyu.fail_decision_audit()');}
});
async function waitForLock(query:string,count=1){const deadline=Date.now()+3000;let n=0;while(Date.now()<deadline){n=(await fixture.pool.query("SELECT count(*)::int AS n FROM pg_stat_activity WHERE wait_event_type='Lock' AND query LIKE $1",[query])).rows[0].n;if(n>=count)break;await new Promise(r=>setTimeout(r,5));}assert.equal(n,count,'independent real DB connections must overlap');}
test('competing approve and reject overlap on the real document lock with one committed winner',async()=>{
 const d=await pending(),blocker=await fixture.pool.connect();await blocker.query('BEGIN');await blocker.query('SELECT id FROM juyu.documents WHERE id=$1 FOR UPDATE',[d.id]);const work=Promise.allSettled([service().decideReview(d.id,{expectedSequence:1,action:'approve'}),service().decideReview(d.id,{expectedSequence:1,action:'reject',reason:'补来源'})]);try{await waitForLock('SELECT id FROM juyu.documents%');await waitForLock('SELECT pg_advisory_xact_lock(hashtextextended%');}finally{await blocker.query('ROLLBACK');blocker.release();}const results=await work;assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.match(String((results.find(x=>x.status==='rejected') as PromiseRejectedResult).reason),/CONFLICT/);assert.deepEqual(await counts(d.id),{reviews:1,decisions:1});
});
test('a reviewer downgraded while the decision waits fails fresh eligibility after locking',async()=>{
 const d=await pending(),blocker=await fixture.pool.connect();await blocker.query('BEGIN');await blocker.query("UPDATE juyu.members SET observed_role='support' WHERE clerk_user_id='b'");const work=service().decideReview(d.id,{expectedSequence:1,action:'approve'}).then(value=>({value,error:null}),error=>({value:null,error}));try{await waitForLock('SELECT clerk_user_id FROM juyu.members%');}finally{await blocker.query('COMMIT');blocker.release();}try{assert.match((await work).error?.message??'unexpected success',/FORBIDDEN/);assert.equal((await service(a).editor(d.id)).sequence,1);}finally{await fixture.pool.query("UPDATE juyu.members SET observed_role='admin' WHERE clerk_user_id='b'");}
});
test('pending member operations exclude decisions and a submitted save cannot race across approval',async()=>{
 const d=await pending(),lock=await issuer.connect();await lock.query('SELECT pg_advisory_lock(84620915)');try{await assert.rejects(service().decideReview(d.id,{expectedSequence:1,action:'approve'}),/MEMBER_BUSY/);}finally{await lock.query('SELECT pg_advisory_unlock(84620915)');lock.release();}
 const blocker=await fixture.pool.connect();await blocker.query('BEGIN');await blocker.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`editor:${d.id}`]);const work=Promise.allSettled([service().decideReview(d.id,{expectedSequence:1,action:'approve'}),service(a).saveDraft(d.id,{expectedSequence:1,title:'覆盖',body:'JUYU_BLOCKNOTE_V1\n[]',kind:'article',audience:'staff',tags:[],cover:null})]);try{await waitForLock('SELECT pg_advisory_xact_lock(hashtextextended%',2);}finally{await blocker.query('ROLLBACK');blocker.release();}const results=await work;assert.equal(results[0].status,'fulfilled');assert.equal(results[1].status,'rejected');assert.match(String((results[1] as PromiseRejectedResult).reason),/INVALID_STATE|CONFLICT/);assert.equal((await service().reviewDetail(d.id)).article.body,'正式内容');
});
test('workspace approved and returned filters reflect only actual committed decisions',async()=>{
 const approve=await pending(),reject=await pending();assert.ok((await service().workspace({status:'in_review'})).items.some(x=>x.id===approve.id));assert.ok(!(await service().workspace({status:'approved'})).items.some(x=>x.id===approve.id));
 await service().decideReview(approve.id,{expectedSequence:1,action:'approve'});assert.ok((await service().workspace({status:'approved'})).items.some(x=>x.id===approve.id));assert.ok(!(await service().workspace({status:'in_review'})).items.some(x=>x.id===approve.id));
 await service().decideReview(reject.id,{expectedSequence:1,action:'reject',reason:'补证据'});assert.ok(!(await service().workspace({status:'approved'})).items.some(x=>x.id===reject.id));assert.ok((await service(a).workspace({scope:'returned',status:'changes_requested'})).items.some(x=>x.id===reject.id));
});
test('approval acknowledgement is exact and cannot survive a later workflow change or lost eligibility',async()=>{
 const d=await pending(),input={expectedSequence:1,action:'approve'};const ack=await service().decideReview(d.id,input);assert.deepEqual(await service().decideReview(d.id,input),ack);assert.deepEqual(await counts(d.id),{reviews:1,decisions:1});
 await fixture.pool.query("INSERT INTO juyu.role_enrollments(member_id,requested_role,purpose) VALUES('b','support','default')");try{await assert.rejects(service().reviewDetail(d.id),/FORBIDDEN/);await assert.rejects(service().decideReview(d.id,input),/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.role_enrollments SET state='complete',confirmed_at=now() WHERE member_id='b'");}
 await repo.execute(d.id,{type:'queue'},a,{expectedSequence:2});await assert.rejects(service().decideReview(d.id,input),/CONFLICT/);
});
test('changed assignment and a newer submission invalidate old decision requests',async()=>{
 const d=await pending();await repo.execute(d.id,{type:'reassign'},a,{expectedSequence:1,reviewer:c});assert.equal((await service().reviewDetail(d.id)).canDecide,false);assert.equal((await service(c).reviewDetail(d.id)).canDecide,true);await assert.rejects(service().decideReview(d.id,{expectedSequence:1,action:'approve'}),/CONFLICT/);await assert.rejects(service().decideReview(d.id,{expectedSequence:2,action:'approve'}),/NOT_REVIEWER/);
 await service(c).decideReview(d.id,{expectedSequence:2,action:'reject',reason:'需要资料'});await repo.execute(d.id,{type:'edit',title:'补过',body:'附资料',audience:'staff'},a,{expectedSequence:3});await service(a).submitReview(d.id,{expectedSequence:4,reviewerId:'b'});await assert.rejects(service(c).decideReview(d.id,{expectedSequence:2,action:'reject',reason:'需要资料'}),/CONFLICT/);assert.equal((await service().reviewDetail(d.id)).review?.revision,2);assert.equal((await service().reviewDetail(d.id)).review?.status,'in_review');
});
test('the longest accepted reason persists precisely while invalid text fails before mutation',async()=>{
 const d=await pending();await assert.rejects(service().decideReview(d.id,{expectedSequence:1,action:'reject',reason:'text\0text'}),/INVALID_INPUT/);const reason='理'.repeat(2000);assert.equal((await service().decideReview(d.id,{expectedSequence:1,action:'reject',reason})).reason,reason);assert.equal((await service(a).reviewDetail(d.id)).review?.reason,reason);
});
