import assert from 'node:assert/strict';
import {before,after,test} from 'node:test';
import {randomBytes,randomUUID} from 'node:crypto';
import type {Pool} from 'pg';
import {temporaryDatabase} from './fixture.ts';
import {migrate} from '../../src/server/database/migrate.ts';
import {ScopedDatabase} from '../../src/server/database/scoped.ts';
import {DocumentRepository} from '../../src/server/database/repository.ts';
import {AuthorizationService} from '../../src/server/authorization/service.ts';
import type {Viewer,Document} from '../../src/domain/model.ts';
let fixture:Awaited<ReturnType<typeof temporaryDatabase>>,runtime:Pool,issuer:Pool,db:ScopedDatabase,repo:DocumentRepository,service:AuthorizationService;
const a:Viewer={id:'a',role:'admin',companyVerified:true},b:Viewer={...a,id:'b'},staff:Viewer={id:'staff',role:'support',companyVerified:true};
before(async()=>{fixture=await temporaryDatabase();await migrate(fixture.pool);await fixture.pool.query("INSERT INTO juyu.members(clerk_user_id,display_name,observed_role) VALUES('a','A','admin'),('b','B','admin'),('staff','Staff','support')");await fixture.pool.query("UPDATE juyu.members SET verified_email=clerk_user_id||'@example.test',observed_at=now()");const rp=randomBytes(24).toString('hex'),ip=randomBytes(24).toString('hex');await fixture.pool.query(`CREATE ROLE lifecycle_runtime LOGIN PASSWORD '${rp}' IN ROLE juyu_runtime; CREATE ROLE lifecycle_issuer LOGIN PASSWORD '${ip}' IN ROLE juyu_context_issuer`);runtime=fixture.connectAs('lifecycle_runtime',rp);issuer=fixture.connectAs('lifecycle_issuer',ip);db=new ScopedDatabase(runtime,issuer);repo=new DocumentRepository(db);service=new AuthorizationService(db,async()=>a);});
after(async()=>{if(runtime)await runtime.end();if(issuer)await issuer.end();if(fixture)await fixture.close();});
async function draft(){return repo.create({id:randomUUID(),kind:'article',title:'确认标题',body:'private body',audience:'staff'},a);}
async function act(d:Document,type:'submit'|'approve'|'queue'|'publish'){return repo.execute(d.id,{type},type==='approve'?b:a,{expectedSequence:d.sequence,reviewer:b});}
test('lifecycle endpoint is available only to an authenticated Admin',async()=>{assert.equal(typeof service.lifecycle,'function');const d=await draft();await assert.rejects(new AuthorizationService(db,async()=>staff).lifecycle(d.id,{action:'trash',expectedSequence:0}),/FORBIDDEN/);await assert.rejects(db.run(staff,c=>c.query("SELECT * FROM juyu.change_document_lifecycle($1,'trash',0,NULL)",[d.id])),/FORBIDDEN/);await assert.rejects(runtime.query("SELECT * FROM juyu.change_document_lifecycle($1,'trash',0,NULL)",[d.id]),/FORBIDDEN/);});
test('trash withdraws pending review, closes existing publication and restore stays unpublished draft',async()=>{let d=await draft();for(const t of ['submit','approve','queue','publish'] as const)d=await act(d,t);d=await repo.execute(d.id,{type:'edit',title:'new title',body:'new body',audience:'staff'},a,{expectedSequence:d.sequence});d=await act(d,'submit');assert.ok(await new AuthorizationService(db,async()=>staff).article(d.id));const result=await service.lifecycle(d.id,{action:'trash',expectedSequence:d.sequence});assert.equal(result.sequence,d.sequence+1);assert.equal(await new AuthorizationService(db,async()=>staff).article(d.id),null);const trashed=await repo.getForManagement(d.id,a);assert.equal(trashed?.workflow.status,'draft');assert.equal(trashed?.publishedRevisionId,null);assert.equal((await fixture.pool.query("SELECT status FROM juyu.reviews WHERE document_id=$1 ORDER BY submitted_sequence DESC LIMIT 1",[d.id])).rows[0].status,'withdrawn');await service.lifecycle(d.id,{action:'restore',expectedSequence:result.sequence});const restored=await repo.getForManagement(d.id,a);assert.equal(restored?.lifecycle,'active');assert.equal(restored?.workflow.status,'draft');assert.equal(restored?.publishedRevisionId,null);assert.equal(restored?.workflow.reviewerId,null);assert.equal(restored?.revisions.length,d.revisions.length);assert.equal(await new AuthorizationService(db,async()=>staff).article(d.id),null);});
test('discarding a working draft restores the published revision without taking the article offline',async()=>{
 let d=await draft();for(const t of ['submit','approve','queue','publish'] as const)d=await act(d,t);
 const published=d.publishedRevisionId!;
 d=await repo.execute(d.id,{type:'edit',title:'尚未发布的新标题',body:'尚未发布的新内容',audience:'staff'},a,{expectedSequence:d.sequence});
 const discarded=d.workflow.revisionId;
 const result=await service.discardDraft(d.id,{expectedSequence:d.sequence});
 assert.equal(result.sequence,d.sequence+1);
 const saved=await repo.getForManagement(d.id,a);
 assert.equal(saved?.workflow.status,'published');
 assert.equal(saved?.workflow.revisionId,published);
 assert.equal(saved?.publishedRevisionId,published);
 assert.ok(saved?.revisions.some(revision=>revision.id===discarded),'discarded revision stays in immutable history');
 assert.equal((await new AuthorizationService(db,async()=>staff).article(d.id))?.title,'确认标题');
 const audit=(await fixture.pool.query('SELECT action,revision_id,discarded_revision_id FROM juyu.audit_log WHERE document_id=$1 ORDER BY sequence DESC LIMIT 1',[d.id])).rows[0];
 assert.deepEqual(audit,{action:'discard_draft',revision_id:published,discarded_revision_id:discarded});
 assert.deepEqual(await service.discardDraft(d.id,{expectedSequence:d.sequence}),result,'an exact retry is idempotent');
});
test('discard rejects new drafts, non-draft workflow states and stale versions',async()=>{
 const fresh=await draft();await assert.rejects(service.discardDraft(fresh.id,{expectedSequence:fresh.sequence}),/INVALID_STATE/);
 let published=await draft();for(const t of ['submit','approve','queue','publish'] as const)published=await act(published,t);
 await assert.rejects(service.discardDraft(published.id,{expectedSequence:published.sequence}),/INVALID_STATE/);
 published=await repo.execute(published.id,{type:'edit',title:'草稿',body:'修改',audience:'staff'},a,{expectedSequence:published.sequence});
 await assert.rejects(service.discardDraft(published.id,{expectedSequence:published.sequence-1}),/CONFLICT/);
});
test('stale versions, duplicate transitions and purge without exact confirmation fail without mutation',async()=>{const d=await draft();await assert.rejects(service.lifecycle(d.id,{action:'restore',expectedSequence:0}),/INVALID_STATE/);await assert.rejects(service.lifecycle(d.id,{action:'purge',expectedSequence:0,confirmation:'确认标题'}),/INVALID_STATE/);await assert.rejects(service.lifecycle(d.id,{action:'trash',expectedSequence:1}),/CONFLICT/);await service.lifecycle(d.id,{action:'trash',expectedSequence:0});await assert.rejects(service.lifecycle(d.id,{action:'trash',expectedSequence:1}),/INVALID_STATE/);await assert.rejects(service.lifecycle(d.id,{action:'purge',expectedSequence:1,confirmation:' 确认标题'}),/CONFIRMATION_REQUIRED/);assert.equal((await repo.getForManagement(d.id,a))?.sequence,1);});
test('concurrent transitions accept exactly one current sequence',async()=>{const d=await draft();const results=await Promise.allSettled([service.lifecycle(d.id,{action:'trash',expectedSequence:0}),service.lifecycle(d.id,{action:'trash',expectedSequence:0})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.match((results.find(r=>r.status==='rejected') as PromiseRejectedResult).reason.message,/CONFLICT/);});
test('purge deletes content and asset metadata, retains immutable receipt and retryable private jobs',async()=>{const d=await act(await draft(),'submit');const asset=randomUUID();await fixture.pool.query("INSERT INTO juyu.assets(id,document_id,uploaded_by,filename,mime_type,byte_size,object_key,status) VALUES($1::uuid,$2,'a','private.txt','text/plain',1,$1::text,'ready')",[asset,d.id]);await fixture.pool.query("INSERT INTO juyu.upload_events(asset_id,actor_id,status) VALUES($1,'a','ready')",[asset]);await service.lifecycle(d.id,{action:'trash',expectedSequence:d.sequence});const command={action:'purge',expectedSequence:d.sequence+1,confirmation:'确认标题'};const result=await service.lifecycle(d.id,command);assert.equal(result.cleanupPending,1);for(const table of ['documents','revisions','reviews','audit_log','assets'])assert.equal((await fixture.pool.query(`SELECT count(*)::int AS n FROM juyu.${table} WHERE ${table==='documents'?'id':'document_id'}=$1`,[d.id])).rows[0].n,0);const receipt=(await fixture.pool.query('SELECT * FROM juyu.deletion_receipts WHERE document_id=$1',[d.id])).rows[0];assert.equal(receipt.actor_id,'a');assert.equal(receipt.audit.length,3);assert.equal(receipt.reviews[0].status,'withdrawn');assert.ok(!JSON.stringify(receipt).includes('private body'));await assert.rejects(fixture.pool.query("UPDATE juyu.deletion_receipts SET title='changed' WHERE document_id=$1",[d.id]),/IMMUTABLE/);assert.deepEqual(await service.lifecycle(d.id,command),result);await assert.rejects(new AuthorizationService(db,async()=>b).lifecycle(d.id,command),/NOT_FOUND/);await assert.rejects(repo.create({id:d.id,kind:'article',title:'reuse',body:'x',audience:'staff'},a),/PURGED_ID/);assert.deepEqual(await service.cleanupJobs(d.id),[{id:asset,object_key:asset,bucket:'juyu-private'}]);const page=await service.trash();assert.ok(page.cleanup.some(x=>x.documentId===d.id&&x.pending===1));assert.ok(!JSON.stringify(page).includes(asset));await assert.rejects(new AuthorizationService(db,async()=>staff).cleanupJobs(d.id),/FORBIDDEN/);await assert.rejects(new AuthorizationService(db,async()=>staff).finishCleanup(d.id,asset),/FORBIDDEN/);await assert.rejects(service.finishCleanup(randomUUID(),asset),/NOT_FOUND/);await service.finishCleanup(d.id,asset);assert.deepEqual(await service.cleanupJobs(d.id),[]);assert.equal((await service.lifecycle(d.id,command)).cleanupPending,0);});
test('ordinary SQL cannot bypass immutable history or forge scoped deletion permission',async()=>{const d=await draft();await assert.rejects(db.run(a,c=>c.query('DELETE FROM juyu.revisions WHERE document_id=$1',[d.id])),{code:'42501'});await assert.rejects(db.run(a,c=>c.query("UPDATE juyu.documents SET lifecycle='trashed' WHERE id=$1",[d.id])),/LIFECYCLE_COMMAND_REQUIRED/);await assert.rejects(runtime.query('SELECT * FROM juyu.lifecycle_contexts'),{code:'42501'});await assert.rejects(fixture.pool.query('DELETE FROM juyu.revisions WHERE document_id=$1',[d.id]),/IMMUTABLE/);await assert.rejects(fixture.pool.query("UPDATE juyu.revisions SET body='rewrite' WHERE document_id=$1",[d.id]),/IMMUTABLE/);});
test('purge removes every document relation but leaves other documents and category definitions intact',async()=>{let d=await draft();for(const t of ['submit','approve','queue','publish'] as const)d=await act(d,t);const other=await draft(),category=randomUUID(),asset=randomUUID(),search=randomUUID(),notification=randomUUID();await fixture.pool.query("INSERT INTO juyu.categories(id,name) VALUES($1,'shared')",[category]);await fixture.pool.query('INSERT INTO juyu.revision_categories VALUES($1,1,$2)',[d.id,category]);await fixture.pool.query("INSERT INTO juyu.assets(id,document_id,uploaded_by,filename,mime_type,byte_size,object_key,status) VALUES($1::uuid,$2,'a','a.txt','text/plain',1,$1::text,'ready')",[asset,d.id]);await fixture.pool.query('INSERT INTO juyu.revision_assets(document_id,revision_id,asset_id) VALUES($1,1,$2)',[d.id,asset]);await fixture.pool.query("INSERT INTO juyu.favorites(member_id,document_id) VALUES('staff',$1);",[d.id]);await fixture.pool.query("INSERT INTO juyu.recent_views(member_id,document_id,revision_id) VALUES('staff',$1,1)",[d.id]);await new AuthorizationService(db,async()=>staff).saveFeedback(d.id,{revision:1,helpful:true,comment:'private feedback',expectedVersion:0});await fixture.pool.query("INSERT INTO juyu.search_queries(id,member_id,query,result_count) VALUES($1,'staff','sha256:'||encode(sha256(convert_to('query','UTF8')),'hex'),1)",[search]);await fixture.pool.query('INSERT INTO juyu.search_results(search_id,position,document_id,revision_id) VALUES($1,1,$2,1)',[search,d.id]);await fixture.pool.query("INSERT INTO juyu.analytics_events(id,member_id,kind,document_id,revision_id,search_id,result_position) VALUES($1,'staff','search_click',$2,1,$3,1)",[randomUUID(),d.id,search]);await fixture.pool.query("INSERT INTO juyu.notifications(id,title,body,target_document_id,created_by) VALUES($1,'notice','private notice',$2,'a')",[notification,d.id]);await fixture.pool.query("INSERT INTO juyu.notification_receipts(notification_id,member_id,seen_at) VALUES($1,'staff',now())",[notification]);await service.lifecycle(d.id,{action:'trash',expectedSequence:d.sequence});await service.lifecycle(d.id,{action:'purge',expectedSequence:d.sequence+1,confirmation:'确认标题'});for(const table of ['revision_assets','revision_categories','favorites','recent_views','feedback','search_results','analytics_events'])assert.equal((await fixture.pool.query(`SELECT count(*)::int AS n FROM juyu.${table} WHERE document_id=$1`,[d.id])).rows[0].n,0);assert.equal((await fixture.pool.query('SELECT count(*)::int AS n FROM juyu.notifications WHERE id=$1',[notification])).rows[0].n,0);assert.equal((await fixture.pool.query('SELECT count(*)::int AS n FROM juyu.notification_receipts WHERE notification_id=$1',[notification])).rows[0].n,0);assert.ok(await repo.getForManagement(other.id,a));assert.equal((await fixture.pool.query('SELECT count(*)::int AS n FROM juyu.categories WHERE id=$1',[category])).rows[0].n,1);});
test('a failed purge rolls back content, receipt, cleanup jobs and private authorization context together',async()=>{const d=await draft();await service.lifecycle(d.id,{action:'trash',expectedSequence:0});await fixture.pool.query("CREATE FUNCTION juyu.fail_lifecycle_delete() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected purge failure'; END $$; CREATE TRIGGER fail_purge BEFORE DELETE ON juyu.documents FOR EACH ROW EXECUTE FUNCTION juyu.fail_lifecycle_delete()");try{await assert.rejects(service.lifecycle(d.id,{action:'purge',expectedSequence:1,confirmation:'确认标题'}),/injected purge failure/);assert.equal((await repo.getForManagement(d.id,a))?.sequence,1);assert.equal((await fixture.pool.query('SELECT count(*)::int AS n FROM juyu.deletion_receipts WHERE document_id=$1',[d.id])).rows[0].n,0);assert.equal((await fixture.pool.query('SELECT count(*)::int AS n FROM juyu.lifecycle_contexts')).rows[0].n,0);}finally{await fixture.pool.query('DROP TRIGGER fail_purge ON juyu.documents; DROP FUNCTION juyu.fail_lifecycle_delete()');}});
test('stale authenticated Admin claims cannot read or mutate after actual role downgrade',async()=>{const d=await draft();await fixture.pool.query("UPDATE juyu.members SET observed_role='support' WHERE clerk_user_id='a'");try{await assert.rejects(service.lifecycle(d.id,{action:'trash',expectedSequence:0}),/FORBIDDEN/);await assert.rejects(service.trash(),/FORBIDDEN/);await assert.rejects(service.cleanupJobs(d.id),/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.members SET observed_role='admin' WHERE clerk_user_id='a'");}});
test('purged asset identities cannot be reused while durable cleanup evidence exists',async()=>{const d=await draft(),asset=randomUUID();await service.reserveUpload(d.id,asset,{filename:'a.txt',mime:'text/plain',size:1});await service.finishUpload(asset,true);await service.lifecycle(d.id,{action:'trash',expectedSequence:0});await service.lifecycle(d.id,{action:'purge',expectedSequence:1,confirmation:'确认标题'});const next=await draft();await assert.rejects(service.reserveUpload(next.id,asset,{filename:'b.txt',mime:'text/plain',size:1}),/PURGED_ASSET_ID/);});
test('in-flight uploads block trash and purge until the reserved upload is settled',async()=>{const d=await draft(),asset=randomUUID();await service.reserveUpload(d.id,asset,{filename:'upload.txt',mime:'text/plain',size:1});await assert.rejects(service.lifecycle(d.id,{action:'trash',expectedSequence:0}),/UPLOAD_IN_PROGRESS/);assert.equal((await repo.getForManagement(d.id,a))?.lifecycle,'active');await service.finishUpload(asset,true);await service.lifecycle(d.id,{action:'trash',expectedSequence:0});await fixture.pool.query("UPDATE juyu.assets SET status='pending' WHERE id=$1",[asset]);await assert.rejects(service.lifecycle(d.id,{action:'purge',expectedSequence:1,confirmation:'确认标题'}),/UPLOAD_IN_PROGRESS/);await service.finishUpload(asset,false);assert.equal((await service.lifecycle(d.id,{action:'purge',expectedSequence:1,confirmation:'确认标题'})).cleanupPending,1);});
test('concurrent upload reservation and trash serialize on the document lock',async()=>{const d=await draft(),asset=randomUUID();let reserved!:()=>void,release!:()=>void;const started=new Promise<void>(r=>{reserved=r;}),gate=new Promise<void>(r=>{release=r;});const upload=db.run(a,async c=>{await c.query('SELECT juyu.reserve_upload($1,$2,$3,$4,$5)',[asset,d.id,'upload.txt','text/plain',1]);reserved();await gate;});await started;const trash=service.lifecycle(d.id,{action:'trash',expectedSequence:0});release();await upload;await assert.rejects(trash,/UPLOAD_IN_PROGRESS/);assert.equal((await repo.getForManagement(d.id,a))?.lifecycle,'active');});
test('forged custom settings cannot grant the runtime permission to bypass lifecycle or purge',async()=>{const d=await draft();await assert.rejects(db.run(a,async c=>{await c.query("SELECT set_config('juyu.purge','true',true),set_config('juyu.lifecycle','purge',true)");await c.query("UPDATE juyu.documents SET lifecycle='trashed' WHERE id=$1",[d.id]);}),/LIFECYCLE_COMMAND_REQUIRED/);await assert.rejects(db.run(a,c=>c.query("INSERT INTO juyu.lifecycle_contexts VALUES(pg_backend_pid(),txid_current(),$1,'purge')",[d.id])),{code:'42501'});});
test('trash and pending-cleanup pagination are independent, and cleanup totals include all batches',async()=>{for(let i=0;i<31;i++){const d=await draft();await service.lifecycle(d.id,{action:'trash',expectedSequence:0});const id=randomUUID();await fixture.pool.query("INSERT INTO juyu.deletion_receipts(document_id,title,actor_id,expected_sequence,sequence,audit,reviews,upload_events) VALUES($1,'pending title','a',1,2,'[]','[]','[]')",[id]);for(let j=0;j<(i===0?26:1);j++){const key=randomUUID();await fixture.pool.query("INSERT INTO juyu.storage_cleanup_jobs(id,document_id,bucket,object_key) VALUES($1::uuid,$2,'juyu-private',$1::text)",[key,id]);}if(i===0){assert.equal((await service.cleanupJobs(id)).length,25);assert.equal(await service.cleanupPending(id),26);const jobs=await service.cleanupJobs(id);for(const job of jobs)await service.finishCleanup(id,job.id);assert.equal(await service.cleanupPending(id),1);}}
 const first=await service.trash(1,1),second=await service.trash(2,2);assert.equal(first.items.length,30);assert.equal(first.cleanup.length,30);assert.ok(second.items.length>0);assert.ok(second.cleanup.length>0);assert.ok(first.items.every(x=>!second.items.some(y=>x.id===y.id)));assert.ok(first.cleanup.every(x=>!second.cleanup.some(y=>x.documentId===y.documentId)));await assert.rejects(service.trash(0),/INVALID_INPUT/);await assert.rejects(service.trash(1,0),/INVALID_INPUT/);
});
test('cleanup status requires a real deletion receipt and accepts verified zero-job receipts',async()=>{
 const missing=randomUUID();
 await assert.rejects(service.cleanupJobs(missing),/NOT_FOUND/);
 await assert.rejects(service.cleanupPending(missing),/NOT_FOUND/);
 const d=await draft();await assert.rejects(service.cleanupPending(d.id),/NOT_FOUND/);
 await service.lifecycle(d.id,{action:'trash',expectedSequence:0});
 const deleted=await service.lifecycle(d.id,{action:'purge',expectedSequence:1,confirmation:'确认标题'});
 assert.equal(deleted.cleanupPending,0);assert.deepEqual(await service.cleanupJobs(d.id),[]);assert.equal(await service.cleanupPending(d.id),0);
 const fileDoc=await draft(),asset=randomUUID();await service.reserveUpload(fileDoc.id,asset,{filename:'finished.txt',mime:'text/plain',size:1});await service.finishUpload(asset,true);
 await service.lifecycle(fileDoc.id,{action:'trash',expectedSequence:0});await service.lifecycle(fileDoc.id,{action:'purge',expectedSequence:1,confirmation:'确认标题'});await service.finishCleanup(fileDoc.id,asset);
 assert.deepEqual(await service.cleanupJobs(fileDoc.id),[]);assert.equal(await service.cleanupPending(fileDoc.id),0);
});
test('an upload waiting on an uncommitted purge cannot reuse the purged object identity',async()=>{
 const old=await draft(),next=await draft(),asset=randomUUID();
 await service.reserveUpload(old.id,asset,{filename:'old.txt',mime:'text/plain',size:1});await service.finishUpload(asset,true);
 await service.lifecycle(old.id,{action:'trash',expectedSequence:0});
 let purged!:()=>void,commit!:()=>void,reserving!:(pid:number)=>void;
 const ready=new Promise<void>(r=>{purged=r;}),gate=new Promise<void>(r=>{commit=r;}),reservationStarted=new Promise<number>(r=>{reserving=r;});
 const purge=db.run(a,async c=>{await c.query("SELECT * FROM juyu.change_document_lifecycle($1,'purge',1,'确认标题')",[old.id]);purged();await gate;});
 await ready;
 const reserve=db.run(a,async c=>{const pid=(await c.query('SELECT pg_backend_pid() AS pid')).rows[0].pid;reserving(pid);await c.query('SELECT juyu.reserve_upload($1,$2,$3,$4,$5)',[asset,next.id,'new.txt','text/plain',1]);});
 const outcome=reserve.then(()=>({error:null}),error=>({error}));
 try{
  const pid=await reservationStarted;let waiting=false;
  const deadline=Date.now()+2000;
  while(Date.now()<deadline){waiting=(await fixture.pool.query("SELECT wait_event_type='Lock' AS waiting FROM pg_stat_activity WHERE pid=$1",[pid])).rows[0]?.waiting===true;if(waiting)break;await new Promise(r=>setTimeout(r,5));}
  assert.equal(waiting,true,'the second real connection must be blocked by the uncommitted purge');
 }finally{commit();}
 await purge;const result=await outcome;
 assert.match(result.error?.message??'reservation unexpectedly succeeded',/PURGED_ASSET_ID/);
 assert.equal((await fixture.pool.query('SELECT count(*)::int AS n FROM juyu.assets WHERE id=$1',[asset])).rows[0].n,0);
 assert.equal(await service.cleanupPending(old.id),1);
});
test('cleanup retry ordering advances only objects whose execution actually started',async()=>{
 assert.equal(typeof service.startCleanupAttempt,'function');
 const id=randomUUID(),keys=Array.from({length:3},()=>randomUUID()).sort();
 await fixture.pool.query("INSERT INTO juyu.deletion_receipts(document_id,title,actor_id,expected_sequence,sequence,audit,reviews,upload_events) VALUES($1,'fair retry','a',1,2,'[]','[]','[]')",[id]);
 for(const key of keys)await fixture.pool.query("INSERT INTO juyu.storage_cleanup_jobs(id,document_id,bucket,object_key) VALUES($1::uuid,$2,'juyu-private',$1::text)",[key,id]);
 assert.deepEqual((await service.cleanupJobs(id)).map(job=>job.id),keys);
 // The runner exhausts its deadline on two slow failures, never starting the third.
 await service.startCleanupAttempt(id,keys[0]);await service.startCleanupAttempt(id,keys[1]);
 const second=await service.cleanupJobs(id);assert.equal(second[0].id,keys[2],'the unstarted object must lead the next retry');
 const attempts=(await fixture.pool.query('SELECT id,last_attempt_at FROM juyu.storage_cleanup_jobs WHERE document_id=$1 ORDER BY id',[id])).rows;
 assert.ok(attempts[0].last_attempt_at);assert.ok(attempts[1].last_attempt_at);assert.equal(attempts[2].last_attempt_at,null);
 assert.equal(await service.cleanupPending(id),3,'starting an attempt never acknowledges deletion');
 await service.trash();await service.cleanupJobs(id);await service.cleanupPending(id);
 assert.deepEqual((await fixture.pool.query('SELECT id,last_attempt_at FROM juyu.storage_cleanup_jobs WHERE document_id=$1 ORDER BY id',[id])).rows,attempts,'GETs cannot change retry order');
 await assert.rejects(new AuthorizationService(db,async()=>staff).startCleanupAttempt(id,keys[2]),/FORBIDDEN/);
 await assert.rejects(db.run(staff,c=>c.query('SELECT juyu.start_storage_cleanup_attempt($1,$2)',[id,keys[2]])),/FORBIDDEN/);
 await assert.rejects(service.startCleanupAttempt(randomUUID(),keys[2]),/NOT_FOUND/);
 await assert.rejects(service.startCleanupAttempt(id,randomUUID()),/NOT_FOUND/);
 await assert.rejects(service.startCleanupAttempt(id,'bad-id'),/INVALID_INPUT/);
 await service.startCleanupAttempt(id,keys[2]);await service.finishCleanup(id,keys[2]);
 await assert.rejects(service.startCleanupAttempt(id,keys[2]),/NOT_FOUND/);
 assert.equal(await service.cleanupPending(id),2);
 assert.deepEqual((await service.cleanupJobs(id)).map(job=>job.id),keys.slice(0,2));
});
