import assert from 'node:assert/strict';
import {before,after,beforeEach,test} from 'node:test';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import type {Pool} from 'pg';
import {temporaryDatabase} from './fixture.ts';
import {migrate} from '../../src/server/database/migrate.ts';
import {ScopedDatabase} from '../../src/server/database/scoped.ts';
import {DocumentRepository} from '../../src/server/database/repository.ts';
import {AuthorizationService} from '../../src/server/authorization/service.ts';
import {writeCategoryDefinition} from '../../src/server/categories/repository.ts';
import {writeNavigationSettings} from '../../src/server/navigation-settings/repository.ts';
import {defaultNavigationEntries,type NavigationEntry} from '../../src/navigation-settings/model.ts';
import {categoryPage} from '../../src/reader/category-page.ts';
import type {Viewer} from '../../src/domain/model.ts';
let fixture:Awaited<ReturnType<typeof temporaryDatabase>>,runtime:Pool,issuer:Pool,db:ScopedDatabase,repo:DocumentRepository;
const admin:Viewer={id:'a',role:'admin',companyVerified:true},reviewer:Viewer={...admin,id:'b'},support:Viewer={id:'s',role:'support',companyVerified:true},ops:Viewer={id:'o',role:'ops',companyVerified:true};
const service=(v:Viewer=admin)=>new AuthorizationService(db,async()=>v);
const entry=(page:'home'|'ops'|'reference'|'qa'|'favorites'|'recent'|'forms'='home'):NavigationEntry=>({id:randomUUID(),label:page,enabled:true,roles:['support','ops','admin'],target:{type:'page',page}});
const category=(id= randomUUID(),parentId:string|null=null,audience='staff')=>db.run(admin,c=>writeCategoryDefinition(c,id,{expectedVersion:null,name:'Category',parentId,position:0,audience,enabled:true}));
async function published(categoryIds:string[]=[],audience:'staff'|'ops'|'admin'='staff') {const d=await repo.create({id:randomUUID(),kind:'article',title:'Formal',body:'Published body',audience,categoryIds},admin);await service().submitReview(d.id,{expectedSequence:0,reviewerId:'b'});await service(reviewer).decideReview(d.id,{expectedSequence:1,action:'approve'});await service().changePublication(d.id,{expectedSequence:2,action:'queue'});await service().changePublication(d.id,{expectedSequence:3,action:'publish'});return (await repo.getForManagement(d.id,admin))!;}
before(async()=>{fixture=await temporaryDatabase();await migrate(fixture.pool);await fixture.pool.query("INSERT INTO juyu.members(clerk_user_id,display_name,observed_role,verified_email,observed_at) VALUES('a','Admin','admin','a@example.test',now()),('b','Reviewer','admin','b@example.test',now()),('s','Support','support','s@example.test',now()),('o','Ops','ops','o@example.test',now())");const rp=randomBytes(24).toString('hex'),ip=randomBytes(24).toString('hex');await fixture.pool.query(`CREATE ROLE navigation_runtime LOGIN PASSWORD '${rp}' IN ROLE juyu_runtime; CREATE ROLE navigation_issuer LOGIN PASSWORD '${ip}' IN ROLE juyu_context_issuer`);runtime=fixture.connectAs('navigation_runtime',rp);issuer=fixture.connectAs('navigation_issuer',ip);db=new ScopedDatabase(runtime,issuer);repo=new DocumentRepository(db);});
after(async()=>{await runtime?.end();await issuer?.end();await fixture?.close();});
beforeEach(async()=>{await fixture.pool.query('TRUNCATE juyu.documents,juyu.settings,juyu.categories CASCADE');});
test('absent config projects documented version0 defaults; configured empty is not replaced by defaults',async()=>{
 assert.deepEqual(await service().navigationSettings(),{version:0,entries:defaultNavigationEntries});assert.equal((await service(support).readerMenu()).length,6);assert.equal((await service(ops).readerMenu()).length,7);
 const saved=await service().saveNavigationSettings({expectedVersion:0,entries:[]});assert.deepEqual(saved,{version:1,entries:[]});assert.deepEqual(await service().navigationSettings(),saved);assert.deepEqual(await service(support).readerMenu(),[]);
});
test('whole config writes keep exact same actor retries and immutable version audit',async()=>{
 const a=entry(),b=entry('forms'),first=await service().saveNavigationSettings({expectedVersion:0,entries:[a,b]});assert.equal(first.version,1);assert.deepEqual(await service().saveNavigationSettings({expectedVersion:0,entries:[a,b]}),first);
 await assert.rejects(service(reviewer).saveNavigationSettings({expectedVersion:0,entries:[a,b]}),/NAVIGATION_CONFLICT/);await assert.rejects(service().saveNavigationSettings({expectedVersion:0,entries:[b,a]}),/NAVIGATION_CONFLICT/);
 const changed=await service().saveNavigationSettings({expectedVersion:1,entries:[b,{...a,label:'Renamed'}]});assert.equal(changed.version,2);assert.deepEqual((await service(support).readerMenu()).map(x=>x.id),[b.id,a.id]);assert.equal((await fixture.pool.query("SELECT count(*)::int n FROM juyu.setting_versions v JOIN juyu.settings s ON s.id=v.setting_id WHERE s.key='reader-navigation'")).rows[0].n,2);
 await assert.rejects(fixture.pool.query("UPDATE juyu.setting_versions SET config='{}' WHERE setting_id=(SELECT id FROM juyu.settings WHERE key='reader-navigation')"),/IMMUTABLE/);
});
test('entry roles and current OPS authorization both apply and hidden shortcuts do not change destination access',async()=>{
 const document=await published(),home={...entry(),enabled:false},opsEntry={...entry('ops'),roles:['support','ops'] as NavigationEntry['roles']},forms={...entry('forms'),roles:['support'] as NavigationEntry['roles']};await service().saveNavigationSettings({expectedVersion:0,entries:[home,opsEntry,forms]});assert.deepEqual((await service(support).readerMenu()).map(x=>x.id),[forms.id]);assert.deepEqual((await service(ops).readerMenu()).map(x=>x.id),[opsEntry.id]);assert.deepEqual(await service(admin).readerMenu(),[]);assert.ok(await service(support).article(document.id));
 await assert.rejects(service(support).ops(),/FORBIDDEN/);
});
test('category entries require readable current publications throughout inherited restrictions and draft edits',async()=>{
 const root=await category(),child=await category(randomUUID(),root.id),empty=await category(),shortcut={...entry(),label:'Private menu label',target:{type:'category' as const,categoryId:root.id}},emptyShortcut={...entry(),target:{type:'category' as const,categoryId:empty.id}};await service().saveNavigationSettings({expectedVersion:0,entries:[shortcut,emptyShortcut]});assert.deepEqual(await service(support).readerMenu(),[]);
 const d=await published([child.id]);assert.deepEqual(await service(support).readerMenu(),[{id:shortcut.id,label:shortcut.label,href:`/help-centre/categories/${root.id}`}]);await repo.execute(d.id,{type:'edit',title:'Draft only',body:'Draft',audience:'staff',categoryIds:[empty.id]},admin,{expectedSequence:d.sequence});assert.deepEqual((await service(support).readerMenu()).map(x=>x.id),[shortcut.id]);
 await db.run(admin,c=>writeCategoryDefinition(c,root.id,{expectedVersion:1,name:root.name,parentId:null,position:0,audience:'ops',enabled:true}));assert.deepEqual(await service(support).readerMenu(),[]);assert.equal((await service(ops).readerMenu()).length,1);
 await db.run(admin,c=>writeCategoryDefinition(c,root.id,{expectedVersion:2,name:root.name,parentId:null,position:0,audience:'ops',enabled:false}));assert.deepEqual(await service(admin).readerMenu(),[]);assert.ok(!JSON.stringify(await service(support).readerMenu()).includes(shortcut.label));assert.equal(await service(support).article(d.id),null);assert.equal(categoryPage(await service(support).categoryNavigationTree(),root.id),null);
});
test('any selected category membership can expose the category shortcut even if tree ranks another category first',async()=>{
 const one=await category(),two=await category();const document=await published([one.id,two.id]);const first={...entry(),target:{type:'category' as const,categoryId:one.id}},second={...entry(),target:{type:'category' as const,categoryId:two.id}};await service().saveNavigationSettings({expectedVersion:0,entries:[first,second]});assert.deepEqual((await service(support).readerMenu()).map(x=>x.id),[first.id,second.id]);const tree=await service(support).categoryNavigationTree();assert.ok(categoryPage(tree,one.id));assert.ok(categoryPage(tree,two.id));await service().saveNavigationSettings({expectedVersion:1,entries:[]});assert.deepEqual(await service(support).readerMenu(),[]);assert.ok(await service(support).article(document.id));assert.ok(categoryPage(await service(support).categoryNavigationTree(),two.id));
});
test('raw SQL validates exact shape roles labels fixed targets unknown categories and bounds',async()=>{
 const valid=entry(),raw=(entries:unknown)=>db.run(admin,c=>c.query('SELECT juyu.write_navigation_settings(0,$1)',[JSON.stringify(entries)]));
 for(const entries of [[{...valid,extra:true}],[{...valid,label:' Bad '}],[{...valid,label:'x'.repeat(81)}],[{...valid,label:'\u0085'}],[{...valid,enabled:'true'}],[{...valid,roles:['admin','support']}],[{...valid,roles:['support','support']}],[{...valid,roles:[]}],[{...valid,target:{type:'page',page:'../../admin'}}],[{...valid,target:{type:'url',url:'https://evil.test'}}],[{...valid,target:{type:'category',categoryId:randomUUID()}}],[valid,valid],Array.from({length:41},()=>entry())])await assert.rejects(raw(entries),/INVALID_INPUT/);
 for(const version of [null,-1,2147483647])await assert.rejects(db.run(admin,c=>c.query('SELECT juyu.write_navigation_settings($1,$2)',[version,JSON.stringify([valid])])),/INVALID_INPUT/);
 assert.deepEqual(await service().navigationSettings(),{version:0,entries:defaultNavigationEntries});
});
test('runtime and stale profiles cannot read raw navigation settings or mutate configuration',async()=>{
 await service().saveNavigationSettings({expectedVersion:0,entries:[entry()]});for(const v of [support,ops]){await assert.rejects(service(v).navigationSettings(),/FORBIDDEN/);await assert.rejects(service(v).saveNavigationSettings({expectedVersion:1,entries:[]}),/FORBIDDEN/);assert.deepEqual((await db.run(v,c=>c.query("SELECT * FROM juyu.settings WHERE kind='navigation'"),true)).rows,[]);assert.deepEqual((await db.run(v,c=>c.query('SELECT * FROM juyu.setting_versions'),true)).rows,[]);}
 await assert.rejects(runtime.query('SELECT juyu.read_reader_menu()'),/FORBIDDEN/);await assert.rejects(db.run(admin,c=>c.query("UPDATE juyu.settings SET enabled=false WHERE key='reader-navigation'")),/permission denied/);await assert.rejects(db.run(support,c=>c.query('SELECT juyu.navigation_config()')),/permission denied/);
 for(const state of ["disabled_at=now()","observed_role='ops'","verified_email=null","observed_at=null"]){await fixture.pool.query(`UPDATE juyu.members SET ${state} WHERE clerk_user_id='a'`);try{await assert.rejects(service().navigationSettings(),/FORBIDDEN/);await assert.rejects(service().saveNavigationSettings({expectedVersion:1,entries:[]}),/FORBIDDEN/);await assert.rejects(service().readerMenu(),/FORBIDDEN/);assert.deepEqual((await db.run(admin,c=>c.query('SELECT * FROM juyu.setting_versions'),true)).rows,[]);}finally{await fixture.pool.query("UPDATE juyu.members SET disabled_at=null,observed_role='admin',verified_email='a@example.test',observed_at=now() WHERE clerk_user_id='a'");}}
});
async function waitForLock(query:string){const deadline=Date.now()+3000;while(Date.now()<deadline){if((await fixture.pool.query("SELECT count(*)::int n FROM pg_stat_activity WHERE wait_event_type='Lock' AND query LIKE $1",[query])).rows[0].n>0)return;await new Promise(r=>setTimeout(r,5));}assert.fail('concurrent database lock was not reached');}
test('parallel exact retries commit one audit and different edits have a single winner',async()=>{
 const entries=[entry()],retries=await Promise.all([service().saveNavigationSettings({expectedVersion:0,entries}),service().saveNavigationSettings({expectedVersion:0,entries})]);assert.deepEqual(retries[0],retries[1]);const competing=await Promise.allSettled([service().saveNavigationSettings({expectedVersion:1,entries:[]}),service().saveNavigationSettings({expectedVersion:1,entries:[entry('forms')]})]);assert.equal(competing.filter(r=>r.status==='fulfilled').length,1);assert.match(String((competing.find(r=>r.status==='rejected') as PromiseRejectedResult).reason),/NAVIGATION_CONFLICT/);assert.equal((await fixture.pool.query('SELECT count(*)::int n FROM juyu.setting_versions')).rows[0].n,2);
});
test('writer rechecks eligibility after concurrent demotion and member exclusion lock fails busy',async()=>{
 const blocker=await fixture.pool.connect();await blocker.query('BEGIN');await blocker.query("UPDATE juyu.members SET observed_role='ops' WHERE clerk_user_id='a'");const writing=service().saveNavigationSettings({expectedVersion:0,entries:[entry()]}).then(()=>null,error=>error);try{await waitForLock('SELECT juyu.write_navigation_settings%');}finally{await blocker.query('COMMIT');blocker.release();}try{assert.match((await writing)?.message??'unexpected success',/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.members SET observed_role='admin' WHERE clerk_user_id='a'");}
 const member=await fixture.pool.connect();await member.query('BEGIN');await member.query('SELECT pg_advisory_xact_lock(84620915)');try{await assert.rejects(db.run(admin,c=>writeNavigationSettings(c,{expectedVersion:0,entries:[]})),/MEMBER_BUSY/);}finally{await member.query('ROLLBACK');member.release();}
});
test('pending membership and enrollment revoke configuration menu and direct category landing',async()=>{
 const op=(await fixture.pool.query("INSERT INTO juyu.member_operations(actor_id,target_id,kind,requested_role) VALUES('b','a','role','support') RETURNING id")).rows[0].id;try{await assert.rejects(service().navigationSettings(),/FORBIDDEN/);await assert.rejects(service().saveNavigationSettings({expectedVersion:0,entries:[]}),/FORBIDDEN/);await assert.rejects(service().readerMenu(),/FORBIDDEN/);await assert.rejects(service().categoryNavigationTree(),/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.member_operations SET status='conflict',finished_at=now() WHERE id=$1",[op]);}
 await fixture.pool.query("INSERT INTO juyu.role_enrollments(member_id,requested_role,purpose) VALUES('s','support','default')");try{await assert.rejects(service(support).readerMenu(),/FORBIDDEN/);await assert.rejects(service(support).categoryNavigationTree(),/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.role_enrollments SET state='complete',confirmed_at=now() WHERE member_id='s'");}
});
test('migration23 preserves generic legacy settings categories and replay state',async()=>{
 const old=await temporaryDatabase();try{await old.pool.query('CREATE SCHEMA juyu; CREATE TABLE juyu.schema_migrations(version text PRIMARY KEY,checksum text NOT NULL,applied_at timestamptz NOT NULL DEFAULT now())');const versions=(await fixture.pool.query("SELECT version FROM juyu.schema_migrations WHERE version<'0023_navigation_settings' ORDER BY version")).rows;
 for(const {version} of versions){const sql=await readFile(new URL(`../../src/server/database/migrations/${version}.sql`,import.meta.url),'utf8');await old.pool.query(sql);await old.pool.query('INSERT INTO juyu.schema_migrations(version,checksum) VALUES($1,$2)',[version,createHash('sha256').update(sql).digest('hex')]);}
 await old.pool.query("INSERT INTO juyu.members(clerk_user_id,display_name) VALUES('legacy','Legacy');INSERT INTO juyu.categories(name) VALUES('Existing category')");const setting=randomUUID(),c=await old.pool.connect();try{await c.query('BEGIN');await c.query("INSERT INTO juyu.settings(id,key,kind,current_version) VALUES($1,'legacy-navigation','navigation',1)",[setting]);await c.query("INSERT INTO juyu.setting_versions(setting_id,version,config,changed_by) VALUES($1,1,'{}','legacy')",[setting]);await c.query('COMMIT');}finally{c.release();}
 const before=(await old.pool.query('SELECT * FROM juyu.setting_versions')).rows,categories=(await old.pool.query('SELECT * FROM juyu.categories')).rows;assert.deepEqual(await migrate(old.pool),['0023_navigation_settings', '0024_feature_flags', '0025_setting_history', '0026_announcements', '0027_native_editor']);assert.deepEqual(await migrate(old.pool),[]);assert.deepEqual((await old.pool.query('SELECT * FROM juyu.setting_versions')).rows,before);assert.deepEqual((await old.pool.query('SELECT * FROM juyu.categories')).rows,categories);assert.deepEqual((await old.pool.query('SELECT juyu.navigation_config() AS config')).rows[0].config,{version:0,entries:defaultNavigationEntries});
 }finally{await old.close();}
});
