import assert from 'node:assert/strict';
import {before,after,beforeEach,test} from 'node:test';
import {randomBytes,randomUUID} from 'node:crypto';
import type {Pool} from 'pg';
import {temporaryDatabase} from './fixture.ts';
import {migrate} from '../../src/server/database/migrate.ts';
import {ScopedDatabase} from '../../src/server/database/scoped.ts';
import {DocumentRepository} from '../../src/server/database/repository.ts';
import {AuthorizationService} from '../../src/server/authorization/service.ts';
import {encodeEditorBody} from '../../src/editor/document.ts';
import type {Viewer,Document} from '../../src/domain/model.ts';
let fixture:Awaited<ReturnType<typeof temporaryDatabase>>,runtime:Pool,issuer:Pool,db:ScopedDatabase,repo:DocumentRepository;
const admin:Viewer={id:'a',role:'admin',companyVerified:true},reviewer:Viewer={...admin,id:'b'},ops:Viewer={id:'o',role:'ops',companyVerified:true},support:Viewer={id:'s',role:'support',companyVerified:true};
const service=(v:Viewer|null=ops)=>new AuthorizationService(db,async()=>v);
async function draft(title='OPS formal',kind:Document['kind']='ops',audience:'ops'|'admin'|'staff'='ops') {return repo.create({id:randomUUID(),kind,title,body:'Formal body',audience,tags:['Formal tag']},admin);}
async function publish(d:Document){await service(admin).submitReview(d.id,{expectedSequence:d.sequence,reviewerId:'b'});await service(reviewer).decideReview(d.id,{expectedSequence:d.sequence+1,action:'approve'});await service(admin).changePublication(d.id,{expectedSequence:d.sequence+2,action:'queue'});await service(admin).changePublication(d.id,{expectedSequence:d.sequence+3,action:'publish'});return (await repo.getForManagement(d.id,admin))!;}
async function asset(id:string){const aid=randomUUID();await fixture.pool.query("INSERT INTO juyu.assets(id,document_id,uploaded_by,filename,mime_type,byte_size,object_key,status) VALUES($1::uuid,$2,'a','ops.pdf','application/pdf',4,$1::text,'ready')",[aid,id]);await fixture.pool.query("INSERT INTO juyu.revision_assets(document_id,revision_id,asset_id,usage) VALUES($1,1,$2,'attachment')",[id,aid]);return aid;}
before(async()=>{fixture=await temporaryDatabase();await migrate(fixture.pool);await fixture.pool.query("INSERT INTO juyu.members(clerk_user_id,display_name,observed_role,verified_email,observed_at) VALUES('a','Admin','admin','a@example.test',now()),('b','Reviewer','admin','b@example.test',now()),('o','Ops','ops','o@example.test',now()),('s','Support','support','s@example.test',now())");const rp=randomBytes(24).toString('hex'),ip=randomBytes(24).toString('hex');await fixture.pool.query(`CREATE ROLE ops_runtime LOGIN PASSWORD '${rp}' IN ROLE juyu_runtime; CREATE ROLE ops_issuer LOGIN PASSWORD '${ip}' IN ROLE juyu_context_issuer`);runtime=fixture.connectAs('ops_runtime',rp);issuer=fixture.connectAs('ops_issuer',ip);db=new ScopedDatabase(runtime,issuer);repo=new DocumentRepository(db);});
after(async()=>{await runtime?.end();await issuer?.end();await fixture?.close();});
beforeEach(async()=>{await fixture.pool.query('TRUNCATE juyu.documents CASCADE');});
test('reader section entry requires current verified Ops or Admin and rejects stale or unverified identities',async()=>{assert.deepEqual(await service(support).readerSections(),{ops:false});assert.deepEqual(await service().readerSections(),{ops:true});assert.deepEqual(await service(admin).readerSections(),{ops:true});await assert.rejects(service(support).ops(),/FORBIDDEN/);for(const v of [null,{...ops,companyVerified:false},{...ops,role:'owner'}])await assert.rejects(service(v as Viewer|null).readerSections(),/FORBIDDEN/);
 for(const state of ["observed_role='support'","disabled_at=now()","verified_email=null","observed_at=null"]){await fixture.pool.query(`UPDATE juyu.members SET ${state} WHERE clerk_user_id='o'`);try{await assert.rejects(service().readerSections(),/FORBIDDEN/);await assert.rejects(service().ops(),/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.members SET observed_role='ops',disabled_at=null,verified_email='o@example.test',observed_at=now() WHERE clerk_user_id='o'");}}
});
test('collection includes only allowed active formal OPS publications and uses formal title tags during re-edit',async()=>{const allowed=await publish(await draft());await repo.execute(allowed.id,{type:'edit',title:'Secret new draft',body:'Draft secret',audience:'admin',tags:['Secret draft tag']},admin,{expectedSequence:allowed.sequence});await publish(await draft('Regular','article','staff'));await draft('Unpublished');const hidden=await publish(await draft('Admin only','ops','admin'));const archived=await publish(await draft('Archived'));await service(admin).changeAvailability(archived.id,{expectedSequence:archived.sequence,action:'archive'});const trashed=await publish(await draft('Trashed'));await service(admin).lifecycle(trashed.id,{expectedSequence:trashed.sequence,action:'trash'});
 const parent=randomUUID(),child=randomUUID();await fixture.pool.query("INSERT INTO juyu.categories(id,name,audience,parent_id) VALUES($1,'Restricted parent','admin',null),($2,'Public child','staff',$1)",[parent,child]);const restricted=await publish(await draft('Ancestor restricted'));await fixture.pool.query('INSERT INTO juyu.revision_categories VALUES($1,1,$2)',[restricted.id,child]);const disabledParent=randomUUID(),disabledChild=randomUUID();await fixture.pool.query("INSERT INTO juyu.categories(id,name,audience,parent_id,enabled) VALUES($1,'Disabled parent','staff',null,false),($2,'Child','staff',$1,true)",[disabledParent,disabledChild]);const disabled=await publish(await draft('Disabled ancestor'));await fixture.pool.query('INSERT INTO juyu.revision_categories VALUES($1,1,$2)',[disabled.id,disabledChild]);
 assert.deepEqual(await service().ops(),{items:[{id:allowed.id,title:'OPS formal',revision:1,tags:['Formal tag']}],total:1,page:1,pages:1});const adminPage=await service(admin).ops();assert.equal(adminPage.total,3);assert.deepEqual(new Set(adminPage.items.map(x=>x.id)),new Set([allowed.id,hidden.id,restricted.id]));assert.ok(!JSON.stringify(adminPage).includes('Secret'));
});
test('collection pagination is stable by formal title and id with totals clamped pages and strict input',async()=>{for(let i=0;i<32;i++)await publish(await draft(i<2?'A identical':`B ${String(i).padStart(2,'0')}`));const first=await service().ops(),last=await service().ops(999);assert.equal(first.total,32);assert.equal(first.pages,2);assert.equal(first.items.length,30);assert.equal(last.page,2);assert.equal(last.items.length,2);assert.deepEqual(last.items.map(x=>x.title),['B 30','B 31']);assert.ok(first.items[0].id<first.items[1].id);assert.equal(new Set([...first.items,...last.items].map(x=>x.id)).size,32);for(const page of [0,-1,1.5,NaN,'1',2147483648])await assert.rejects(service().ops(page as number),/INVALID_INPUT/);});
test('empty allowed collection is distinct from denied access and pending membership or enrollment fail closed',async()=>{assert.deepEqual(await service().ops(),{items:[],total:0,page:1,pages:1});const operation=(await fixture.pool.query("INSERT INTO juyu.member_operations(actor_id,target_id,kind,requested_role) VALUES('a','o','role','support') RETURNING id")).rows[0].id;try{await assert.rejects(service().readerSections(),/FORBIDDEN/);await assert.rejects(service().ops(),/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.member_operations SET status='conflict',finished_at=now() WHERE id=$1",[operation]);}await fixture.pool.query("INSERT INTO juyu.role_enrollments(member_id,requested_role,purpose) VALUES('o','support','default')");try{await assert.rejects(service().readerSections(),/FORBIDDEN/);await assert.rejects(service().ops(),/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.role_enrollments SET state='complete',confirmed_at=now() WHERE member_id='o'");}});
test('support cannot discover or fetch OPS including malformed legacy staff audience across reader and personal surfaces',async()=>{const d=await publish(await draft('OPS secret')),file=await asset(d.id);// Deliberately simulate a legacy malformed row in this disposable cluster only.
 const owner=await fixture.pool.connect();try{await owner.query('BEGIN');await owner.query('ALTER TABLE juyu.revisions DISABLE TRIGGER immutable_revision');await owner.query("UPDATE juyu.revisions SET audience='staff' WHERE document_id=$1",[d.id]);await owner.query('ALTER TABLE juyu.revisions ENABLE TRIGGER immutable_revision');await owner.query('COMMIT');}catch(error){await owner.query('ROLLBACK');throw error;}finally{owner.release();}await fixture.pool.query("INSERT INTO juyu.favorites(member_id,document_id) VALUES('s',$1);",[d.id]);await fixture.pool.query("INSERT INTO juyu.recent_views(member_id,document_id,revision_id) VALUES('s',$1,1)",[d.id]);assert.deepEqual(await service(support).navigation(),[]);assert.deepEqual(await service(support).navigationTree(),[]);assert.equal((await service(support).search('OPS')).search.total,0);assert.equal((await service(support).reader(d.id)).article,null);assert.equal(await service(support).article(d.id),null);assert.equal(await service(support).asset(file),null);await assert.rejects(service(support).pdf(d.id,1),/NOT_FOUND/);await assert.rejects(service(support).feedback(d.id,1),/NOT_FOUND/);await assert.rejects(service(support).saveFeedback(d.id,{revision:1,helpful:true,comment:'',expectedVersion:0}),/NOT_FOUND/);await db.run(support,async c=>{for(const table of ['favorites','recent_views'])assert.deepEqual((await c.query(`SELECT * FROM juyu.${table}`)).rows,[]);});assert.equal((await service().article(d.id))?.revision_id,1);});
test('Ops reading grants no management editor submission review history or raw document access',async()=>{const d=await publish(await draft());for(const action of [()=>service().workspace(),()=>service().management(d.id),()=>service().editor(d.id),()=>service().saveDraft(d.id,{}),()=>service().submitReview(d.id,{}),()=>service().decideReview(d.id,{}),()=>service().history(d.id),()=>service().historyVersion(d.id,1),()=>service().restoreVersion(d.id,{})])await assert.rejects(action(),/FORBIDDEN/);assert.deepEqual(await db.run(ops,async c=>(await c.query('SELECT * FROM juyu.documents')).rows),[]);await assert.rejects(service(admin).saveDraft(randomUUID(),{expectedSequence:null,title:'Invalid Ops',body:encodeEditorBody([]),kind:'ops',audience:'staff',tags:[],cover:null}),/INVALID_INPUT/);});
test('unpublish archive and purge close collection and subsequent publication asset PDF and feedback reads',async()=>{for(const action of ['unpublish','archive','purge']){const d=await publish(await draft(action)),file=await asset(d.id);assert.equal((await service().ops()).items.length,1);assert.ok(await service().asset(file));assert.equal((await service().pdf(d.id,1)).article.revision,1);if(action==='unpublish')await service(admin).changeAvailability(d.id,{expectedSequence:d.sequence,action:'unpublish'});else if(action==='archive')await service(admin).changeAvailability(d.id,{expectedSequence:d.sequence,action:'archive'});else{await service(admin).lifecycle(d.id,{expectedSequence:d.sequence,action:'trash'});await service(admin).lifecycle(d.id,{expectedSequence:d.sequence+1,action:'purge',confirmation:action});}assert.equal((await service().ops()).total,0);assert.equal(await service().article(d.id),null);assert.equal(await service().asset(file),null);await assert.rejects(service().pdf(d.id,1),/NOT_FOUND/);await assert.rejects(service().feedback(d.id,1),/NOT_FOUND/);}});
test('SQL projection grants only the narrow formal collection and denies anonymous or support callers',async()=>{await publish(await draft());assert.equal((await fixture.pool.query("SELECT EXISTS(SELECT 1 FROM pg_proc p CROSS JOIN LATERAL aclexplode(p.proacl) a WHERE p.oid='juyu.read_ops_publications()'::regprocedure AND a.grantee=0 AND a.privilege_type='EXECUTE') ok")).rows[0].ok,false);await assert.rejects(runtime.query('SELECT * FROM juyu.read_ops_publications()'),/FORBIDDEN/);await assert.rejects(db.run(support,c=>c.query('SELECT * FROM juyu.read_ops_publications()')),/FORBIDDEN/);const rows=await db.run(ops,async c=>(await c.query('SELECT * FROM juyu.read_ops_publications()')).rows);assert.deepEqual(Object.keys(rows[0]).sort(),['id','revision','tags','title']);});
