import assert from 'node:assert/strict';
import {before,after,test} from 'node:test';
import {randomBytes,randomUUID} from 'node:crypto';
import type {Pool} from 'pg';
import {temporaryDatabase} from './fixture.ts';
import {migrate} from '../../src/server/database/migrate.ts';
import {ScopedDatabase} from '../../src/server/database/scoped.ts';
import {DocumentRepository} from '../../src/server/database/repository.ts';
import {AuthorizationService} from '../../src/server/authorization/service.ts';
import type {Viewer} from '../../src/domain/model.ts';
let fixture:Awaited<ReturnType<typeof temporaryDatabase>>,runtime:Pool,issuer:Pool,db:ScopedDatabase,repo:DocumentRepository;
const a:Viewer={id:'a',role:'admin',companyVerified:true},b:Viewer={...a,id:'b'},c:Viewer={...a,id:'c'},manager:Viewer={...a,id:'manager'},superAdmin:Viewer={id:'super',role:'super_admin',companyVerified:true},staff:Viewer={id:'staff',role:'support',companyVerified:true};
const service=(v:Viewer|null=manager)=>new AuthorizationService(db,async()=>v);
async function draft(){return repo.create({id:randomUUID(),kind:'article',title:'审核管理',body:'正式内容',audience:'staff'},a);}
async function pending(){const d=await draft();await service(a).submitReview(d.id,{expectedSequence:0,reviewerId:'b'});return d;}
async function restoreMember(id:string){await fixture.pool.query("UPDATE juyu.members SET disabled_at=null,observed_role='admin',verified_email=$2,observed_at=now() WHERE clerk_user_id=$1",[id,`${id}@example.test`]);}
before(async()=>{fixture=await temporaryDatabase();await migrate(fixture.pool);await fixture.pool.query("INSERT INTO juyu.members(clerk_user_id,display_name,observed_role,verified_email,observed_at) VALUES('a','A','admin','a@example.test',now()),('b','B','admin','b@example.test',now()),('c','C','admin','c@example.test',now()),('manager','Manager','admin','manager@example.test',now()),('super','Super','super_admin','super@example.test',now()),('staff','Support','support','staff@example.test',now())");const rp=randomBytes(24).toString('hex'),ip=randomBytes(24).toString('hex');await fixture.pool.query(`CREATE ROLE publication_runtime LOGIN PASSWORD '${rp}' IN ROLE juyu_runtime; CREATE ROLE publication_issuer LOGIN PASSWORD '${ip}' IN ROLE juyu_context_issuer`);runtime=fixture.connectAs('publication_runtime',rp);issuer=fixture.connectAs('publication_issuer',ip);db=new ScopedDatabase(runtime,issuer);repo=new DocumentRepository(db);});
after(async()=>{if(runtime)await runtime.end();if(issuer)await issuer.end();if(fixture)await fixture.close();});
test('publication boundary exists before releasing approved revisions',async()=>{
 assert.equal(typeof service().publicationDetail,'function');
 assert.equal(typeof service().changePublication,'function');
});
async function approved(){const d=await pending();await service(b).decideReview(d.id,{expectedSequence:1,action:'approve'});return (await repo.getForManagement(d.id,a))!;}
async function publish(id:string,sequence:number){await service().changePublication(id,{expectedSequence:sequence,action:'queue'});return service().changePublication(id,{expectedSequence:sequence+1,action:'publish'});}
async function asset(id:string,mime='image/png',status='ready'){const aid=randomUUID();await fixture.pool.query("INSERT INTO juyu.assets(id,document_id,uploaded_by,filename,mime_type,byte_size,object_key,status) VALUES($1::uuid,$2,'a','file',$3,4,$1::text,$4)",[aid,id,mime,status]);return aid;}
test('theme image requires both local ready images and publishes both authorized references',async()=>{
 const d=await draft(),other=await draft(),light=await asset(d.id),dark=await asset(d.id),foreign=await asset(other.id);
 const input=(darkAssetId:string)=>({type:'edit' as const,title:'主题图片',body:'正文',audience:'staff' as const,blocks:[{id:'theme',type:'image' as const,assetId:light,darkAssetId,caption:'',alt:'主题截图'}]});
 await assert.rejects(repo.execute(d.id,input(foreign),a,{expectedSequence:0}),/INVALID_MEDIA/);
 let edited=await repo.execute(d.id,input(dark),a,{expectedSequence:0});
 const associations=(await fixture.pool.query("SELECT asset_id FROM juyu.revision_assets WHERE document_id=$1 AND revision_id=$2 AND usage='inline'",[d.id,edited.workflow.revisionId])).rows.map(r=>r.asset_id);
 assert.deepEqual(new Set(associations),new Set([light,dark]));
 await service(a).submitReview(d.id,{expectedSequence:edited.sequence,reviewerId:'b'});edited=(await repo.getForManagement(d.id,a))!;
 await service(b).decideReview(d.id,{expectedSequence:edited.sequence,action:'approve'});edited=(await repo.getForManagement(d.id,a))!;
 await publish(d.id,edited.sequence);
 assert.ok(await service(staff).asset(light));assert.ok(await service(staff).asset(dark));
});
async function waitForLock(query:string,count=1){const deadline=Date.now()+3000;let n=0;while(Date.now()<deadline){n=(await fixture.pool.query("SELECT count(*)::int AS n FROM pg_stat_activity WHERE wait_event_type='Lock' AND query LIKE $1",[query])).rows[0].n;if(n>=count)break;await new Promise(r=>setTimeout(r,5));}assert.equal(n,count,'independent real DB connections must overlap');}
test('approved revision queues manually before publication and returns named immutable history',async()=>{
 const d=await approved(),detail=await service().publicationDetail(d.id);assert.equal(detail.revision,1);assert.equal(detail.article.sequence,2);assert.equal(detail.canQueue,true);assert.equal(detail.canPublish,false);assert.equal(detail.approval?.reviewerId,'b');assert.equal(detail.approval?.reviewerName,'B');assert.ok(detail.approval?.approvedAt);assert.deepEqual(detail.history,[]);
 await assert.rejects(service().changePublication(d.id,{expectedSequence:2,action:'publish'}),/INVALID_STATE/);
 const queued=await service().changePublication(d.id,{expectedSequence:2,action:'queue'});assert.deepEqual(queued,{documentId:d.id,sequence:3,revision:1,action:'queue',status:'queued',publishedRevision:null,approvedBy:'b'});assert.equal(await service(staff).article(d.id),null);assert.equal((await service().publicationDetail(d.id)).canPublish,true);
 const published=await service(c).changePublication(d.id,{expectedSequence:3,action:'publish'});assert.deepEqual(published,{documentId:d.id,sequence:4,revision:1,action:'publish',status:'published',publishedRevision:1,approvedBy:'b'});assert.equal((await service(staff).article(d.id))?.body,'正式内容');
 const saved=await service().publicationDetail(d.id);assert.equal(saved.canQueue,false);assert.equal(saved.canPublish,false);assert.equal(saved.historyMore,false);assert.deepEqual(saved.history.map(({at,...x})=>{assert.ok(at);return x;}),[{sequence:4,revision:1,action:'publish',actorId:'c',actorName:'C'},{sequence:3,revision:1,action:'queue',actorId:'manager',actorName:'Manager'}]);
});
test('Super Admin directly publishes only their own saved draft with exact retry acknowledgement',async()=>{
 const own=await repo.create({id:randomUUID(),kind:'article',title:'Super 草稿',body:'核对完成',audience:'staff'},superAdmin);
 assert.equal((await service().publicationDetail(own.id)).canDirectPublish,false);
 const detail=await service(superAdmin).publicationDetail(own.id);assert.equal(detail.canDirectPublish,true);assert.equal(detail.canQueue,false);assert.equal(detail.canPublish,false);
 await assert.rejects(service().changePublication(own.id,{expectedSequence:0,action:'direct_publish'}),/FORBIDDEN/);
 const input={expectedSequence:0,action:'direct_publish' as const};
 const first=await service(superAdmin).changePublication(own.id,input);
 assert.deepEqual(first,{documentId:own.id,sequence:1,revision:1,action:'direct_publish',status:'published',publishedRevision:1,approvedBy:'super'});
 assert.deepEqual(await service(superAdmin).changePublication(own.id,input),first);
 const saved=await repo.getForManagement(own.id,superAdmin);assert.equal(saved?.audit.filter(item=>item.action==='direct_publish').length,1);
 assert.equal((await service(superAdmin).publicationDetail(own.id)).history[0]?.action,'direct_publish');
 const other=await draft();assert.equal((await service(superAdmin).publicationDetail(other.id)).canDirectPublish,false);
 await assert.rejects(service(superAdmin).changePublication(other.id,{expectedSequence:0,action:'direct_publish'}),/FORBIDDEN/);
});
test('direct publication rechecks role after the document lock and validates pending uploads',async()=>{
 const own=await repo.create({id:randomUUID(),kind:'article',title:'锁定草稿',body:'正文',audience:'staff'},superAdmin);
 const pending=await asset(own.id,'image/png','pending');
 await assert.rejects(service(superAdmin).changePublication(own.id,{expectedSequence:0,action:'direct_publish'}),/UPLOAD_IN_PROGRESS/);
 await fixture.pool.query("UPDATE juyu.assets SET status='quarantined' WHERE id=$1",[pending]);
 const blocker=await fixture.pool.connect();await blocker.query('BEGIN');await blocker.query('SELECT id FROM juyu.documents WHERE id=$1 FOR UPDATE',[own.id]);
 const work=service(superAdmin).changePublication(own.id,{expectedSequence:0,action:'direct_publish'}).then(value=>({value,error:null}),error=>({value:null,error}));
 try{await waitForLock('SELECT id FROM juyu.documents%');await fixture.pool.query("UPDATE juyu.members SET observed_role='admin' WHERE clerk_user_id='super'");}finally{await blocker.query('COMMIT');blocker.release();}
 try{assert.match((await work).error?.message??'unexpected success',/FORBIDDEN/);assert.equal((await service(a).editor(own.id)).sequence,0);}finally{await fixture.pool.query("UPDATE juyu.members SET observed_role='super_admin' WHERE clerk_user_id='super'");}
});
test('only current eligible company Admin may read or publish even with stale trusted context',async()=>{
 const d=await approved();for(const v of [null,staff,{...manager,companyVerified:false}]){await assert.rejects(service(v).publicationDetail(d.id),/FORBIDDEN/);await assert.rejects(service(v).changePublication(d.id,{expectedSequence:2,action:'queue'}),/FORBIDDEN/);}
 for(const update of ["disabled_at=now()","observed_role='support'","verified_email=null","observed_at=null"]){await fixture.pool.query(`UPDATE juyu.members SET ${update} WHERE clerk_user_id='manager'`);try{await assert.rejects(service().publicationDetail(d.id),/FORBIDDEN/);await assert.rejects(service().changePublication(d.id,{expectedSequence:2,action:'queue'}),/FORBIDDEN/);}finally{await restoreMember('manager');}}
 const op=(await fixture.pool.query("INSERT INTO juyu.member_operations(actor_id,target_id,kind,requested_role) VALUES('a','manager','role','support') RETURNING id")).rows[0].id;try{await assert.rejects(service().publicationDetail(d.id),/FORBIDDEN/);await assert.rejects(service().changePublication(d.id,{expectedSequence:2,action:'queue'}),/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.member_operations SET status='conflict',finished_at=now() WHERE id=$1",[op]);}
 await fixture.pool.query("INSERT INTO juyu.role_enrollments(member_id,requested_role,purpose) VALUES('manager','support','default')");try{await assert.rejects(service().publicationDetail(d.id),/FORBIDDEN/);await assert.rejects(service().changePublication(d.id,{expectedSequence:2,action:'queue'}),/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.role_enrollments SET state='complete',confirmed_at=now() WHERE member_id='manager'");}
});
test('historical independent approval survives approver demotion and deactivation',async()=>{
 for(const update of ["disabled_at=now()","observed_role='support'","verified_email=null","observed_at=null"]){const d=await approved();await fixture.pool.query(`UPDATE juyu.members SET ${update} WHERE clerk_user_id='b'`);try{assert.equal((await service().publicationDetail(d.id)).canQueue,true);await publish(d.id,2);assert.equal((await service(staff).article(d.id))?.body,'正式内容');}finally{await restoreMember('b');}}
 const d=await pending();await service().changeReviewControl(d.id,{expectedSequence:1,action:'reassign',reviewerId:'c'});await service(c).decideReview(d.id,{expectedSequence:2,action:'approve'});assert.equal((await publish(d.id,3)).approvedBy,'c');
});
test('strict publication input rejects coercion, unknown scheduling fields and invalid sequence bounds',async()=>{
 const d=await approved();for(const input of [null,[],{}, {expectedSequence:2,action:'approve'},{expectedSequence:'2',action:'queue'},{expectedSequence:-1,action:'queue'},{expectedSequence:1.5,action:'queue'},{expectedSequence:2147483647,action:'queue'},{expectedSequence:NaN,action:'queue'},{expectedSequence:2,action:'publish',scheduledAt:'2026-09-10'},{expectedSequence:2,action:'queue',approvedBy:'b'}])await assert.rejects(service().changePublication(d.id,input),/INVALID_INPUT/);
 await assert.rejects(service().publicationDetail(' bad'),/INVALID_INPUT/);await assert.rejects(service().publicationDetail(randomUUID()),/NOT_FOUND/);await assert.rejects(service().changePublication(randomUUID(),{expectedSequence:0,action:'queue'}),/NOT_FOUND/);assert.equal((await service().editor(d.id)).sequence,2);
});
test('draft and pending versions cannot skip approval; new edits cannot reuse historical approval',async()=>{
 const d=await draft();assert.equal((await service().publicationDetail(d.id)).approval,null);await assert.rejects(service().changePublication(d.id,{expectedSequence:0,action:'queue'}),/INVALID_STATE/);await service(a).submitReview(d.id,{expectedSequence:0,reviewerId:'b'});await assert.rejects(service().changePublication(d.id,{expectedSequence:1,action:'queue'}),/INVALID_STATE/);await service(b).decideReview(d.id,{expectedSequence:1,action:'approve'});await repo.execute(d.id,{type:'edit',title:'新草稿',body:'未审核',audience:'staff'},a,{expectedSequence:2});const detail=await service().publicationDetail(d.id);assert.equal(detail.revision,2);assert.equal(detail.approval,null);assert.equal(detail.canQueue,false);await assert.rejects(service().changePublication(d.id,{expectedSequence:3,action:'queue'}),/INVALID_STATE/);
});
test('inactive documents cannot be read or acted on by the publication boundary',async()=>{
 for(const lifecycle of ['archived','trashed']){const d=await approved();await fixture.pool.query('UPDATE juyu.documents SET lifecycle=$2 WHERE id=$1',[d.id,lifecycle]);await assert.rejects(service().publicationDetail(d.id),/INACTIVE_DOCUMENT/);await assert.rejects(service().changePublication(d.id,{expectedSequence:2,action:'queue'}),/INACTIVE_DOCUMENT/);}
});
test('duplicate concurrent actions acknowledge exactly once; changed actor or later state never replay',async()=>{
 const d=await approved();for(const [action,expectedSequence] of [['queue',2],['publish',3]] as const){const input={action,expectedSequence},results=await Promise.all([service().changePublication(d.id,input),service().changePublication(d.id,input)]);assert.deepEqual(results[0],results[1]);const before=await repo.getForManagement(d.id,a);assert.deepEqual(await service().changePublication(d.id,input),results[0]);assert.deepEqual(await repo.getForManagement(d.id,a),before);await assert.rejects(service(c).changePublication(d.id,input),/CONFLICT/);}
 assert.equal((await service().publicationDetail(d.id)).history.length,2);await assert.rejects(service().changePublication(d.id,{expectedSequence:2,action:'queue'}),/CONFLICT/);await repo.execute(d.id,{type:'edit',title:'下一轮',body:'新',audience:'staff'},a,{expectedSequence:4});await service(a).submitReview(d.id,{expectedSequence:5,reviewerId:'b'});await service(b).decideReview(d.id,{expectedSequence:6,action:'approve'});await assert.rejects(service().changePublication(d.id,{expectedSequence:3,action:'publish'}),/CONFLICT/);
});
test('old formal content remains through approval and queue then publication changes audience, search, cover, tags, files and PDF access',async()=>{
 let d=await draft();const first=await asset(d.id),second=await asset(d.id),file=await asset(d.id,'application/pdf');d=await repo.execute(d.id,{type:'edit',title:'旧标题',body:'原正文',audience:'staff',tags:['旧标签'],cover:{assetId:first,alt:'旧图',position:50}},a,{expectedSequence:0});await service(a).submitReview(d.id,{expectedSequence:1,reviewerId:'b'});await service(b).decideReview(d.id,{expectedSequence:2,action:'approve'});await publish(d.id,3);
 d=await repo.execute(d.id,{type:'edit',title:'新标题',body:'新正文',audience:'admin',tags:['新标签'],cover:{assetId:second,alt:'新图',position:30},blocks:[{id:'file',type:'file',assetId:file,caption:'新附件',alt:''}]},a,{expectedSequence:5});await service(a).submitReview(d.id,{expectedSequence:6,reviewerId:'b'});await service(b).decideReview(d.id,{expectedSequence:7,action:'approve'});
 for(const sequence of [8,9]){const old=await service(staff).reader(d.id);assert.equal(old.article?.title,'旧标题');assert.deepEqual(old.article?.tags,['旧标签']);assert.ok(await service(staff).asset(first));assert.equal(await service(staff).asset(second),null);assert.ok(await service(staff).pdf(d.id,2));if(sequence===8)await service().changePublication(d.id,{expectedSequence:8,action:'queue'});}
 await service().changePublication(d.id,{expectedSequence:9,action:'publish'});assert.equal(await service(staff).article(d.id),null);await assert.rejects(service(staff).pdf(d.id,2),/NOT_FOUND/);assert.equal(await service(staff).asset(first),null);assert.equal(await service(staff).asset(file),null);assert.equal((await service(staff).navigation()).some(x=>x.id===d.id),false);const current=await service().reader(d.id);assert.equal(current.article?.body,'新正文');assert.deepEqual(current.article?.tags,['新标签']);assert.equal(current.article?.cover?.assetId,second);assert.equal(await service().asset(first),null);assert.ok(await service().asset(file));assert.ok(await service().pdf(d.id,3));await assert.rejects(service().pdf(d.id,2),/VERSION_CHANGED/);assert.equal((await service().pdf(d.id,3)).files[0]?.id,file);assert.equal((await service(staff).search("新标题")).search.total,0);
});
test('pending and quarantined referenced assets block queue and publish without partial history',async()=>{
 for(const action of ['queue','publish'] as const){const d=await approved();if(action==='publish')await service().changePublication(d.id,{expectedSequence:2,action:'queue'});const sequence=action==='queue'?2:3,attached=await asset(d.id);await fixture.pool.query("INSERT INTO juyu.revision_assets(document_id,revision_id,asset_id,usage) VALUES($1,1,$2,'attachment')",[d.id,attached]);const before=await repo.getForManagement(d.id,a);await fixture.pool.query("UPDATE juyu.assets SET status='quarantined' WHERE id=$1",[attached]);await assert.rejects(service().changePublication(d.id,{expectedSequence:sequence,action}),/INVALID_MEDIA/);await fixture.pool.query("UPDATE juyu.assets SET status='ready' WHERE id=$1",[attached]);const pendingAsset=await asset(d.id,'image/png','pending');await assert.rejects(service().changePublication(d.id,{expectedSequence:sequence,action}),/UPLOAD_IN_PROGRESS/);assert.deepEqual(await repo.getForManagement(d.id,a),before);await fixture.pool.query("UPDATE juyu.assets SET status='quarantined' WHERE id=$1",[pendingAsset]);await service().changePublication(d.id,{expectedSequence:sequence,action});}
});
test('mismatched completed receipts and forged approve audits fail closed while runtime cannot rewrite evidence',async()=>{
 const d=await approved();await assert.rejects(db.run(manager,c=>c.query("UPDATE juyu.reviews SET decided_at=now() WHERE document_id=$1",[d.id])),/permission denied|IMMUTABLE/);await assert.rejects(db.run(manager,c=>c.query("UPDATE juyu.audit_log SET actor_id='manager' WHERE document_id=$1",[d.id])),/permission denied|IMMUTABLE/);
 for(const [table,trigger,column,value] of [['reviews','preserve_review_history','decided_at',"decided_at+interval '1 second'"],['reviews','preserve_review_history','submitted_at',"submitted_at+interval '1 second'"],['reviews','preserve_review_history','submitted_by',"'c'"],['audit_log','immutable_audit','actor_id',"'manager'"]] as const){const owner=await fixture.pool.connect();await owner.query('BEGIN');try{await owner.query(`ALTER TABLE juyu.${table} DISABLE TRIGGER ${trigger}`);await owner.query(`UPDATE juyu.${table} SET ${column}=${value} WHERE document_id=$1 ${table==='audit_log'?"AND action='approve'":''}`,[d.id]);await owner.query(`ALTER TABLE juyu.${table} ENABLE TRIGGER ${trigger}`);await owner.query('COMMIT');}finally{owner.release();}try{const detail=await service().publicationDetail(d.id);assert.equal(detail.approval,null);assert.equal(detail.canQueue,false);await assert.rejects(service().changePublication(d.id,{expectedSequence:2,action:'queue'}),/INVALID_APPROVAL/);}finally{const restore=await fixture.pool.connect();await restore.query('BEGIN');try{await restore.query(`ALTER TABLE juyu.${table} DISABLE TRIGGER ${trigger}`);const original=table==='audit_log'?"'b'":column==='submitted_by'?"'a'":`${column}-interval '1 second'`;await restore.query(`UPDATE juyu.${table} SET ${column}=${original} WHERE document_id=$1 ${table==='audit_log'?"AND action='approve'":''}`,[d.id]);await restore.query(`ALTER TABLE juyu.${table} ENABLE TRIGGER ${trigger}`);await restore.query('COMMIT');}finally{restore.release();}}}
});
test('audit insertion failure rolls back both queue and publication pointer',async()=>{
 const d=await approved();await publish(d.id,2);await repo.execute(d.id,{type:'edit',title:'新',body:'不能半发布',audience:'staff'},a,{expectedSequence:4});await service(a).submitReview(d.id,{expectedSequence:5,reviewerId:'b'});await service(b).decideReview(d.id,{expectedSequence:6,action:'approve'});
 for(const action of ['queue','publish'] as const){const sequence=action==='queue'?7:8,before=await repo.getForManagement(d.id,a);await fixture.pool.query("CREATE FUNCTION juyu.fail_publication_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected publication failure'; END $$; CREATE TRIGGER fail_publication BEFORE INSERT ON juyu.audit_log FOR EACH ROW EXECUTE FUNCTION juyu.fail_publication_audit()");try{await assert.rejects(service().changePublication(d.id,{expectedSequence:sequence,action}),/injected publication failure/);assert.deepEqual(await repo.getForManagement(d.id,a),before);assert.equal((await service(staff).article(d.id))?.body,'正式内容');}finally{await fixture.pool.query('DROP TRIGGER fail_publication ON juyu.audit_log; DROP FUNCTION juyu.fail_publication_audit()');}if(action==='queue')await service().changePublication(d.id,{expectedSequence:7,action:'queue'});}
});
test('queue and publish compete with editing and trash on real document locks',async()=>{
 for(const action of ['queue','publish'] as const)for(const rival of ['edit','trash'] as const){const d=await approved();if(action==='publish')await service().changePublication(d.id,{expectedSequence:2,action:'queue'});const sequence=action==='queue'?2:3,blocker=await fixture.pool.connect();await blocker.query('BEGIN');await blocker.query('SELECT id FROM juyu.documents WHERE id=$1 FOR UPDATE',[d.id]);const first=service().changePublication(d.id,{expectedSequence:sequence,action});await waitForLock('SELECT id FROM juyu.documents%');const second=rival==='edit'?service(a).saveDraft(d.id,{expectedSequence:sequence,title:'竞争编辑',body:'JUYU_BLOCKNOTE_V1\n[]',kind:'article',audience:'staff',tags:[],cover:null}):service(a).lifecycle(d.id,{expectedSequence:sequence,action:'trash'});const work=Promise.allSettled([first,second]);try{await waitForLock(rival==='edit'?'SELECT pg_advisory_xact_lock(hashtextextended%':'SELECT * FROM juyu.change_document_lifecycle%');}finally{await blocker.query('ROLLBACK');blocker.release();}const results=await work;assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.match(String((results.find(x=>x.status==='rejected') as PromiseRejectedResult).reason),/CONFLICT|INACTIVE_DOCUMENT/);assert.equal((await service(a).editor(d.id)).sequence,sequence+1);}
});
test('actor role change committed while publication waits is rechecked after member lock',async()=>{
 for(const action of ['queue','publish'] as const){const d=await approved();if(action==='publish')await service().changePublication(d.id,{expectedSequence:2,action:'queue'});const sequence=action==='queue'?2:3,blocker=await fixture.pool.connect();await blocker.query('BEGIN');await blocker.query("UPDATE juyu.members SET observed_role='support' WHERE clerk_user_id='manager'");const work=service().changePublication(d.id,{expectedSequence:sequence,action}).then(value=>({value,error:null}),error=>({value:null,error}));try{await waitForLock('SELECT clerk_user_id FROM juyu.members%');}finally{await blocker.query('COMMIT');blocker.release();}try{assert.match((await work).error?.message??'unexpected success',/FORBIDDEN/);assert.equal((await service(a).editor(d.id)).sequence,sequence);}finally{await restoreMember('manager');}}
});
test('asset quarantine committed while publication waits is rechecked under SHARE lock',async()=>{
 const d=await approved(),attached=await asset(d.id);await fixture.pool.query("INSERT INTO juyu.revision_assets(document_id,revision_id,asset_id,usage) VALUES($1,1,$2,'attachment')",[d.id,attached]);const blocker=await fixture.pool.connect();await blocker.query('BEGIN');await blocker.query("UPDATE juyu.assets SET status='quarantined' WHERE id=$1",[attached]);const work=service().changePublication(d.id,{expectedSequence:2,action:'queue'}).then(value=>({value,error:null}),error=>({value:null,error}));try{await waitForLock('SELECT%FROM juyu.assets%FOR SHARE%');}finally{await blocker.query('COMMIT');blocker.release();}assert.match((await work).error?.message??'unexpected success',/INVALID_MEDIA/);assert.equal((await service(a).editor(d.id)).sequence,2);
});
test('member management exclusion lock yields explicit busy result',async()=>{
 const d=await approved(),lock=await issuer.connect();await lock.query('SELECT pg_advisory_lock(84620915)');try{await assert.rejects(service().changePublication(d.id,{expectedSequence:2,action:'queue'}),/MEMBER_BUSY/);}finally{await lock.query('SELECT pg_advisory_unlock(84620915)');lock.release();}
});
test('publication history is capped at last 20 events with truthful continuation indicator',async()=>{
 let d=await approved();for(let round=0;round<11;round++){await publish(d.id,d.sequence);if(round<10){d=await repo.execute(d.id,{type:'edit',title:`轮次${round}`,body:'正文',audience:'staff'},a,{expectedSequence:d.sequence+2});await service(a).submitReview(d.id,{expectedSequence:d.sequence,reviewerId:'b'});await service(b).decideReview(d.id,{expectedSequence:d.sequence+1,action:'approve'});d=(await repo.getForManagement(d.id,a))!;}}const detail=await service().publicationDetail(d.id);assert.equal(detail.history.length,20);assert.equal(detail.historyMore,true);assert.equal(detail.history[0].sequence,54);assert.equal(detail.history.at(-1)?.sequence,8);
});
test('restored documents require a fresh review and historical action replay conflicts',async()=>{
 for(const queued of [false,true]){const d=await approved();if(queued)await service().changePublication(d.id,{expectedSequence:2,action:'queue'});const sequence=queued?3:2;await service(a).lifecycle(d.id,{expectedSequence:sequence,action:'trash'});await service(a).lifecycle(d.id,{expectedSequence:sequence+1,action:'restore'});const detail=await service().publicationDetail(d.id);assert.equal(detail.approval,null);assert.equal(detail.canQueue,false);assert.equal(detail.canPublish,false);assert.equal(detail.article.status,'draft');if(queued)await assert.rejects(service().changePublication(d.id,{expectedSequence:2,action:'queue'}),/CONFLICT/);await assert.rejects(service().changePublication(d.id,{expectedSequence:sequence+2,action:queued?'publish':'queue'}),/INVALID_STATE/);await service(a).submitReview(d.id,{expectedSequence:sequence+2,reviewerId:'b'});await service(b).decideReview(d.id,{expectedSequence:sequence+3,action:'approve'});await publish(d.id,sequence+4);}
});
