import assert from 'node:assert/strict';
import {before,after,beforeEach,test} from 'node:test';
import {randomBytes,randomUUID} from 'node:crypto';
import type {Pool} from 'pg';
import {temporaryDatabase} from './fixture.ts';
import {migrate} from '../../src/server/database/migrate.ts';
import {ScopedDatabase} from '../../src/server/database/scoped.ts';
import {DocumentRepository} from '../../src/server/database/repository.ts';
import {AuthorizationService} from '../../src/server/authorization/service.ts';
import {encodeEditorBody} from '../../src/editor/document.ts';
import type {Viewer,Document} from '../../src/domain/model.ts';
import type {MediaBlock} from '../../src/media/model.ts';
let fixture:Awaited<ReturnType<typeof temporaryDatabase>>,runtime:Pool,issuer:Pool,db:ScopedDatabase,repo:DocumentRepository;
const admin:Viewer={id:'a',role:'admin',companyVerified:true},reviewer:Viewer={...admin,id:'b'},ops:Viewer={id:'o',role:'ops',companyVerified:true},support:Viewer={id:'s',role:'support',companyVerified:true};
const service=(v:Viewer|null=support)=>new AuthorizationService(db,async()=>v);
const table={id:'formal-table',type:'table' as const,headers:['Name','Value'],rows:[['Formal example','Original']]};
async function draft(title='Reference formal',kind:Document['kind']='reference',audience:'ops'|'admin'|'staff'='staff',body='Formal body',blocks:MediaBlock[]=[]){return repo.create({id:randomUUID(),kind,title,audience,body,blocks,tags:['Formal tag']},admin);}
async function publish(d:Document){await service(admin).submitReview(d.id,{expectedSequence:d.sequence,reviewerId:'b'});await service(reviewer).decideReview(d.id,{expectedSequence:d.sequence+1,action:'approve'});await service(admin).changePublication(d.id,{expectedSequence:d.sequence+2,action:'queue'});await service(admin).changePublication(d.id,{expectedSequence:d.sequence+3,action:'publish'});return (await repo.getForManagement(d.id,admin))!;}
async function replaceBody(id:string,body:string){const c=await fixture.pool.connect();try{await c.query('BEGIN');await c.query('ALTER TABLE juyu.revisions DISABLE TRIGGER immutable_revision');await c.query('UPDATE juyu.revisions SET body=$2 WHERE document_id=$1',[id,body]);await c.query('ALTER TABLE juyu.revisions ENABLE TRIGGER immutable_revision');await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
before(async()=>{fixture=await temporaryDatabase();await migrate(fixture.pool);await fixture.pool.query("INSERT INTO juyu.members(clerk_user_id,display_name,observed_role,verified_email,observed_at) VALUES('a','Admin','admin','a@example.test',now()),('b','Reviewer','admin','b@example.test',now()),('o','Ops','ops','o@example.test',now()),('s','Support','support','s@example.test',now())");const rp=randomBytes(24).toString('hex'),ip=randomBytes(24).toString('hex');await fixture.pool.query(`CREATE ROLE reference_runtime LOGIN PASSWORD '${rp}' IN ROLE juyu_runtime; CREATE ROLE reference_issuer LOGIN PASSWORD '${ip}' IN ROLE juyu_context_issuer`);runtime=fixture.connectAs('reference_runtime',rp);issuer=fixture.connectAs('reference_issuer',ip);db=new ScopedDatabase(runtime,issuer);repo=new DocumentRepository(db);});
after(async()=>{await runtime?.end();await issuer?.end();await fixture?.close();});
beforeEach(async()=>{await fixture.pool.query('TRUNCATE juyu.documents CASCADE');});
test('Reference boundary provides collection and selected formal table detail',()=>{assert.equal(typeof (service() as unknown as Record<string,unknown>).reference,'function');assert.equal(typeof (service() as unknown as Record<string,unknown>).referenceDetail,'function');});
test('Reference collection includes only current allowed published references with current Admin editing flag',async()=>{const allowed=await publish(await draft());const hidden=await publish(await draft('Admin only','reference','admin'));const opsOnly=await publish(await draft('Ops only','reference','ops'));for(const kind of ['article','qa','ops'] as const)await publish(await draft(kind,kind,kind==='ops'?'ops':'staff'));const unpublished=await draft('Draft');
 const parent=randomUUID(),child=randomUUID();await fixture.pool.query("INSERT INTO juyu.categories(id,name,audience,parent_id) VALUES($1,'Restricted parent','admin',null),($2,'Child','staff',$1)",[parent,child]);const restricted=await publish(await draft('Ancestor restricted'));await fixture.pool.query('INSERT INTO juyu.revision_categories VALUES($1,1,$2)',[restricted.id,child]);const disabled=await publish(await draft('Disabled ancestor'));const dp=randomUUID(),dc=randomUUID();await fixture.pool.query("INSERT INTO juyu.categories(id,name,audience,parent_id,enabled) VALUES($1,'Disabled','staff',null,false),($2,'Child','staff',$1,true)",[dp,dc]);await fixture.pool.query('INSERT INTO juyu.revision_categories VALUES($1,1,$2)',[disabled.id,dc]);
 assert.deepEqual(await service().reference(),{items:[{id:allowed.id,title:'Reference formal',revision:1,tags:['Formal tag']}],total:1,page:1,pages:1,canEdit:false});assert.equal((await service(ops).reference()).total,2);const ap=await service(admin).reference();assert.equal(ap.canEdit,true);assert.equal(ap.total,4);assert.deepEqual(new Set(ap.items.map(x=>x.id)),new Set([allowed.id,hidden.id,opsOnly.id,restricted.id]));for(const id of [hidden.id,opsOnly.id,restricted.id,disabled.id,unpublished.id])await assert.rejects(service().referenceDetail(id),/NOT_FOUND/);
});
test('Reference pagination counts only permitted rows, orders by title and id and validates inputs',async()=>{for(let i=0;i<22;i++)await publish(await draft(i<2?'A identical':`B ${String(i).padStart(2,'0')}`));await publish(await draft('Hidden','reference','admin'));const first=await service().reference(),last=await service().reference(999);assert.equal(first.total,22);assert.equal(first.pages,2);assert.equal(first.items.length,20);assert.equal(last.page,2);assert.deepEqual(last.items.map(x=>x.title),['B 20','B 21']);assert.ok(first.items[0].id<first.items[1].id);assert.equal(new Set([...first.items,...last.items].map(x=>x.id)).size,22);for(const page of [0,-1,1.5,NaN,'1',2147483648])await assert.rejects(service().reference(page as number),/INVALID_INPUT/);for(const id of ['', ' bad ', 'x'.repeat(201),[],null])await assert.rejects(service().referenceDetail(id as string),/INVALID_INPUT/);await assert.rejects(service().referenceDetail(randomUUID()),/NOT_FOUND/);});
test('Reference distinguishes empty collection and empty tables from forbidden identities and stale Admin role',async()=>{assert.deepEqual(await service().reference(),{items:[],total:0,page:1,pages:1,canEdit:false});const d=await publish(await draft());assert.deepEqual((await service().referenceDetail(d.id)).tables,[]);for(const v of [null,{...support,companyVerified:false},{...support,role:'owner'}])await assert.rejects(service(v as Viewer|null).reference(),/FORBIDDEN/);for(const id of ['s','a']){for(const state of ["disabled_at=now()",`observed_role='${id==='a'?'support':'ops'}'`,"verified_email=null","observed_at=null"]){await fixture.pool.query(`UPDATE juyu.members SET ${state} WHERE clerk_user_id=$1`,[id]);try{const v=id==='a'?admin:support;await assert.rejects(service(v).reference(),/FORBIDDEN/);await assert.rejects(service(v).referenceDetail(d.id),/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.members SET disabled_at=null,observed_role=$2,verified_email=$3,observed_at=now() WHERE clerk_user_id=$1",[id,id==='a'?'admin':'support',`${id}@example.test`]);}}}});
test('Reference rejects pending member operations and pending enrollment on collection and detail',async()=>{const d=await publish(await draft());const operation=(await fixture.pool.query("INSERT INTO juyu.member_operations(actor_id,target_id,kind,requested_role) VALUES('a','s','role','ops') RETURNING id")).rows[0].id;try{await assert.rejects(service().reference(),/FORBIDDEN/);await assert.rejects(service().referenceDetail(d.id),/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.member_operations SET status='conflict',finished_at=now() WHERE id=$1",[operation]);}await fixture.pool.query("INSERT INTO juyu.role_enrollments(member_id,requested_role,purpose) VALUES('s','support','default')");try{await assert.rejects(service().reference(),/FORBIDDEN/);await assert.rejects(service().referenceDetail(d.id),/FORBIDDEN/);}finally{await fixture.pool.query("UPDATE juyu.role_enrollments SET state='complete',confirmed_at=now() WHERE member_id='s'");}});
test('Reference projects pipe tables then legacy blocks, without prose or other block payloads',async()=>{const body='Private prose not needed\n\n| Header A | Header B |\n| --- | --- |\n| Row A | Row B |\n\n| Empty A | Empty B |\n| --- | --- |';const d=await publish(await draft('Legacy','reference','staff',body,[table,{id:'hint',type:'hint',style:'info',title:'Other payload',body:'Exclude this prose'}]));const detail=await service().referenceDetail(d.id);assert.deepEqual(detail.tables,[{id:'legacy:1',headers:['Header A','Header B'],rows:[['Row A','Row B']]},{id:'legacy:2',headers:['Empty A','Empty B'],rows:[]},{id:table.id,headers:table.headers,rows:table.rows}]);assert.deepEqual(Object.keys(detail).sort(),['id','revision','tables','tags','title']);assert.ok(!JSON.stringify(detail).includes('Private prose'));assert.ok(!JSON.stringify(detail).includes('Exclude this prose'));assert.ok(!JSON.stringify(await service().reference()).includes('Row A'));});
test('Reference traverses nested BlockNote tables once in document order and fails closed for corrupt bodies',async()=>{const second={...table,id:'second',rows:[]};const body=encodeEditorBody([{id:'parent',type:'paragraph',content:[{type:'text',text:'Private prose',styles:{}}],children:[{id:table.id,type:'juyu',props:{payload:JSON.stringify(table)}}]},{id:second.id,type:'juyu',props:{payload:JSON.stringify(second)}}]);const d=await publish(await draft('Structured','reference','staff',body,[table,second]));assert.deepEqual((await service().referenceDetail(d.id)).tables,[{id:table.id,headers:table.headers,rows:table.rows},{id:second.id,headers:second.headers,rows:[]}]);await replaceBody(d.id,'JUYU_BLOCKNOTE_V1\n{"secret":"never expose raw JSON"}');await assert.rejects(service().referenceDetail(d.id),/INVALID_EDITOR_DOCUMENT/);});
test('Reference excludes other kinds from selected detail and gives readers no editor history or raw document grants',async()=>{for(const kind of ['article','qa','ops'] as const){const d=await publish(await draft(kind,kind,kind==='ops'?'ops':'staff','body',[table]));await assert.rejects(service(admin).referenceDetail(d.id),/NOT_FOUND/);}const d=await publish(await draft());for(const v of [support,ops]){assert.equal((await service(v).reference()).canEdit,false);for(const action of [()=>service(v).editor(d.id),()=>service(v).saveDraft(d.id,{}),()=>service(v).history(d.id),()=>service(v).submitReview(d.id,{})])await assert.rejects(action(),/FORBIDDEN/);assert.deepEqual(await db.run(v,async c=>(await c.query('SELECT * FROM juyu.documents')).rows),[]);}});
test('Reference editor tables preserve old formal data until a different Admin reviews and publishes the new revision',async()=>{const id=randomUUID();const body=(value:string)=>encodeEditorBody([{id:table.id,type:'juyu',props:{payload:JSON.stringify({...table,rows:[[value,'Example']]})}}]);const input={expectedSequence:null,title:'Formal table',body:body('Old formal'),kind:'reference',audience:'staff',tags:['Old tag'],cover:null};await service(admin).saveDraft(id,input);let d=await publish((await repo.getForManagement(id,admin))!);const oldDetail=await service().referenceDetail(id);await service(admin).saveDraft(id,{...input,expectedSequence:d.sequence,title:'New table',body:body('New draft'),tags:['New tag']});assert.deepEqual(await service().referenceDetail(id),oldDetail);assert.equal((await service().reference()).items[0].title,'Formal table');d=(await repo.getForManagement(id,admin))!;await service(admin).submitReview(id,{expectedSequence:d.sequence,reviewerId:'b'});await assert.rejects(service(admin).decideReview(id,{expectedSequence:d.sequence+1,action:'approve'}),/NOT_REVIEWER/);assert.deepEqual(await service().referenceDetail(id),oldDetail);await service(reviewer).decideReview(id,{expectedSequence:d.sequence+1,action:'approve'});await service(admin).changePublication(id,{expectedSequence:d.sequence+2,action:'queue'});assert.deepEqual(await service().referenceDetail(id),oldDetail);await service(admin).changePublication(id,{expectedSequence:d.sequence+3,action:'publish'});const detail=await service().referenceDetail(id);assert.equal(detail.revision,2);assert.equal(detail.title,'New table');assert.deepEqual(detail.tables[0].rows,[['New draft','Example']]);assert.deepEqual(detail.tags,['New tag']);assert.ok((await service(admin).historyVersion(id,1)).version.body.includes('Old formal'));assert.ok((await service(admin).historyVersion(id,2)).version.body.includes('New draft'));assert.equal((await service().article(id))?.revision_id,2);});
test('Reference unpublish archive trash and purge hide later collection detail reader and PDF accesses',async()=>{for(const action of ['unpublish','archive','trash','purge']){const d=await publish(await draft(action,'reference','staff','body',[table]));assert.equal((await service().reference()).total,1);assert.equal((await service().referenceDetail(d.id)).tables.length,1);if(action==='unpublish'||action==='archive')await service(admin).changeAvailability(d.id,{expectedSequence:d.sequence,action});else{await service(admin).lifecycle(d.id,{expectedSequence:d.sequence,action:'trash'});if(action==='purge')await service(admin).lifecycle(d.id,{expectedSequence:d.sequence+1,action:'purge',confirmation:action});}assert.equal((await service().reference()).total,0);await assert.rejects(service().referenceDetail(d.id),/NOT_FOUND/);assert.equal(await service().article(d.id),null);await assert.rejects(service().pdf(d.id,1),/NOT_FOUND/);}});
test('Reference SQL collection projection grants only authorized metadata and denies anonymous callers',async()=>{await publish(await draft());assert.equal((await fixture.pool.query("SELECT EXISTS(SELECT 1 FROM pg_proc p CROSS JOIN LATERAL aclexplode(p.proacl) a WHERE p.oid='juyu.read_reference_publications()'::regprocedure AND a.grantee=0 AND a.privilege_type='EXECUTE') ok")).rows[0].ok,false);await assert.rejects(runtime.query('SELECT * FROM juyu.read_reference_publications()'),/FORBIDDEN/);const rows=await db.run(support,async c=>(await c.query('SELECT * FROM juyu.read_reference_publications()')).rows);assert.deepEqual(Object.keys(rows[0]).sort(),['id','revision','tags','title']);});
