export const navigationPages=['home','ops','reference','qa','favorites','recent','forms'] as const;
export type NavigationPage=typeof navigationPages[number];
export type NavigationTarget={type:'page';page:NavigationPage}|{type:'category';categoryId:string};
export interface NavigationEntry {id:string;label:string;enabled:boolean;roles:('support'|'ops'|'admin')[];target:NavigationTarget}
export interface NavigationConfig {version:number;entries:NavigationEntry[]}
export interface NavigationWrite {expectedVersion:number;entries:NavigationEntry[]}
export interface MenuItem {id:string;label:string;href:string}
const roles=['support','ops','admin'] as const;
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const bad=():never=>{throw new Error('INVALID_INPUT');};
function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))return bad();return value as Record<string,unknown>;}
function exact(value:Record<string,unknown>,keys:string[]){if(Object.keys(value).length!==keys.length||keys.some(k=>!Object.hasOwn(value,k)))bad();}
function label(value:unknown):string{if(typeof value!=='string'||!value.trim()||[...value.trim()].length>80||/[\u0000-\u001f\u007f-\u009f]/.test(value))return bad();return value.trim();}
function target(value:unknown):NavigationTarget{const x=object(value);if(x.type==='page'){exact(x,['type','page']);if(!navigationPages.includes(x.page as NavigationPage))return bad();return {type:'page',page:x.page as NavigationPage};}if(x.type==='category'){exact(x,['type','categoryId']);if(typeof x.categoryId!=='string'||!uuid.test(x.categoryId))return bad();return {type:'category',categoryId:x.categoryId};}return bad();}
function entries(value:unknown,canonical=false):NavigationEntry[]{if(!Array.isArray(value)||value.length>40)return bad();const out=value.map(v=>{const x=object(v);exact(x,['id','label','enabled','roles','target']);if(typeof x.id!=='string'||!uuid.test(x.id)||typeof x.enabled!=='boolean'||!Array.isArray(x.roles)||x.roles.length<1||x.roles.length>3||x.roles.some(r=>!roles.includes(r))||new Set(x.roles).size!==x.roles.length)return bad();const sorted=roles.filter(r=>(x.roles as unknown[]).includes(r)),name=label(x.label);if(canonical&&(name!==x.label||JSON.stringify(sorted)!==JSON.stringify(x.roles)))return bad();return {id:x.id,label:name,enabled:x.enabled,roles:sorted,target:target(x.target)};});if(new Set(out.map(e=>e.id)).size!==out.length)return bad();return out;}
function version(value:unknown):number{if(!Number.isSafeInteger(value)||Number(value)<0||Number(value)>=2147483647)return bad();return Number(value);}
export function parseNavigationWrite(value:unknown):NavigationWrite{const x=object(value);exact(x,['expectedVersion','entries']);return {expectedVersion:version(x.expectedVersion),entries:entries(x.entries)};}
export function normalizeNavigationConfig(value:unknown):NavigationConfig{const x=object(value);exact(x,['version','entries']);return {version:version(x.version),entries:entries(x.entries,true)};}
export function navigationHref(value:NavigationTarget):string{const normalized=target(value);return normalized.type==='page'?(normalized.page==='home'?'/help-centre':`/help-centre/${normalized.page}`):`/help-centre/categories/${normalized.categoryId}`;}
export function normalizeMenuItems(value:unknown):MenuItem[]{if(!Array.isArray(value)||value.length>40)return bad();const allowed=navigationPages.map(page=>navigationHref({type:'page',page}));const items=value.map(v=>{const x=object(v);exact(x,['id','label','href']);if(typeof x.id!=='string'||!uuid.test(x.id)||typeof x.href!=='string'||(!allowed.includes(x.href)&&!/^\/help-centre\/categories\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(x.href)))return bad();const name=label(x.label);if(name!==x.label)return bad();return {id:x.id,label:name,href:x.href};});if(new Set(items.map(x=>x.id)).size!==items.length)return bad();return items;}
export const defaultNavigationEntries:NavigationEntry[]=navigationPages.map((page,index)=>({id:`00000000-0000-4000-8000-${String(index+1).padStart(12,'0')}`,label:({home:'帮助中心',ops:'OPS Internal',reference:'Reference 速查',qa:'Q&A 问答',favorites:'我的收藏',recent:'最近浏览',forms:'内部表单'})[page],enabled:true,roles:page==='ops'?['ops','admin']:['support','ops','admin'],target:{type:'page',page}}));
