import {requireFeature} from '../features/repository.ts';
import type {PoolClient} from 'pg';
import {normalizeForms,parseFormWrite,parseSubmission,normalizeReceipt,normalizeRecord,normalizeRecordPage,parseProcessInput,normalizeProcessAck,type FormDefinition,type Receipt,type FormRecord,type FormRecordPage,type ProcessAck} from '../../forms/model.ts';
function id(value:string){if(typeof value!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(value))throw new Error('INVALID_INPUT');return value;}
export async function readForms(c:PoolClient,admin=false):Promise<FormDefinition[]>{await requireFeature(c,'forms');return normalizeForms((await c.query('SELECT juyu.read_forms($1) AS forms',[admin])).rows[0].forms);}
export async function readForm(c:PoolClient,formId:string,admin=false):Promise<FormDefinition>{await requireFeature(c,'forms');return normalizeForms([(await c.query('SELECT juyu.read_form($1,$2) AS form',[id(formId),admin])).rows[0].form])[0];}
export async function writeForm(c:PoolClient,formId:string,value:unknown):Promise<FormDefinition>{await requireFeature(c,'forms');const {expectedVersion,...config}=parseFormWrite(value);return normalizeForms([(await c.query('SELECT juyu.write_form($1,$2,$3) AS form',[id(formId),expectedVersion,JSON.stringify(config)])).rows[0].form])[0];}
export async function submitForm(c:PoolClient,formId:string,value:unknown):Promise<Receipt>{await requireFeature(c,'forms');const input=parseSubmission(value);return normalizeReceipt((await c.query('SELECT juyu.submit_form($1,$2,$3,$4) AS receipt',[id(formId),input.id,input.formVersion,JSON.stringify(input.values)])).rows[0].receipt);}
export async function readFormRecords(c:PoolClient,page=1):Promise<FormRecordPage>{await requireFeature(c,'forms');if(!Number.isSafeInteger(page)||page<1||page>=2147483647)throw new Error('INVALID_INPUT');return normalizeRecordPage((await c.query('SELECT juyu.read_form_records($1) AS records',[page])).rows[0].records);}
export async function readFormRecord(c:PoolClient,recordId:string):Promise<FormRecord>{await requireFeature(c,'forms');return normalizeRecord((await c.query('SELECT juyu.read_form_record($1) AS record',[id(recordId)])).rows[0].record);}
export async function processFormRecord(c:PoolClient,recordId:string,value:unknown):Promise<ProcessAck>{await requireFeature(c,'forms');const input=parseProcessInput(value);return normalizeProcessAck((await c.query('SELECT juyu.process_form_record($1,$2,$3,$4) AS result',[id(recordId),input.expectedSequence,input.status,input.note])).rows[0].result);}
