import {contentPath} from '../../reader/content-path';
import type {RecentPage} from '../../recent/model';
import {kinds} from '../../workspace/model';
import {SearchResultItem} from '../gitbook/Search/SearchResultItem';
function viewedTime(value:string,locale:'zh-CN'|'en'){return new Intl.DateTimeFormat(locale==='en'?'en-MY':'zh-CN',{timeZone:'Asia/Kuala_Lumpur',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value));}
export function RecentView({data,state,locale='zh-CN'}:{data?:RecentPage;state:'ready'|'denied'|'unavailable';locale?:'zh-CN'|'en'}){
 const english=locale==='en',base=english?'/help-centre/recent?lang=en':'/help-centre/recent',pageHref=(page:number)=>`${base}${english?'&':'?'}page=${page}`;
 return <section className="favorites-view recent-view" aria-label={english?'Recently viewed':'最近浏览'}><a className="search-back" href={english?'/help-centre?lang=en':'/help-centre'}>{english?'← Help Centre':'← 返回员工资料库'}</a><header><p className="reader-eyebrow">PERSONAL</p><h1>{english?'Recently viewed':'最近浏览'}</h1><p className="reader-description">{english?'Pick up where you left off. This list holds up to 100 items and only shows published content you can still access.':'找回最近打开的资料。每人最多保留 100 篇，只显示你目前有权阅读的正式内容。'}</p></header>
 {state!=='ready'||!data?<div role="alert" className="search-state"><h2>{english?(state==='denied'?'Your recent items are unavailable':'Recent items are unavailable right now'):state==='denied'?'最近浏览访问已暂停':'最近浏览暂时无法读取'}</h2><p>{english?'Please try again. If this keeps happening, contact an admin.':'请重新读取；如果持续失败，请联系管理员。'}</p><a className="secondary-link" href={base}>{english?'Try again':'重新读取最近浏览'}</a></div>:<><a className="secondary-link" href={pageHref(data.page)}>{english?'Refresh':'刷新最近浏览'}</a><p className="search-summary" role="status">{english?`${data.total} items you can still read · Page ${data.page} of ${data.pages}`:`共 ${data.total} 篇可阅读的资料 · 第 ${data.page} / ${data.pages} 页`}</p>
 {data.items.length?<ul className="gitbook-search-results" aria-label={english?'Recently viewed publications':'最近打开的正式资料'}>{data.items.map(item=><li key={item.id}><SearchResultItem href={contentPath(item.kind,item.id,locale)} label={english?`Read again: ${item.title}`:`再次阅读：${item.title}`} leadingIcon={<span aria-hidden="true">↺</span>}><p className="search-result-breadcrumbs">{english?{article:'Article',ops:'OPS Internal',reference:'Reference',qa:'Q&A'}[item.kind]:kinds[item.kind]} · {english?'Published':'已发布'}{item.viewedRevision!==item.revision?(english?' · Updated since your last visit':' · 上次阅读后有更新'):''}</p><h2>{item.title}</h2>{item.tags.length>0&&<p className="search-result-breadcrumbs">{item.tags.join(' · ')}</p>}<p className="search-result-breadcrumbs">{english?'Last viewed ':'上次打开 '}<time dateTime={item.viewedAt}>{viewedTime(item.viewedAt,locale)}</time>（UTC+8）</p></SearchResultItem></li>)}</ul>:<div className="search-state"><h2>{english?'Nothing here yet':'暂无可阅读的浏览记录'}</h2><p>{english?'Open a published article to see it here. Unpublished items and content you can no longer access stay hidden.':'打开正式文章后会自动记录。已下线或不再有权阅读的资料不会显示。'}</p><a className="secondary-link" href={english?'/help-centre?lang=en':'/help-centre'}>{english?'Browse articles':'前往资料库'}</a></div>}
 {data.pages>1&&<nav className="search-pagination" aria-label={english?'Recently viewed pages':'最近浏览翻页'}>{data.page>1&&<a className="secondary-link" href={pageHref(data.page-1)}>{english?'Previous':'上一页'}</a>}<span>{data.page} / {data.pages}</span>{data.page<data.pages&&<a className="secondary-link" href={pageHref(data.page+1)}>{english?'Next':'下一页'}</a>}</nav>}
 </>}
 </section>;
}
