import {normalizeFieldDefinitions,type FieldDefinition} from '../fields/model.ts';
export interface FormField {field:FieldDefinition;required:boolean;width:'full'|'half'}
export interface FormDefinition {id:string;version:number;title:string;description:string;audience:'staff'|'ops'|'admin';enabled:boolean;fields:FormField[]}
export interface FormWrite {expectedVersion:number|null;title:string;description:string;audience:'staff'|'ops'|'admin';enabled:boolean;fields:{id:string;version:number;required:boolean;width:'full'|'half'}[]}
export interface FormValue {fieldId:string;value:string|number|boolean|null}
export interface SubmissionInput {id:string;formVersion:number;values:FormValue[]}
export interface Receipt {id:string;formId:string;formVersion:number;submittedAt:string}
export interface FormRecord {id:string;formId:string;formVersion:number;title:string;submittedBy:{id:string;name:string};submittedAt:string;status:'new'|'processing'|'resolved';sequence:number;note:string;processedBy:{id:string;name:string}|null;processedAt:string|null;fields:FormField[];values:FormValue[]}
export interface ProcessInput {expectedSequence:number;status:'processing'|'resolved';note:string}
export interface ProcessAck {id:string;sequence:number;status:'processing'|'resolved';note:string;processedBy:{id:string;name:string};processedAt:string}
export interface FormRecordPage {items:FormRecord[];total:number;page:number;pages:number}
const fail=():never=>{throw new Error('INVALID_INPUT');};
const record=(v:unknown):Record<string,unknown>=>{if(!v||typeof v!=='object'||Array.isArray(v))return fail();return v as Record<string,unknown>;};
const exact=(x:Record<string,unknown>,keys:string[])=>{if(Object.keys(x).length!==keys.length||keys.some(k=>!Object.hasOwn(x,k)))fail();};
const integer=(v:unknown,min=1)=>Number.isSafeInteger(v)&&Number(v)>=min&&Number(v)<2147483647;
const uuid=(v:unknown):v is string=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(v);
function string(v:unknown,max:number,required=false):string{if(typeof v!=='string'||[...v].length>max||/\u0000/.test(v)||(required&&!v.trim()))return fail();return v;}
function title(v:unknown):string{const s=string(v,120,true);if(/[\u0000-\u001f\u007f-\u009f]/.test(s))return fail();return s.trim();}
function timestamp(v:unknown):string{if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}T(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d{1,6})?(?:Z|[+-](?:[01]\d|2[0-3]):[0-5]\d)$/.test(v)||v.startsWith('0000-')||!Number.isFinite(Date.parse(v)))return fail();const calendar=new Date(`${v.slice(0,10)}T00:00:00.000Z`);if(!Number.isFinite(calendar.getTime())||calendar.toISOString().slice(0,10)!==v.slice(0,10))return fail();return new Date(v).toISOString();}
function person(v:unknown){const x=record(v);exact(x,['id','name']);return {id:string(x.id,200,true),name:string(x.name,200,true)};}
function fieldList(value:unknown):FormField[]{if(!Array.isArray(value)||value.length<1||value.length>20)return fail();const fields=value.map(v=>{const x=record(v);exact(x,['field','required','width']);if(typeof x.required!=='boolean'||!['full','half'].includes(String(x.width)))return fail();return {field:normalizeFieldDefinitions([x.field])[0],required:x.required,width:x.width as FormField['width']};});if(new Set(fields.map(f=>f.field.id)).size!==fields.length)return fail();return fields;}
export function parseFormWrite(value:unknown):FormWrite{
 const x=record(value);exact(x,['expectedVersion','title','description','audience','enabled','fields']);if(x.expectedVersion!==null&&!integer(x.expectedVersion))return fail();if(typeof x.enabled!=='boolean'||!['staff','ops','admin'].includes(String(x.audience))||!Array.isArray(x.fields)||x.fields.length<1||x.fields.length>20)return fail();
 const fields=x.fields.map(v=>{const f=record(v);exact(f,['id','version','required','width']);if(!uuid(f.id)||!integer(f.version)||typeof f.required!=='boolean'||!['full','half'].includes(String(f.width)))return fail();return {id:f.id,version:Number(f.version),required:f.required,width:f.width as FormField['width']};});if(new Set(fields.map(f=>f.id)).size!==fields.length)return fail();return {expectedVersion:x.expectedVersion as number|null,title:title(x.title),description:string(x.description,2000),audience:x.audience as FormWrite['audience'],enabled:x.enabled,fields};
}
export function normalizeForms(value:unknown):FormDefinition[]{
 if(!Array.isArray(value)||value.length>50)return fail();const forms=value.map(v=>{const x=record(v);exact(x,['id','version','title','description','audience','enabled','fields']);if(!uuid(x.id)||!integer(x.version)||typeof x.enabled!=='boolean'||!['staff','ops','admin'].includes(String(x.audience)))return fail();const label=title(x.title);if(label!==x.title)return fail();return {id:x.id,version:Number(x.version),title:label,description:string(x.description,2000),audience:x.audience as FormDefinition['audience'],enabled:x.enabled,fields:fieldList(x.fields)};});if(new Set(forms.map(f=>f.id)).size!==forms.length)return fail();return forms;
}
function values(value:unknown):FormValue[]{if(!Array.isArray(value)||value.length>20)return fail();const out=value.map(v=>{const x=record(v);exact(x,['fieldId','value']);if(!uuid(x.fieldId)||!(x.value===null||typeof x.value==='boolean'||(typeof x.value==='number'&&Number.isFinite(x.value))||(typeof x.value==='string'&&[...x.value].length<=2000&&!/\u0000/.test(x.value))))return fail();return {fieldId:x.fieldId,value:x.value as FormValue['value']};});if(new Set(out.map(v=>v.fieldId)).size!==out.length)return fail();return out.sort((a,b)=>a.fieldId.localeCompare(b.fieldId));}
export function parseSubmission(value:unknown):SubmissionInput{const x=record(value);exact(x,['id','formVersion','values']);if(!uuid(x.id)||!integer(x.formVersion))return fail();return {id:x.id,formVersion:Number(x.formVersion),values:values(x.values)};}
function validateValues(fields:FormField[],input:FormValue[]){if(input.length!==fields.length)return fail();for(const {field,required} of fields){const v=input.find(v=>v.fieldId===field.id);if(!v)return fail();if(v.value===null){if(required)return fail();continue;}if(field.type==='number'){if(typeof v.value!=='number'||!Number.isFinite(v.value))return fail();}else if(field.type==='boolean'){if(typeof v.value!=='boolean')return fail();}else{if(typeof v.value!=='string'||!v.value.trim())return fail();if(field.type==='select'&&!field.options.includes(v.value))return fail();if(field.type==='date'){if(!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(v.value)||v.value.startsWith('0000-'))return fail();const d=new Date(`${v.value}T00:00:00.000Z`);if(!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==v.value)return fail();}}}}
export function validateSubmission(form:FormDefinition,value:unknown):SubmissionInput{const normalized=normalizeForms([form])[0],input=parseSubmission(value);if(input.formVersion!==normalized.version)throw new Error('FORM_CONFLICT');validateValues(normalized.fields,input.values);return input;}
export function normalizeReceipt(value:unknown):Receipt{const x=record(value);exact(x,['id','formId','formVersion','submittedAt']);if(!uuid(x.id)||!uuid(x.formId)||!integer(x.formVersion))return fail();return {id:x.id,formId:x.formId,formVersion:Number(x.formVersion),submittedAt:timestamp(x.submittedAt)};}
export function parseProcessInput(value:unknown):ProcessInput{const x=record(value);exact(x,['expectedSequence','status','note']);if(!integer(x.expectedSequence,0)||!['processing','resolved'].includes(String(x.status)))return fail();return {expectedSequence:Number(x.expectedSequence),status:x.status as ProcessInput['status'],note:string(x.note,2000)};}
export function normalizeProcessAck(value:unknown):ProcessAck{const x=record(value);exact(x,['id','sequence','status','note','processedBy','processedAt']);if(!uuid(x.id)||!integer(x.sequence)||!['processing','resolved'].includes(String(x.status)))return fail();return {id:x.id,sequence:Number(x.sequence),status:x.status as ProcessAck['status'],note:string(x.note,2000),processedBy:person(x.processedBy),processedAt:timestamp(x.processedAt)};}
export function normalizeRecord(value:unknown):FormRecord{const x=record(value);exact(x,['id','formId','formVersion','title','submittedBy','submittedAt','status','sequence','note','processedBy','processedAt','fields','values']);const receipt=normalizeReceipt({id:x.id,formId:x.formId,formVersion:x.formVersion,submittedAt:x.submittedAt});if(!integer(x.sequence,0)||!['new','processing','resolved'].includes(String(x.status)))return fail();const label=title(x.title);if(label!==x.title)return fail();const fields=fieldList(x.fields),entries=values(x.values);validateValues(fields,entries);if(x.status==='new'?(x.sequence!==0||x.processedBy!==null||x.processedAt!==null||x.note!==''):(x.sequence===0||x.processedBy===null||x.processedAt===null))return fail();return {...receipt,title:label,submittedBy:person(x.submittedBy),status:x.status as FormRecord['status'],sequence:Number(x.sequence),note:string(x.note,2000),processedBy:x.processedBy===null?null:person(x.processedBy),processedAt:x.processedAt===null?null:timestamp(x.processedAt),fields,values:entries};}
export function normalizeRecordPage(value:unknown):FormRecordPage{const x=record(value);exact(x,['items','total','page','pages']);if(!Array.isArray(x.items)||x.items.length>20||!integer(x.total,0)||!integer(x.page)||!integer(x.pages)||Number(x.pages)!==Math.max(1,Math.ceil(Number(x.total)/20))||Number(x.page)>Number(x.pages))return fail();const items=x.items.map(normalizeRecord);if(new Set(items.map(i=>i.id)).size!==items.length||items.length!==Math.min(20,Math.max(0,Number(x.total)-(Number(x.page)-1)*20)))return fail();return {items,total:Number(x.total),page:Number(x.page),pages:Number(x.pages)};}
