'use client';
import {useState} from 'react';
import {ArrowClockwise,X,ArrowUpRight} from '@phosphor-icons/react';
import {analyticsRangeParams,type DashboardRange,type DashboardData,type SearchGroup} from '../../analytics/dashboard';
import {analyticsPercent,visibleDuration} from '../../analytics/dashboard-format';
import {contentPath} from '../../reader/content-path';
import {AnalyticsDateFilter} from './AnalyticsDateFilter';
import {AnalyticsPeople} from './AnalyticsPeople';
type State='ready'|'unavailable'|'denied'|'invalid';
function dateLabel(value:string){return new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Kuala_Lumpur',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value));}
export function AnalyticsDashboard({data,state='ready',days=30}:{data?:DashboardData;state?:State;days?:DashboardRange}){
 const [tab,setTab]=useState<'overview'|'documents'|'employees'>('documents'),[selected,setSelected]=useState<string|null>(null),[sort,setSort]=useState<'views'|'readers'>('views');
 const ready=state==='ready'&&data!==undefined,range:DashboardRange=ready?(data.dateRange??data.days as 7|30|90):days,rangeKey=analyticsRangeParams(range).toString();
 const article=ready?data.popularArticles.find(x=>x.documentId===selected):undefined;
 const usage=ready?data.usage:undefined;
 const articles=ready?[...data.popularArticles].sort((a,b)=>sort==='views'?b.views-a.views:(usage?.articles.find(x=>x.documentId===b.documentId)?.readers??0)-(usage?.articles.find(x=>x.documentId===a.documentId)?.readers??0)):[];
 return <main id="main-content" className="admin-data-main analytics-workspace">
 <div className="admin-data-heading"><div><h1>使用分析</h1><p>了解资料被谁使用，以及员工查找资料的情况。</p></div><a className="admin-data-button" href={`/admin/analytics?${rangeKey}`}><ArrowClockwise size={16}/>刷新统计</a></div>
 <AnalyticsDateFilter range={range}/>
 {!ready?<section className="analytics-notice" role="alert"><h2>{state==='invalid'?'统计范围不正确':state==='denied'?'没有查看使用分析的权限':'使用分析暂时无法读取'}</h2><p>{state==='invalid'?'请选择有效的统计日期，最多 90 天。':'请重新读取；如果持续失败，请检查服务连接或联系管理员。'}</p><a className="admin-data-button" href="/admin/analytics">重新读取统计</a></section>:<>
 <p className="admin-data-caption">统计时间：<time dateTime={data.from}>{dateLabel(data.from)}</time> ～ <time dateTime={data.asOf}>{dateLabel(data.asOf)}</time>（UTC+8）</p>
 <div className="admin-data-tabs" role="tablist" aria-label="分析视图">{([['overview','概览'],['documents','资料'],['employees','员工']] as const).map(([key,label])=><button key={key} id={`analytics-tab-${key}`} role="tab" aria-selected={tab===key} aria-controls="analytics-panel" tabIndex={tab===key?0:-1} onKeyDown={event=>{const keys=['overview','documents','employees'] as const;const offset=event.key==='ArrowRight'?1:event.key==='ArrowLeft'?-1:0;if(offset){event.preventDefault();const next=keys[(keys.indexOf(tab)+offset+3)%3];setTab(next);document.getElementById(`analytics-tab-${next}`)?.focus();}}} onClick={()=>{setTab(key);setSelected(null);}}>{label}</button>)}</div>
 <section id="analytics-panel" role="tabpanel" aria-labelledby={`analytics-tab-${tab}`}>
 <dl className="admin-data-metrics" aria-label="资料使用概览"><Metric label="打开次数" value={String(data.summary.views)} detail="当前可读正式资料，包含其旧版本访问"/><Metric label="打开人数" value={usage?String(usage.readers):'未记录'} detail="同一员工多次打开，只计算一个人"/><Metric label="平均可见停留" value={visibleDuration(usage?.averageVisibleMs)} detail={`${usage?.measuredViews??0} 次打开有时长记录 · 历史记录不补算`}/></dl>
 {data.summary.searches===0&&data.summary.views===0&&data.summary.feedbackTotal===0&&<p className="admin-data-empty" role="status">所选时间内暂无可展示的数据。</p>}
 {tab==='employees'?<section className="admin-data-section" aria-label="员工使用"><h2>员工使用</h2><AnalyticsPeople key={`all-${rangeKey}`} range={range}/></section>:<div className={`admin-data-split${article?' has-detail':''}`}>
 <div className="admin-data-primary">
 {usage&&<section className="admin-data-section" aria-label="资料打开趋势"><div className="admin-data-section-heading"><h2>资料打开趋势</h2><span>按日 · UTC+8</span></div>{usage.trend.some(day=>day.views>0)?<><OpenTrend days={usage.trend} total={data.summary.views}/><div className="analytics-trend-labels"><span>{usage.trend[0]?.date}</span><span>{usage.trend.at(-1)?.date}</span></div></>:<p className="admin-data-empty">这段时间还没有打开记录。</p>}</section>}
 <section className="admin-data-section" aria-label="热门资料"><div className="admin-data-section-heading"><h2>热门资料</h2><label>排序<select aria-label="热门资料排序" value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="views">打开次数</option><option value="readers">打开人数</option></select></label></div><p className="admin-data-caption">打开次数最多的前 10 篇。点击资料名称，查看是谁打开，以及可见停留时间。</p>
 {articles.length?<div className="admin-data-table-scroll"><table className="admin-data-table"><thead><tr><th>资料名称</th><th>打开次数</th><th>打开人数</th><th>平均可见停留</th></tr></thead><tbody>{articles.map(item=>{const stats=usage?.articles.find(x=>x.documentId===item.documentId);return <tr key={item.documentId} className={selected===item.documentId?'is-selected':''}><th scope="row"><button className="admin-data-row-button" aria-expanded={selected===item.documentId} onClick={()=>setSelected(selected===item.documentId?null:item.documentId)}>{item.title}</button></th><td>{item.views}</td><td>{stats?.readers??'未记录'}</td><td>{visibleDuration(stats?.averageVisibleMs)}<small>{stats?.measuredViews??0} 次有时长</small></td></tr>;})}</tbody></table></div>:<p className="admin-data-empty">所选时间内没有当前可读资料的打开记录。</p>}
 </section></div>
 {article&&<aside className="admin-data-detail" aria-label="员工使用明细"><div className="admin-data-section-heading"><h2>员工使用明细</h2><button aria-label="关闭员工明细" onClick={()=>setSelected(null)}><X size={18}/></button></div><h3>{article.title}</h3><a className="admin-data-text-link" href={contentPath(article.kind,article.documentId)} target="_blank" rel="noreferrer">打开正式资料<ArrowUpRight size={14}/></a><AnalyticsPeople key={`${article.documentId}-${rangeKey}`} range={range} documentId={article.documentId}/></aside>}
 </div>}
 {tab==='overview'&&<div className="analytics-support-grid"><section className="admin-data-section"><h2>搜索使用情况</h2><dl className="analytics-metrics"><Metric label="搜索次数" value={String(data.summary.searches)} detail="每次显示搜索结果记一次，包含翻页"/><Metric label="没有找到资料" value={String(data.summary.zeroResults)} detail={`占搜索展示 ${analyticsPercent(data.summary.zeroResults,data.summary.searches)}`}/><Metric label="搜索点击率" value={analyticsPercent(data.summary.clickedSearches,data.summary.searches)} detail={`${data.summary.clickedSearches} 次展示有点击；共 ${data.summary.searchClicks} 次结果点击`}/></dl><p className="admin-data-caption">搜索词原文未保存，无法显示具体关键词。</p><details className="analytics-diagnostics"><summary>技术诊断：搜索分组</summary><SearchGroups title="热门搜索分组" rows={data.popularSearches} description="同一搜索内容使用同一匿名标识，最多显示前 10 组。" empty="没有搜索展示记录。"/><SearchGroups title="零结果搜索分组" rows={data.zeroResultSearches} description="按没有找到结果的次数排序。" empty="没有零结果记录。"/></details></section><section className="admin-data-section" aria-label="需要改进的资料"><h2>资料反馈</h2><p className="admin-data-caption">共 {data.summary.feedbackTotal} 份评价 · {data.summary.feedbackNegative} 份没有帮助</p>{data.negativeFeedback.length?<ul className="admin-data-feedback">{data.negativeFeedback.map(item=><li key={item.documentId}><a href={`/admin/feedback?document=${encodeURIComponent(item.documentId)}&revision=${item.revision}`}>{item.title}</a><span>{item.negative} / {item.total} 份没有帮助</span></li>)}</ul>:<p className="admin-data-empty">暂无负面评价；没有评价并不代表资料没有问题。</p>}<a className="admin-data-text-link" href="/admin/feedback">查看文章反馈<ArrowUpRight size={14}/></a></section></div>}
 </section><p className="admin-data-caption">仅展示成功采集的记录，可能存在漏报。可见停留不代表读完，也不用于判断员工表现。</p>
 </>}
 </main>;
}
function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <div className="analytics-metric"><dt>{label}</dt><dd>{value}</dd><dd className="analytics-metric-detail">{detail}</dd></div>;}
function SearchGroups({title,description,rows,empty}:{title:string;description:string;rows:SearchGroup[];empty:string}){return <section className="analytics-section" aria-label={title}><h2>{title}</h2><p>{description}</p>{rows.length?<div className="analytics-table-scroll" role="region" aria-label={`${title}表格，可横向滚动`} tabIndex={0}><table><caption className="sr-only">{title}</caption><thead><tr><th scope="col">搜索标识</th><th scope="col">展示</th><th scope="col">零结果</th><th scope="col">有点击的展示</th><th scope="col">点击率</th></tr></thead><tbody>{rows.map(row=><tr key={row.fingerprint}><th scope="row"><abbr className="analytics-fingerprint" title={row.fingerprint}>{row.fingerprint.replace(/^sha256:/,'').slice(0,12)}</abbr></th><td>{row.searches}</td><td>{row.zeroResults}</td><td>{row.clickedSearches}</td><td>{analyticsPercent(row.clickedSearches,row.searches)}</td></tr>)}</tbody></table></div>:<p className="analytics-empty">{empty}</p>}</section>;}

function OpenTrend({days,total}:{days:{date:string;views:number}[];total:number}){
 const max=Math.max(1,...days.map(day=>day.views));
 const points=days.map((day,i)=>({x:8+i*584/Math.max(1,days.length-1),y:112-day.views/max*104,...day}));
 const path=points.map((point,i)=>`${i?'L':'M'}${point.x},${point.y}`).join(' ');
 return <><svg className="analytics-line-trend" viewBox="0 0 600 120" role="img" aria-label={`每日打开次数，合计 ${total} 次`} preserveAspectRatio="none"><path className="analytics-trend-grid" d="M8,8 H592 M8,60 H592 M8,112 H592"/><path className="analytics-trend-area" d={`${path} L592,112 L8,112 Z`}/><path className="analytics-trend-line" d={path}/>{points.map(point=><circle key={point.date} cx={point.x} cy={point.y} r="2.5"><title>{point.date}：{point.views} 次</title></circle>)}</svg><details className="analytics-trend-data"><summary>查看每日数据</summary><div className="admin-data-table-scroll"><table className="admin-data-table"><thead><tr><th>日期（UTC+8）</th><th>打开次数</th></tr></thead><tbody>{days.map(day=><tr key={day.date}><th scope="row">{day.date}</th><td>{day.views}</td></tr>)}</tbody></table></div></details></>;
}
