import {normalizeFieldDefinitions} from '../fields/model.ts';
import {normalizeCategoryDefinitions} from '../categories/model.ts';
import {normalizeForms} from '../forms/model.ts';
import {normalizeNavigationConfig} from '../navigation-settings/model.ts';
import {normalizeFeatureConfig,featureLabels,type FeatureKey} from '../features/model.ts';
export const historyKinds=['field','category','form','navigation','features'] as const;
export type HistoryKind=typeof historyKinds[number];
export const historyLabels:Record<HistoryKind,string>={field:'自定义字段',category:'分类',form:'内部表单',navigation:'导航设置',features:'功能开关'};
export interface HistoryTarget {kind:HistoryKind;id:string;version:number}
export interface RestoreInput extends HistoryTarget {expectedVersion:number;requestId:string}
export interface RestoreAck extends RestoreInput {newVersion:number}
export interface HistoryEntry extends HistoryTarget {label:string;actor:{id:string;name:string}|null;changedAt:string;restoredFrom:number|null}
export interface HistoryPage {items:HistoryEntry[];total:number;page:number;pages:number}
export interface HistoryDetail {entry:HistoryEntry;before:Record<string,unknown>|null;after:Record<string,unknown>;current:{version:number;config:Record<string,unknown>}}
const bad=():never=>{throw new Error('INVALID_INPUT');};
const object=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:bad();
const exact=(x:Record<string,unknown>,keys:string[])=>{if(Object.keys(x).length!==keys.length||keys.some(k=>!Object.hasOwn(x,k)))bad();};
const integer=(v:unknown,min=1):v is number=>Number.isSafeInteger(v)&&Number(v)>=min&&Number(v)<2147483647;
const uuid=(v:unknown):v is string=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(v);
const text=(v:unknown,max=200):string=>typeof v==='string'&&v.trim()&&[...v].length<=max&&!/[\u0000-\u001f\u007f]/.test(v)?v:bad();
export function parseHistoryQuery(p:URLSearchParams){const kind=p.get('kind')??'all',raw=p.get('page')??'1';if([...p.keys()].some(k=>!['kind','page'].includes(k))||p.getAll('kind').length>1||p.getAll('page').length>1||!['all',...historyKinds].includes(kind)||!/^[1-9][0-9]*$/.test(raw)||!integer(Number(raw)))return bad();return {kind:kind as HistoryKind|'all',page:Number(raw)};}
export function parseHistoryTarget(v:unknown):HistoryTarget{const x=object(v);exact(x,['kind','id','version']);if(!historyKinds.includes(x.kind as HistoryKind)||!uuid(x.id)||!integer(x.version))return bad();return {kind:x.kind as HistoryKind,id:x.id,version:x.version};}
export function parseRestore(v:unknown):RestoreInput{const x=object(v);exact(x,['kind','id','version','expectedVersion','requestId']);const target=parseHistoryTarget({kind:x.kind,id:x.id,version:x.version});if(!uuid(x.requestId)||!integer(x.expectedVersion)||x.expectedVersion>=2147483646||x.expectedVersion<=target.version)return bad();return {...target,expectedVersion:x.expectedVersion,requestId:x.requestId};}
function entry(v:unknown):HistoryEntry{const x=object(v);exact(x,['kind','id','version','label','actor','changedAt','restoredFrom']);const t=parseHistoryTarget({kind:x.kind,id:x.id,version:x.version});if(x.restoredFrom!==null&&(!integer(x.restoredFrom)||x.restoredFrom>=t.version))return bad();if(typeof x.changedAt!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?(?:Z|[+-]\d{2}:\d{2})$/.test(x.changedAt)||!Number.isFinite(Date.parse(x.changedAt)))return bad();let actor=null;if(x.actor!==null){const a=object(x.actor);exact(a,['id','name']);actor={id:text(a.id),name:text(a.name)};}return {...t,label:text(x.label),actor,changedAt:new Date(x.changedAt).toISOString(),restoredFrom:x.restoredFrom as number|null};}
export function normalizeHistoryPage(v:unknown):HistoryPage{const x=object(v);exact(x,['items','total','page','pages']);if(!integer(x.total,0)||!integer(x.page)||!integer(x.pages)||x.pages!==Math.max(1,Math.ceil(x.total/20))||x.page>x.pages||!Array.isArray(x.items)||x.items.length!==Math.min(20,Math.max(0,x.total-(x.page-1)*20)))return bad();const items=x.items.map(entry);if(new Set(items.map(i=>`${i.kind}:${i.id}:${i.version}`)).size!==items.length)return bad();return {items,total:x.total,page:x.page,pages:x.pages};}
function config(kind:HistoryKind,v:unknown,id:string,version:number){const x=object(v);if(Object.hasOwn(x,'id')||Object.hasOwn(x,'version'))return bad();if(kind==='field')normalizeFieldDefinitions([{...x,id,version}]);else if(kind==='category')normalizeCategoryDefinitions([{...x,id,version}]);else if(kind==='form')normalizeForms([{...x,id,version}]);else if(kind==='navigation')normalizeNavigationConfig({...x,version});else normalizeFeatureConfig({...x,version});return x;}
export function normalizeHistoryDetail(v:unknown):HistoryDetail{const x=object(v);exact(x,['entry','before','after','current']);const e=entry(x.entry),c=object(x.current);exact(c,['version','config']);if(!integer(c.version)||c.version<e.version||(e.version>1&&x.before===null))return bad();return {entry:e,before:x.before===null?null:config(e.kind,x.before,e.id,Math.max(1,e.version-1)),after:config(e.kind,x.after,e.id,e.version),current:{version:c.version,config:config(e.kind,c.config,e.id,c.version)}};}
export function normalizeRestoreAck(v:unknown):RestoreAck{const x=object(v);exact(x,['kind','id','version','expectedVersion','requestId','newVersion']);const {newVersion,...rest}=x,input=parseRestore(rest);if(!integer(newVersion)||newVersion!==input.expectedVersion+1)return bad();return {...input,newVersion};}
const labels:Record<string,string>={name:'名称',type:'字段类型',required:'必填',enabled:'启用',options:'选项',parentId:'上级分类编号',position:'顺序',audience:'可见范围',title:'标题',description:'说明',fields:'表单字段与顺序',entries:'导航入口与顺序'};
const names:Record<string,string>={text:'文字',number:'数字',date:'日期',select:'下拉选择',boolean:'是／否',staff:'全体员工',support:'客服',ops:'运营',admin:'管理员',full:'整行',half:'半行',home:'帮助中心',reference:'Reference 速查',qa:'Q&A 问答',favorites:'我的收藏',recent:'最近浏览',forms:'内部表单'};
function display(key:string,v:unknown):string{if(v===null)return '无';if(typeof v==='boolean')return v?'开启':'关闭';if(Array.isArray(v)){if(key==='fields')return v.map((row,i)=>{const x=object(row),f=object(x.field);return `${i+1}. ${f.name} · 字段版本 ${f.version} · ${x.required?'必填':'选填'} · ${names[String(x.width)]}\n编号：${f.id}`;}).join('\n');if(key==='entries')return v.map((row,i)=>{const x=object(row),target=object(x.target);return `${i+1}. ${x.label} · ${x.enabled?'开启':'关闭'} · ${(x.roles as string[]).map(r=>names[r]).join('、')}\n目标：${target.type==='category'?'分类 '+target.categoryId:names[String(target.page)]}`;}).join('\n')||'无入口';return v.join('、')||'无';}return names[String(v)]??String(v);}
export function configRows(kind:HistoryKind,value:Record<string,unknown>|null):{label:string;value:string}[]{if(value===null)return [{label:'记录情况',value:'首次记录，没有更早的配置记录'}];if(kind==='features')return Object.entries(value.flags as Record<FeatureKey,boolean>).map(([key,value])=>({label:featureLabels[key as FeatureKey],value:value?'开启':'关闭'}));return Object.entries(value).map(([key,value])=>({label:labels[key]??key,value:display(key,value)}));}
