// Full navigations retain native unsaved-input protection.
'use client';
import {useEffect,useRef,useState} from 'react';
import {featureKeys,featureLabels,featureDescriptions,type FeatureConfig,type FeatureFlags,type FeatureWrite} from '../../features/model';
import {loadFeatures,saveFeatures,FeatureRejected} from '../../features/client';
export function FeatureSettings({initial}:{initial?:FeatureConfig}){
 const [config,setConfig]=useState(initial),[draft,setDraft]=useState<FeatureFlags|undefined>(initial?.flags),[pending,setPending]=useState<FeatureWrite|null>(null),[backups,setBackups]=useState<FeatureWrite[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');const lock=useRef(false),leaving=useRef(false);
 const dirty=!!draft&&JSON.stringify(draft)!==JSON.stringify(config?.flags),guard=dirty||!!pending||backups.length>0||busy;
 useEffect(()=>{leaving.current=false;if(!guard)return;function unload(e:BeforeUnloadEvent){if(leaving.current)return;e.preventDefault();e.returnValue='';}function click(e:MouseEvent){const a=e.target instanceof Element?e.target.closest('a[href]'):null;if(!a||e.defaultPrevented||e.ctrlKey||e.metaKey||e.shiftKey||a.getAttribute('target')==='_blank')return;e.preventDefault();e.stopPropagation();if(lock.current)return;if(window.confirm('本页有未保存、待确认的修改或输入备份，离开后会丢失。确定离开吗？')){leaving.current=true;location.assign(a.getAttribute('href')!);}}addEventListener('beforeunload',unload);document.addEventListener('click',click,true);return()=>{removeEventListener('beforeunload',unload);document.removeEventListener('click',click,true);};},[guard]);
 async function save(retry=false){if(lock.current||!draft||!config)return;const input=retry?pending:{expectedVersion:config.version,flags:{...draft}};if(!input)return;if(!retry){const names=featureKeys.filter(k=>draft[k]!==config.flags[k]).map(k=>`${draft[k]?'开启':'关闭'}${featureLabels[k]}`);if(!names.length)return;if(!confirm(names.join('、')+'。影响全体成员的功能使用，已有数据保留。确定保存吗？'))return;}lock.current=true;setBusy(true);setError('');setNotice('');setPending(input);try{const next=await saveFeatures(input);setConfig(next);setDraft(next.flags);setPending(null);setNotice('功能开关已保存。新的功能请求会按当前设置执行。');}catch(e){if(e instanceof FeatureRejected&&!retry){setPending(null);setError(e.message==='FEATURE_CONFLICT'?'另一位管理员已修改设置。输入已保留，请载入最新设置后再核对。':e.message==='FORBIDDEN'?'当前账号没有管理权限，输入已保留。':'设置未通过校验，输入已保留。');}else setError('无法确认原保存结果。输入已锁定，请重试原保存，或保留备份并载入最新设置。');}finally{lock.current=false;setBusy(false);}}
 async function reload(){if(lock.current)return;if((dirty||pending)&&!confirm('载入前会在本页保留一份输入备份，请核对最新设置后再保存。继续吗？'))return;lock.current=true;setBusy(true);setError('');try{const next=await loadFeatures();if(config&&draft)setBackups(xs=>[...xs,{expectedVersion:config.version,flags:{...draft}}]);setConfig(next);setDraft(next.flags);setPending(null);setNotice('已载入最新设置，已有输入备份仍保留在下方。');}catch{setError('暂时无法载入最新设置，当前输入和备份未改变。');}finally{lock.current=false;setBusy(false);}}
 function restore(value:FeatureWrite){if(busy||pending||!config||!draft)return;if(dirty)setBackups(xs=>[...xs,{expectedVersion:config.version,flags:{...draft}}]);setDraft({...value.flags});setNotice('备份已放回编辑区，尚未保存，请核对后保存。');setError('');}
 return <section className="feature-settings"><header><div><p className="card-kicker">SYSTEM SETTINGS</p><h1>功能开关</h1><p>暂停或恢复已实现的功能，已有资料和记录会保留。</p></div><a className="secondary-link" href="/admin">返回管理后台</a></header><p>影响所有角色；登录、资料权限和管理设置始终保留。修改菜单可见性请使用导航设置。</p>{config&&draft?<><p>当前配置版本 {config.version}{config.version===0?' · 尚未保存，使用默认全部开启':''}</p><div className="feature-grid">{featureKeys.map(k=><label className="feature-card" key={k}><span><strong>{featureLabels[k]}</strong><small>{featureDescriptions[k]}</small></span><span className="feature-switch"><input type="checkbox" aria-label={featureLabels[k]} checked={draft[k]} disabled={busy||!!pending} onChange={e=>setDraft({...draft,[k]:e.target.checked})}/>{draft[k]?'开启':'关闭'}</span></label>)}</div><button type="button" className="primary-link" disabled={busy||!!pending||!dirty} onClick={()=>void save()}>保存开关</button>{pending&&<button type="button" className="secondary-link" disabled={busy} onClick={()=>void save(true)}>重试原保存</button>}</>:<p role="status">暂时无法读取功能开关，请检查服务连接或重试。</p>}<button type="button" className="secondary-link" disabled={busy} onClick={()=>void reload()}>保留输入并载入最新设置</button>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{backups.map((b,i)=><details key={i} open><summary>输入备份 {i+1}</summary><textarea aria-label={`功能开关输入备份 ${i+1}`} readOnly value={JSON.stringify(b,null,2)}/><button type="button" disabled={busy||!!pending} onClick={()=>restore(b)}>恢复备份 {i+1} 到编辑区</button></details>)}</section>;
}
