'use client';
/* eslint-disable @next/next/no-img-element -- Authenticated private asset delivery; no public image optimizer. */
import {useState} from 'react';
import {UploadSimple,SquaresFour,ListBullets,X,FileText,FilePdf,FilmStrip,MusicNotes,ImageSquare,DownloadSimple,ArrowUpRight,MagnifyingGlass} from '@phosphor-icons/react';
import {libraryHref,fileCategory,formatBytes,type LibraryAsset,type FileCategory,type MediaLibraryData} from '../../media/library';
import {MediaUpload} from './MediaUpload';
const categoryNames:Record<FileCategory,string>={all:'全部',image:'图片',video:'视频',audio:'音频',file:'文件'};
const assetHref=(id:string)=>`/api/admin/assets/${encodeURIComponent(id)}`;
function FilePreview({asset,large=false}:{asset:LibraryAsset;large?:boolean}){
 const [failed,setFailed]=useState(false),type=fileCategory(asset.mime);
 if(type==='image'&&!failed)return <img src={assetHref(asset.id)} alt={large?asset.filename:''} loading={large?'eager':'lazy'} onError={()=>setFailed(true)}/>;
 if(type==='video'&&large&&!failed)return <video controls preload="metadata" src={assetHref(asset.id)} aria-label={asset.filename} onError={()=>setFailed(true)}/>;
 if(type==='audio'&&large&&!failed)return <audio controls preload="metadata" src={assetHref(asset.id)} aria-label={asset.filename} onError={()=>setFailed(true)}/>;
 const Icon=failed?ImageSquare:type==='video'?FilmStrip:type==='audio'?MusicNotes:asset.mime==='application/pdf'?FilePdf:FileText;
 return <div className="media-file-icon"><Icon size={large?56:40}/><span>{failed?'预览无法读取':asset.mime==='application/pdf'?'PDF':type==='video'?'视频':type==='audio'?'音频':asset.filename.split('.').at(-1)?.toUpperCase()}</span></div>;
}
export function MediaLibrary({data,state='ready'}:{data?:MediaLibraryData;state?:'ready'|'unavailable'|'invalid'}){
 const [uploading,setUploading]=useState(false);
 if(state!=='ready'||!data)return <main id="main-content" className="admin-data-main"><div className="admin-data-heading"><h1>媒体文件</h1></div><div className="admin-data-empty" role="alert"><p>{state==='invalid'?'筛选条件不正确。':'媒体文件暂时无法读取。'}</p><a className="admin-data-button" href="/admin/media">重新读取文件</a></div></main>;
 const {query,selected}=data;
 return <main id="main-content" className="admin-data-main media-library"><div className="admin-data-heading"><div><h1>媒体文件</h1><p>查找、预览已上传文件，并查看它们用于哪篇文章。</p></div><button className="admin-data-primary-button" onClick={()=>setUploading(true)}><UploadSimple size={17}/>上传文件</button></div>
 <div className="media-library-workspace"><nav className="media-library-types" aria-label="文件类型">{(['all','image','video','audio','file'] as const).map(type=>{const Icon=type==='all'?SquaresFour:type==='image'?ImageSquare:type==='video'?FilmStrip:type==='audio'?MusicNotes:FileText;return <a key={type} href={libraryHref(query,{type,page:1,file:undefined})} aria-current={query.type===type?'page':undefined}><Icon size={18}/><span>{categoryNames[type]}</span><small>{data.counts[type]}</small></a>;})}</nav>
 <div className="media-library-content"><form action="/admin/media" method="get" className="admin-data-toolbar media-library-toolbar"><label className="media-library-search"><MagnifyingGlass size={17}/><span className="sr-only">搜索文件名称</span><input type="search" name="q" maxLength={120} defaultValue={query.q} placeholder="搜索文件名称"/></label><input type="hidden" name="type" value={query.type}/><input type="hidden" name="view" value={query.view}/><label><span className="sr-only">文件排序</span><select name="sort" defaultValue={query.sort} aria-label="文件排序"><option value="recent">上传时间（新 → 旧）</option><option value="name">文件名称</option><option value="size">文件大小（大 → 小）</option></select></label><button type="submit">应用筛选</button><div className="media-view-toggle"><a aria-label="网格视图" aria-current={query.view==='grid'?'page':undefined} href={libraryHref(query,{view:'grid'})}><SquaresFour size={18}/></a><a aria-label="列表视图" aria-current={query.view==='list'?'page':undefined} href={libraryHref(query,{view:'list'})}><ListBullets size={18}/></a></div></form>
 <p className="admin-data-caption">共 {data.total} 个文件{query.q?` · 搜索“${query.q}”`:''} · 来自有效文章的已成功上传文件</p>
 <div className={`admin-data-split${selected?' has-detail':''}`}><div className="admin-data-primary">{data.items.length?(query.view==='grid'?<ul className="media-library-grid">{data.items.map(asset=><li key={asset.id}><a className={`media-library-tile${query.file===asset.id?' is-selected':''}`} href={libraryHref(query,{file:asset.id})} aria-label={`查看文件 ${asset.filename}`}><div className="media-library-thumbnail"><FilePreview key={asset.id} asset={asset}/></div><strong>{asset.filename}</strong><small>{asset.mime.split('/').at(-1)?.toUpperCase()} · {formatBytes(asset.size)}</small><span>{asset.documentTitle}</span></a></li>)}</ul>:<div className="admin-data-table-scroll"><table className="admin-data-table media-library-table"><thead><tr><th>文件名称</th><th>类型</th><th>大小</th><th>所属文章</th></tr></thead><tbody>{data.items.map(asset=><tr key={asset.id} className={query.file===asset.id?'is-selected':''}><th scope="row"><a href={libraryHref(query,{file:asset.id})}><div className="media-list-thumbnail"><FilePreview key={asset.id} asset={asset}/></div><span>{asset.filename}</span></a></th><td>{categoryNames[fileCategory(asset.mime)]}</td><td>{formatBytes(asset.size)}</td><td>{asset.documentTitle}</td></tr>)}</tbody></table></div>):<div className="admin-data-empty"><p>{query.q||query.type!=='all'?'没有找到符合条件的文件。':'还没有已上传的文件。'}</p>{query.q||query.type!=='all'?<a className="admin-data-button" href="/admin/media">清除筛选</a>:<button onClick={()=>setUploading(true)}>上传第一个文件</button>}</div>}
 <div className="admin-data-pagination">{data.page>1?<a href={libraryHref(query,{page:data.page-1,file:undefined})}>上一页</a>:<span>上一页</span>}<span>第 {data.page} / {data.pages} 页</span>{data.page<data.pages?<a href={libraryHref(query,{page:data.page+1,file:undefined})}>下一页</a>:<span>下一页</span>}</div></div>
 {selected&&<aside className="admin-data-detail media-library-detail" aria-label="文件详情"><div className="admin-data-section-heading"><h2>文件详情</h2><a className="admin-data-button" href={libraryHref(query,{file:undefined})} aria-label="关闭文件详情"><X size={18}/></a></div><div className="media-library-large-preview"><FilePreview key={selected.id} asset={selected} large/></div><h3>{selected.filename}</h3><p className="admin-data-caption">{selected.mime.split('/').at(-1)?.toUpperCase()} · {formatBytes(selected.size)}</p><div className="media-library-actions"><a className="admin-data-button" href={assetHref(selected.id)} target="_blank" rel="noreferrer"><ArrowUpRight size={16}/>预览原文件</a><a className="admin-data-button" href={`${assetHref(selected.id)}?download=1`}><DownloadSimple size={16}/>下载文件</a></div><section><h3>所属文章与使用位置</h3><a className="admin-data-text-link" href={`/admin/editor?article=${encodeURIComponent(selected.documentId)}`}>{selected.documentTitle}<ArrowUpRight size={14}/></a>{selected.usages.length?<ul>{selected.usages.map(usage=><li key={`${usage.state}-${usage.usage}`}>{usage.state==='published'?'正式版':'当前草稿'} · {usage.usage==='cover'?'封面':usage.usage==='inline'?'正文内容':'附件'}</li>)}</ul>:<p className="admin-data-caption">已上传，还未用于当前草稿或正式版。</p>}</section><dl className="media-library-metadata"><dt>上传时间</dt><dd>{new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Kuala_Lumpur',dateStyle:'medium',timeStyle:'short'}).format(new Date(selected.createdAt))}</dd><dt>上传人</dt><dd>{selected.uploadedBy}</dd></dl></aside>}
 {query.file&&!selected&&<p role="status" className="admin-data-empty">此文件已不可用。请重新选择文件。</p>}</div></div></div>
 {uploading&&<MediaUpload initialArticle={selected?.canUpload?{id:selected.documentId,title:selected.documentTitle}:undefined} onClose={()=>setUploading(false)} onUploaded={id=>{window.location.assign(libraryHref({...query,q:'',type:'all',page:1},{file:id}));}}/>}
 </main>;
}
