export const targets={search:{label:'资料搜索',href:'/help-centre?q=',admin:false},pdf:{label:'文章 PDF',href:'/help-centre',admin:false},favorites:{label:'我的收藏',href:'/help-centre/favorites',admin:false},recent:{label:'最近浏览',href:'/help-centre/recent',admin:false},feedback:{label:'文章反馈',href:'/help-centre',admin:false},forms:{label:'内部表单',href:'/help-centre/forms',admin:false},ops:{label:'OPS Internal',href:'/help-centre/ops',admin:false},reference:{label:'Reference 速查',href:'/help-centre/reference',admin:false},qa:{label:'Q&A 问答',href:'/help-centre/qa',admin:false},editor:{label:'内容编辑',href:'/admin/editor',admin:true},analytics:{label:'使用分析',href:'/admin/analytics',admin:true},history:{label:'设置变更记录',href:'/admin/settings/history',admin:true}} as const;
export type AnnouncementTarget=keyof typeof targets;
export interface AnnouncementConfig{title:string;body:string;target:AnnouncementTarget;audience:'staff'|'ops'|'admin';enabled:boolean}
export interface Announcement extends AnnouncementConfig{id:string;revision:number;seen:boolean}
export interface AnnouncementWrite extends AnnouncementConfig{expectedVersion:number}
export interface ReceiptInput{revision:number;action:'seen'|'dismiss'}
export interface ReceiptAck{id:string;revision:number;seen:true;dismissed:boolean;target:AnnouncementTarget}
function bad():never{throw new Error('INVALID_INPUT');}
const object=(x:unknown):Record<string,unknown>=>x&&typeof x==='object'&&!Array.isArray(x)?x as Record<string,unknown>:bad();
function exact(x:Record<string,unknown>,keys:string[]){if(Object.keys(x).length!==keys.length||keys.some(k=>!Object.hasOwn(x,k)))bad();}
function integer(x:unknown,min=1):x is number{return Number.isSafeInteger(x)&&Number(x)>=min&&Number(x)<2147483647;}
export function announcementId(x:unknown):string{if(typeof x!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(x))return bad();return x;}
function label(x:unknown,max:number):string{if(typeof x!=='string'||!x.trim()||x!==x.trim()||[...x].length>max||/[\u0000-\u001f\u007f-\u009f]/.test(x))return bad();return x;}
function config(x:Record<string,unknown>):AnnouncementConfig{if(typeof x.target!=='string'||!Object.hasOwn(targets,x.target)||!['staff','ops','admin'].includes(String(x.audience))||typeof x.enabled!=='boolean')return bad();return {title:label(x.title,120),body:label(x.body,600),target:x.target as AnnouncementTarget,audience:x.audience as AnnouncementConfig['audience'],enabled:x.enabled};}
export function parseAnnouncementWrite(v:unknown):AnnouncementWrite{const x=object(v);exact(x,['expectedVersion','title','body','target','audience','enabled']);if(!integer(x.expectedVersion,0)||x.expectedVersion>=2147483646)return bad();return {expectedVersion:x.expectedVersion,...config(x)};}
export function normalizeAnnouncements(v:unknown):Announcement[]{if(!Array.isArray(v)||v.length>50)return bad();const items=v.map(item=>{const x=object(item);exact(x,['id','revision','title','body','target','audience','enabled','seen']);if(!integer(x.revision)||typeof x.seen!=='boolean')return bad();return {id:announcementId(x.id),revision:x.revision,...config(x),seen:x.seen};});if(new Set(items.map(x=>x.id)).size!==items.length)return bad();return items;}
export function parseReceipt(v:unknown):ReceiptInput{const x=object(v);exact(x,['revision','action']);if(!integer(x.revision)||!['seen','dismiss'].includes(String(x.action)))return bad();return {revision:x.revision,action:x.action as ReceiptInput['action']};}
export function normalizeReceipt(v:unknown):ReceiptAck{const x=object(v);exact(x,['id','revision','seen','dismissed','target']);if(!integer(x.revision)||x.seen!==true||typeof x.dismissed!=='boolean'||typeof x.target!=='string'||!Object.hasOwn(targets,x.target))return bad();return {id:announcementId(x.id),revision:x.revision,seen:true,dismissed:x.dismissed,target:x.target as AnnouncementTarget};}
