import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {createRequire} from 'node:module';
import ts from 'typescript';
const require=createRequire(import.meta.url);
import {prepareUserMenuFixture} from './user-menu-browser';

/** Actual account controls; only Next routing and the external Clerk client are replaced. */
export async function accountMenuBundle(){
 const dir=resolve('output/verification/account-menu-fixture');await mkdir(dir,{recursive:true});
 const files=['components/shell/AccountControls.tsx','components/employee-sign-out.tsx','authentication/sign-out.ts','authentication/login-flow.ts','editor/local-recovery.ts','reader/recent-search.ts','reader/search.ts','reader/content-path.ts','review/leave.ts','components/feedback/feedback.ts'];
 for(const file of files){const target=resolve(dir,file.replace(/\.tsx?$/,'.js'));await mkdir(dirname(target),{recursive:true});await writeFile(target,ts.transpileModule(await readFile('src/'+file,'utf8'),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022,rewriteRelativeImportExtensions:true}}).outputText);}
 const cssRule=await prepareUserMenuFixture(dir);
 await writeFile(resolve(dir,'navigation.js'),`export const usePathname=()=>'/admin';export const useRouter=()=>({push:href=>location.assign(href)});`);
 await writeFile(resolve(dir,'link.js'),`import React from 'react';export default function Link({prefetch,...props}){return React.createElement('a',props);}`);
 await writeFile(resolve(dir,'clerk.js'),`import React from 'react';const params=new URLSearchParams(location.search);let attempts=0;export const ClerkFailed=({children})=>params.has('provider-failed')?children:null;export const ClerkLoading=({children})=>params.has('loading')?children:null;export const useUser=()=>({isLoaded:!params.has('loading'),isSignedIn:!params.has('signed-out'),user:{fullName:'Haley QA',publicMetadata:{role:params.get('role')||'super_admin'},primaryEmailAddress:{emailAddress:'haley-qa@example.test'},imageUrl:'/__missing-avatar'}});export const useSession=()=>({isLoaded:!params.has('loading'),session:params.has('no-session')?null:{id:'sess_local_qa'}});export const useClerk=()=>({openUserProfile:()=>{if(params.has('profile-fails'))throw new Error('PROFILE_OFFLINE');document.getElementById('profile-result').textContent='账号设置已打开';},signOut:async options=>{attempts++;document.getElementById('logout-result').textContent=JSON.stringify({attempts,options});if(params.has('delay'))await new Promise(resolve=>setTimeout(resolve,250));if(params.has('logout-fails')&&attempts===1)throw new Error('OFFLINE');document.getElementById('logout-success').textContent='已退出测试会话';}});`);
 await writeFile(resolve(dir,'entry.js'),`import React from 'react';import {createRoot} from 'react-dom/client';import {ThemeProvider} from 'next-themes';import {AccountMenu} from './components/shell/AccountControls';import {registerReviewLeaveGuard} from './review/leave';const params=new URLSearchParams(location.search);if(params.has('guard'))registerReviewLeaveGuard({check:async()=>false,commit:()=>{document.getElementById('guard-result').textContent='committed';},reset:()=>{document.getElementById('guard-result').textContent='reset';}});if(params.has('logout-fails'))registerReviewLeaveGuard({check:async()=>true,commit:()=>{document.getElementById('guard-result').textContent='committed';},reset:()=>{document.getElementById('guard-result').textContent='reset';}});createRoot(document.getElementById('account')).render(React.createElement(ThemeProvider,{attribute:'class',defaultTheme:'light',enableSystem:true},React.createElement(AccountMenu,{enabled:!params.has('unconfigured'),admin:!params.has('reader'),accountOnly:params.has('sidebar'),locale:params.get('lang')==='en'?'en':'zh-CN'})));`);
 const {webpack}=require('next/dist/compiled/webpack/webpack');
 await new Promise<void>((done,reject)=>{const compiler=webpack({mode:'development',devtool:false,entry:resolve(dir,'entry.js'),output:{path:dir,filename:'bundle.js'},resolve:{modules:[resolve('node_modules')],alias:{'next/navigation':resolve(dir,'navigation.js'),'next/link':resolve(dir,'link.js'),'@clerk/nextjs':resolve(dir,'clerk.js')}},module:{rules:[{test:/\.m?js$/,resolve:{fullySpecified:false}},cssRule]}});compiler.run((error:Error|null,stats:{hasErrors():boolean;toString():string})=>compiler.close(()=>error||stats.hasErrors()?reject(error??new Error(stats.toString())):done()));});
 return {script:await readFile(resolve(dir,'bundle.js'),'utf8'),css:(await readFile('src/app/globals.css','utf8')).replace('@import "tailwindcss";','')+await readFile('src/app/product-shell.css','utf8')+(await readFile('src/app/fumadocs-reader.css','utf8')).replace(/^@import.*;$/gm,'')};
}
