import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';import {resolve,dirname} from 'node:path';import {createRequire} from 'node:module';import ts from 'typescript';
const require=createRequire(import.meta.url);
export async function analyticsBrowserBundle(){
 const dir=resolve('output/verification/analytics-fixture');await mkdir(dir,{recursive:true});
 for(const file of ['analytics/client.ts','analytics/search.ts','components/analytics/ArticleAnalytics.tsx','components/analytics/SearchAnalytics.tsx','reader/search.ts',...['SearchResults','SearchPageResultItem','SearchResultItem','HighlightQuery'].map(x=>'components/gitbook/Search/'+x+'.tsx')]){const target=resolve(dir,file.replace(/\.tsx?$/,'.js'));await mkdir(dirname(target),{recursive:true});await writeFile(target,ts.transpileModule(await readFile(`src/${file}`,'utf8'),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022,rewriteRelativeImportExtensions:true}}).outputText);}
 await writeFile(resolve(dir,'entry.js'),`import React from 'react';import {createRoot} from 'react-dom/client';import {ArticleAnalytics} from './components/analytics/ArticleAnalytics';import {SearchAnalytics} from './components/analytics/SearchAnalytics';import {SearchResults} from './components/gitbook/Search/SearchResults';const data=JSON.parse(document.getElementById('data').textContent);const root=createRoot(document.getElementById('analytics'));const render=(props,mode=data.mode)=>root.render(React.createElement(React.StrictMode,null,mode==='search'?React.createElement(SearchAnalytics,props,React.createElement(SearchResults,{search:props.search,failed:props.enabled===false,retryHref:'/help-centre'})):React.createElement(ArticleAnalytics,props)));render(data.props);window.switchAnalytics=(id,revision=1)=>render({documentId:id,revision},'view');`);
 const {webpack}=require('next/dist/compiled/webpack/webpack');await new Promise<void>((done,reject)=>{const compiler=webpack({mode:'development',devtool:false,entry:resolve(dir,'entry.js'),output:{path:dir,filename:'bundle.js'},resolve:{modules:[resolve('node_modules')]},module:{rules:[{test:/\.js$/,resolve:{fullySpecified:false}}]}});compiler.run((error:Error|null,stats:{hasErrors():boolean;toString():string})=>compiler.close(()=>error||stats.hasErrors()?reject(error??new Error(stats.toString())):done()));});
 return {script:await readFile(resolve(dir,'bundle.js'),'utf8'),css:(await Promise.all((await readdir('.next/static/chunks')).filter(n=>n.endsWith('.css')).map(n=>readFile(`.next/static/chunks/${n}`,'utf8')))).join('\n')+await readFile('src/app/globals.css','utf8')};
}
