import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {createRequire} from 'node:module';
import ts from 'typescript';
import type {ReviewDetail} from '../../src/review/decision';
const require=createRequire(import.meta.url);
export const decisionFixture:ReviewDetail={article:{documentId:'decision-local',title:'需要二审的文章',body:'# 核对本次正文\n\n完整正文 <script>alert(1)</script>',sequence:4,status:'in_review',lifecycle:'active',blocks:[],cover:null,tags:[],assets:[],kind:'article',audience:'staff',publishedRevision:1},review:{revision:2,submittedBy:'admin-a',reviewerId:'admin-b',reviewerName:'Ivy',status:'in_review',reason:null,submittedAt:'2026-09-09T01:00:00Z',decidedAt:null},canDecide:true};
export async function decisionBrowserBundle(){
 const dir=resolve('output/verification/decision-fixture');await mkdir(dir,{recursive:true});
const files=['reader/icon-keys.ts','reader/icons.tsx','components/review/useReviewLeaveGuard.ts','review/history-guard.ts','review/leave.ts','components/feedback/feedback.ts','editor/inline.ts','editor/table.ts','editor/highlight.ts','editor/print.ts','editor/annotation.ts','editor/inline-embed.ts','categories/model.ts','categories/editor.ts','components/categories/ArticleCategories.tsx','fields/model.ts','fields/editor.ts','components/fields/FieldValues.tsx','qa/metadata.ts','history/paths.ts','components/review/ReviewDecision.tsx','review/decision-client.ts','editor/recovery.ts','editor/legacy.ts','editor/document.ts','workspace/model.ts','domain/presentation.ts','media/model.ts','media/tab-body.ts','media/code-lines.ts','media/external-embed.ts','reader/body.ts','reader/inline.ts','science/model.ts',...['ImageGallery','TableExplorer','MediaBlocks','ArticleReferenceContext','ArticleReference','ExternalEmbed'].map(f=>`components/gitbook/Media/${f}.tsx`),...['StructuredInline','StructuredDocument','DocumentView','Inline','Heading','Paragraph','InlineAnnotation'].map(f=>`components/gitbook/Reading/${f}.tsx`),...['Math','Diagram','Hint','CodeBlock','CopyCodeButton','DynamicTabs','Steps','Columns','ActionButton'].map(f=>`components/gitbook/RichBlocks/${f}.tsx`)];
 for(const file of files){const target=resolve(dir,file.replace(/\.tsx?$/,'.js'));await mkdir(dirname(target),{recursive:true});await writeFile(target,ts.transpileModule(await readFile(`src/${file}`,'utf8'),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022,rewriteRelativeImportExtensions:true}}).outputText);}
 await writeFile(resolve(dir,'entry.js'),`import React from 'react';import {createRoot} from 'react-dom/client';import {ReviewDecision} from './components/review/ReviewDecision';const initial=JSON.parse(document.getElementById('data').textContent);createRoot(document.getElementById('review')).render(React.createElement(ReviewDecision,{initial}));`);
 const {webpack}=require('next/dist/compiled/webpack/webpack');
 await new Promise<void>((done,reject)=>{const compiler=webpack({mode:'development',devtool:false,plugins:[new webpack.DefinePlugin({'process.env':JSON.stringify({NODE_ENV:'development',__NEXT_ROUTER_BASEPATH:''})})],entry:resolve(dir,'entry.js'),output:{path:dir,filename:'bundle.js',publicPath:'/__decision_assets/'},resolve:{modules:[resolve('node_modules')]},module:{rules:[{test:/\.m?js$/,resolve:{fullySpecified:false}}]}});compiler.run((error:Error|null,stats:{hasErrors():boolean;toString():string})=>compiler.close(()=>error||stats.hasErrors()?reject(error??new Error(stats.toString())):done()));});
 const css=(await Promise.all((await readdir('.next/static/chunks')).filter(f=>f.endsWith('.css')).map(f=>readFile(resolve('.next/static/chunks',f),'utf8')))).join('\n')+await readFile('src/app/globals.css','utf8');
 return {script:await readFile(resolve(dir,'bundle.js'),'utf8'),css};
}
