import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {createRequire} from 'node:module';
import ts from 'typescript';
import type {EditorData} from '../../src/editor/contract';
const require=createRequire(import.meta.url);
export const editorFixture:EditorData={documentId:'editor-local',title:'编辑测试文章',body:'原始正文',sequence:3,status:'draft',lifecycle:'active',blocks:[],cover:null,tags:[],assets:[],kind:'article',audience:'staff',publishedRevision:null};
export async function editorBrowserBundle(){
 const dir=resolve('output/verification/editor-fixture');await mkdir(dir,{recursive:true});
const files=['reader/icon-keys.ts','reader/icon-components.ts','reader/icons.tsx','components/editor/LocalRecovery.tsx','editor/local-recovery.ts','editor/errors.ts','components/feedback/feedback.ts','editor/highlight.ts','components/editor/colors.ts','editor/native.ts','editor/inline.ts','editor/inline-embed.ts','editor/annotation.ts','editor/table.ts','editor/blocknote-table.ts','categories/model.ts','categories/editor.ts','components/categories/ArticleCategories.tsx','fields/model.ts','fields/editor.ts','components/fields/FieldValues.tsx','components/fields/FieldInputs.tsx','qa/metadata.ts','history/paths.ts','components/review/SubmitReview.tsx','components/review/DirectPublishConfirmation.tsx','review/client.ts','review/publication-client.ts','components/lifecycle/DocumentTrashAction.tsx','lifecycle/client.ts','components/editor/EditorRecovery.tsx','editor/recovery.ts','components/editor/ArticleEditor.tsx','components/editor/schema.tsx','components/editor/TableBorderControls.tsx','components/editor/TableConfigFields.tsx','components/editor/MediaFields.tsx','components/editor/ArticleReferenceFields.tsx','components/editor/TabBodyEditor.tsx','editor/document.ts','editor/legacy.ts','editor/autosave.ts','workspace/model.ts','domain/presentation.ts','media/model.ts','media/external-embed.ts','media/code-lines.ts','media/tab-body.ts','reader/body.ts','reader/inline.ts','science/model.ts','components/rich-block-fields.tsx','components/science-fields.tsx','components/gitbook/Media/ImageGallery.tsx','components/reader-support/TableExplorer.tsx','components/reader-support/ArticleReferenceContext.tsx','components/gitbook/Media/ArticleReference.tsx','components/gitbook/RichBlocks/ActionButton.tsx','components/gitbook/Media/ExternalEmbed.tsx','components/gitbook/Media/MediaBlocks.tsx','components/reader-support/InlineAnnotation.tsx','components/reader-support/StructuredInline.tsx',...['StructuredDocument','DocumentView','Inline','Heading','Paragraph'].map(f=>`components/gitbook/Reading/${f}.tsx`),...['Math','Diagram','Hint','CodeBlock','CopyCodeButton','DynamicTabs','Steps','Columns'].map(f=>`components/gitbook/RichBlocks/${f}.tsx`)];
 files.push('editor/reusable-fragment.ts','editor/inline-canvas.ts','components/editor/ReusableFragmentDialog.tsx');
 for(const file of files){const target=resolve(dir,file.replace(/\.tsx?$/,'.js'));await mkdir(dirname(target),{recursive:true});const source=(await readFile(`src/${file}`,'utf8')).replace(/^import ['"].*\.css['"];?$/gm,'');await writeFile(target,ts.transpileModule(source,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022,rewriteRelativeImportExtensions:true}}).outputText);}
 await writeFile(resolve(dir,'entry.js'),`import React from 'react';import {createRoot} from 'react-dom/client';import {ThemeProvider} from 'next-themes';import ArticleEditor from './components/editor/ArticleEditor';const initial=JSON.parse(document.getElementById('data').textContent);const editor=React.createElement(ArticleEditor,{initial,recoveryOwner:'local-admin',categoryOptions:JSON.parse(document.getElementById('category-options')?.textContent??'[]'),fieldDefinitions:JSON.parse(document.getElementById('definitions')?.textContent??'[]'),newReference:new URLSearchParams(location.search).get('kind')==='reference',newQa:new URLSearchParams(location.search).get('kind')==='qa'});createRoot(document.getElementById('editor')).render(React.createElement(ThemeProvider,{attribute:'class',defaultTheme:'system',enableSystem:true},editor));`);
 const {webpack}=require('next/dist/compiled/webpack/webpack');
 await new Promise<void>((done,reject)=>{const compiler=webpack({mode:'development',devtool:false,entry:resolve(dir,'entry.js'),output:{path:dir,filename:'bundle.js',publicPath:'/__editor_assets/'},resolve:{modules:[resolve('node_modules')]},module:{rules:[{test:/\.m?js$/,resolve:{fullySpecified:false}}]}});compiler.run((error:Error|null,stats:{hasErrors():boolean;toString():string})=>compiler.close(()=>error||stats.hasErrors()?reject(error??new Error(stats.toString())):done()));});
 const css=(await Promise.all((await readdir('.next/static/chunks')).filter(f=>f.endsWith('.css')).map(f=>readFile(resolve('.next/static/chunks',f),'utf8')))).join('\n');
 return {script:await readFile(resolve(dir,'bundle.js'),'utf8'),css};
}
