import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';import {resolve,dirname} from 'node:path';import {createRequire} from 'node:module';import ts from 'typescript';
const require=createRequire(import.meta.url);
export async function favoritesBrowserBundle(){
 const dir=resolve('output/verification/favorites-fixture');await mkdir(dir,{recursive:true});
 for(const file of ['qa/answer-cache.ts','reader/content-path.ts','favorites/client.ts','components/favorites/FavoriteButton.tsx','components/favorites/FavoritesView.tsx','workspace/model.ts','components/gitbook/Search/SearchResultItem.tsx']){const target=resolve(dir,file.replace(/\.tsx?$/,'.js'));await mkdir(dirname(target),{recursive:true});await writeFile(target,ts.transpileModule(await readFile(`src/${file}`,'utf8'),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022,rewriteRelativeImportExtensions:true}}).outputText);}
 await writeFile(resolve(dir,'clerk.js'),`import {useSyncExternalStore} from 'react';let auth={isLoaded:true,userId:'fixture',sessionId:'session-a'};const listeners=new Set();window.switchFavoriteSession=(userId,sessionId)=>{auth={isLoaded:true,userId,sessionId};listeners.forEach(f=>f());};export function useAuth(){return useSyncExternalStore(f=>{listeners.add(f);return()=>listeners.delete(f);},()=>auth,()=>auth);}`);
 await writeFile(resolve(dir,'entry.js'),`import './clerk.js';import React from 'react';import {createRoot} from 'react-dom/client';import {FavoritesView} from './components/favorites/FavoritesView';import {FavoriteButton} from './components/favorites/FavoriteButton';const data=JSON.parse(document.getElementById('data').textContent);const root=createRoot(document.getElementById('favorites'));root.render(React.createElement(data.mode==='list'?FavoritesView:FavoriteButton,{...data.props,viewerId:'fixture'}));window.unmountFavorite=()=>root.render(null);window.switchFavorite=(id)=>root.render(React.createElement(FavoriteButton,{documentId:id,revision:1,viewerId:'fixture'}));`);
 const {webpack}=require('next/dist/compiled/webpack/webpack');await new Promise<void>((done,reject)=>{const compiler=webpack({mode:'development',devtool:false,entry:resolve(dir,'entry.js'),output:{path:dir,filename:'bundle.js'},resolve:{alias:{'@clerk/nextjs':resolve(dir,'clerk.js')},modules:[resolve('node_modules')]},module:{rules:[{test:/\.js$/,resolve:{fullySpecified:false}}]}});compiler.run((error:Error|null,stats:{hasErrors():boolean;toString():string})=>compiler.close(()=>error||stats.hasErrors()?reject(error??new Error(stats.toString())):done()));});
 return {script:await readFile(resolve(dir,'bundle.js'),'utf8'),css:(await Promise.all((await readdir('.next/static/chunks')).filter(n=>n.endsWith('.css')).map(n=>readFile(`.next/static/chunks/${n}`,'utf8')))).join('\n')+await readFile('src/app/globals.css','utf8')};
}
