import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';import {resolve,dirname} from 'node:path';import {createRequire} from 'node:module';import ts from 'typescript';
const require=createRequire(import.meta.url);
export async function featureBrowserBundle(){
 const dir=resolve('output/verification/features-fixture');await mkdir(dir,{recursive:true});
 for(const file of ['components/feedback/feedback.ts','features/model.ts','features/client.ts','components/features/FeatureSettings.tsx','components/features/FeatureNotice.tsx']){const target=resolve(dir,file.replace(/\.tsx?$/,'.js'));await mkdir(dirname(target),{recursive:true});await writeFile(target,ts.transpileModule(await readFile(`src/${file}`,'utf8'),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022,rewriteRelativeImportExtensions:true}}).outputText);}
 await writeFile(resolve(dir,'entry.js'),`import React from 'react';import {createRoot} from 'react-dom/client';import {FeatureSettings} from './components/features/FeatureSettings';import {FeatureNotice} from './components/features/FeatureNotice';const p=JSON.parse(document.getElementById('data').textContent);createRoot(document.getElementById('features')).render(p.notice?React.createElement(FeatureNotice,p.notice):React.createElement(FeatureSettings,{initial:p.config}));`);
 const {webpack}=require('next/dist/compiled/webpack/webpack');await new Promise<void>((done,reject)=>{const compiler=webpack({mode:'development',devtool:false,plugins:[new webpack.DefinePlugin({'process.env':JSON.stringify({NODE_ENV:'development',__NEXT_ROUTER_BASEPATH:''})})],entry:resolve(dir,'entry.js'),output:{path:dir,filename:'bundle.js'},resolve:{modules:[resolve('node_modules')]},module:{rules:[{test:/\.js$/,resolve:{fullySpecified:false}}]}});compiler.run((error:Error|null,stats:{hasErrors():boolean;toString():string})=>compiler.close(()=>error||stats.hasErrors()?reject(error??new Error(stats.toString())):done()));});
 return {script:await readFile(resolve(dir,'bundle.js'),'utf8'),css:(await Promise.all((await readdir('.next/static/chunks')).filter(n=>n.endsWith('.css')).map(n=>readFile(`.next/static/chunks/${n}`,'utf8')))).join('\n')+await readFile('src/app/globals.css','utf8')+await readFile('src/app/feature-settings.css','utf8')};
}
