import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {createRequire} from 'node:module';
import ts from 'typescript';
import type {HistoryPage,HistoryVersion} from '../../src/history/model';
const require=createRequire(import.meta.url);
export const historyAssetId='00000000-0000-4000-8000-000000000039';
export const historyVersionFixture:HistoryVersion={documentId:'history-local',sequence:9,currentRevision:3,publishedRevision:2,lifecycle:'active',status:'draft',version:{revision:1,title:'旧版客服处理流程',authorId:'author-id',authorName:'原作者 Ivy',editorId:'editor-id',editorName:'当时编辑 Alex',createdAt:'2026-09-01T01:00:00Z',body:'# 完整历史正文\n\n保留这段旧版说明 <script>不执行</script>\n\n| 步骤 | 负责人 |\n| --- | --- |\n| 核对资料 | 客服 |',audience:'ops',tags:['旧版标签','处理流程'],cover:{assetId:historyAssetId,alt:'旧版封面',position:30},blocks:[{id:'old-file',type:'file',assetId:historyAssetId,alt:'',caption:'旧版附件说明'},{id:'old-hint',type:'hint',style:'warning',title:'旧版提醒',body:'请保留来源说明'}]},categories:[{id:'category-old',name:'客服流程（旧版）'}],assets:[{id:historyAssetId,filename:'source-only.png',mime:'image/png',size:'67',status:'ready'}],canRestore:true};
export const historyPageFixture:HistoryPage={documentId:'history-local',title:'当前客服流程',sequence:9,revision:3,publishedRevision:2,lifecycle:'active',status:'draft',events:[{sequence:9,action:'restore_version',revision:3,actorId:'operator',actorName:'Tony',reviewerId:null,reviewerName:null,previousReviewerId:null,previousReviewerName:null,reason:null,sourceRevision:1,previousPublishedRevision:2,at:'2026-09-09T01:00:00Z'},{sequence:8,action:'reassign',revision:2,actorId:'operator',actorName:'Tony',reviewerId:'reviewer-b',reviewerName:'新审核人',previousReviewerId:'reviewer-a',previousReviewerName:'旧审核人',reason:'交接给其他审核人',sourceRevision:null,previousPublishedRevision:null,at:'2026-09-08T01:00:00Z'}],eventPage:1,eventPages:2,eventTotal:32,versions:[{revision:3,title:'当前客服流程',authorId:'author-id',authorName:'原作者 Ivy',editorId:'operator',editorName:'Tony',createdAt:'2026-09-09T01:00:00Z'},historyVersionFixture.version],versionPage:1,versionPages:2,versionTotal:31};
export async function historyBrowserBundle(){
 const dir=resolve('output/verification/history-fixture');await mkdir(dir,{recursive:true});
const files=['reader/icon-keys.ts','reader/icons.tsx','editor/inline.ts','editor/table.ts','editor/highlight.ts','editor/print.ts','fields/model.ts','fields/editor.ts','components/fields/FieldValues.tsx','qa/metadata.ts','components/history/HistoryTimeline.tsx','components/history/DeletedHistoryList.tsx','components/history/HistoryVersionPanel.tsx','history/client.ts','history/paths.ts','editor/document.ts','domain/presentation.ts','media/model.ts','media/tab-body.ts','reader/body.ts','reader/inline.ts','science/model.ts','components/gitbook/Media/ImageGallery.tsx','components/gitbook/Media/TableExplorer.tsx','components/gitbook/Media/MediaBlocks.tsx',...['StructuredInline','StructuredDocument','DocumentView','Inline','Heading','Paragraph'].map(f=>`components/gitbook/Reading/${f}.tsx`),...['Math','Diagram','Hint','CodeBlock','CopyCodeButton','DynamicTabs'].map(f=>`components/gitbook/RichBlocks/${f}.tsx`)];
 for(const file of files){const target=resolve(dir,file.replace(/\.tsx?$/,'.js'));await mkdir(dirname(target),{recursive:true});await writeFile(target,ts.transpileModule(await readFile(`src/${file}`,'utf8'),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022,rewriteRelativeImportExtensions:true}}).outputText);}
 await writeFile(resolve(dir,'entry.js'),`import React from 'react';import {createRoot} from 'react-dom/client';import {HistoryTimeline} from './components/history/HistoryTimeline';import {DeletedHistoryList} from './components/history/DeletedHistoryList';import {HistoryVersionPanel} from './components/history/HistoryVersionPanel';const data=JSON.parse(document.getElementById('data').textContent);createRoot(document.getElementById('root')).render(document.body.dataset.timeline==='2'?React.createElement(DeletedHistoryList,{data}):document.body.dataset.timeline==='1'?React.createElement(HistoryTimeline,{data}):React.createElement(HistoryVersionPanel,{initial:data}));`);
 const {webpack}=require('next/dist/compiled/webpack/webpack');await new Promise<void>((done,reject)=>{const compiler=webpack({mode:'development',devtool:false,plugins:[new webpack.DefinePlugin({'process.env':JSON.stringify({NODE_ENV:'development',__NEXT_ROUTER_BASEPATH:''})})],entry:resolve(dir,'entry.js'),output:{path:dir,filename:'bundle.js',publicPath:'/__history_assets/'},resolve:{modules:[resolve('node_modules')]},module:{rules:[{test:/\.m?js$/,resolve:{fullySpecified:false}}]}});compiler.run((error:Error|null,stats:{hasErrors():boolean;toString():string})=>compiler.close(()=>error||stats.hasErrors()?reject(error??new Error(stats.toString())):done()));});
 const css=(await Promise.all((await readdir('.next/static/chunks')).filter(f=>f.endsWith('.css')).map(f=>readFile(resolve('.next/static/chunks',f),'utf8')))).join('\n')+await readFile('src/app/globals.css','utf8');return {css,script:await readFile(resolve(dir,'bundle.js'),'utf8')};
}
