import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';import {resolve,dirname} from 'node:path';import {createRequire} from 'node:module';import ts from 'typescript';
const require=createRequire(import.meta.url);
export async function referenceBrowserBundle(){
 const dir=resolve('output/verification/reference-fixture');await mkdir(dir,{recursive:true});
 for(const file of ['editor/inline.ts','editor/inline-embed.ts','editor/annotation.ts','reader/content-path.ts','reader/icon-keys.ts','reader/icons.tsx','history/paths.ts','science/model.ts','components/reader-support/ArticleReferenceContext.tsx','components/reader-support/InlineAnnotation.tsx','reference/native.ts','components/reference/NativeReferenceTable.tsx','components/reader-support/StructuredInline.tsx','reference/filter.ts','reader/search.ts','components/reference/ReferenceView.tsx','components/reference/ReferenceTable.tsx','components/gitbook/Search/SearchResultItem.tsx']){const target=resolve(dir,file.replace(/\.tsx?$/,'.js'));await mkdir(dirname(target),{recursive:true});await writeFile(target,ts.transpileModule(await readFile(`src/${file}`,'utf8'),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022,rewriteRelativeImportExtensions:true}}).outputText);}
 await writeFile(resolve(dir,'entry.js'),`import React from 'react';import {createRoot} from 'react-dom/client';import {ReferenceView} from './components/reference/ReferenceView';const data=JSON.parse(document.getElementById('data').textContent);createRoot(document.getElementById('reference')).render(React.createElement(ReferenceView,data));`);
 const {webpack}=require('next/dist/compiled/webpack/webpack');await new Promise<void>((done,reject)=>{const compiler=webpack({mode:'development',devtool:false,entry:resolve(dir,'entry.js'),output:{path:dir,filename:'bundle.js'},resolve:{modules:[resolve('node_modules')]},module:{rules:[{test:/\.js$/,resolve:{fullySpecified:false}}]}});compiler.run((error:Error|null,stats:{hasErrors():boolean;toString():string})=>compiler.close(()=>error||stats.hasErrors()?reject(error??new Error(stats.toString())):done()));});
 return {script:await readFile(resolve(dir,'bundle.js'),'utf8'),css:(await Promise.all((await readdir('.next/static/chunks')).filter(n=>n.endsWith('.css')).map(n=>readFile(`.next/static/chunks/${n}`,'utf8')))).join('\n')+await readFile('src/app/globals.css','utf8')};
}
