'use client';
import {useState} from 'react';
import type {LifecyclePage,LifecycleItem} from '../../lifecycle/model';
import {lifecycleRequest,lifecycleError} from '../../lifecycle/client';
export function TrashManager({initial}:{initial?:LifecyclePage}){
 const [data,setData]=useState(initial);const [busy,setBusy]=useState(false);const [error,setError]=useState(initial?'':'回收站暂时无法读取。');const [notice,setNotice]=useState('');const [chosen,setChosen]=useState<LifecycleItem|null>(null);const [confirmation,setConfirmation]=useState('');
 async function refresh(){setError('');try{const r=await fetch(`/api/admin/trash?page=${data?.page??1}&cleanupPage=${data?.cleanupPage??1}`,{cache:'no-store',signal:AbortSignal.timeout(20000)});const v=await r.json();if(!r.ok||!Array.isArray(v.items)||!Array.isArray(v.cleanup))throw new Error('UNAVAILABLE');setData(v);setChosen(null);setConfirmation('');}catch{setData(undefined);setError('列表未能更新，请重新读取。');}}
 async function act(item:LifecycleItem,action:'restore'|'purge'){if(busy)return;setBusy(true);setError('');setNotice('');try{const result=await lifecycleRequest(item.id,{action,expectedSequence:item.sequence,...(action==='purge'?{confirmation}:{})});setNotice(action==='restore'?'已恢复为未发布草稿，请回到内容管理编辑和提交审核。':result.cleanupPending>0?`正文及历史内容已永久删除，仍有 ${result.cleanupPending} 个附件待清理。`:'正文及历史内容已永久删除，附件清理完成。');await refresh();}catch(e){setError(lifecycleError(e));}finally{setBusy(false);}}
 async function cleanup(id:string){if(busy)return;setBusy(true);setError('');setNotice('');try{const r=await fetch(`/api/admin/lifecycle/${encodeURIComponent(id)}/cleanup`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}',signal:AbortSignal.timeout(45000)});const v=await r.json();if(!r.ok)throw new Error(v.error);if(v.documentId!==id||!Number.isSafeInteger(v.cleanupPending)||v.cleanupPending<0)throw new Error('INVALID_ACK');setNotice(v.cleanupPending===0?'附件清理完成。':`仍有 ${v.cleanupPending} 个附件待清理，可继续重试。`);await refresh();}catch(e){setError(lifecycleError(e));}finally{setBusy(false);}}
 return <main className="trash-manager" id="main-content"><a href="/admin">← 内容管理</a><h1>回收站</h1><p>这里的文章已下线。恢复只回到未发布草稿，员工不会自动看到。</p><button type="button" disabled={busy} onClick={()=>{setBusy(true);void refresh().finally(()=>setBusy(false));}}>重新读取回收站</button>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {data&&<><p>共 {data.total} 篇 · 第 {data.page} / {data.pages} 页</p>{data.items.length===0?<p>回收站没有文章。</p>:<ul className="trash-list">{data.items.map(item=><li key={item.id}><h2>{item.title}</h2><p>版本 {item.sequence} · 已下线</p>{!busy&&<a href={`/admin/history?article=${encodeURIComponent(item.id)}`}>历史记录与版本</a>}<div className="lifecycle-actions"><button type="button" disabled={busy} onClick={()=>void act(item,'restore')}>恢复为未发布草稿</button><button type="button" disabled={busy} onClick={()=>{setChosen(item);setConfirmation('');}}>永久删除</button></div></li>)}</ul>}
 <nav aria-label="回收站分页">{data.page>1&&<a href={`/admin/trash?page=${data.page-1}&cleanupPage=${data.cleanupPage}`}>上一页</a>}{data.page<data.pages&&<a href={`/admin/trash?page=${data.page+1}&cleanupPage=${data.cleanupPage}`}>下一页</a>}</nav>
 {chosen&&<section className="lifecycle-confirm" aria-label="永久删除确认"><h2>永久删除“{chosen.title}”</h2><p>正文、历史版本、评论反馈与关联记录会被删除，无法从回收站恢复。仅保留删除审计；附件清理失败会保留重试任务。</p><label>输入文章标题确认永久删除<input value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off" disabled={busy}/></label><button type="button" disabled={busy||confirmation!==chosen.title} onClick={()=>void act(chosen,'purge')}>永久删除这篇文章</button><button type="button" disabled={busy} onClick={()=>{setChosen(null);setConfirmation('');}}>取消永久删除</button></section>}
 <section className="cleanup-list" aria-label="附件清理"><h2>待清理附件</h2>{!busy&&<a href="/admin/history">查看永久删除记录</a>}<p>文章已永久删除，以下文件仍等待存储服务确认清理完成。</p>{data.cleanup.length===0?<p>没有待清理附件。</p>:data.cleanup.map(item=><article key={item.documentId}><h3>{item.title}</h3><p>{item.pending} 个附件待清理</p><button type="button" disabled={busy} onClick={()=>void cleanup(item.documentId)}>重试清理附件</button></article>)}<nav aria-label="附件清理分页">{data.cleanupPage>1&&<a href={`/admin/trash?page=${data.page}&cleanupPage=${data.cleanupPage-1}`}>上一页清理记录</a>}<span>第 {data.cleanupPage} / {data.cleanupPages} 页</span>{data.cleanupPage<data.cleanupPages&&<a href={`/admin/trash?page=${data.page}&cleanupPage=${data.cleanupPage+1}`}>下一页清理记录</a>}</nav></section>
 </>}
 </main>;
}
