import type {ReferencePage,ReferenceDetail} from '../../reference/model';
import {ReferenceTable} from './ReferenceTable';
import {articleContentPath} from '../../reader/content-path';

export function ReferenceView({data,detail,state,detailState='idle',locale='zh-CN',withinDocsPage=false}:{data?:ReferencePage;detail?:ReferenceDetail;state:'ready'|'denied'|'unavailable';detailState?:'idle'|'ready'|'unavailable';locale?:'zh-CN'|'en';withinDocsPage?:boolean}){
 const english=locale==='en',suffix=english?'&lang=en':'';
 const label=(zh:string,en:string)=>english?en:zh;
 return <section className="reference-view" aria-label={label('Reference 速查资料','Reference articles')}>{!withinDocsPage&&<><a className="search-back" href={english?'/help-centre?lang=en':'/help-centre'}>← {label('返回员工资料库','Back to Help Centre')}</a><header><p className="reader-eyebrow">Reference</p><h1>{label('速查资料','Quick reference')}</h1><p className="reader-description">{label('查阅有权阅读的正式表格，快速查找费用、注册商和业务规则。','Check published tables for fees, registrars, and business rules you can access.')}</p></header></>}
 {state!=='ready'||!data?<div role="alert" className="search-state">{!withinDocsPage&&<h2>{state==='denied'?label('无法访问这类资料','You cannot access these references'):label('资料暂时无法读取','Could not load references')}</h2>}<p>{label('请重新载入；如果持续失败，请联系管理员。','Try again. If the problem continues, contact an administrator.')}</p><a className="secondary-link" href={english?'/help-centre/reference?lang=en':'/help-centre/reference'}>{label('重新读取','Try again')}</a></div>:<>
 {data.canEdit&&<p className="reader-actions"><a className="secondary-link" href="/admin/editor?kind=reference">{label('新建速查资料','Create reference article')}</a></p>}<p className="search-summary" role="status">{english?`${data.total} reference articles${data.pages>1?` · Page ${data.page} of ${data.pages}`:''}`:<>共 {data.total} 份速查资料{data.pages>1&&<> · 第 {data.page} / {data.pages} 页</>}</>}</p>
 {data.items.length?<nav id="reference-list" className="reference-selector" aria-label={label('选择速查资料','Choose a reference')}>{data.items.map(item=><a key={item.id} href={`/help-centre/reference?page=${data.page}&article=${encodeURIComponent(item.id)}${suffix}#reference-detail`} aria-label={english?`Open reference: ${item.title}`:`打开速查：${item.title}`} aria-current={detailState==='ready'&&detail?.id===item.id?'page':undefined}>{item.title}</a>)}</nav>:<div className="search-state"><h2>{label('暂时没有已发布的速查资料','No published English references yet')}</h2><p>{label('管理员发布后，有权限的资料会显示在这里。','Published references you can access will appear here.')}</p></div>}
 {data.pages>1&&<nav className="search-pagination" aria-label={label('速查资料翻页','Reference pages')}>{data.page>1&&<a className="secondary-link" href={`/help-centre/reference?page=${data.page-1}${suffix}`}>{label('上一页','Previous')}</a>}<span>{english?`Page ${data.page} of ${data.pages}`:`${data.page} / ${data.pages}`}</span>{data.page<data.pages&&<a className="secondary-link" href={`/help-centre/reference?page=${data.page+1}${suffix}`}>{label('下一页','Next')}</a>}</nav>}
 {detailState==='unavailable'?<section role="alert" className="search-state"><h2>{label('所选速查资料暂时无法读取','The selected reference is unavailable')}</h2><p>{label('可能已更新、下线或权限已改变，请从上方重新选择。','It may have changed, been unpublished, or become restricted. Choose another reference above.')}</p></section>:detailState==='ready'&&detail?<section id="reference-detail" className="reference-detail" aria-label={label('所选正式资料','Selected published reference')}><h2>{detail.title}</h2><p>{english?(detail.publicationNumber?`Published version ${detail.publicationNumber}`:'Published'):(detail.publicationNumber?`正式版本 ${detail.publicationNumber}`:'已发布')} · {label('表格仅供查阅','Read-only tables')}</p><details className="reference-more"><summary>{label('其他操作','More options')}</summary><div className="reader-actions"><a className="secondary-link" href={articleContentPath(detail.id)}>{label('阅读全文','Read full article')}</a><a className="secondary-link" href={`/help-centre/pdf?article=${encodeURIComponent(detail.id)}&revision=${detail.revision}${suffix}`}>{label('完整正式版 PDF','Full published PDF')}</a>{data.canEdit&&<a className="secondary-link" href={`/admin/editor?article=${encodeURIComponent(detail.id)}`}>{label('编辑此资料','Edit reference')}</a>}</div></details><p className="reference-note">{label('筛选仅影响当前查看，不修改资料；PDF 包含完整正式文章。更新内容须由管理员编辑、二审及发布。','Filters only change this view. The PDF contains the complete published article. Administrators review and publish updates.')}</p>{detail.tables.length?detail.tables.map((table,i)=><ReferenceTable key={`${detail.id}:${detail.revision}:${table.id}`} table={table} number={i+1} locale={locale}/>):<p role="status">{label('这篇正式资料还没有表格，可以阅读全文。','This reference has no table yet. You can read the full article.')}</p>}</section>:data.items.length>0?<p className="reference-note">{label('从上方选择资料，即可查看表格。','Choose a reference above to view its tables.')}</p>:null}
 </>}
 </section>;
}
