import type {ReferencePage,ReferenceDetail} from '../../reference/model';
import {ReferenceTable} from './ReferenceTable';
export function ReferenceView({data,detail,state,detailState='idle'}:{data?:ReferencePage;detail?:ReferenceDetail;state:'ready'|'denied'|'unavailable';detailState?:'idle'|'ready'|'unavailable'}){
 return <section className="reference-view" aria-label="Reference 速查资料"><a className="search-back" href="/help-centre">← 返回员工资料库</a><header><p className="reader-eyebrow">Reference</p><h1>速查资料</h1><p className="reader-description">查阅有权阅读的正式表格，快速查找费用、注册商和业务规则。</p></header>
 {state!=='ready'||!data?<div role="alert" className="search-state"><h2>{state==='denied'?'无法访问这类资料':'资料暂时无法读取'}</h2><p>请重新载入；如果持续失败，请联系管理员。</p><a className="secondary-link" href="/help-centre/reference">重新读取</a></div>:<>
 {data.canEdit&&<p className="reader-actions"><a className="secondary-link" href="/admin/editor?kind=reference">新建速查资料</a></p>}<p className="search-summary" role="status">共 {data.total} 份速查资料{data.pages>1&&<> · 第 {data.page} / {data.pages} 页</>}</p>
 {data.items.length?<nav id="reference-list" className="reference-selector" aria-label="选择速查资料">{data.items.map(item=><a key={item.id} href={`/help-centre/reference?page=${data.page}&article=${encodeURIComponent(item.id)}#reference-detail`} aria-label={`打开速查：${item.title}`} aria-current={detailState==='ready'&&detail?.id===item.id?'page':undefined}>{item.title}</a>)}</nav>:<div className="search-state"><h2>暂时没有已发布的速查资料</h2><p>管理员发布后，有权限的资料会显示在这里。</p></div>}
 {data.pages>1&&<nav className="search-pagination" aria-label="速查资料翻页">{data.page>1&&<a className="secondary-link" href={`/help-centre/reference?page=${data.page-1}`}>上一页</a>}<span>{data.page} / {data.pages}</span>{data.page<data.pages&&<a className="secondary-link" href={`/help-centre/reference?page=${data.page+1}`}>下一页</a>}</nav>}
 {detailState==='unavailable'?<section role="alert" className="search-state"><h2>所选速查资料暂时无法读取</h2><p>可能已更新、下线或权限已改变，请从上方重新选择。</p></section>:detailState==='ready'&&detail?<section id="reference-detail" className="reference-detail" aria-label="所选正式资料"><h2>{detail.title}</h2><p>{detail.publicationNumber?`正式版本 ${detail.publicationNumber}`:'已发布'} · 表格仅供查阅</p><details className="reference-more"><summary>其他操作</summary><div className="reader-actions"><a className="secondary-link" href={`/help-centre?article=${encodeURIComponent(detail.id)}`}>阅读全文</a><a className="secondary-link" href={`/help-centre/pdf?article=${encodeURIComponent(detail.id)}&revision=${detail.revision}`}>完整正式版 PDF</a>{data.canEdit&&<a className="secondary-link" href={`/admin/editor?article=${encodeURIComponent(detail.id)}`}>编辑此资料</a>}</div></details><p className="reference-note">筛选仅影响当前查看，不修改资料；PDF 包含完整正式文章。更新内容须由管理员编辑、二审及发布。</p>{detail.tables.length?detail.tables.map((table,i)=><ReferenceTable key={`${detail.id}:${detail.revision}:${table.id}`} table={table} number={i+1}/>):<p role="status">这篇正式资料还没有表格，可以阅读全文。</p>}</section>:data.items.length>0?<p className="reference-note">从上方选择资料，即可查看表格。</p>:null}
 </>}
 </section>;
}
