'use client';
import {useId,useState} from 'react';
import type {ReferenceTableData} from '../../reference/model';
import {filterReferenceRows} from '../../reference/filter';
export function ReferenceTable({table,number}:{table:ReferenceTableData;number:number}){
 const id=useId();const [query,setQuery]=useState(''),[column,setColumn]=useState<number|null>(null),[page,setPage]=useState(1);const result=filterReferenceRows(table,query,column,page);
 return <section className="reference-table" aria-label={`速查表 ${number}`}><h3>速查表 {number}</h3><div className="reference-filters"><label htmlFor={`${id}-query`}>筛选表格<input id={`${id}-query`} value={query} placeholder="输入关键词，多个词用空格分开" aria-invalid={result.status==='invalid'||undefined} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><label htmlFor={`${id}-column`}>筛选范围<select id={`${id}-column`} value={column??'all'} onChange={e=>{setColumn(e.target.value==='all'?null:Number(e.target.value));setPage(1);}}><option value="all">全部列</option>{table.headers.map((header,i)=><option key={i} value={i}>{header||`第 ${i+1} 列`}</option>)}</select></label><button type="button" onClick={()=>{setQuery('');setColumn(null);setPage(1);}}>清除筛选</button></div>
 {result.status==='invalid'?<p role="alert">筛选条件不正确，关键词最多 120 个字符。</p>:<><p role="status">共 {table.rows.length} 行 · 符合 {result.total} 行 · 第 {result.page} / {result.pages} 页</p>{result.items.length?<div className="reader-scroll-region" role="region" tabIndex={0} aria-label={`速查表 ${number}，可横向滚动`}><table><caption className="sr-only">速查表 {number}，当前页筛选结果</caption><thead><tr><th scope="col">原行号</th>{table.headers.map((header,i)=><th key={i} scope="col">{header||`第 ${i+1} 列`}</th>)}</tr></thead><tbody>{result.items.map(row=><tr key={row.index}><th scope="row">{row.index+1}</th>{row.cells.map((cell,i)=><td key={i}>{cell}</td>)}</tr>)}</tbody></table></div>:<p>{table.rows.length?'没有符合条件的行，请更换关键词或清除筛选。':'这张表还没有数据行。'}</p>}{result.pages>1&&<nav className="reference-row-pages" aria-label={`速查表 ${number} 翻页`}><button disabled={result.page===1} onClick={()=>setPage(result.page-1)}>上一页</button><span>{result.page} / {result.pages}</span><button disabled={result.page===result.pages} onClick={()=>setPage(result.page+1)}>下一页</button></nav>}</>}
 </section>;
}
