'use client';
import {useEffect,useRef,useState} from 'react';
import {historyKinds,historyLabels,configRows,type HistoryKind,type HistoryTarget,type HistoryPage,type HistoryDetail,type RestoreInput} from '../../setting-history/model';
import {loadHistory,loadHistoryDetail,restoreHistory,HistoryRejected} from '../../setting-history/client';
const date=(value:string)=>new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Kuala_Lumpur',hour12:false});
function Snapshot({title,kind,value}:{title:string;kind:HistoryKind;value:Record<string,unknown>|null}){return <section className="setting-snapshot"><h3>{title}</h3><dl>{configRows(kind,value).map(row=><div key={row.label}><dt>{row.label}</dt><dd>{row.value}</dd></div>)}</dl>{value&&<details><summary>完整配置记录</summary><pre>{JSON.stringify(value,null,2)}</pre></details>}</section>;}
export function SettingHistory({initial}:{initial?:HistoryPage}){
 const [data,setData]=useState(initial),[kind,setKind]=useState<HistoryKind|'all'>('all'),[detail,setDetail]=useState<HistoryDetail>(),[target,setTarget]=useState<HistoryTarget>(),[pending,setPending]=useState<RestoreInput>(),[busy,setBusy]=useState(false),[fresh,setFresh]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const lock=useRef(false),leaving=useRef(false);
 useEffect(()=>{if(!pending)return;const unload=(e:BeforeUnloadEvent)=>{if(!leaving.current){e.preventDefault();e.returnValue='';}};const click=(e:MouseEvent)=>{const a=e.target instanceof Element?e.target.closest('a[href]'):null;if(!a||e.defaultPrevented||e.ctrlKey||e.metaKey||e.shiftKey)return;e.preventDefault();e.stopPropagation();if(!lock.current&&confirm('恢复结果仍待确认。离开将丢失本页的重试请求，请先复制请求记录。确定离开吗？')){leaving.current=true;location.assign(a.getAttribute('href')!);}};addEventListener('beforeunload',unload);document.addEventListener('click',click,true);return()=>{removeEventListener('beforeunload',unload);document.removeEventListener('click',click,true);};},[pending]);
 async function list(nextKind=kind,page=1){if(lock.current||pending)return;lock.current=true;setBusy(true);setError('');try{const next=await loadHistory(nextKind,page);setData(next);setKind(nextKind);setDetail(undefined);setTarget(undefined);setFresh(false);}catch{setError('历史列表暂时无法读取，已有记录未改变。请重试。');}finally{lock.current=false;setBusy(false);}}
 async function inspect(value:HistoryTarget){if(lock.current||pending)return;lock.current=true;setBusy(true);setFresh(false);setDetail(undefined);setTarget(value);setError('');try{setDetail(await loadHistoryDetail(value));setFresh(true);}catch{setError('暂时无法读取该版本和当前设置，请重新载入详情。');}finally{lock.current=false;setBusy(false);}}
 async function restore(retry=false){if(lock.current)return;const input=retry?pending:detail&&fresh?{kind:detail.entry.kind,id:detail.entry.id,version:detail.entry.version,expectedVersion:detail.current.version,requestId:crypto.randomUUID()}:undefined;if(!input)return;if(!retry&&!confirm(`将「${detail!.entry.label}」版本 ${input.version} 的配置恢复为新版本，替换当前版本 ${input.expectedVersion}。设置立即生效，可能改变员工的可见范围、表单或功能使用；旧记录保留。确定恢复吗？`))return;
  lock.current=true;setBusy(true);setError('');setNotice('');setPending(input);setFresh(false);
  try{const ack=await restoreHistory(input);setPending(undefined);setDetail(undefined);setNotice(`恢复操作已确认，生成版本 ${ack.newVersion}，来源版本 ${ack.version}。请重新载入详情核对当前设置；其他管理员可能已继续修改。`);}catch(e){if(e instanceof HistoryRejected&&!retry){setPending(undefined);const code=e.message;setError(code==='FORBIDDEN'?'当前账号没有管理权限。':code==='FEATURE_DISABLED'?'内部表单已暂停，请先在功能开关中开启，再重新核对。':['CATEGORY_CYCLE','CATEGORY_DEPTH','FIELD_CONFLICT','INVALID_INPUT'].includes(code)?'旧设置未通过当前规则校验，不能直接恢复。请到对应设置页调整分类或字段依赖，再重新核对。':'设置已变化或版本不存在，恢复未执行。请重新载入详情核对。');}else setError('无法确认原恢复结果。请重试原恢复请求；核对前不能发起其他操作。');}finally{lock.current=false;setBusy(false);}
 }
 return <section className="setting-history"><header><div><p className="card-kicker">SYSTEM SETTINGS</p><h1>设置变更记录</h1><p>查看修改前后内容；恢复会生成新版本，旧记录仍会保留。</p></div><a className="secondary-link" href="/admin">返回管理后台</a></header><p className="history-note">仅管理员可见。时间为马来西亚时间；操作人名称显示当前名称，旧记录未保存的操作人不会补造。表单暂停时仍可查阅历史，恢复前需开启表单。</p><div className="history-toolbar"><label>设置类型 <select aria-label="设置类型" value={kind} disabled={busy||!!pending} onChange={e=>void list(e.target.value as HistoryKind|'all',1)}><option value="all">全部设置</option>{historyKinds.map(k=><option key={k} value={k}>{historyLabels[k]}</option>)}</select></label><button className="secondary-link" disabled={busy||!!pending} onClick={()=>void list(kind,data?.page??1)}>刷新历史列表</button><a href="/admin/settings/features">管理功能开关</a></div>
 {data?<><p>共 {data.total} 条记录 · 第 {data.page} / {data.pages} 页</p>{!data.total?<p>尚无已保存的设置变更记录。</p>:<ol className="history-entries">{data.items.map(e=><li key={`${e.kind}:${e.id}:${e.version}`}><div><strong>{e.label}</strong><p>{historyLabels[e.kind]} · 版本 {e.version}{e.restoredFrom!==null?` · 从版本 ${e.restoredFrom} 恢复`:''}</p><small>{date(e.changedAt)} · {e.actor?.name??'历史导入（操作人未记录）'}</small></div><button className="secondary-link" disabled={busy||!!pending} onClick={()=>void inspect({kind:e.kind,id:e.id,version:e.version})}>查看 {e.label} 版本 {e.version}</button></li>)}</ol>}<nav className="history-pagination" aria-label="历史分页"><button disabled={busy||!!pending||data.page===1} onClick={()=>void list(kind,data.page-1)}>上一页</button><button disabled={busy||!!pending||data.page===data.pages} onClick={()=>void list(kind,data.page+1)}>下一页</button></nav></>:<p role="status">暂时无法读取设置历史，请重试。</p>}
 {busy&&<p role="status">正在处理，请稍候…</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {target&&<div className="history-detail-tools"><button className="secondary-link" disabled={busy||!!pending} onClick={()=>void inspect(target)}>重新载入详情</button></div>}
 {detail&&<section className="history-detail" aria-label="版本详情"><h2>{detail.entry.label} · 版本 {detail.entry.version}</h2><p>修改时间：{date(detail.entry.changedAt)} · 操作人：{detail.entry.actor?`${detail.entry.actor.name}（${detail.entry.actor.id}）`:'未记录'}</p><div className="history-comparison"><Snapshot title="修改前" kind={detail.entry.kind} value={detail.before}/><Snapshot title="修改后（恢复目标）" kind={detail.entry.kind} value={detail.after}/></div><Snapshot title={`当前设置 · 版本 ${detail.current.version}`} kind={detail.entry.kind} value={detail.current.config}/><div className="history-restore"><p>恢复会重新检查当前权限与配置规则，可能立即改变员工可见范围或可用功能；文章版本和提交记录不会被改写。</p>{detail.current.version>detail.entry.version?<button className="primary-link" disabled={busy||!!pending||!fresh} onClick={()=>void restore()}>恢复此版本为新设置</button>:<p>这已是当前版本，无需恢复。</p>}</div></section>}
 {pending&&<section className="history-pending"><h2>待确认的恢复请求</h2><p>请保留此记录。重试只核对并继续这一次恢复，不重复生成版本。</p><textarea aria-label="恢复请求记录" readOnly value={JSON.stringify(pending,null,2)}/><button className="secondary-link" disabled={busy} onClick={()=>void restore(true)}>重试原恢复请求</button></section>}
 </section>;
}
