"use client";
/* eslint-disable @next/next/no-html-link-for-pages -- Full navigations preserve native unload protection for pending submissions and input backups. */
import {useRef,useState,type FormEvent} from 'react';
import {fieldInputValue,fieldValueText} from '../../fields/editor';
import {validateSubmission,parseProcessInput,type FormDefinition,type FormField,type FormRecord,type FormRecordPage,type Receipt,type SubmissionInput,type ProcessInput} from '../../forms/model';
import {FormRejected,readEmployeeForm,submitEmployeeForm,readRecord,processRecord} from '../../forms/client';
import {confirmAction} from '../feedback/feedback';
import {useReviewLeaveGuard} from '../review/useReviewLeaveGuard';
import {Card,Cards} from 'fumadocs-ui/components/card';
import {buttonVariants} from 'fumadocs-ui/components/ui/button';
const statuses={new:'新提交',processing:'处理中',resolved:'已处理'};
const date=(value:string)=>new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Kuala_Lumpur',hour12:false});
function useLeaveGuard(dirty:boolean,locked:boolean){useReviewLeaveGuard({dirty,busy:locked,uncertain:false});}
export function FormCollection({data,state=data?'ready':'unavailable',withinDocsPage=false}:{data?:FormDefinition[];state?:'ready'|'disabled'|'unavailable';withinDocsPage?:boolean}){return <section className="forms-section">{!withinDocsPage&&<header className="forms-heading"><div><h1>内部表单</h1><p>填写并提交给管理员处理。</p></div><a className={buttonVariants({variant:'outline'})} href="/help-centre">返回资料库</a></header>}{state!=='ready'||!data?<div role="status"><p>{state==='disabled'?'内部表单目前已关闭；如需使用，请联系管理员。':'暂时无法读取表单，请稍后重试。'}</p>{state!=='disabled'&&<a className={buttonVariants({variant:'outline'})} href="/help-centre/forms">重新载入</a>}</div>:data.length===0?<p>目前没有可填写的表单。</p>:<Cards className="forms-collection" aria-label="可填写的内部表单">{data.map(form=><Card key={form.id} href={`/help-centre/forms/${form.id}`} aria-label={`填写表单：${form.title}`} icon={<span aria-hidden="true">▤</span>} title={form.title} description={<><span>{form.description}</span><span>{form.fields.length} 个填写项 · 打开表单</span></>}/>)}</Cards>}</section>;}
export function FormInputFields({fields,inputs,onChange,disabled}:{fields:FormField[];inputs:Record<string,string>;onChange:(id:string,value:string)=>void;disabled:boolean}){return <fieldset className="forms-fieldset" disabled={disabled}><legend>填写内容</legend><p>标有 * 的项目为必填。</p><div className="forms-grid">{fields.map(({field,required,width})=><label className={`forms-field forms-width-${width}`} key={field.id}><span id={`form-field-${field.id}`}>{field.name}{required?' *':''}</span>{field.type==='select'||field.type==='boolean'?<select aria-labelledby={`form-field-${field.id}`} aria-required={required} value={inputs[field.id]??''} onChange={e=>onChange(field.id,e.target.value)}><option value="">请选择</option>{field.type==='boolean'?<><option value="true">是</option><option value="false">否</option></>:field.options.map(option=><option key={option} value={option}>{option}</option>)}</select>:field.type==='text'?<textarea aria-labelledby={`form-field-${field.id}`} rows={3} maxLength={2000} aria-required={required} value={inputs[field.id]??''} onChange={e=>onChange(field.id,e.target.value)}/>:<input aria-labelledby={`form-field-${field.id}`} aria-required={required} type={field.type==='date'?'date':'text'} inputMode={field.type==='number'?'decimal':undefined} value={inputs[field.id]??''} onChange={e=>onChange(field.id,e.target.value)}/>}</label>)}</div></fieldset>;}
export function FormFill({initial,withinDocsPage=false}:{initial:FormDefinition;withinDocsPage?:boolean}){
 const [form,setForm]=useState(initial),[inputs,setInputs]=useState<Record<string,string>>({}),[submissionId,setSubmissionId]=useState(()=>crypto.randomUUID());
 const [receipt,setReceipt]=useState<Receipt|null>(null),[pending,setPending]=useState<SubmissionInput|null>(null),[busy,setBusy]=useState(false),[blocked,setBlocked]=useState(false),[error,setError]=useState(''),[backups,setBackups]=useState<string[]>([]);const lock=useRef(false);
 const dirty=Object.values(inputs).some(v=>v!=='');useLeaveGuard((!receipt&&dirty)||backups.length>0,busy||pending!==null);
 const frozen=busy||pending!==null||receipt!==null;
 async function submit(e?:FormEvent){e?.preventDefault();if(lock.current||receipt||blocked&&!pending)return;let operation=pending;const wasUncertain=pending!==null;if(!operation){try{operation=validateSubmission(form,{id:submissionId,formVersion:form.version,values:form.fields.map(({field})=>({fieldId:field.id,value:fieldInputValue(field.type,inputs[field.id]??'')}))});}catch{setError('请检查必填项、数字、日期和选项，输入仍保留。');return;}}
 lock.current=true;setBusy(true);setPending(operation);setError('');try{const saved=await submitEmployeeForm(form.id,operation);setReceipt(saved);setPending(null);}catch(e){if(e instanceof FormRejected&&!wasUncertain){setPending(null);setBlocked(['FORM_CONFLICT','NOT_FOUND','FORBIDDEN'].includes(e.message));setError(e.message==='FORM_CONFLICT'?'表单已经更新。请保留输入并载入最新版后核对，再提交。':e.message==='NOT_FOUND'||e.message==='FORBIDDEN'?'表单已停用或当前账号不能提交。输入仍保留。':'提交被拒绝，请检查内容。输入仍保留。');}else{setError('暂时无法确认此前是否提交成功。原提交已锁定，请重试原提交，避免重复记录。');}}finally{lock.current=false;setBusy(false);}}
 async function reload(){if(lock.current||pending||receipt)return;if(dirty&&!await confirmAction('将保留本次输入备份并载入最新表单，填写区会重置。确定继续吗？'))return;lock.current=true;setBusy(true);setError('');try{const current=await readEmployeeForm(form.id);setBackups(old=>[...old,JSON.stringify({form,inputs,submissionId},null,2)]);setForm(current);setInputs({});setSubmissionId(crypto.randomUUID());setBlocked(false);}catch{setError('无法载入最新表单。当前输入仍保留，请稍后重试。');}finally{lock.current=false;setBusy(false);}}
 return <section className="forms-section" aria-label="填写内部表单" aria-busy={busy}>{!withinDocsPage&&<header className="forms-heading"><div><h1>{form.title}</h1><p>{form.description}</p></div><a className={buttonVariants({variant:'outline'})} href="/help-centre/forms">返回表单列表</a></header>}<p className="forms-note">提交后由管理员处理，内容会作为本次记录保留。</p>
 {receipt&&<div className="forms-success" role="status"><h2>提交成功</h2><p>已收到你的填写内容，等待管理员处理。</p><p>记录编号：{receipt.id}</p><p>{date(receipt.submittedAt)}</p><button className={buttonVariants({variant:'secondary'})} type="button" onClick={()=>{setReceipt(null);setInputs({});setSubmissionId(crypto.randomUUID());setError('');}}>再填写一份</button></div>}
 <form onSubmit={submit}><FormInputFields fields={form.fields} inputs={inputs} onChange={(id,value)=>setInputs(old=>({...old,[id]:value}))} disabled={frozen}/>{!receipt&&<div className="forms-actions"><button type="submit" className={buttonVariants({variant:'primary'})} disabled={busy||blocked&&!pending}>{busy?'正在提交…':pending?'重试原提交':'提交表单'}</button>{!pending&&<button className={buttonVariants({variant:'outline'})} type="button" disabled={busy} onClick={()=>void reload()}>保留输入并载入最新版</button>}</div>}</form>
 {error&&<p className="forms-error" role="alert">{error}</p>}{(error||pending)&&<details><summary>保留当前输入</summary><textarea className="forms-backup" readOnly aria-label="当前表单输入备份" value={JSON.stringify({form,inputs,submissionId,pending},null,2)}/></details>}
 {backups.map((backup,index)=><details open key={index}><summary>载入前的输入备份 {index+1}</summary><textarea className="forms-backup" readOnly aria-label={"载入前的表单输入备份 "+(index+1)} value={backup}/></details>)}</section>;
}
export function FormRecords({data}:{data?:FormRecordPage}){return <section className="forms-section"><header className="forms-heading"><div><h1>表单提交记录</h1><p>查看员工填写内容并记录处理结果。</p></div><a href="/admin">返回管理后台</a></header><a href="/admin/settings/forms">配置表单 →</a>{!data?<div role="status"><p>暂时无法读取提交记录。</p><a href="/admin/forms">重新载入</a></div>:<><p>共 {data.total} 条记录</p>{data.items.length===0?<p>还没有提交记录。</p>:<ul className="forms-records">{data.items.map(record=><li key={record.id}><a href={`/admin/forms/${record.id}`}><strong>{record.title}</strong><span className="forms-badge">{statuses[record.status]}</span><span>{record.submittedBy.name} · {date(record.submittedAt)}</span></a></li>)}</ul>}<nav className="forms-actions" aria-label="提交记录分页">{data.page>1&&<a href={`/admin/forms?page=${data.page-1}`}>上一页</a>}<span>第 {data.page} / {data.pages} 页</span>{data.page<data.pages&&<a href={`/admin/forms?page=${data.page+1}`}>下一页</a>}</nav></>}</section>;}
export function FormRecordView({initial}:{initial:FormRecord}){
 const [record,setRecord]=useState(initial),[status,setStatus]=useState<ProcessInput['status']>(initial.status==='resolved'?'resolved':'processing'),[note,setNote]=useState(initial.note);
 const [pending,setPending]=useState<ProcessInput|null>(null),[busy,setBusy]=useState(false),[blocked,setBlocked]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[backups,setBackups]=useState<string[]>([]);const lock=useRef(false);
 const dirty=note!==record.note||status!==(record.status==='resolved'?'resolved':'processing');useLeaveGuard(dirty||backups.length>0,busy||pending!==null);
 async function process(e?:FormEvent){e?.preventDefault();if(lock.current||blocked&&!pending)return;let operation=pending;const wasUncertain=pending!==null;try{operation??=parseProcessInput({expectedSequence:record.sequence,status,note});}catch{setError('请检查处理状态和备注，备注最多 2000 字。');return;}lock.current=true;setBusy(true);setPending(operation);setError('');setNotice('');try{const saved=await processRecord(record.id,operation);setRecord(old=>({...old,...saved}));setPending(null);setBlocked(false);setNotice('处理结果已保存。');}catch(e){if(e instanceof FormRejected&&!wasUncertain){setPending(null);setBlocked(true);setError(e.message==='CONFLICT'?'另一位管理员已经处理这条记录。输入已保留，请载入最新记录后核对。':'处理未保存。请检查权限或载入最新记录。');}else setError('暂时无法确认此前是否处理成功，请重试原操作。');}finally{lock.current=false;setBusy(false);}}
 async function reload(){if(lock.current)return;if((dirty||pending)&&!await confirmAction('将保留当前输入备份并载入最新记录。此操作不会撤销可能已保存的处理。确定继续吗？'))return;lock.current=true;setBusy(true);setError('');try{const latest=await readRecord(record.id,record.sequence);setBackups(old=>[...old,JSON.stringify({status,note,pending},null,2)]);setRecord(latest);setStatus(latest.status==='resolved'?'resolved':'processing');setNote(latest.note);setPending(null);setBlocked(false);setNotice('已载入服务器当前处理状态。');}catch{setError('暂时无法载入记录，输入仍保留。');}finally{lock.current=false;setBusy(false);}}
 return <section className="forms-section" aria-label="处理表单记录" aria-busy={busy}><header className="forms-heading"><div><h1>{record.title}</h1><p>{record.submittedBy.name} · {date(record.submittedAt)}</p></div><a href="/admin/forms">返回提交记录</a></header><p>当前状态：<strong>{statuses[record.status]}</strong></p><p className="forms-note">以下为提交时的内容，不随表单设置修改。</p><dl className="forms-answers">{record.fields.map(({field})=><div key={field.id}><dt>{field.name}</dt><dd>{fieldValueText(record.values.find(v=>v.fieldId===field.id)!.value)}</dd></div>)}</dl>
 {record.processedBy&&<p>最近处理：{record.processedBy.name} · {date(record.processedAt!)}</p>}
 <form onSubmit={process}><fieldset className="forms-fieldset" disabled={busy||pending!==null}><legend>处理结果</legend><label>处理状态<select aria-label="处理状态" value={status} onChange={e=>setStatus(e.target.value as ProcessInput['status'])}><option value="processing">处理中</option><option value="resolved">已处理</option></select></label><label>处理备注<textarea aria-label="处理备注" maxLength={2000} rows={4} value={note} onChange={e=>setNote(e.target.value)}/></label></fieldset><div className="forms-actions"><button className="forms-primary" type="submit" disabled={busy||blocked&&!pending}>{busy?'正在保存…':pending?'重试原操作':'保存处理结果'}</button><button type="button" disabled={busy} onClick={()=>void reload()}>保留输入并载入最新记录</button></div></form>
 {error&&<p role="alert" className="forms-error">{error}</p>}{notice&&<p role="status" className="forms-success">{notice}</p>}{backups.map((backup,index)=><details open key={index}><summary>载入前的处理输入 {index+1}</summary><textarea readOnly className="forms-backup" aria-label={"处理输入备份 "+(index+1)} value={backup}/></details>)}</section>;
}
